function loadCampaign(){
	x="<b>+Duel House Rules</b><br><br>1) Any ring can be called when using Predict.<br>RAW: Predict can only be called for Air, Earth, Fire and Water, not for Void.<br>Rationale: I don't see any reason why void should be different & immune to Predict in this case.<br><br>2) When striking or otherwise making an attack, if the strike misses, the attacker takes the defender's vigilance in strife.  <br>RAW: There is no penalty to missing a strike in a duel.<br>Rationale: This is to stop duels becoming two people slashing wildly at the air around each other until one connects - pretty sure duels should not look like this - as with the rules as written, this is pretty much the most effective tactic.  When there is a penalty to missing, Center action becomes useful.  A high composure character can still slash wildly all around a low vigilance opponent for a while before he strifes out, but it is no longer the best strategy for everyone.<br><br>"
	x += "<b>+Mirumoto Niten User Nerf</b><br><br>1) Mirumoto Niten school ability can only be used with a daisho.  No using karate chops with it, no using it with kusari-gama, no using it with anything other than your normal daisho.<br>RAW: You can use it with your hands, or with anything you want.<br>Rationale: Abusable, unthematic, OP.<br><br>"
	x += "<b>+Resist Checks Opportunity Spend House Rules</b><br><br>1) You cannot use Opportunities from your resist checks.  <br>RAW: You can use Opportunities from resist checks.<br>Rationale: This results in perplexing situations where your opponent has made you stronger by trying to inflict a condition on you.  Also speeds things up.<br><br>"
	x += "<b>+Prone House Rule</b><br><br>1) Prone characters cannot take actions that require checks.<br>RAW: Prone is an advantage, try not to make your opponents prone because it will make them stronger, it doesn't make anything more difficult for them except they move more slowly because they are not standing, lifeprotip: don't get up out of bed in the morning, spend all day slithering on the floor, be more effective or no less effective for less energy spent.<br>Rationale: The RAW is retarded in this case.<br><br>"
	x += "<b>+Animal Handling Skill</b><br><br>1) Animal Handling is a separate skill under Trade skills, split from Survival.  If you can take Survival during character creation, you can choose to take Animal Handling instead.<br><br>"
	x += "<b>+Dark Theology Skill</b><br><br>1) Dark Theology is a separate skill under Scholar skills, split from Theology.  If Theology covers 'the way things should be', Dark Theology covers things which are taboo or forbidden - diagnosing the Taint, being able to identify maho use, knowledge about oni etc.  If you can take Theology in character creation and your backstory or clan function support it, then you can choose to take Dark Theology instead (i.e. a Kuni shugenja would probably have access to Dark Theology learning materials and mentors, but an Asahina artificer making art in some cushy Crane place would have no exposure under normal circumstances.)<br><br>"
	x += "<b>+Taint House Rules</b><br><br>I am using a 1 to 100 scale for Taint, similar to Honor and Glory, where the Shadowlands Taint disadvantages happen when the character gets to 20, 40, 60, 80 and 100 points.  This lets Taint happen to a character more than 5 times in their lives before they are lost, lets the Taint grow over time to consume the victim's mind and body slowly, and I might throw in Shadowlands Taint advantages when they hit 10, 30, 50, 70, and 90.<br><br>Afflicted condition is applied normally.<br><br>When an Afflicted character is Afflicted again, roll Fitness to resist the Taint, failing on that roll results in a Tainted character.<br><br>When an Afflicted character becomes Compromised, roll Meditation to resist the Taint.  Failing on that roll results in a Tainted character.<br><br>Using evil items Afflicts, then Taints you.  Using maho straight up taints you.<br><br>"
	x += "<b>+Critical Strike Rules</b><br><br>Coming Soon, my issue here is that Dying is less bad than being drastically maimed, it is really hard to die as long as you have a half decent medic around but really super easy to get life changing injuries.  I am sort of glad that you don't die by accident all the time, as I want to be able to make fights without worrying that Random Basic Bandit #348 will roll 3 10s on his damage roll and decapitate your samurai, because that is really uncinematic and also sort of disruptive - mainly I just want a smoother graph of Crit Severity-to-Badness rather than the weird up and down curve it makes at the moment.<br><br>"
	divcontents("houserules",x)
}