var definitions = {
	"Skirmish Actions":{

	"Skirmish Initiative":" <br><br>During this phase of a skirmish, characters get their bearings, identify their foes, determine their initiative value, and prepare to do battle. For a skirmish, the Initiative check is a <b>TN 1 Tactics</b> check to gain a read on the battlefield conditions and enemy. Remember, characters may spend <span class='l5r'>O</span> from this check to get additional information about their surroundings or undertake small tasks such as readying weapons or diving for cover (Core p328). Characters act in descending order of initiative value for the scene. If two or more characters tie for initiative, the character with the lowest honor acts first, and then the other tied characters act in ascending order of honor.   A character can use any ring for this check. After a character resolves their Initiative check, that character enters the stance matching the ring they used. Each PC participating in a scene should make an Initiative check, as should each sufficiently important NPC (minion NPCs can generate initiative value without a check, using their focus or vigilance attribute).<br><br><b>Determine Initiative Values</b><br> A character's initiative value is based on their state of preparedness when the conflict began.<br> <span class='L5R'>b</span> If the character was ready for the conflict, their base initiative value is their focus attribute. <br><span class='L5R'>b</span> If the character was unprepared (such as when surprised), their base initiative value is their vigilance attribute.<br>Then, if the character succeeded on their Initiative check, they add 1 to their base initiative value, plus an additional amount equal to their bonus successes.<br><br><b>Set Initiative Order</b><br>Organize the characters by their initiative value, highest to lowest, and record this initiative order along with the values. This is the sequence in which the characters act during Phase 2: Take Turns in many conflict types. If two or more characters have the same initiative value, the one with the lowest honor attribute acts first, followed by the others in ascending order of honor",
	Clashes:"(Core p264) <br><br>Even as lesser combatants swirl around them, heroes frequently mark each other out for challenges. A clash is one way to embed a duel in another scene. Clashes can arise from the use of the Challenge action, or via narrative events that lead to a formal duel occurring during another scene (such as an intrigue). <br><br><b>Fighting a clash</b><br>At the end of the round, participants fight one round of a duel using these steps: 1. Staredown: The characters receive strife equal to the round of the clash and bid strife to increase their current initiative. 2. Take Turns: The character with the higher initiative value takes a turn, followed by the one with the lower value (if tied, the one with lower honor acts first). 3. Determine Winner: If a character inflicts the Incapacitated, Unconscious, or Dying condition on their enemy (or kills them) without suffering any of these, they win. Otherwise, the clash is inconclusive.<br><br><b>Finishing Blows</b><br>Like duels, clashes use the rules for Finishing Blows (Core p259) when a character becomes Compromised or unmasks. <br><br><b>Interrupting a clash</b><br>Other characters can interrupt a clash before it begins or during the clash. Using the Challenge action on an enemy involved in a clash allows a character to 'cut in,'' exchanging themself for an ally in a clash. Any other form of interruption requires the character to forfeit 10 honor. Any participant they helped must also forfeit their staked honor. <br><br><b>Extending a clash</b><br>After characters clash inconclusively, they may extend the clash by one round. If both characters choose to continue, they skip their turns in the initiative order and do not take actions until the clash resumes at the end of the next round. If either character chooses to withdraw, the clash ends.",

	"//":"",

		Assist:"(Core p263)<br><br>As an Attack, Scheme, and Support action, describe how you are helping one other character at range 0-2 with their next action.<br><br>If the GM accepts your suggestion, you provide assistance (Core p26) on the chosen character&apos;s next action check.  Skilled assistance adds <span class='L5R white'>D</span> while unskilled assistance adds <span class='L5R'>d</span>." ,
		"Calming Breath":"(Core p263)<br><br>As a Support action, you may take a deep breath to calm yourself and recover stamina.<br><br>If your strife is greater than half your composure, you remove 1 <span class='L5R'>T</span>. If your fatigue is greater than half your endurance, you remove 1 fatigue.",
		Challenge:"(Core p263)<br><br>As a Scheme action, you may make a TN 1 Command check to issue a formal combat challenge targeting one character at range 0-5. You must stake 10 honor and 5 glory upon the challenge, which you forfeit if you sabotage the clash. <br><br>Effects: If you succeed, the target must choose whether to accept or decline; resolve one of the following: <br><br><span class='L5R'>b</span> If the target accepts, they stake 10 honor and 5 glory, which they forfeit if they take any Attack or Scheme action before the clash. At the end of the round, the clash begins. <br><br><span class='L5R'>b</span> To decline, the target must forfeit glory equal to your ranks in Command plus your bonus successes. Each of their allies with lower glory than you suffers 2 strife. Then, you gain 1 Void point. If you win the clash, each of your foe&apos;s allies in the skirmish suffers 3 <span class='L5R'>T</span>. If you lose the clash, each of your allies suffers 3 <span class='L5R'>T</span>.",
		Guard:"(Core p264)<br><br>As a Support action using a readied weapon, you may make a TN 1 Tactics check targeting yourself or one other character within the weapon's range.<br><br>If you succeed, you guard the target until the beginning of your next turn. Increase the TN of Attack checks against the guarded target by one, plus an additional one per two bonus <span class='L5R'>S</span>." ,
		Maneuver:"(Core p264)<br><br>As a Movement action, you may reposition for more distance. Optionally, you may make a TN 2 Fitness check as part of this action.<br><br>Move one range band. If you choose to make the Fitness check and you succeed, you may instead move two range bands, plus one additional range band per two bonus <span class='L5R'>S</span>." ,
		"Prepare Item":"(Core p264)<br><br>As a Support action, you may interact with one item.<br><br>Prepare one item for use, ready a weapon in a grip of your choice, or stow an item." ,
		Strike:"(Core p264)<br><br>As an Attack action using one readied weapon, you may make a TN 2 Martial Arts check using the appropriate skill for the weapon, targeting one character within the weapon's range.<br><br>If you succeed, you deal physical damage to the target equal to the weapon's base damage plus your bonus successes.  <br><br><span class='L5R'>O</span> <span class='L5R'>O</span>: If you succeed, you inflict a critical strike on your target with severity equal to your weapon's deadliness." ,
		"Unique Actions":"(Core p264)<br><br>As an action, you make a skill check to attempt a task you have described to the GM.<br><br>If you succeed, you may use the skill for its narrative effects, for implementing any sample use that can be completed in a single action, or for pursuing another task that the GM deems appropriate." ,
		Wait:"(Core p264)<br><br>As an Attack, Scheme, and Support action, you may declare a non-Movement action you will perform after the occurrence of a specified event before the end of the round.<br><br>After the specified event occurs before the end of the round, you may perform the action. You must still use the ring matching your stance for this action.  If the specified event does not occur this round, you may perform one action of your choice (other than Wait) at the end of the round.", 
	

	},
"Intrigue Actions":{

	"Intrigue Initiative":" <br><br>For an intrigue, the Initiative check is a <b>TN 1 Sentiment</b> check not just to listen, but to politely probe other characters&apos; strengths, weaknesses, and perhaps most importantly, objectives. A character can use any ring for this check. After a character resolves their Initiative check, that character enters the stance matching the ring they used. Each PC participating in a scene should make an Initiative check, as should each sufficiently important NPC (minion NPCs can generate initiative value without a check, using their focus or vigilance attribute).<br><br><b>Determine Initiative Values</b><br> A character's initiative value is based on their state of preparedness when the conflict began.<br><span class='l5r'>b</span> If the character was ready for the conflict, their base initiative value is their focus attribute. <br><span class='l5r'>b</span> If the character was unprepared (such as when surprised), their base initiative value is their vigilance attribute.<br>Then, if the character succeeded on their Initiative check, they add 1 to their base initiative value, plus an additional amount equal to their bonus successes.<br><br><b>Set Initiative Order</b><br>Organize the characters by their initiative value, highest to lowest, and record this initiative order along with the values. This is the sequence in which the characters act during Phase 2: Take Turns in many conflict types. If two or more characters have the same initiative value, the one with the lowest honor attribute acts first, followed by the others in ascending order of honor.<br><br>Intrigues are relatively freeflowing scenes, so each character takes one turn when they see fit during each round, rather than at an appointed time based on the initiative order. Initiative values instead come into play when two or more characters wish to act simultaneously, at which point the character with the highest initiative acts first, followed by the character with the next highest initiative, and so on. However, because propriety is vitally important in Rokugan, a character must forfeit 1 honor and 1 glory to preempt one or more characters of higher status in this way (and might suffer further narrative ramifications for doing so, depending on circumstances).",

	"//":"",

		"Appeal to a Person or Group":"(Core p255)<br><br>A general social objective that covers many reasons a character would enter an intrigue, this objective signifies that the character is trying to convince someone to behave in a certain way. Often, this objective is directed at a character's lord, in an effort to get the lord to back the character in one of their efforts or take one of their claims seriously. However, it might also be used to get a belligerent party to agree to come to terms, to sway a judge away from (or toward) meting out a punishment, or to win wide support from a large number of people. A character who chooses this objective should state their target at the outset, along with what they want to persuade them to believe or do.<br><br><b>What Does It Take to Complete?</b><br>A character can get someone else to adopt their viewpoint by accumulating a preset number of momentum points on successful Social skill checks against that target. The GM sets the difficulty value to complete this objective (and can tell the players this value, or not, at their discretion). The focus attribute of the target of the Persuade action is a good starting value for this number, but the GM can adjust this value up or down based on factors like stubbornness and the character's innate resistance to the perspective being proposed.<br><br>		<b>What Is Achieved by Completing It?</b><br>At the end of any round in which a character accumulates momentum points equal to or exceeding the difficulty value of the objective, the target is persuaded to adopt their perspective (or stops raising an argument against it). If another character has accumulated a greater number of momentum points at that time, that character persuades the target to adopt their perspective instead. In the case of a tie, the character with the highest status wins. Various circumstances, such as certain ways of unmasking (on the part of the person doing the persuading or the target) or narrative events such as giving grave offense or creating a significant interruptions, can make it impossible to sway someone during the course of an intrigue, in which case this social objective cannot be completed. Additionally, if the target retires from the scene before completion of this social objective (whether or not they have completed a separate personal social objective), this social objective cannot be completed..",

		"Discern Qualities":"(Core p255) <br><br>Sometimes, information-gathering is a character's main social objective: they seek to ferret out the strengths, weaknesses, or loyalties of another character. This goes deeper than understanding their target's social objective; it extends to trying to get a measure of their target's character. Beyond quiet observation, this objective requires engaging with a target to draw out their less obvious qualities. A character who chooses this objective should state their target at the outset, along with which features of their target they want to uncover.<br><br><b>What Does It Take to Complete?</b><br>A character can draw out and study someone else's nature by accumulating momentum points equal to or exceeding the difficulty value of the objective on appropriate Social skill checks against that target. A character might also investigate the target with other skills (like Culture or Sentiment) to fulfill this objective. The GM sets the number of momentum points needed to achieve this objective (and can tell the player this value or not, at their discretion). The vigilance attribute of the target is a good starting value for this number, but the GM can adjust this value up or down based on the target's wariness in the situation.<br><br><b>What Is Achieved by Completing It?</b><br>>At the end of any round in which a character accumulates the requisite points, the character learns up to three of the following about their target: social objective, ninjo, giri, composure, endurance, one advantage, one disadvantage. The same option cannot be selected multiple times this way. If the target retires from the scene before completion (after completing their own objective or otherwise), this objective cannot be completed.",

		"Discredit Someone":"(Core p255) <br><br>Provoking one's enemies directly is a dangerous art, but it can put them in positions where they must accept a loss lest their reputation suffer harm. Applying this pressure subtly, without exposing oneself to criticism, is no easy task. A character who chooses this objective should state their target at the outset.<br><br><b>What Does It Take to Complete?</b><br>A character can back someone into a corner by causing them to become Compromised. The character can do this by inflicting strife on the target (or getting others to do so), which in turn is something they can accomplish by using various <span class='l5r'>O</span> (Core p328) and techniques. When the chosen character unmasks, they must forfeit glory equal to their glory rank (as they allow themself to be humiliated or shamed for a moment of vulnerability) unless they retire from the intrigue, and the objective is considered complete. Such provocation makes it very hard to get someone to take the provoker's side in a matter, so if the target's support is vital to a cause, this tactic is usually very ineffective. Further, many samurai respond to this sort of humiliation with a demand for a duel - or with a dagger in the night, if they are of a less-than-honorable persuasion. If the target retires from the scene before completion (after completing their own objective or otherwise), this objective cannot be completed.",

		"Spread a Rumor":"(Core p256) <br><br>Rumors are among the courtier's greatest weapons, and a well-placed rumor can lay the groundwork for future victories. Spies often place rumors in enemy courts as well, to lead foes astray or into cunningly laid traps. A character who chooses this objective should state the rumor they wish to spread at the outset.<br><br><b>What Does It Take to Complete?</b><br>A character can spread a rumor across a group by accumulating momentum points equal to or exceeding the difficulty value of the objective on appropriate Social skill checks. However, no two of those Social skill checks can target the same character, as the rumor must appear to come from multiple sources to be accepted. The GM sets the difficulty value to achieve this objective (and can tell the player this value at their discretion). The vigilance attribute of the character in the scene with the highest status is a good starting point, but the GM can adjust this value up or down based on that character's disposition toward the rumor in question.<br><br><b>What Is Achieved By Completing It?</b><br>At the end of any round in which a character accumulates momentum points equal to or exceeding the difficulty value of the objective, the rumor becomes self-sustaining within the group. This does not necessarily mean that everyone believes it, but they do discuss it, for it is too reputable (or intriguing) to fully ignore. If the character fails at two consecutive checks to spread the rumor, it fails to take root, and this objective cannot be completed in this scene.",

		"//x":"",

		"Assist":"(Core p257) <br><br>Description: You offer an ally an argument they might use, an insight about the opposition, or a novel idea. <br><br>Activation: As an Attack, Intrigue, and Support action, describe how you are helping one other character at range 0-2 with their next action. <br><br>Effects: If the GM accepts your suggestion, you provide assistance (Core p26) on the chosen character's next action check.",

		"Calming Breath":"(Core p257) <br><br>Description: During a conflict, you may inhale deeply before exhaling, drawing upon your inner strength. <br><br>Activation: As a Support action, you may take a deep breath to calm yourself and recover stamina. <br><br>Effects: If your strife is greater than half your composure, you remove 1 strife. If your fatigue is greater than half your endurance, you remove 1 fatigue.",

		"Persuade":"(Core p257) <br><br> Description: You attempt to foster or quell an idea, emotion, or desire in a person (based on the approach you are using, as described in Social Skills, on page 151).<br><br>Activation: As a Scheme action, you make a Social skill check targeting one or more characters who can hear you. The TN of the check is equal to the highest vigilance among your targets. Additionally, if applicable, apply one of the following modifications to the TN based on the skill you use on the check:<br><br><span class='l5r'>b</span> Command: You present a plan with authority, sweeping your targets along with all the confidence a lord should have among their vassals. If each target's status rank is lower than yours, decrease the TN of this check by 1. <br><span class='l5r'>b</span> Courtesy: You present a proposal backed by honeyed words and clever implications - perfect for dealing with one's superiors, but perhaps overly deferential when addressing equals or subordinates. If each target's status rank is higher than yours, decrease the TN of this check by 1. <br><span class='l5r'>b</span> Games/Performance/Other Skills: You offer a diversion from the affairs at hand, turning the conversation to a less pressing topic. If each target's status rank is equal to yours, decrease the TN of this check by 1.<br><br>Effects: If you succeed, you add one momentum point toward an appropriate social objective, plus one additional momentum point for every two bonus successes. Further, any narrative ramifications of your check resolve.",

		"Unique Action":"(Core p257) <br><br> Description: You make a check using a skill for a mechanical or narrative effect, as described in Chapter 3: Skills (Core p140).<br><br>Activation: As an action, you make a skill check to attempt a task you have described to the GM.<Br><br>Effects: If you succeed, you may use the skill for its narrative effects, for implementing any sample use that can be completed in a single action, or for pursuing another task that the GM deems appropriate."},
"Duel Actions":{
	"Duel Initiative":" (Core p259)<br><br>For a duel, the Initiative check is a <b>TN 1 Meditation</b> check to attempt to foresee how the duel will transpire. <br><br><b>Determine Initiative Values</b><br><span class='l5r'>b</span> Base initiative value is the focus attribute. <br>Then, if the character succeeded on their Initiative check, they add 1 to their base initiative value, plus an additional amount equal to their bonus successes.<br>However, <b>each round</b>, at the start of Phase 2: Take Turns, the characters participate in a staredown that modifies initiative.<br><br><b>Staredown</b><br>The staredown is a special step at the start of Phase 2: Take Turns each round. During the staredown, each character receives strife equal to the number of the round (1 strife for the first round, 2 for the second, 3 for the third, and so forth). Additionally, after receiving this strife, each character who is not Compromised may bid additional strife to increase their initiative value for that round. To bid, each participating character secretly chooses a number between 0 and their focus attribute. Then, all simultaneously reveal their number, and each suffers that amount of strife, and adds it to their initiative for the round.",

	"Finishing Blow":" (Core p259)<br><br>As a combatant begins to make a move, a gap sometimes opens in their defenses, giving their foe a chance to end the fight with a well-placed attack. <br><br>The first time their opponent becomes Compromised or unmasks during a duel, a character may immediately execute a finishing blow. This is a special action that can be performed out of turn. <br><br>A character executes the finishing blow by choosing an Attack action and performing it against their opponent, interrupting anything their target is doing (including resolving a check of their own, in which case the finishing blow resolves during Step 6 of the check, after <span class='l5r'>T</span> symbols are resolved but before <span class='l5r'>O</span> is spent). One finishing blow can even interrupt another! <br><br>If the character executing a finishing blow succeeds, instead of dealing damage, the finishing blow inflicts a critical strike with severity equal to two times the deadliness of the weapon or Attack action used, plus the attacker's bonus successes. Any other effects of the Attack action are resolved as usual. <br><br>If two characters trigger finishing blows simultaneously for any reason (such as the mandatory strife gained during the staredown), the one with the lower honor fully executes their finishing blow first, then the other character executes theirs (assuming they are still alive!). If the duel's objective is achieved by the finishing blow, the duel ends immediately. Otherwise, the duel picks up where it left off (including returning to resolving a check, if one was interrupted).",

	"//":"",

	"Calming Breath":"(Core p260)<br><br>Description: During a conflict, you may inhale deeply before exhaling, drawing upon your inner strength.<br><br>Activation: As a Support action, you may take a deep breath to calm yourself and recover stamina.<Br><br>Effects: If your strife is greater than half your composure, you remove 1 strife. If your fatigue is greater than half your endurance, you remove 1 fatigue.",
	"Center":"(Core p260)<br><br>Description: You let the world around you slow as the Void overtakes your senses. Everything but the moment fades as you instinctively seek victory. Your mind weaves through infinite treacherous possibilities and the razor steel of your foe to the outcome you desire.<br><br>Activation: As a Support action in Void stance, you may focus your energy inward, envisioning your action in your mind and seeking the perfect moment to take it. You must name a skill when you use Center.<br><br>Effects: Roll a number of Skill dice up to your ranks in the skill you chose and reserve any number of those dice. If you do, the next time you make a check using the chosen skill (or use the Center action) this scene, after rolling dice, you may replace any number of rolled dice with the reserved dice (set to the results they were showing when reserved). You cannot reserve a number of dice greater than your ranks in the skill this way.",
	"Predict":"(Core p260)<br><br>Description: You shift subtly to draw a reaction out of your foe by repositioning or signaling a strike you never intend to throw. By predicting your foe's reaction, you aim to win the battle in the mind, leaving the foe open to a decisive strike or forcing them to attack early.<br><br>Activation: As an Attack and Scheme action, you may secretly select Air, Earth, Fire, or Water and record it.<br><br>Effects: The next time your opponent chooses their stance, you may reveal your selection; if it matches the stance they chose, your opponent receives 4 strife and must choose a different stance. This effect persists until the end of your next turn.",
	"Prepare Item":"(Core p260)<br><br>Description: You prepare, ready, or stow one weapon or other item.<br><br>Activation: As a Support action, you may use this action.<br><br>Effects: Prepare one item for use, ready a weapon in a grip of your choice, or stow an item.",
	"Strike":"(Core p260)<br><br>Description: You make an attack against a single foe.<br><br>Activation: As an Attack action using one readied weapon, you may make a TN 2 Martial Arts check using the appropriate skill for the weapon, targeting one character within the weapon's range.<br><br>Effects: If you succeed, you deal physical damage to the target equal to the weapon's base damage plus your bonus successes.<br><br>New Opportunities<br><span class='l5r'>O</span> <span class='l5r'>O</span>: If you succeed, inflict a critical strike on your target with severity equal to your weapon's deadliness.",
	"Unique Action":"(Core p260)<br><br>Description: You make a check using a skill for a mechanical or narrative effect, as described in Chapter 3: Skills (Core p140).<br><br>Activation: As an action, you make a skill check to attempt a task you have described to the GM.<br><br>Effects: If you succeed, you may use the skill for its narrative effects, for implementing any sample use that can be completed in a single action, or for pursuing another task that the GM deems appropriate.",},
"Advantages and Disadvantages": {
	"Inverting your Advantage":"(Core p100) <br><br>If one of a character's advantages creates a logical vulnerability for that character on a specific check, the GM may invert that advantage, causing it to be applied as a corresponding disadvantage for the check (a distinction becoming an adversity, or a passion becoming an anxiety, for instance). If the GM does so, the character gains 1 Void point after resolving the check.",
	"Seizing an Advantage":"(Core p101) <br><br>Advantages of other characters can also be used against them sometimes. If a character's check has one or more targets, their player may choose one of the target's known advantages that logically could be a weakness for that check. If the GM agrees, the player may spend 1 Void point to seize the target's advantage, causing it to be applied as an advantage on the player's check.",
	"Leveraging your Disadvantage":"(Core p101) <br><br>If one of a character's disadvantages creates a logical edge for that character on a specific check and the GM agrees, the player may spend 1 Void point to leverage that disadvantage, causing it to be applied as a corresponding advantage for the check (an adversity becoming a distinction, or an anxiety becoming a passion, for instance).",
	"Exploiting a Disadvantage":"(Core p101) <br><br>If the check has one or more targets, the player may choose a known disadvantage of one of the targets that logically could be used against the target on that check. If the GM agrees, the player may spend 1 Void point to exploit the target's disadvantage, causing it to be applied as a corresponding advantage on the check (an adversity becoming a distinction, or an anxiety becoming a passion, for instance)",
},

Skills:{
	Aesthetics: "<br><br><span class='l5r'>b</span> Restore Approach (<span class='l5r earth'>e</span>): Restoring a damaged piece, maintaining something's beauty, safely transporting a piece. <br><br><span class='l5r'>b</span> Adapt Approach (<span class='l5r water'>w</span>): Altering an existing work, completely reworking or rebuilding an existing piece, finding inspiration for new works. <br><br><span class='l5r'>b</span> Invent Approach (<span class='l5r fire'>f</span>): Creating a new work, brainstorming new possible works, developing new methods and techniques for creating art. <br><br><span class='l5r'>b</span> Refine Approach (<span class='l5r air'>a</span>): Finding a flaw in a piece and removing it, adding a detail that enhances a piece, hiding a subtle message within a work. <br><br><span class='l5r'>b</span> Attune Approach (<span class='l5r void'>v</span>): Learning a work's purpose, discerning whether a work has any supernatural qualities or features and awakening those features within it.  ",	

	Composition:" <br><br><span class='l5r'>b</span> Restore Approach (<span class='l5r earth'>e</span>): Restoring an old text that has been damaged by time or exposure, annotating a difficult text with references that make it easier for readers to understand, transcribing a work without errors. <br><br><span class='l5r'>b</span> Adapt Approach (<span class='l5r water'>w</span>): Translating a text from another language, adapting a work for a new medium, using an old quote in a new context that reframes its meaning, combining visual elements with textual elements. <br><br><span class='l5r'>b</span> Invent Approach (<span class='l5r fire'>f</span>): Writing a first draft of a new text, filling in the missing gaps of an incomplete text, brainstorming ideas for new written works. <br><br><span class='l5r'>b</span> Refine Approach (<span class='l5r air'>a</span>): Correcting errors in a work, removing excessive and unnecessary verbiage from a work to make it read more cleanly and quickly, adding a nuanced allusion or reference, introducing implications and subtext. <br><br><span class='l5r'>b</span> Attune Approach (<span class='l5r void'>v</span>): Understanding a writer's deeper purpose behind a work, discerning whether a work has any supernatural qualities or features, learning about oneself from a text  "	,

	Design: "<br><br><span class='l5r'>b</span> Restore Approach (<span class='l5r earth'>e</span>): Stitching up a tear in a damaged piece of clothing, storing a piece of clothing such that it will not degrade, replacing lost parts of a piece of clothing. <br><br><span class='l5r'>b</span> Adapt Approach (<span class='l5r water'>w</span>): Repurposing an old piece of clothing to serve a new function, adding a new element to an outfit to let it function in different circumstances, turning an old piece of clothing into raw materials for a new project.  <br><br><span class='l5r'>b</span> Invent Approach (<span class='l5r fire'>f</span>): Sewing a new piece of clothing, inventing a new style, crafting a new accessory, conjecturing about possible new trends in clothing. <br><br><span class='l5r'>b</span> Refine Approach (<span class='l5r air'>a</span>): Improving an existing piece of clothing with embellishment, choosing clothes that send a specific message, adding filigree to a piece of jewelry that enhances its beauty. <br><br><span class='l5r'>b</span> Attune Approach (<span class='l5r void'>v</span>): Learning the deeper purpose for which a piece of clothing was made, discerning whether a worn item has any supernatural features, awakening the supernatural properties slumbering in an object of power. ", 	

	Smithing:" <br><br><span class='l5r'>b</span> Restore Approach (<span class='l5r earth'>e</span>): Repairing a damaged weapon or piece of armor, performing routine upkeep and cleaning on a weapon or piece of armor, treating a weapon or piece of armor to prevent rust and corrosion. <br><br><span class='l5r'>b</span> Adapt Approach (<span class='l5r water'>w</span>): Improving an existing weapon or piece of armor, reshaping a mundane item into a weapon, sizing a weapon for a new wielder, salvaging a destroyed sword to reforge it. <br><br><span class='l5r'>b</span> Invent Approach (<span class='l5r fire'>f</span>): Forging a new blade, crafting a new piece of armor, inventing a new weapon or piece of armor, conjecturing about possible new weapons and armor technologies. <br><br><span class='l5r'>b</span> Refine Approach (<span class='l5r air'>a</span>): Polishing a blade to hone its edge, improving a spear's grip, adding embellishments to a naginata to accent the beautiful wave pattern of the steel. <br><br><span class='l5r'>b</span> Attune Approach (<span class='l5r void'>v</span>): Learning the purpose for which a weapon or piece of armor was forged, discerning whether a weapon or piece of armor has any supernatural features, unlocking supernatural potential within a forged item.",  	

	"//1":"",

	Command: "<br><br><span class='l5r'>b</span> Reason Approach (<span class='l5r earth'>e</span>): Verbally reprimanding a group of soldiers who have grown lax in their duties, establishing order on a chaotic battlefield, making someone afraid of the consequences of their actions. <br><br><span class='l5r'>b</span> Charm Approach (<span class='l5r water'>w</span>): Cultivating loyalty from troops under your command, motivating troops with a promised reward, getting a mixed force to stop squabbling, making someone afraid of letting you down.  <br><br><span class='l5r'>b</span> Incite Approach (<span class='l5r fire'>f</span>): Restoring morale to weary troops, stoking an old grudge, getting others to follow you despite danger to life and limb, making someone afraid of you personally. <br><br><span class='l5r'>b</span> Trick Approach (<span class='l5r air'>a</span>): Giving an assignment without letting on to the dangers it entails, misleading your own troops to confuse your enemy, communicating in code with your troops. <br><br><span class='l5r'>b</span> Enlighten Approach (<span class='l5r void'>v</span>): Convincing troops embroiled in a battle to see its pointlessness, persuading enemy soldiers that their cause is not just, snapping someone out of shock or a rage in battle.",  	

	Courtesy: "<br><br><span class='l5r'>b</span> Reason Approach (<span class='l5r earth'>e</span>): Convincing someone to listen to reason rather than their emotions, reminding someone of their duties, convincing someone to wait rather than acting and suffering potential consequences. <br><br><span class='l5r'>b</span> Charm Approach (<span class='l5r water'>w</span>): Getting someone to like or trust you, fostering desire for something or someone in a person, altering someone's current desires, efficiently making your way through the complex bureaucracy of a court by being pleasant and gregarious. <br><br><span class='l5r'>b</span> Incite Approach (<span class='l5r fire'>f</span>): Convincing someone to listen to their emotions rather than reason, reminding someone of their desires, drawing attention to yourself, getting someone to ignore risks before them, insulting someone openly. <br><br><span class='l5r'>b</span> Trick Approach (<span class='l5r air'>a</span>): Convincing someone of something untrue (or incomplete), deflecting attention from yourself onto others, spreading a rumor about someone, leading someone to an idea to convince them it is their own, insulting someone subtly and deniably. <br><br><span class='l5r'>b</span> Enlighten Approach (<span class='l5r void'>v</span>): Using well-chosen words to get someone to question a truth they held as absolute, getting someone to remember their true self when they are acting out of fear, despair, rage, or supernatural influence.  ",	

	Games: "<br><br><span class='l5r'>b</span> Reason Approach (<span class='l5r earth'>e</span>): Playing without upsetting your opponent, playing cautiously, instructing someone else in the basics of a game, minimizing your losses. <br><br><span class='l5r'>b</span> Charm Approach (<span class='l5r water'>w</span>): Using a game to build a rapport with your opponent (or someone else present), playing casually, using a game to get your opponent to trust you. <br><br><span class='l5r'>b</span> Incite Approach (<span class='l5r fire'>f</span>): Using a game to make your opponent angry or afraid, playing aggressively, spurring your opponent to wager more, developing new tactics in a game. <br><br><span class='l5r'>b</span> Trick Approach (<span class='l5r air'>a</span>): Using a game to uncover your opponent's strengths and weaknesses, playing deceptively, cheating, losing deliberately (without being obvious), sending a subtle message through your play. <br><br><span class='l5r'>b</span> Enlighten Approach (<span class='l5r void'>v</span>): Using a game to shock your opponent into seeing something clearly, playing minimally, leaving the fate of the game to pure chance.  	",

	Performance: "<br><br><span class='l5r'>b</span> Reason Approach (<span class='l5r earth'>e</span>): Transmitting some moral lesson to your audience, soothing your audience, educating your audience on a particular matter, setting your audience members' minds at ease. <br><br><span class='l5r'>b</span> Charm Approach (<span class='l5r water'>w</span>): Gaining your audience's sympathy, causing your audience to desire something, building a positive rapport with your audience. <br><br><span class='l5r'>b</span> Incite Approach (<span class='l5r fire'>f</span>): Rousing your audience into a state of excitement, intentionally needling your audience, stirring your audience to immediate action. <br><br><span class='l5r'>b</span> Trick Approach (<span class='l5r air'>a</span>): Giving an extremely convincing performance, getting your audience to come to a particular conclusion without stating it outright, impersonating others convincingly. <br><br><span class='l5r'>b</span> Enlighten Approach (<span class='l5r void'>v</span>): Causing your audience to reevaluate something in their lives, breaking your audience out of an emotional rut such as sorrow or rage, delivering a message to your audience in spite of supernatural interference. ", 	

	"//2":"",

	Culture: "<br><br><span class='l5r'>b</span> Recall Approach (<span class='l5r earth'>e</span>): Remembering the names of the most influential members of a particular court, knowing the particular customs of a region, remembering the geographical features of an area. <br><br><span class='l5r'>b</span> Survey Approach (<span class='l5r water'>w</span>): Identifying a fellow samurai using their clan, family, and personal mon (crest); identifying an object's region of origin; identifying a samurai's general status by their manner of dress; identifying which cultures have influenced a location; determining one's location in an unfamiliar city based on common architectural patterns. <br><br><span class='l5r'>b</span> Theorize Approach (<span class='l5r fire'>f</span>): Guessing where an influential person might go in an unfamiliar city, conjecturing about the proper decorum for an unusual social situation, anticipating social trends in different regions. <br><br><span class='l5r'>b</span> Analyze Approach (<span class='l5r air'>a</span>): Detecting traces of a regional accent in a character's speech, noticing slight imperfections in a mon or personal chop that reveal it to be a forgery, assessing the way a practice differs in a specific region. <br><br><span class='l5r'>b</span> Sense Approach (<span class='l5r void'>v</span>): Identifying the purpose traditions fulfill in society, identifying the rising stars at a particular court, intuiting the supernatural underpinnings of a cultural practice. ", 

	Government: "<br><br><span class='l5r'>b</span> Recall Approach (<span class='l5r earth'>e</span>): Knowing the letter of the law, knowing the explicit structure of government, knowing about past events and legal precedents, knowing political history and precedent in detail, knowing past scholars of history and law and quoting their works. <br><br><span class='l5r'>b</span> Survey Approach (<span class='l5r water'>w</span>): Identifying an illegal act, reading the tacit structure of power, determining who to ask to get something done within a bureaucracy, noticing classic bureaucratic schemes and ploys put into play by one's opponents. <br><br><span class='l5r'>b</span> Theorize Approach (<span class='l5r fire'>f</span>): Understanding the various ways the law could be applied in an unprecedented case, framing an argument about why the law should be applied differently in a particular instance, guessing the political ramifications of a new ruler's ascension. <br><br><span class='l5r'>b</span> Analyze Approach (<span class='l5r air'>a</span>): Finding a contradiction or loophole in a system or the law, assessing the strengths and weaknesses of a legal argument, studying a system in detail to find the places where pressure can be applied to get specific results. <br><br><span class='l5r'>b</span> Sense Approach (<span class='l5r void'>v</span>): Knowing how likely a given verdict is in a particular case, identifying the candidate most likely to hold a position next, knowing the likelihood of success for a particular ploy or scheme.  ",

	Medicine: "<br><br><span class='l5r'>b</span> Recall Approach (<span class='l5r earth'>e</span>): Studying and recalling existing remedies, creating bandages and medical supplies (Restore), stanching blood loss (Restore), mending other minor harm (Restore). <br><br><span class='l5r'>b</span> Survey Approach (<span class='l5r water'>w</span>): Identifying helpful and harmful herbs, gathering ingredients, finding hazards and contaminants in an environment, brewing remedies (Adapt), relieving exhaustion and pain (Adapt), speeding patients' recovery from long-term illness and injury (Adapt). <br><br><span class='l5r'>b</span> Theorize Approach (<span class='l5r fire'>f</span>): Studying new medicines and treatments, treating unknown ailments, experimenting with unknown ingredients (Invent), brewing poisons (Invent), instilling patients with energy (Invent). <br><br><span class='l5r'>b</span> Analyze Approach (<span class='l5r air'>a</span>): Recognizing symptoms, diagnosing diseases and ailments in patients, performing surgery in the field or a place of healing (Refine), administering medicines and poisons in the proper dosage for the desired effect (Refine). <br><br><span class='l5r'>b</span> Sense Approach (<span class='l5r void'>v</span>): Detecting spiritual ailments, working entirely without ingredients, realigning the energy in others (Attune), treating spiritual ailments (Attune). ", 

	Sentiment: "<br><br><span class='l5r'>b</span> Recall Approach (<span class='l5r earth'>e</span>): Detecting inconsistencies between someone's current and past behavior, understanding someone's fears and responsibilities, determining how best to set someone at ease. <br><br><span class='l5r'>b</span> Survey Approach (<span class='l5r water'>w</span>): Discerning someone's personal feelings about a person or subject (and whether they are positive, negative, or neutral), detecting whether someone's intentions are hostile, understanding someone's desires, determining how best to win someone's approval or support. <br><br><span class='l5r'>b</span> Theorize Approach (<span class='l5r fire'>f</span>): Determining whether someone has left out important details or told you a lie of omission, catching that someone has left out something important, understanding someone's convictions and ideals, determining how best to excite or enrage someone. <br><br><span class='l5r'>b</span> Analyze Approach (<span class='l5r air'>a</span>): Knowing whether someone is lying to you directly, knowing how a choice or action will make someone feel, understanding someone's self-perceptions and vulnerabilities, determining how best to get someone to do something you want. <br><br><span class='l5r'>b</span> Sense Approach (<span class='l5r void'>v</span>): Determining whether someone is under the effects of supernatural persuasion or a supernatural being, studying and understanding one's own emotions, determining whether someone is acting in opposition to their own desires or is suppressing their emotions, knowing the purpose behind someone's words.",  

	Theology: "<br><br><span class='l5r'>b</span> Recall Approach (<span class='l5r earth'>e</span>): Knowing facts about the formal doctrines of religious traditions of the Emerald Empire, knowing about historical occurrences of supernatural events, correctly reciting scripture, remembering the weaknesses of a supernatural being from folklore, communing with earth kami. <br><br><span class='l5r'>b</span> Survey Approach (<span class='l5r water'>w</span>): Identifying religious artifacts and supernatural phenomena, knowing how the average person of a given walk of life interacts with spiritual traditions, researching a piece of scripture to learn its meaning, communing with water kami. <br><br><span class='l5r'>b</span> Theorize Approach (<span class='l5r fire'>f</span>): Guessing what supernatural forces might be at work based on secondary evidence, reconciling two contradictory pieces of religious doctrine, offering a novel explanation of the meaning of a piece of scripture, communing with fire kami. <br><br><span class='l5r'>b</span> Analyze Approach (<span class='l5r air'>a</span>): Determining how religious or spiritual a person is and what traditions they follow, finding and untangling subtle nuance or apparent contradictions in scripture, noticing the telltale signs of a supernatural creature walking among humans, communing with air kami. <br><br><span class='l5r'>b</span> Sense Approach (<span class='l5r void'>v</span>): Performing divinations, determining the veracity of a supernatural occurrence, predicting the behavior of supernatural entities, knowing the philosophical ramifications of a decision, communing with the root of the universe. ", 

	"//3":"",

	Fitness: "<br><br><span class='l5r'>b</span> Withstand Approach (<span class='l5r earth'>e</span>): Moving cautiously, pushing one's body to the breaking point without suffering permanent harm, marching long distances, holding up heavy objects for long periods of time, hiding by standing still, taking a hit. <br><br><span class='l5r'>b</span> Shift Approach (<span class='l5r water'>w</span>): Moving around obstacles and through crowds without slowing, fitting through small spaces, performing exercises to speed recovery from injury, losing pursuers in a crowd, rolling with the punches. <br><br><span class='l5r'>b</span> Overwhelm Approach (<span class='l5r fire'>f</span>): Moving without heed for obstacles, leaping long distances, pushing and lifting heavy objects quickly, breaking things, catching someone in a footrace, meeting incoming attacks with equal opposing force. <br><br><span class='l5r'>b</span> Feint Approach (<span class='l5r air'>a</span>): Moving stealthily, maintaining balance, trailing someone without their realizing it, falling safely and landing gracefully, evading someone in a footrace, controlling where hits land on your body. <br><br><span class='l5r'>b</span> Sacrifice Approach (<span class='l5r void'>v</span>): Acting on sheer instinct, pushing one's body beyond the breaking point to achieve a goal, overcoming physical limitations with sheer will, taking hits directly. ", 

	Melee: "<br><br><span class='l5r'>b</span> Withstand Approach (<span class='l5r earth'>e</span>): Fighting defensively, blocking carefully, exhausting your opponent, practicing techniques that rely on stamina. <br><br><span class='l5r'>b</span> Shift Approach (<span class='l5r water'>w</span>): Fighting reactively, redirecting force, drawing out your opponent, practicing techniques that rely on fluidity of motion and flexibility. <br><br><span class='l5r'>b</span> Overwhelm Approach (<span class='l5r fire'>f</span>): Fighting aggressively, attacking directly, unnerving your opponent, practicing techniques that rely on bursts of speed and power. <br><br><span class='l5r'>b</span> Feint Approach (<span class='l5r air'>a</span>): Fighting subtly, attacking indirectly, outmaneuvering your opponent, evading attacks, practicing techniques that rely on grace and poise, reading your opponent's moves. <br><br><span class='l5r'>b</span> Sacrifice Approach (<span class='l5r void'>v</span>): Fighting instinctively or without regard for your life, attacking without regard for anything else, putting mind over matter. ", 

	Ranged: "<br><br><span class='l5r'>b</span> Withstand Approach (<span class='l5r earth'>e</span>): Maintaining a consistent field of fire, suppressing targets, firing to keep targets from overtaking a position, properly stowing ranged weapons. <br><br><span class='l5r'>b</span> Shift Approach (<span class='l5r water'>w</span>): Fighting reactively, redirecting force, drawing out your opponent, firing to create openings to reposition. <br><br><span class='l5r'>b</span> Overwhelm Approach (<span class='l5r fire'>f</span>): Firing to deplete enemy forces, firing to allow allies to advance, firing to terrify the enemy. <br><br><span class='l5r'>b</span> Feint Approach (<span class='l5r air'>a</span>): Firing without giving away your position, hitting specific parts of your target, firing to create vulnerabilities in the target's defenses. <br><br><span class='l5r'>b</span> Sacrifice Approach (<span class='l5r void'>v</span>): Exposing yourself to get a shot on your target, putting your faith in the universe that your shot will find its mark.",  

	Unarmed: "<br><br><span class='l5r'>b</span> Withstand Approach (<span class='l5r earth'>e</span>): Fighting defensively, blocking forcefully, exhausting your opponent, practicing techniques that rely on stamina. <br><br><span class='l5r'>b</span> Shift Approach (<span class='l5r water'>w</span>): Fighting reactively, redirecting force, drawing out your opponent, practicing techniques that rely on fluidity of motion and flexibility. <br><br><span class='l5r'>b</span> Overwhelm Approach (<span class='l5r fire'>f</span>): Fighting aggressively, attacking directly, unnerving your opponent, practicing techniques that rely on bursts of speed and power. <br><br><span class='l5r'>b</span> Feint Approach (<span class='l5r air'>a</span>): Fighting subtly, attacking indirectly, outmaneuvering your opponent, evading attacks, practicing techniques that rely on grace and poise. <br><br><span class='l5r'>b</span> Sacrifice Approach (<span class='l5r void'>v</span>): Attacking without regard for anything else, including your life, putting mind over matter ", 

	Meditation: "<br><br><span class='l5r'>b</span> Withstand Approach (<span class='l5r earth'>e</span>): Using logic to overcome your personal feelings, reflecting on the nature of your responsibilities, maintaining a level head despite challenges and provocation, resisting temptation. <br><br><span class='l5r'>b</span> Shift Approach (<span class='l5r water'>w</span>): Understanding your own emotions and desires, reflecting on the nature of your desires, understanding how to align your goals with your desires, resisting rage. <br><br><span class='l5r'>b</span> Overwhelm Approach (<span class='l5r fire'>f</span>): Using your emotions to reject a seemingly inevitable conclusion before you, maintaining concentration on a single topic, staying in an emotional state for long periods of time, resisting fear. <br><br><span class='l5r'>b</span> Feint Approach (<span class='l5r air'>a</span>): Convincing yourself of the truth of something, finding weaknesses in your viewpoints and ideologies, understanding how to align your goals with your ideals, resisting despair. <br><br><span class='l5r'>b</span> Sacrifice Approach (<span class='l5r void'>v</span>): Understanding your place in the universe, understanding the role fate has provided for you, knowing what you are willing to give up to achieve your goals, seeing glimpses of your own future, resisting supernatural mental interference. ", 

	Tactics: "<br><br><span class='l5r'>b</span> Withstand Approach (<span class='l5r earth'>e</span>): Resisting a head-on assault, holding a point at all costs, mitigating losses during a retreat, overseeing the construction of siege weapons. <br><br><span class='l5r'>b</span> Shift Approach (<span class='l5r water'>w</span>): Executing a counterattack, repositioning swiftly after an attack, taking full advantage of useful terrain, moving and operating siege weapons. <br><br><span class='l5r'>b</span> Overwhelm Approach (<span class='l5r fire'>f</span>): Executing a head-on assault, overrunning the enemy, breaking enemy morale with terrifying tactics, designing siege weapons. <br><br><span class='l5r'>b</span> Feint Approach (<span class='l5r air'>a</span>): Executing a feigned retreat, flanking the enemy, discerning weaknesses in the enemy's defenses and targets of interest. <br><br><span class='l5r'>b</span> Sacrifice Approach (<span class='l5r void'>v</span>): Sending a unit to die to create a strategic opening, commanding a force without revealing one's identity to the enemy",  

	"//4":"",

	"Animal Handling": "<br><br><span class='l5r'>b</span> Produce Approach (<span class='l5r earth'>e</span>): Calming agitated animals, working routine tasks and tricks. <br><br><span class='l5r'>b</span> Exchange Approach (<span class='l5r water'>w</span>): Gaining an animals's affection, motivating an animal with a promised reward, communicating your feelings to the animal. <br><br><span class='l5r'>b</span> Innovate Approach (<span class='l5r fire'>f</span>): Training an animal to perform a new task or trick, communicating a new concept to the animal, riling up an animal to attack, spurring an animal to move quickly. <br><br><span class='l5r'>b</span> Con Approach (<span class='l5r air'>a</span>): Deceiving or fooling an animal, see through an animal's deception. <br><br><span class='l5r'>b</span> Subsist Approach (<span class='l5r void'>v</span>): Understand an animal's motivation or emotion.",

	Commerce: "<br><br><span class='l5r'>b</span> Produce Approach (<span class='l5r earth'>e</span>): Balancing accounts, storing and maintaining merchandise, moving merchandise safely. <br><br><span class='l5r'>b</span> Exchange Approach (<span class='l5r water'>w</span>): Buying goods from wholesalers, finding a good deal on items and services, bartering on favorable terms, getting an item as cheaply as possible. <br><br><span class='l5r'>b</span> Innovate Approach (<span class='l5r fire'>f</span>): Finding ways to make your product or service distinctive, creating new incentives for customers, inventing a new product or service, finding a new market to serve. <br><br><span class='l5r'>b</span> Con Approach (<span class='l5r air'>a</span>): Convincing someone your goods are of the highest quality or best price, determining a product's monetary value, getting as much money out of a customer as possible, assessing the competition's progress and possible weaknesses. <br><br><span class='l5r'>b</span> Subsist Approach (<span class='l5r void'>v</span>): Operating with minimal expenditures, stretching supplies as far as possible, knowing how product values will change in the future.",  

	Labor: "<br><br><span class='l5r'>b</span> Produce Approach (<span class='l5r earth'>e</span>): Mass-producing items, laying groundwork and foundations, maintaining tools, plowing fields, planting seeds, harvesting crops. <br><br><span class='l5r'>b</span> Exchange Approach (<span class='l5r water'>w</span>): Acquiring items and tools, negotiating with tax collectors, fermenting harvested goods, cooking food. <br><br><span class='l5r'>b</span> Innovate Approach (<span class='l5r fire'>f</span>): Developing tools to make your work easier, drafting new plans and designs, experimenting with new methods, creating new recipes. <br><br><span class='l5r'>b</span> Con Approach (<span class='l5r air'>a</span>): Organizing the work of others on a project, covering over flaws in one's work, disguising one sort of object as another, pretending to work. <br><br><span class='l5r'>b</span> Subsist Approach (<span class='l5r void'>v</span>): Knowing how to expend minimal supplies in your work, using the natural landscape to do your work for you, knowing when to let a field",   

	Seafaring: "<br><br><span class='l5r'>b</span> Produce Approach (<span class='l5r earth'>e</span>): Maintaining boats, maintaining ship logs and records, knowing facts about historical routes, knowing how long supplies will last, filtering out salt to create potable water. <br><br><span class='l5r'>b</span> Exchange Approach (<span class='l5r water'>w</span>): Navigating on the ocean, knowing which routes are the fastest, determining your current location on a body of water, operating a boat. <br><br><span class='l5r'>b</span> Innovate Approach (<span class='l5r fire'>f</span>): Building new boats, map-making, pioneering new routes. <br><br><span class='l5r'>b</span> Con Approach (<span class='l5r air'>a</span>): Convincing someone to hire your ship instead, managing sailors during a voyage, trailing another ship without being noticed, escaping a pursuing vessel, finding signs of the passage of another ship. <br><br><span class='l5r'>b</span> Subsist Approach (<span class='l5r void'>v</span>): Sensing storms before they descend, placating ocean and wind kami with sailors' traditions.  ",

	Skulduggery: "<br><br><span class='l5r'>b</span> Produce Approach (<span class='l5r earth'>e</span>): Securing a location, constructing locks and other security measures, memorizing maps and codes, dividing spoils in an organized manner. <br><br><span class='l5r'>b</span> Exchange Approach (<span class='l5r water'>w</span>): Finding a fence to sell stolen items to, knowing how to move freely through a city while avoiding law enforcement, determining the fastest way to break into a secure facility. <br><br><span class='l5r'>b</span> Innovate Approach (<span class='l5r fire'>f</span>): Creating secret codes, creating new tools for criminal activities, concocting complex plots to slip past security measures, picking an unfamiliar lock. <br><br><span class='l5r'>b</span> Con Approach (<span class='l5r air'>a</span>): Picking someone's pocket, shadowing a mark without being noticed, organizing a group of thieves on a job, tracking someone through a city, knowing the right bribe to secure a corrupt official's cooperation. <br><br><span class='l5r'>b</span> Subsist Approach (<span class='l5r void'>v</span>): Erasing all trace of your presence, blending into a crowd, placating spirits and other supernatural beings who might punish you for your sins.",  

	Survival: "<br><br><span class='l5r'>b</span> Produce Approach (<span class='l5r earth'>e</span>): Creating shelter, storing food. Creating accurate details on a map.<br><br><span class='l5r'>b</span> Exchange Approach (<span class='l5r water'>w</span>): Foraging for food and potable water, fishing, cooking familiar ingredients. <br><br><span class='l5r'>b</span> Innovate Approach (<span class='l5r fire'>f</span>): Finding ways to cook unfamiliar ingredients, building makeshift weapons, finding alternative routes to save travel time. <br><br><span class='l5r'>b</span> Con Approach (<span class='l5r air'>a</span>): Making and using traps, tracking people and animals in the wild, staying out of sight in the wild. <br><br><span class='l5r'>b</span> Subsist Approach (<span class='l5r void'>v</span>): Rationing food and water, sensing natural disasters before they occur, placating mountain and forest kami.",   
}
}