var clans = ["Crab","Crane","Dragon","Lion","Phoenix","Scorpion","Unicorn","Imperial","Minor"];

var ronintypelist = ["Samurai or Ronin Origin","Peasant Origin","Gaijin Origin"]

var clandata = {	
	Crab:{	name:"Crab",
			clanring:{Earth:+1},
			clanskill:"Martial",
			clanstatus:30,
			weapons:["Tetsubo","Otsuchi",],
			armor:["Ashigaru Armor","Lacquered Armor"],
			advantages:["Inured to Horrors (Fire) [Scholar, Martial; Mental]",
					"Veteran of the Shadowlands (Earth) [Scholar, Martial; Mental]",
					"Blood of Osano-Wo (Earth) [Martial, Trade; Spiritual]",
					"Famously Courageous (Fire) [Martial, Social; Interpersonal]",
					],
			disadvantages:[
					"Bluntness (Air) [Social; Interpersonal]",
					"Shadowlands Taint (Earth) [Martial, Social; Curse, Physical, Spiritual]",
					"I don't get this art... (Water) [Social, Artisan; Interpersonal]",
					"Old Battle Wound (Water) [Martial, Trade; Physical, Injury]",
					"Ends Justify The Means (Void) [Scholar; Mental]",
					],
		},
	Crane:{	name:"Crane",
		clanring:{Air:+1},
		clanskill:"Artisan",
		clanstatus:35,
		weapons:["Katana","Wakizashi"],
		armor:["Ceremonial Robes"],
		advantages:["Height of Fashion (Fire) [Artisan, Social; Interpersonal]",
				"Benten's Blessing (Air) [Social; Interpersonal, Spiritual]",
				"In On The Good Gossip (Water) [Social; Interpersonal]",
				"Unflappable Poise (Air) [Social; Interpersonal]",
				],
		disadvantages:["Accustomed to Luxury (Earth) [Martial, Social, Trade; Interpersonal]",
				"Pacifist (Fire) [Martial; Mental, Physical]",
				"Vanity (Air) [Social; Mental]",
				"Purple Mist of Entitlement (Fire) [Social; Interpersonal]",
				],
		},
	Dragon:{name:"Dragon",
			clanring:{Fire:+1},
			clanskill:"Scholar",
			clanstatus:30,
			weapons:["Bo","Ji"],
			armor:["Sanctified Robes"],
			advantages:["Mysterious Personage (Void) [Social; Interpersonal]",
				"Friend of the Brotherhood (Water) [Social; Interpersonal]",
				"Level Headed (Earth) [Martial, Social; Interpersonal, Mental]",
				"Famously Honest (Air) [Social; Interpersonal]"
				],
			disadvantages:["Ascetic (Void) [Social; Mental]",
				"Irresponsible Personage (Earth) [Social; Interpersonal]",
				"Rumors of Worldly Attachments (Void) [Social; Interpersonal]",
				"Detached and Aloof (Water) [Social; Interpersonal, Mental]",
				],

		},
	Lion:{name:"Lion",
			clanring:{Water:+1},
			clanskill:"Martial",
			clanstatus:35,
			weapons:[],
			armor:["Ashigaru Armor"],
			advantages:["Intense and Sincere! (Fire) [Social; Interpersonal]",
						"Famed for a Valiant Battle (Water) [Social; Interpersonal]",
						"Fearless Fighter (Fire) [Social, Martial; Mental]",
				],
			disadvantages:[
				"Painfully Honest (Air) [Social: Mental]",
				"Unbending Pride (Water) [Social; Mental]",
				"Idealistic (Air) [Social: Mental]",
				"No Compassion for Peasants (Water) [Social; Interpersonal]",
				"Craves Glory (Earth) [Social; Interpersonal]",
				],
		},
	Phoenix:{name:"Phoenix",
			clanring:{"Void":+1,},
			clanskill:"Scholar",
			clanstatus:30,
			weapons:["Yumi"],
			armor:["Sanctified Robes"],
			advantages:["Fukurokujin's Blessing (Fire) [Scholar; Mental, Spiritual]",		
					"Just and Idealistic (Earth) [Social; Interpersonal]",
					"Widely Versed in Esoteric Lore (Fire) [Scholar; Mental]",
					"Single-minded Purpose (Void) [Scholar; Mental]",
					],
			disadvantages:[
					"Knows Better Than You (Water) [Scholar, Social; Mental]",
					"Always Has An Opinion (Water) [Scholar, Social; Mental]",
					"Narcissistic and Pompous (Water) [Social; Interpersonal]",
					"Pacifist (Fire) [Martial; Mental, Physical]",
					],
		},
	Scorpion:{name:"Scorpion",
		clanring:{"Air":+1},
			clanskill:"Social",
			clanstatus:35,
			weapons:["Chokuto","Shuriken"],
			armor:["Concealed Armor"],
			advantages:["Keeper of Secrets (Void) [Social, Scholar; Mental, Interpersonal]",
				"Underworld Contacts (Water) [Social; Interpersonal]",
				"Trained in Poisons (Water) [Scholar; Mental]",
				"Heartless (Water) [Social; Interpersonal]",
				],
			disadvantages:["Whispers of Treachery (Air) [Social; Interpersonal, Infamy]",
				"Whispers of Shady Dealings",
				"Has Beloved Family (Fire) [Social; Interpersonal]",
				"Distrustful (Void) [Social; Interpersonal]",
				"Vengeful When Slighted (Earth) [Social; Interpersonal]",
					],
		},
Unicorn:{name:"Unicorn",
		clanring:{"Water":+1},
			clanskill:"Trade",
			clanstatus:30,
			weapons:["Scimitar",],
			armor: ["Ashigaru Armor"],
			advantages: [
				"Expert Rider (Water) [Trade, Martial; Physical]",
				"Friendly and Gregarious (Water) [Social; Interpersonal]",
				"Way of the Land (Water) [Trade, Martial; Physical]",
				"Famously Compassionate (Water) [Social; Interpersonal]",
				],
			disadvantages: ["Gaijin Heritage (Fire) [Social; Mental, Interpersonal or Physical]",
				"No Time For Etiquette (Air) [Social; Interpersonal]",
				"Bad with Animals (Water) [Social; Interpersonal, Infamy]",
				],
},

	Imperial:{name:"Imperial",
		clanring: {"Earth":+1},
		clanskill: "Social",
		clanstatus:40,
		weapons:[],
		armor:["Ceremonial Robes","Lacquered Armor",],			
		advantages: ["Blessed Lineage (Void) [Social; Spiritual]",
				"Resourceful Bureaucrat (Air) [Scholar, Social; Interpersonal, Mental]",
				"Powerful Connections (Water) [Social; Interpersonal]",
		],
		disadvantages: ["Naivete (Air) [Social; Mental]",
					"Spoiled (Water) [Social; Interpersonal]",
					"Easily Scandalized (Earth) [Social; Interpersonal]",
					],

		},
	Minor:{name:"Minor",
		clanring: {},
		clanskill: "",
		clanstatus:0,
		weapons:[],
		armor:["Ashigaru Armor",],			
		advantages: [
		],
		disadvantages: [
					],

		},
}

var families = {
		hida: {
			name:'Hida',
			clan:'Crab',
			ring1:"Earth",
			ring2:"Fire",
			advantages:["Large Stature (Earth) [Martial, Trade; Physical]",
			"Bishamon's Blessing (Water) [Martial, Trade; Physical, Spiritual]",
			],
			disadvantages:["Slow Moving (Water) [Martial; Physical]",
			"Naive to Trickery (Air) [Social; Mental]",
			"Wall Weary (Earth) [Social; Interpersonal]",
			],
			skill1:"Command",
			skill2:"Tactics",demeanor:[],
			glory:44,
			wealth:4,
			},
		hiruma: {
			name:'Hiruma',
			clan:'Crab',
			ring1:"Air",
			ring2:"Water",
			advantages:["Careful Skulker (Air) [Martial; Physical]",
				"Light Sleeper (Water) [Martial, Trade; Physical]",
			],
			disadvantages:["Driven (Water) [Any; Mental]",
			"Wall Weary (Earth) [Social; Interpersonal]",
			"Dour Presence (Water) [Social; Interpersonal]",
			],
			skill1:"Skulduggery",
			skill2:"Survival",demeanor:[],
			glory:39,
			wealth:3,
			},
		kaiu: {
			name:'Kaiu',
			clan:'Crab',
			ring1:"Earth",
			ring2:"Fire",
			advantages:["Makes Things Work (Fire) [Artisan; Physical]",
			"Brilliant Theorist (Fire) [Scholar; Mental]",
			],
			disadvantages:["Always Taking Things Apart (Water) [Scholar; Mental]",
			"Cold and Withdrawn (Fire) [Social; Interpersonal]",
			],
			skill1:"Smithing",
			skill2:"Labor",demeanor:[],
			glory:40,
			wealth:5,
			},
		kuni: {
			name:'Kuni',
			clan:'Crab',
			ring1:"Earth",
			ring2:"Void",
			advantages:["Knows the Enemy (Earth) [Scholar; Mental]",
			"A Practical Mind (Water) [Any; Interpersonal]",
			"Single-minded Purpose (Void) [Scholar; Mental]",
			],
			disadvantages:["Shadowlands Taint (Fire) [Scholar, Social; Curse, Physical, Spiritual]",
				"Sees Maho in Every Shadow (Water) [Any; Mental]",
				"Fascinated by Shadowlands Beasts (Fire) [Any; Mental]",
				"Wall Weary (Earth) [Social; Interpersonal]",
				"Benten's Curse (Air) [Social; Interpersonal, Spiritual]",
			],
			skill1:"Medicine",
			skill2:"Theology",demeanor:[],
			glory:40,
			wealth:4,
			},
		yasuki: {
			name:'Yasuki',
			clan:'Crab',
			ring1:"Air",
			ring2:"Water",
			advantages:["Daikoku's Blessing (Water) [Trade; Interpersonal, Spiritual]",
				"Height of Fashion (Fire) [Artisan, Social; Interpersonal]",
				"Social Connections (Air) [Social; Interpersonal]",
				"Loves Haggling (Water) [Trade; Interpersonal]",
			],
			disadvantages:["Penny Pincher (Water) [Social; Mental]",
				"Accustomed to Luxury (Earth) [Martial, Social, Trade; Interpersonal]",
				"Always Scheming (Water) [Social; Interpersonal]",
			],
			skill1:"Commerce",
			skill2:"Design",demeanor:[],
			glory:39,
			wealth:10,
			},

		asahina: {
		name:'Asahina',
		clan:'Crane',
			ring1:"Water",
			ring2:"Void",
			advantages:[
			"Dedicated Artiste (Fire) [Artisan, Social; Interpersonal]",
			"Appears Harmless (Air) [Social; Interpersonal]",
			"Perceptive Mind (Air) [Scholar, Social; Mental]",
			],
			disadvantages:["Gentle Heart (Fire) [Any; Interpersonal]",
				"Meek (Fire) [Social; Interpersonal]",
				"Easily Scandalized (Earth) [Social; Interpersonal]",
				"Jurojin's Curse (Void) [Martial, Trade; Physical, Spiritual]",
			],
			skill1:"Aesthetics",
			skill2:"Theology",demeanor:[],
			glory:40,
			wealth:6,
		},
		daidoji: {
		name:'Daidoji',
		clan:'Crane',
			ring1:"Earth",
			ring2:"Water",
			advantages:["A Practical Mind (Water) [Any; Interpersonal]",
			"Careful Skulker (Air) [Martial; Physical]",
			"Tested in War (Earth) [Martial: Mental, Physical]",
			"Sharp Eyes (Water) [Scholar; Physical]",
			],
			disadvantages:["Sharp Eyes (Water) [Scholar; Physical]",
			"Stodgy Traditionalist (Fire) [Scholar, Social; Mental]",
			"Dour Presence (Water) [Social; Interpersonal]",
			],
			skill1:"Fitness",
			skill2:"Tactics",demeanor:[],
			glory:40,
			wealth:7,
		},
		doji: {
		name:'Doji',
		clan:'Crane',
			ring1:"Air",
			ring2:"Water",
			advantages:["Friends in All Places (Air) [Social; Interpersonal]",
			"Owed Favours (Water) [Social; Interpersonal]",
			"Inexhaustible Politeness (Air) [Social; Interpersonal]",
			"Benten's Blessing (Air) [Social; Interpersonal, Spiritual]",
			"Height of Fashion (Fire) [Artisan, Social; Interpersonal]",
			],
			disadvantages:["Easily Scandalized (Earth) [Social; Interpersonal]",
			"Perfectionist (Water) [Any; Physical, Mental]",
			"Accustomed to Luxury (Earth) [Martial, Social, Trade; Interpersonal]",
			],
			skill1:"Courtesy",
			skill2:"Design",demeanor:[],
			glory:44,
			wealth:8,
		},
		kakita: {
		name:'Kakita',
		clan:'Crane',
			ring1:"Air",
			ring2:"Fire",
			advantages:["Dedicated Artiste (Fire) [Artisan, Social; Interpersonal]",
			"Unflappable Poise (Air) [Social; Interpersonal]",
			"Eager to Make a Name (Fire) [Social; Mental]",

			],
			disadvantages:["Glory Hunter (Water) [Any; Interpersonal]",
			"Hypercompetitive (Water) [Social; Mental]",
			"Perfectionist (Water) [Any; Physical, Mental]",
			],
			skill1:"Aesthetics",
			skill2:"Meditation",demeanor:[],
			glory:44,
			wealth:7,
		},
		agasha: {
		name:'Agasha',
		clan:'Dragon',
			ring1:"Fire",
			ring2:"Void",
			advantages:["Widely Versed in Esoteric Lore (Fire) [Scholar; Mental]",
			"Analytical Mind (Fire) [Scholar; Mental]",
			"Keeper of Secrets (Void) [Social, Scholar; Mental, Interpersonal]",
			],
			disadvantages:["Possessed by Curiosity (Water) [Scholar; Mental]",
			"Head in the Clouds (Void) [Social; Mental]",
			"Irresponsible Personage (Earth) [Social; Interpersonal]",
			],
			skill1:"Medicine",
			skill2:"Smithing",demeanor:[],
			glory:40,
			wealth:4,
		},
		kitsuki: {
		name:'Kitsuki',
		clan:'Dragon',
			ring1:"Air",
			ring2:"Water",
			advantages:["Perceptive Mind (Air) [Scholar, Social; Mental]",
			"Sharp Eyes (Water) [Scholar; Physical]",
			"Lateral Thinking (Fire) [Scholar; Mental]",
			"A Nose for the Truth (Water) [Scholar, Social; Mental]",
			"Incisive Scrutiny (Air) [Social; Mental, Interpersonal]",
			],
			disadvantages:["Know-It-All (Air) [Social; Interpersonal]",
			"Cold and Withdrawn (Fire) [Social; Interpersonal]",
			"Always Has An Opinion (Water) [Scholar, Social; Mental]",
			],
			skill1:"Government",
			skill2:"Sentiment",demeanor:[],
			glory:44,
			wealth:6,		},
		mirumoto: {
		name:'Mirumoto',
		clan:'Dragon',
			ring1:"Earth",
			ring2:"Water",
			advantages:["Ambidextrous (Air) [Martial; Physical]",
			],
			disadvantages:["Painfully Honest (Air) [Social: Mental]",
			],
			skill1:"Fitness",
			skill2:"Tactics",demeanor:[],
			glory:44,
			wealth:5,
		},
		togashi: {
		name:'Togashi',
		clan:'Dragon',
			ring1:"Earth",
			ring2:"Void",
			advantages:["Acrobatic Fighter (Air) [Martial; Physical]",
			"Honed Physique (Earth) [Martial; Physical]",
			"Down to earth (Earth) [Social, Trade; Physical]",
			],
			disadvantages:["Head in the Clouds (Void) [Social; Mental]",
			"Naive to Trickery (Air) [Social; Mental]",
			"Painfully Honest (Air) [Social: Mental]",
			"Detached and Aloof (Water) [Social; Interpersonal, Mental]",
			],
			skill1:"Fitness",
			skill2:"Theology",demeanor:[],
			glory:45,
			wealth:3,		},

		akodo: {
		name:'Akodo',
		clan:'Lion',
			ring1:"Air",
			ring2:"Earth",
			advantages:["Sworn to Bushido (Earth) [Social; Interpersonal]",
			"Inured to Horrors (Fire) [Scholar, Martial; Mental]",
			],
			disadvantages:["Easily Scandalized (Earth) [Social; Interpersonal]",
				"Prim and Proper (Fire) [Social; Interpersonal]",
				"Stodgy Traditionalist (Fire) [Scholar, Social; Mental]",
			],
			skill1:"Command",
			skill2:"Government",demeanor:[],
			glory:44,
			wealth:5,		},
		ikoma: {
		name:'Ikoma',
		clan:'Lion',
			ring1:"Air",
			ring2:"Water",
			advantages:["Keen Genealogist (Earth) [Scholar; Mental]",
			"Stodgy Traditionalist (Fire) [Scholar, Social; Mental]",
			],
			disadvantages:["Craves Glory (Earth) [Social; Interpersonal]",
			],
			skill1:"Composition",
			skill2:"Performance",demeanor:[],
			glory:40,
			wealth:5,		},
		kitsu: {
		name:'Kitsu',
		clan:'Lion',
			ring1:"Void",
			ring2:"Water",
			advantages:["Stodgy Traditionalist (Fire) [Scholar, Social; Mental]",
			],
			disadvantages:[
			],
			skill1:"Meditation",
			skill2:"Theology",demeanor:[],
			glory:40,
			wealth:4,		},
		matsu: {
		name:'Matsu',
		clan:'Lion',
			ring1:"Earth",
			ring2:"Fire",
			advantages:["Bishamon's Blessing (Water) [Martial, Trade; Physical, Spiritual]",
			"Intense and Sincere! (Fire) [Social; Interpersonal]",
			"Never Seen A Gamble That Didn't Pay Off (Fire) [Martial,Social; Mental]",
			],
			disadvantages:["Hot-Tempered (Water) [Social: Mental]",
			"Risk-Taker (Air) [Martial; Physical]",
			],
			skill1:"Command",
			skill2:"Fitness",demeanor:[],
			glory:44,
			wealth:5,		},
		asako: {
		name:'Asako',
		clan:'Phoenix',
			ring1:"Air",
			ring2:"Fire",
			advantages:["Incisive Scrutiny (Air) [Social; Mental, Interpersonal]",
						"Bureaucratic Wizard (Fire) [Scholar; Mental]",
			],
			disadvantages:["Sees Maho in Every Shadow (Water) [Any; Mental]",
					"Stodgy Traditionalist (Fire) [Scholar, Social; Mental]",
					"Easily Scandalized (Earth) [Social; Interpersonal]",
			],
			skill1:"Culture",
			skill2:"Sentiment",demeanor:[],
			glory:40,
			wealth:5,		},
		isawa: {
		name:'Isawa',
		clan:'Phoenix',
			ring1:"Fire",
			ring2:"Void",
			advantages:["Brilliant Theorist (Fire) [Scholar; Mental]",
						"Driven to Seek Understanding (Earth) [Scholar; Mental]",
						"Lateral Thinking (Fire) [Scholar; Mental]",
			],
			disadvantages:["Drawn to the Flame (Fire) [Scholar; Mental]",
			"Hypercompetitive (Water) [Social; Mental]",
			"Impatient (Fire) [Any; Mental]",
			"Easily Scandalized (Earth) [Social; Interpersonal]",
			],
			skill1:"Meditation",
			skill2:"Theology",demeanor:[],
			glory:44,
			wealth:5,		},
		shiba: {
		name:'Shiba',
		clan:'Phoenix',
			ring1:"Air",
			ring2:"Void",
			advantages:["Loyal Protector [Social, Martial; Interpersonal]",
				"Benten's Blessing (Air) [Social; Interpersonal, Spiritual]",
				"Dedicated Artiste (Fire) [Artisan, Social; Interpersonal]",
				"Friendly and Gregarious (Water) [Social; Interpersonal]",
			],
			disadvantages:["Naive to Trickery (Air) [Social; Mental]",
			"Naivete (Air) [Social; Mental]",
			"Gentle Heart (Fire) [Any; Interpersonal]",
			],
			skill1:"Fitness",
			skill2:"Theology",demeanor:[],
			glory:40,
			wealth:4,		},
		kaito: {
		name:'Kaito',
		clan:'Phoenix',
			ring1:"Earth",
			ring2:"Water",
			advantages:["Down to earth (Earth) [Social, Trade; Physical]",
			"Steady Hand (Earth) [Artisan; Physical]",
			"Friendly and Gregarious (Water) [Social; Interpersonal]",

			],
			disadvantages:["Outlandish Customs (Water) [Social; Mental]",
			"Rustic Isolation (Fire) [Social; Mental]",
			],
			skill1:"Meditation",
			skill2:"Tactics",demeanor:[],
			glory:40,
			wealth:5,		},

		bayushi: {
		name:'Bayushi',
		clan:'Scorpion',
			ring1:"Air",
			ring2:"Fire",
			advantages:["Dangerous Allure (Fire) [Social; Physical, Interpersonal]",
			"Benten's Blessing (Air) [Social; Interpersonal, Spiritual]",
			],
			disadvantages:["Always Scheming (Water) [Social; Interpersonal]",
				"Vengeful When Slighted (Earth) [Social; Interpersonal]",
			],
			skill1:"Courtesy",
			skill2:"Performance",demeanor:[],
			glory:40,
			wealth:6,		},
		shosuro: {
		name:'Shosuro',
		clan:'Scorpion',
			ring1:"Air",
			ring2:"Void",
			advantages:["Consummate Professional (Any; Mental)",
						"Unmemorable Face (Earth) [Social; Physical, Interpersonal]",
						"Subtle Observer (Water) [Social; Interpersonal]",
			],
			disadvantages:[
			],
			skill1:"Design",
			skill2:"Theology",demeanor:[],
			glory:40,
			wealth:6,		},
		soshi: {
		name:'Soshi',
		clan:'Scorpion',
			ring1:"Air",
			ring2:"Void",
			advantages:["Unmemorable Face (Earth) [Social; Physical, Interpersonal]",
			],
			disadvantages:["Jurojin's Curse (Void) [Martial, Trade; Physical, Spiritual]",
			],
			skill1:"Design",
			skill2:"Theology",demeanor:[],
			glory:40,
			wealth:6,		},
		yogo: {
		name:'Yogo',
		clan:'Scorpion',
			ring1:"Earth",
			ring2:"Void",
			advantages:["Consummate Professional (Any; Mental)",
			],
			disadvantages:["Cold and Withdrawn (Fire) [Social; Interpersonal]",
						"Vengeful When Slighted (Earth) [Social; Interpersonal]",
						"Benten's Curse (Air) [Social; Interpersonal, Spiritual]",
			],
			skill1:"Composition",
			skill2:"Theology",demeanor:[],
			glory:39,
			wealth:4,		},

		ide: {
		name:'Ide',
		clan:'Unicorn',
			ring1:"Earth",
			ring2:"Water",
			advantages:["Daikoku's Blessing (Water) [Trade; Interpersonal, Spiritual]",			
			"Benten's Blessing (Air) [Social; Interpersonal, Spiritual]",
			"Widely Traveled (Water) [Scholar, Trade; Mental]",
			"Loves Haggling (Water) [Trade; Interpersonal]",
			],
			disadvantages:["Materialism (Void) [Social; Mental]",
			],
			skill1:"Commerce",
			skill2:"Courtesy",demeanor:[],
			glory:40,
			wealth:9,		},
		iuchi: {
		name:'Iuchi',
		clan:'Unicorn',
			ring1:"Air",
			ring2:"Void",
			advantages:[
			],
			disadvantages:["Outlandish Customs (Water) [Social; Mental]",
			],
			skill1:"Meditation",
			skill2:"Theology",demeanor:[],
			glory:40,
			wealth:5,		},
		moto: {
		name:'Moto',
		clan:'Unicorn',
			ring1:"Earth",
			ring2:"Fire",
			advantages:[
			],
			disadvantages:["Moto Curse (Void) [Social; Mental, Curse]",
			"Outlandish Customs (Water) [Social; Mental]",
			],
			skill1:"Command",
			skill2:"Survival",demeanor:[],
			glory:40,
			wealth:6,		},
		shinjo: {
		name:'Shinjo',
		clan:'Unicorn',
			ring1:"Fire",
			ring2:"Water",
			advantages:[
			"Widely Traveled (Water) [Scholar, Trade; Mental]",
			"Benten's Blessing (Air) [Social; Interpersonal, Spiritual]",
			"Way of the Land (Water) [Trade, Martial; Physical]",
			],
			disadvantages:[
			],
			skill1:"Sentiment",
			skill2:"Survival",demeanor:[],
			glory:44,
			wealth:8,		},
		utaku: {
		name:'Utaku',
		clan:'Unicorn',
			ring1:"Earth",
			ring2:"Fire",
			advantages:["Paragon of Honor (Earth) [Social, Martial; Mental]",
				"Widely Traveled (Water) [Scholar, Trade; Mental]",
			],
			disadvantages:["Naive to Trickery (Air) [Social; Mental]",
			],
			skill1:"Survival",
			skill2:"Tactics",demeanor:[],
			glory:44,
			wealth:6,			},
		miya: {
			name:'Miya',
			clan:'Imperial',
			ring1:"Air",
			ring2:"Earth",
			advantages:["Widely Traveled (Water) [Scholar, Trade; Mental]",
			"Impeccable Brushwork (Air) [Artisan; Mental]",
			"Wealth and Resources (Water) [Trade; Material]",
			],
			disadvantages:["Accustomed to Luxury (Earth) [Martial, Social, Trade; Interpersonal]",
			],
			skill1:"Courtesy",
			skill2:"Culture",demeanor:[],
			glory:44,
			wealth:8,
		},
		otomo: {
			name:'Otomo',
			clan:'Imperial',
			ring1:"Air",
			ring2:"Water",
			advantages:["Social Connections (Air) [Social; Interpersonal]",
			"Resourceful Bureaucrat (Air) [Scholar, Social; Interpersonal, Mental]",
			"Irreproachable Personage (Fire) [Social; Interpersonal]",
			"Wealth and Resources (Water) [Trade; Material]",
			],
			disadvantages:["Accustomed to Luxury (Earth) [Martial, Social, Trade; Interpersonal]",
			"Haughty Tone (Air) [Social; Interpersonal]",
			"Always Has An Opinion (Water) [Scholar, Social; Mental]",
			"Always Scheming (Water) [Social; Interpersonal]",
			],
			skill1:"Culture",
			skill2:"Sentiment",demeanor:[],
			glory:43,
			wealth:9,
		},
		seppun: {
			name:'Seppun',
			clan:'Imperial',
			ring1:"Earth",
			ring2:"Void",
			advantages:["Intense and Sincere! (Fire) [Social; Interpersonal]",
			"Irreproachable Personage (Fire) [Social; Interpersonal]",
			"Wealth and Resources (Water) [Trade; Material]",
			],
			disadvantages:["Accustomed to Luxury (Earth) [Martial, Social, Trade; Interpersonal]",
			],
			skill1:"Meditation",
			skill2:"Theology",demeanor:[],
			glory:45,
			wealth:6,	
		},

		toritaka: {
			name:'Toritaka',
			clan:'Minor',
			clanring: {"Void":+1},
			clanskill: "Scholar",
			clanstatus: 26,
			ring1:"Earth",
			ring2:"Water",
			advantages:["Mystical Knowledge (Void) [Scholar; Mental]",
			"Widely Versed in Esoteric Lore (Fire) [Scholar; Mental]"
			],
			disadvantages:["Detached and Aloof (Water) [Social; Interpersonal, Mental]",
			],
			skill1:"Survival",
			skill2:"Meditation",demeanor:[],
			glory:"35",
			wealth:"3",	},

		shika: {
			name:'Shika',
			clan:'Minor',
			clanring: {"Air":+1},
			clanskill: "Scholar",
			clanstatus: 30,
			ring1:"Water",
			ring2:"Fire",
			advantages:["Acrobatic Fighter (Air) [Martial; Physical]",
			],
			disadvantages:["Irresponsible Romantic (Earth) [Social; Interpersonal]",
			],
			skill1:"Courtesy",
			skill2:"Culture",demeanor:[],
			glory:"35",
			wealth:"5",	},

		kasuga: {
			name:'Kasuga',
			clan:'Minor',
			clanring: {"Air":+1},
			clanskill: "Trade",
			clanstatus: 26,
			ring1:"Water",
			ring2:"Earth",
			advantages:[
			"Daikoku's Blessing (Water) [Trade; Interpersonal, Spiritual]",
			"Wealth and Resources (Water) [Trade; Material]",
			],
			disadvantages:["Gaijin Heritage (Fire) [Social; Mental, Interpersonal or Physical]",
			"Penny Pincher (Water) [Social; Mental]",
			"Whispers of Avarice (Air) [Social; Mental, Interpersonal]",
			],
			skill1:"Skulduggery",
			skill2:"Government",demeanor:[],
			glory:"33",
			wealth:"9",	},

			mantis: {
			name:'Mantis',
			clan:'Minor',
			clanring: {"Water":+1},
			clanskill: "Trade",
			clanstatus: 25,
			ring1:"Water",
			ring2:"Fire",
			advantages:["Seasoned Seafarer (Water) [Trade, Scholar; Mental, Physical]",
						"Honed Physique (Earth) [Martial; Physical]",
						"Hero of the People (Earth) [Trade, Social; Interpersonal]",
						"Surefooted (Air) [Martial; Physical]",
						"Widely Traveled (Water) [Scholar, Trade; Mental]",
						"Daikoku's Blessing (Water) [Trade; Interpersonal, Spiritual]",
						"I'll tell you a tale of the sea... (Air) [Social; Interpersonal]",
			],
			disadvantages:["Gaijin Heritage (Fire) [Social; Mental, Interpersonal or Physical]",
							"Whispers of Avarice (Air) [Social; Mental, Interpersonal]",
							"Penny Pincher (Water) [Social; Mental]",
							"Craves Glory (Earth) [Social; Interpersonal]",
							"Risk-Taker (Air) [Martial; Physical]",
			],
			skill1:"Commerce",
			skill2:"Survival",demeanor:[],
			glory:"36",
			wealth:"7",	},

}

var roninregions ={
		"Urban Region":{	
			name:"Urban Region",
			clanring:{Air:+1},
			clanskill:"Trade",
			clanstatus:0,
			clanglory:29,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},

		"Farmland Region":{	
			name:"Farmland Region",
			clanring:{Earth:+1},
			clanskill:"Martial",
			clanstatus:0,
			clanglory:34,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},

		"Sea, River or Lake Region":{	
			name:"Sea, River or Lake Region",
			clanring:{Water:+1},
			clanskill:"Trade",
			clanstatus:0,
			clanglory:32,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},

		"Forest Region":{	
			name:"Forest Region",
			clanring:{Earth:+1},
			clanskill:"Trade",
			clanstatus:0,
			clanglory:30,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},

		"Mountain Region":{	
			name:"Mountain Region",
			clanring:{Void:+1},
			clanskill:"Martial",
			clanstatus:0,
			clanglory:33,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},

		"Cursed Region":{	
			name:"Cursed Region",
			clanring:{Fire:+1},
			clanskill:"Social",
			clanstatus:0,
			clanglory:28,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},

		"Ujik of the Plains of Wind and Stone":{	
			name:"Ujik of the Plains of Wind and Stone",
			clanring:{Water:+1},
			clanskill:"Trade",
			clanstatus:0,
			clanglory:30,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},

		"Qamarists of the Cradle of the World":{	
			name:"Qamarists of the Cradle of the World",
			clanring:{Fire:+1},
			clanskill:"Scholar",
			clanstatus:0,
			clanglory:29,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},

		"Yodha of the Ghostlands":{	
			name:"Yodha of the Ghostlands",
			clanring:{Earth:+1},
			clanskill:"Scholar",
			clanstatus:0,
			clanglory:29,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},

		"Sheelavaan of Bhavyatapura":{	
			name:"Sheelavaan of Bhavyatapura",
			clanring:{Air:+1},
			clanskill:"Social",
			clanstatus:0,
			clanglory:28,
			weapons:[],
			armor:[],
			advantages:[
					],
			disadvantages:[
					],
				},
			}

var roninupbringings = {

		craftspersonupbringing: 
			{name: "Craftsman Upbringing", 
			clan: "Ronin", 
			ring1: "Earth", ring2: "Void", 
			advantages: ["Lateral Thinking (Fire) [Scholar; Mental]",
			"Makes Things Work (Fire) [Artisan; Physical]",
			"Eye for Detail (Air) [Artisan; Mental]",
			"Steady Hand (Earth) [Artisan; Physical]",
			'Single-minded Purpose (Void) [Scholar; Mental]',], 
			disadvantages: ["Avaricious (Earth) [Social; Interpersonal]",
			"Poverty (Water) [Trade; Material]",
			"Meek (Fire) [Social; Interpersonal]",
			], 
			skill1: "Culture", skill2: "Design", 
			demeanor: [], 
			glory: "", 
			status: -2,
			wealth: "1 koku",
		},

		geishaupbringing: 
			{name: "Geisha House Upbringing", 
			clan: "Ronin", 
			ring1: "Air", ring2: "Fire", 
			advantages: ['Consummate Professional (Any; Mental)',
			'Dangerous Allure (Fire) [Social; Physical, Interpersonal]',
			'Dedicated Artiste (Fire) [Artisan, Social; Interpersonal]',
			"Benten's Blessing (Air) [Social; Interpersonal, Spiritual]",
			"Friendly and Gregarious (Water) [Social; Interpersonal]",
			"Friends in All Places (Air) [Social; Interpersonal]",
			"In On The Good Gossip (Water) [Social; Interpersonal]",
			"Seems Trustworthy (Water) [Social; Interpersonal]",
			"Height of Fashion (Fire) [Artisan, Social; Interpersonal]",
			"Perceptive Mind (Air) [Scholar, Social; Mental]",
			"Underworld Contacts (Water) [Social; Interpersonal]",
			"Keen Empathy (Air) [Social; Interpersonal]",
			"Unflappable Poise (Air) [Social; Interpersonal]",
			"Subtle Observer (Water) [Social; Interpersonal]",
			"Unmemorable Face (Earth) [Social; Physical, Interpersonal]",
			], disadvantages: ["Accustomed to Luxury (Earth) [Martial, Social, Trade; Interpersonal]",
			"Bad Dreams (Void) [Martial; Mental]",
			"Cold and Withdrawn (Fire) [Social; Interpersonal]",
			"Easily Scandalized (Earth) [Social; Interpersonal]",
			"Doomed Love (Fire) [Social; Interpersonal]",
			"Hypercompetitive (Water) [Social; Mental]",
			"Perfectionist (Water) [Any; Physical, Mental]",
			"Naivete (Air) [Social; Mental]",
			"Prima Donna (Water) [Social; Interpersonal]",
			"Seen It All Before (Earth) [Scholar, Social; Mental]",
			], 
			skill1: "Aesthetics", skill2: "Courtesy", 
			demeanor: [], 
			glory: "", 
			status: -20,
			wealth: "3 koku",
		},

		farmerupbringing: 
			{name: "Farmer Upbringing", 
			clan: "Ronin", 
			ring1: "Earth", ring2: "Water", 
			advantages: ["Friendly and Gregarious (Water) [Social; Interpersonal]",
			"Way of the Land (Water) [Trade, Martial; Physical]",
			"Large Stature (Earth) [Martial, Trade; Physical]",
			"Subtle Observer (Water) [Social; Interpersonal]",
			"Bishamon's Blessing (Water) [Martial, Trade; Physical, Spiritual]",
			], disadvantages: ["Meek (Fire) [Social; Interpersonal]",
			"Naivete (Air) [Social; Mental]",
			"Bad with Animals (Water) [Social; Interpersonal, Infamy]",
			], 
			skill1: "Labor", skill2: "Fitness", 
			demeanor: [], 
			glory: "", 
			status: -4,
			wealth: "2 bu",
		},

		etaupbringing: 
			{name: "Eta Upbringing", 
			clan: "Ronin", 
			ring1: "Water", ring2: "Void", 
			advantages: ["Subtle Observer (Water) [Social; Interpersonal]",
			"Unmemorable Face (Earth) [Social; Physical, Interpersonal]",
			], disadvantages: ["Meek (Fire) [Social; Interpersonal]",
			"Distrustful (Void) [Social; Interpersonal]",
			], 
			skill1: "Labor", skill2: "Survival", 
			demeanor: [], 
			glory: "", 
			status: -20,
			wealth: "5 zeni",
		},

		hunterupbringing: 
			{name: "Hunter Upbringing", 
			clan: "Ronin", 
			ring1: "Earth", ring2: "Water", 
			advantages: ["Way of the Land (Water) [Trade, Martial; Physical]",
			"Careful Skulker (Air) [Martial; Physical]",
			"A Practical Mind (Water) [Any; Interpersonal]",
			"Light Sleeper (Water) [Martial, Trade; Physical]",
			"Expert Rider (Water) [Trade, Martial; Physical]",
			"Expert Tracker (Air) [Trade; Mental]",
			], disadvantages: ["Naive to Trickery (Air) [Social; Mental]",
			"Ascetic (Void) [Social; Mental]",
			"Glory Hunter (Water) [Any; Interpersonal]",
			], 
			skill1: "Labor", skill2: "Survival", 
			demeanor: [], 
			glory: "", 
			status: 3,
			wealth: "4 bu",
		},

		fisherupbringing: 
			{name: "Fisher Upbringing", 
			clan: "Ronin", 
			ring1: "Earth", ring2: "Water", 
			advantages: ["Way of the Sea (Water) [Trade, Martial; Physical]",
			"Surefooted (Air) [Martial; Physical]",
			"Seasoned Seafarer (Water) [Trade, Scholar; Mental, Physical]",
			"I'll tell you a tale of the sea... (Air) [Social; Interpersonal]",
			], disadvantages: ["Risk-Taker (Air) [Martial; Physical]",

			], 
			skill1: "Labor", skill2: "Seafaring", 
			demeanor: [], 
			glory: "", 
			status: 3,
			wealth: "4 bu",
		},

		lawenforcementupbringing: 
			{name: "Law Enforcement Upbringing", 
			clan: "Ronin", 
			ring1: "Earth", ring2: "Air", 
			advantages: ["Driven to Seek Understanding (Earth) [Scholar; Mental]",
			"Brilliant Theorist (Fire) [Scholar; Mental]",
			"Knows the Enemy (Earth) [Scholar; Mental]",
			"Perceptive Mind (Air) [Scholar, Social; Mental]",
			"Just and Idealistic (Earth) [Social; Interpersonal]",
			], disadvantages: ["Always Has An Opinion (Water) [Scholar, Social; Mental]",
			"Busybody (Air) [Social; Mental]",
			"Idealistic (Air) [Social: Mental]",
			"Stodgy Traditionalist (Fire) [Scholar, Social; Mental]",
			"Seen It All Before (Earth) [Scholar, Social; Mental]",
			], 
			skill1: "Government", skill2: "Command", 
			demeanor: [], 
			glory: "", 
			status: 5,
			wealth: "1 koku",
		},

		militaryupbringing: 
			{name: "Military Upbringing", 
			clan: "Ronin", 
			ring1: "Earth", ring2: "Air", 
			advantages: ["Sworn to Bushido (Earth) [Social; Interpersonal]",
			"Inured to Horrors (Fire) [Scholar, Martial; Mental]",
			"Famed for a Valiant Battle (Water) [Social; Interpersonal]",
			"Powerful Connections (Water) [Social; Interpersonal]",
			"Sworn to Bushido (Earth) [Social; Interpersonal]",
			"Tested in War (Earth) [Martial: Mental, Physical]",
			], disadvantages: ["Glory Hunter (Water) [Any; Interpersonal]",
			"Pacifist (Fire) [Martial; Mental, Physical]",
			"Shattered by War (Earth) [Social; Mental]",
			], 
			skill1: "Government", skill2: "Command", 
			demeanor: [], 
			glory: "", 
			status: 5,
			wealth: "1 koku",
		},

		roninfamilyupbringing: 
			{name: "Ronin Family Upbringing", 
			clan: "Ronin", 
			ring1: "Any", ring2: "Any", 
			advantages: ["Widely Traveled (Water) [Scholar, Trade; Mental]",
			"Eager to Make a Name (Fire) [Social; Mental]",
			"A Practical Mind (Water) [Any; Interpersonal]",
			"Sworn to Bushido (Earth) [Social; Interpersonal]",
			], disadvantages: ["Unbending Pride (Water) [Social; Mental]",
			"World-Weariness (Earth) [Social; Interpersonal]",
			"Craves Glory (Earth) [Social; Interpersonal]",
			], 
			skill1: "Courtesy", skill2: "Melee", 
			demeanor: [], 
			glory: "", 
			status: 2,
			wealth: "1 koku",
		},

		organisedcrimeupbringing: 
			{name: "Organised Crime Upbringing", 
			clan: "Ronin", 
			ring1: "Any", ring2: "Any", 
			advantages: ["Subtle Observer (Air) [Interpersonal; Mental]",
			"Trained in Poisons (Water) [Scholar; Mental]",
			"Underworld Contacts (Water) [Social; Interpersonal]",
			"Excellent Liar (Air) [Social; Interpersonal]",
			"A Practical Mind (Water) [Any; Interpersonal]",
			"Excellent Skulker (Air) [Martial, Trade; Physical]",
			"Heartless (Water) [Social; Interpersonal]",
			"Subtle Observer (Water) [Social; Interpersonal]",
			], disadvantages: ["Disdain for Righteousness (Void) [Flaw; Mental]",
				"Paranoia (Water) [Mental; Physical]",
				"Ends Justify The Means (Void) [Scholar; Mental]",
				"Bad Dreams (Void) [Martial; Mental]",
				"Avaricious (Earth) [Social; Interpersonal]",
				"Materialism (Void) [Social; Mental]",
				"Driven (Water) [Any; Mental]",
			], 
			skill1: "Courtesy", skill2: "Melee", 
			demeanor: [], 
			glory: "", 
			status: -8,
			wealth: "3 koku",
		},

		streeturchinupbringing: 
			{name: "Street Urchin Upbringing", 
			clan: "Ronin", 
			ring1: "Air", ring2: "Fire", 
			advantages: ["A Practical Mind (Water) [Any; Interpersonal]",
			"Never Seen A Gamble That Didn't Pay Off (Fire) [Martial,Social; Mental]",
			"Careful Skulker (Air) [Martial; Physical]",
			"Surefooted (Air) [Martial; Physical]",
			"In On The Good Gossip (Water) [Social; Interpersonal]",
			"Light Fingers (Air) [Trade; Physical]",
			"Excellent Liar (Air) [Social; Interpersonal]",
			"Unmemorable Face (Air) [Social; Physical]",
			"Loves Haggling (Water) [Trade; Interpersonal]",
			"Way of the Back Alleys (Water) [Trade, Martial; Physical]",
			"Excellent Skulker (Air) [Martial, Trade; Physical]",
			], disadvantages: ["Meek (Fire) [Social; Interpersonal]",
			"Distrustful (Void) [Social; Interpersonal]",
			"Poverty (Water) [Trade; Material]",
			"Possessed by Curiosity (Water) [Scholar; Mental]",],
			skill1: "Skulduggery", skill2: "Skulduggery", 
			demeanor: [], 
			glory: "", 
			status: -7,
			wealth: "4 bu",
		},

		templeupbringing: 
			{name: "Temple Upbringing", 
			clan: "Ronin", 
			ring1: "Void", ring2: "Air", 
			advantages: ["Friend of the Brotherhood (Water) [Social; Interpersonal]",
			"Holy Personage (Water) [Social; Interpersonal]",
			"Mysterious Personage (Void) [Social; Interpersonal]",
			"Mystical Knowledge (Void) [Scholar; Mental]",	
			"Self-Awareness (Void) [Martial; Mental]",
			], disadvantages: ["Poverty (Water) [Trade; Material]",
			"Ascetic (Void) [Social; Mental]",
			"Busybody (Air) [Social; Mental]",
			"Above Worldly Matters (Water) [Trade, Social; Interpersonal]",
			], 
			skill1: "Theology", skill2: "Courtesy", 
			demeanor: [], 
			glory: "", 
			status: 11,
			wealth: "One day's rations",
		},

		tradespersonupbringing: 
			{name: "Tradesperson Upbringing", 
			clan: "Ronin", 
			ring1: "Air", ring2: "Water", 
			advantages: ["Has Beloved Family (Fire) [Social; Interpersonal]",], 
			disadvantages: ["Meek (Fire) [Social; Interpersonal]",], 
			skill1: "Commerce", skill2: "Aesthetics", 
			demeanor: [], 
			glory: "", 
			status: -6,
			wealth: "2 koku",
		},


}