var npcweapons=[
				{title:"Ritual Knife", range:0, damage:2, deadliness:6, qualities:"Concealable, Razor-Edged, Unholy",type:"equipped"},
				{title:"Obsidian-Edged Katana",range:1,damage:5,deadliness:9,qualities:"Razor-Edged, Unholy",type:"equipped"},
				{title:"Rusty Katana",range:1,damage:4,deadliness:5,qualities:"Ceremonial, Damaged, Razor-Edged",type:"equipped"},
				{title:"Crushing Claws and Fangs",range:"1-2",damage:8,deadliness:6,qualities:"None",type:"natural"},
				{title:"Tusks",range:0,damage:7,deadliness:7,qualities:"Durable, Razor-Edged",type:"natural"},
				{title:"Little Claws",range:0,damage:1,deadliness:2,qualities:"Concealable, Razor-Edged",type:"natural"},
				{title:"Vicious Bite",range:0,damage:4,deadliness:2,qualities:"Snaring",type:"natural"},
				{title:"Little Bite",range:0,damage:2,deadliness:1,qualities:"Snaring",type:"natural"},
				{title:"Beak and Talons",range:0,damage:1,deadliness:6,qualities:"None",type:"natural"},
				{title:"Hooves",range:"1-2",damage:6,deadliness:5,qualities:"None",type:"natural"},
				{title:"Rending Claws and Fangs",range:1,damage:5,deadliness:9,qualities:"Razor-Edged",type:"natural"},
				{title:"Mighty Hooves",range:"1-2",damage:7,deadliness:6,qualities:"None",type:"natural"},
				{title:"Vicious Fangs",range:0,damage:4,deadliness:4,qualities:"Snaring",type:"natural"},
				{title:"Decrepit Yumi",range:"2-5",damage:5,deadliness:3,qualities:"Damaged",type:"equipped"},
				{title:"Twisted Talons",range:"1-2",damage:4,deadliness:5,qualities:"Razor-Edged, Unholy",type:"natural"},
				{title:"Horrific Maw",range:0,damage:1,deadliness:8,qualities:"None",type:"natural"},
				{title:"Small Yari",range:1,damage:5,deadliness:3,qualities:"Wargear",type:"equipped",},
				{title:"Small Yumi",range:"2-3",damage:4,deadliness:3,qualities:"None",type:"equipped"},
				{title:"Crushing Claws",range:"1-2",damage:6,deadliness:8,qualities:"Unholy, Razor-Edged",type:"natural"},
				{title:"Jagged Teeth",range:0,damage:3,deadliness:5,qualities:"Unholy",type:"natural"},
				{title:"Grasping Hands",range:"0-1",damage:2,deadliness:1,qualities:"Snaring",type:"natural"},
				{title:"Massive Cudgel",range:2,damage:9,deadliness:5,qualities:"Cumbersome",type:"natural"},
				{title:"Rending Grip",range:1,damage:4,deadliness:6,qualities:"None",type:"natural"},
				{title:"Majestic Antlers",range:"1-2",damage:4,deadliness:6,qualities:"Ceremonial, Sacred",type:"natural"},
				{title:"Talons of Air",range:"2-3",damage:4,deadliness:7,qualities:"Deals supernatural damage",type:"natural"},
				{title:"Stone Fists",range:"0-2",damage:7,deadliness:4,qualities:"Deals physical or supernatural damage",type:"natural"},
				{title:"Blazing Touch",range:"1-3",damage:6,deadliness:6,qualities:"Razor-Edged, Deals supernatural damage",type:"natural",},
				{title:"Smashing Torrent",range:"1-2",damage:7,deadliness:3,qualities:"Snaring, Deals supernatural damage",type:"natural"},
				{title:"Claws and Teeth",range:"0-2",damage:7,deadliness:7,qualities:"Unholy",type:"natural"},
				{title:"Barbed Hair",range:"0-2",damage:3,deadliness:6,qualities:"Unholy",type:"natural"},
				{title:"Smothering Paper",range:"0-1",damage:4,deadliness:4,qualities:"Unholy, Snaring",type:"natural"},
				{title:"Tentacle Entrails",range:"0-2",damage:5,deadliness:6,qualities:"Snaring, Unholy",type:"natural"},
				{title:"Tree Trunk",range:"1-2",damage:8,deadliness:2,qualities:"",type:"equipped"},
				{title:"Heavy Masakari",range:"0-1",damage:"4/5",deadliness:"4/6",qualities:"Mundane",type:"equipped"},
				{title:"Biting Teeth",range:"0",damage:4,deadliness:3,qualities:"Razor-Edged, Unholy",type:"natural"},
				{title:"Rotted Fists and Teeth",range:"0",damage:6,deadliness:3,qualities:"Unholy",type:"natural"},
				{title:"Crushing Fire",range:"0",damage:4,deadliness:4,qualities:"Unholy",type:"natural"},
				{title:"Tangling Vines",range:"0-2",damage:3,deadliness:2,qualities:"Snaring, Unholy",type:"natural"},
				{title:"Teeth and Hooves",range:"0-1",damage:4,deadliness:3,qualities:"Unholy",type:"natural"},
				{title:"Ritual Dagger",range:"0",damage:2,deadliness:4,qualities:"Unholy, Razor-Edged",type:"equipped"},
				{title:"Nezumi dagger",range:"0-1",damage:3,deadliness:3,qualities:"",type:"equipped"},
				{title:"Nezumi knife",range:"0",damage:2,deadliness:4,qualities:"Concealable, Mundane",type:"equipped"},
				{title:"Nezumi Claws and Teeth",range:"0",damage:2,deadliness:3,qualities:"",type:"natural"},

				];
var npcarmor=[
				{title:"Rags",phys:0,sup:0,qualities:"Mundane",type:"equipped"},
				{title:"None",phys:0,sup:0,qualities:"None",type:"natural"},
				{title:"Sorcerous Raiment",phys:2,sup:4,qualities:"Unholy",type:"equipped"},
				{title:"Thick Hide",phys:4,sup:0,qualities:"None",type:"natural"},
				{title:"Thick Fur",phys:2,sup:0,qualities:"None",type:"natural"},
				{title:"Hide",phys:2,sup:0,qualities:"None",type:"natural"},
				{title:"Hide and Barding",phys:4,sup:0,qualities:"None",type:"natural"},
				{title:"Soft Fur",phys:0,sup:0,qualities:"Resplendant, Lovely to Touch",type:"natural"},
				{title:"Ancient Armor",phys:3,sup:0,qualities:"Wargear",type:"equipped"},
				{title:"Fresh Skin",phys:3,sup:5,qualities:"Unholy",type:"natural"},
				{title:"Demonic Hide",phys:5,sup:5,qualities:"Unholy",type:"natural"},
				{title:"Decaying Flesh",phys:2,sup:0,qualities:"None",type:"natural"},
				{title:"Scaled Hide",phys:1,sup:1,qualities:"None",type:"natural"},
				{title:"Magical Hide",phys:3,sup:3,qualities:"None",type:"natural"},
				{title:"Misty Mantle",phys:6,sup:0,qualities:"Sacred",type:"natural"},
				{title:"Rocky Hide",phys:5,sup:5,qualities:"Unholy",type:"natural"},
				{title:"Corona of Flames",phys:3,sup:0,qualities:"None",type:"natural"},
				{title:"Enshrouding Fog",phys:3,sup:4,qualities:"None",type:"natural"},
				{title:"Bone Plating",phys:3,sup:0,qualities:"Unholy",type:"natural"},
				{title:"Layers of Paper",phys:6,sup:6,qualities:"Unholy",type:"natural"},
				{title:"Body Shell",phys:3,sup:0,qualities:"",type:"natural"},
				{title:"Numerous Hides",phys:2,sup:0,qualities:"",type:"equipped"},
				{title:"Rusted Armor",phys:2,sup:0,qualities:"",type:"equipped"},
				{title:"Slimy Skin",phys:1,sup:0,qualities:"",type:"natural"},
				{title:"Rotting Flesh",phys:3,sup:0,qualities:"",type:"natural"},
				{title:"Wooden Form",phys:3,sup:1,qualities:"",type:"natural"},
				{title:"Outer Husk",phys:3,sup:0,qualities:"",type:"natural"},
				{title:"Corrupted armor",phys:2,sup:1,qualities:"Unholy",type:"equipped"},
				{title:"Defiled priestly robes",phys:1,sup:2,qualities:"Unholy",type:"equipped"},
				{title:"Nezumi vestments",phys:2,sup:2,qualities:"",type:"equipped"},
				{title:"Nezumi armour",phys:2,sup:1,qualities:"Wargear",type:"equipped"},
				{title:"Rememberer's robes",phys:1,sup:2,qualities:"Ceremonial",type:"equipped"},
				{title:"Fur",phys:1,sup:0,qualities:"",type:"natural"},

				];