var npcweapons=[
				{name:"Ritual Knife", range:0, damage:2, deadliness:6, qualities:"Concealable, Razor-Edged, Unholy",type:"equipped", origin:"Deadly Bloodspeaker"},
				{name:"Obsidian-Edged Katana",range:1,damage:5,deadliness:9,qualities:"Razor-Edged, Unholy",type:"equipped", origin:"Deadly Bloodspeaker"},
				{name:"Rusty Katana",range:1,damage:4,deadliness:5,qualities:"Ceremonial, Damaged, Razor-Edged",type:"equipped", origin:"Skeleton Bushi, Bandit Experienced"},
				{name:"Crushing Claws and Fangs",range:"1-2",damage:8,deadliness:6,qualities:"None",type:"natural", origin:"Bear"},
				{name:"Tusks",range:0,damage:7,deadliness:7,qualities:"Durable, Razor-Edged",type:"natural", origin:"Boar"},
				{name:"Little Claws",range:0,damage:1,deadliness:2,qualities:"Concealable, Razor-Edged",type:"natural", origin:"Cat"},
				{name:"Vicious Bite",range:0,damage:4,deadliness:2,qualities:"Snaring",type:"natural", origin:"Dog Large, "},
				{name:"Little Bite",range:0,damage:2,deadliness:1,qualities:"Snaring",type:"natural", origin:"Dog Small, Panda Red, Nezumi Pup"},
				{name:"Beak and Talons",range:0,damage:1,deadliness:6,qualities:"None",type:"natural", origin:"Hawk"},
				{name:"Hooves",range:"1-2",damage:6,deadliness:5,qualities:"None",type:"natural", origin:"Horse Rokugani Pony, Horse Shinjo Riding Horse"},
				{name:"Rending Claws and Fangs",range:1,damage:5,deadliness:9,qualities:"Razor-Edged",type:"natural", origin:"Hunting Cat"},
				{name:"Mighty Hooves",range:"1-2",damage:7,deadliness:6,qualities:"None",type:"natural", origin:"Horse Utaku Steed"},
				{name:"Vicious Fangs",range:0,damage:4,deadliness:4,qualities:"Snaring",type:"natural", origin:"Wolf"},
				{name:"Decrepit Yumi",range:"2-5",damage:5,deadliness:3,qualities:"Damaged",type:"equipped", origin:"Skeleton Bushi"},
				{name:"Twisted Talons",range:"1-2",damage:4,deadliness:5,qualities:"Razor-Edged, Unholy",type:"natural", origin:"Bog Hag"},
				{name:"Horrific Maw",range:0,damage:1,deadliness:8,qualities:"None",type:"natural", origin:"Bog Hag"},
				{name:"Small Yari",range:1,damage:5,deadliness:3,qualities:"Wargear",type:"equipped", origin:"Goblin"},
				{name:"Small Yumi",range:"2-3",damage:4,deadliness:3,qualities:"None",type:"equipped", origin:"Goblin"},
				{name:"Crushing Claws",range:"1-2",damage:6,deadliness:8,qualities:"Unholy, Razor-Edged",type:"natural", origin:"Sinister Oni"},
				{name:"Jagged Teeth",range:0,damage:3,deadliness:5,qualities:"Unholy",type:"natural", origin:"Zombie Peasant"},
				{name:"Grasping Hands",range:"0-1",damage:2,deadliness:1,qualities:"Snaring",type:"natural", origin:"Zombie Peasant"},
				{name:"Massive Cudgel",range:2,damage:9,deadliness:5,qualities:"Cumbersome",type:"natural", origin:"Troll Forest"},
				{name:"Rending Grip",range:1,damage:4,deadliness:6,qualities:"None",type:"natural", origin:"Troll Forest"},
				{name:"Majestic Antlers",range:"1-2",damage:4,deadliness:6,qualities:"Ceremonial, Sacred",type:"natural", origin:"Ki-Rin"},
				{name:"Talons of Air",range:"2-3",damage:4,deadliness:7,qualities:"Deals supernatural damage",type:"natural", origin:"Kami Manifest Air"},
				{name:"Stone Fists",range:"0-2",damage:7,deadliness:4,qualities:"Deals physical or supernatural damage",type:"natural", origin:"Kami Manifest Earth"},
				{name:"Blazing Touch",range:"1-3",damage:6,deadliness:6,qualities:"Razor-Edged, Deals supernatural damage",type:"natural",origin:"Kami Manifest Fire"},
				{name:"Smashing Torrent",range:"1-2",damage:7,deadliness:3,qualities:"Snaring, Deals supernatural damage",type:"natural", origin:"Kami Manifest Water"},
				{name:"Claws and Teeth",range:"0-2",damage:7,deadliness:7,qualities:"Unholy",type:"natural", origin:"Gashadokuro"},
				{name:"Barbed Hair",range:"0-2",damage:3,deadliness:6,qualities:"Unholy",type:"natural", origin:"Harionago"},
				{name:"Smothering Papers",range:"0-1",damage:4,deadliness:4,qualities:"Unholy, Snaring",type:"natural", origin:"Kyorinin"},
				{name:"Tentacle Entrails",range:"0-2",damage:5,deadliness:6,qualities:"Snaring, Unholy",type:"natural", origin:"Penanggalan"},
				{name:"Tree Trunk",range:"1-2",damage:8,deadliness:2,qualities:"",type:"equipped", origin:"Ravenous Shadowlands Ogre"},
				{name:"Heavy Masakari",range:"0-1",damage:"4/5",deadliness:"4/6",qualities:"Mundane",type:"equipped", origin:"Revenant"},
				{name:"Biting Teeth",range:"0",damage:4,deadliness:3,qualities:"Razor-Edged, Unholy",type:"natural", origin:"Tsumunagi"},
				{name:"Rotted Fists and Teeth",range:"0",damage:6,deadliness:3,qualities:"Unholy",type:"natural", origin:"Undead Horror"},
				{name:"Crushing Fire",range:"0",damage:4,deadliness:4,qualities:"Unholy",type:"natural", origin:"Wanyudo"},
				{name:"Tangling Vines",range:"0-2",damage:3,deadliness:2,qualities:"Snaring, Unholy",type:"natural", origin:"Fudoshi"},
				{name:"Teeth and Hooves",range:"0-1",damage:4,deadliness:3,qualities:"Unholy",type:"natural", origin:"Onikage"},
				{name:"Ritual Dagger",range:"0",damage:2,deadliness:4,qualities:"Unholy, Razor-Edged",type:"equipped", origin:"Goblin Accursed Priest"},
				{name:"Nezumi dagger",range:"0-1",damage:3,deadliness:3,qualities:"",type:"equipped", origin:"Nezumi Dreamer"},
				{name:"Nezumi knife",range:"0",damage:2,deadliness:4,qualities:"Concealable, Mundane",type:"equipped", origin:"Nezumi Rememberer"},
				{name:"Nezumi Claws and Teeth",range:"0",damage:2,deadliness:3,qualities:"",type:"natural", origin:"Nezumi Feral"},
				{name:"Sharp Little Teeth",range:"0",damage:1,deadliness:2,qualities:"Razor-Edged",type:"natural", origin:"Fox"},
				{name: "Tentacle Arms", range:"0-5", damage:"8", deadliness:"6", qualities:"", type:"natural", origin:"Akkorokamui"},
				{name: "Scorpion Claws", range:"0", damage:"4", deadliness:"3", qualities:"", type:"natural", origin:"Amikiri"},
				{name: "Tail Stinger", range:"0-1", damage:"3", deadliness:"6", qualities:"", type:"natural", origin:"Amikiri"},
				{name: "None", range:"0", damage:"0", deadliness:"0", qualities:"", type:"natural", origin:""},
				{name: "Arcing Lightning", range:"0-4", damage:"4", deadliness:"5", qualities:"deals Supernatural damage", type:"natural", origin:"Hinotama"},
				{name: "Razor Teeth", range:"0", damage:"7", deadliness:"9", qualities:"Razor-Edged", type:"natural", origin:"Isonade"},
				{name: "Razor Claws", range:"0", damage:"4", deadliness:"6", qualities:"Razor-Edged", type:"natural", origin:"Kappa Mischievous"},
				{name: "Deadly Claws", range:"0-1", damage:"5", deadliness:"4", qualities:"Razor-Edged, Unholy", type:"natural", origin:"Rakshasa"},
				{name: "Cutting Edges", range:"0", damage:"1", deadliness:"2", qualities:"", type:"natural", origin:"Shikigami"},
				{name: "Clawed Talon", range:"0-1", damage:"3", deadliness:"5", qualities:"Razor-Edged", type:"natural", origin:"Basan"},
				{name: "Slicing Winds", range:"0-2", damage:"3", deadliness:"7", qualities:"Deals supernatural damage.", type:"natural", origin:"Kami Manifest Air Tiny"},
				{name: "Rising Rock", range:"1-3", damage:"5", deadliness:"5", qualities:"Deals physical or supernatural damage.", type:"natural", origin:"Kami Manifest Earth Tiny"},
				{name: "Barbed Tail", range:"2", damage:"10", deadliness:"5", qualities:"Razor-Edged", type:"natural", origin:"Isonade"},
{name: "Searing Reach", range:"1-2", damage:"4", deadliness:"5", qualities:"deals supernatural damage.", type:"natural", origin:"Tiny Manifest Fire Kami"},
{name: "Damaging Waves", range:"1-2", damage:"5", deadliness:"3", qualities:"deals supernatural damage", type:"natural", origin:"Tiny Manifest Water Kami"},
				
				];
var npcarmor=[
				{armor:"Rags",phys:0,sup:0,qualities:"Mundane",type:"equipped", origin:"Humble Peasant"},
				{armor:"None",phys:0,sup:0,qualities:"None",type:"natural", origin:""},
				{armor:"Sorcerous Raiment",phys:2,sup:4,qualities:"Unholy",type:"equipped", origin:"Deadly Bloodspeaker"},
				{armor:"Thick Hide",phys:4,sup:0,qualities:"None",type:"natural", origin:"Bear, Boar"},
				{armor:"Thick Fur",phys:2,sup:0,qualities:"None",type:"natural", origin:"Hunting Cat"},
				{armor:"Hide",phys:2,sup:0,qualities:"None",type:"natural", origin:"Dog Large, Horse Rokugani Pony, Horse Shinjo Riding Horse, Wolf"},
				{armor:"Hide and Barding",phys:4,sup:0,qualities:"None",type:"natural", origin:"Horse, Utaku Steed"},
				{armor:"Soft Fur",phys:0,sup:0,qualities:"Resplendant, Lovely to Touch",type:"natural", origin:"Cat, Dog Small, Fox, Panda Red"},
				{armor:"Ancient Armor",phys:3,sup:0,qualities:"Wargear",type:"equipped", origin:"Skeleton Bushi"},
				{armor:"Fresh Skin",phys:3,sup:5,qualities:"Unholy",type:"natural", origin:"Bog Hag"},
				{armor:"Demonic Hide",phys:5,sup:5,qualities:"Unholy",type:"natural", origin:"Sinister Oni"},
				{armor:"Decaying Flesh",phys:2,sup:0,qualities:"None",type:"natural", origin:"Zombie Peasant"},
				{armor:"Scaled Hide",phys:1,sup:1,qualities:"None",type:"natural", origin:"Troll Forest"},
				{armor:"Magical Hide",phys:3,sup:3,qualities:"None",type:"natural", origin:"Ki-Rin"},
				{armor:"Misty Mantle",phys:6,sup:0,qualities:"Sacred",type:"natural", origin:"Kami Manifest Air"},
				{armor:"Rocky Hide",phys:5,sup:5,qualities:"Unholy",type:"natural", origin:"Kami Manifest Earth"},
				{armor:"Corona of Flames",phys:3,sup:0,qualities:"None",type:"natural", origin:"Kami Manifest Fire"},
				{armor:"Enshrouding Fog",phys:3,sup:4,qualities:"None",type:"natural", origin:"Kami Manifest Water"},
				{armor:"Bone Plating",phys:3,sup:0,qualities:"Unholy",type:"natural", origin:"Gashadokuro"},
				{armor:"Layers of Paper",phys:6,sup:6,qualities:"Unholy",type:"natural", origin:"Kyorinin"},
				{armor:"Body Shell",phys:3,sup:0,qualities:"",type:"natural", origin:"Penanggalan"},
				{armor:"Numerous Hides",phys:2,sup:0,qualities:"",type:"equipped", origin:"Ravenous Shadowlands Ogre"},
				{armor:"Rusted Armor",phys:2,sup:0,qualities:"",type:"equipped", origin:"Revenant"},
				{armor:"Slimy Skin",phys:1,sup:0,qualities:"",type:"natural", origin:"Tsumunagi"},
				{armor:"Rotting Flesh",phys:3,sup:0,qualities:"",type:"natural", origin:"Undead Horror"},
				{armor:"Wooden Form",phys:3,sup:1,qualities:"",type:"natural", origin:"Wanyudo"},
				{armor:"Outer Husk",phys:3,sup:0,qualities:"",type:"natural", origin:"Fudoshi"},
				{armor:"Corrupted armor",phys:2,sup:1,qualities:"Unholy",type:"equipped", origin:"Dark Moto Bushi, Onikage"},
				{armor:"Defiled priestly robes",phys:1,sup:2,qualities:"Unholy",type:"equipped", origin:"Goblin Accursed Priest, Harionago"},
				{armor:"Nezumi vestments",phys:2,sup:2,qualities:"",type:"equipped", origin:"Nezumi Dreamer"},
				{armor:"Nezumi armour",phys:2,sup:1,qualities:"Wargear",type:"equipped", origin:"Nezumi Warrior"},
				{armor:"Rememberer's robes",phys:1,sup:2,qualities:"Ceremonial",type:"equipped", origin:"Nezumi Rememberer"},
				{armor:"Fur",phys:1,sup:0,qualities:"",type:"natural", origin:"Nezumi Feral"},
				{armor: "Supernatural Hide", phys:"3", sup:"3", qualities:"", type:"natural", origin:"Akkorokamui"},
				{armor: "Chitinous Hide", phys:"3", sup:"0", qualities:"", type:"natural", origin:"Amikiri"},
				{armor: "Electric Form", phys:"10", sup:"0", qualities:"", type:"natural", origin:"Hinotama"},
				{armor: "Turtle Shell", phys:"4", sup:"2", qualities:"", type:"natural", origin:"Kappa Mischievous"},
				{armor: "Unholy Hide", phys:"3", sup:"2", qualities:"Unholy", type:"equipped", origin:"Rakshasa"},
				{armor: "Cloak of Air", phys:"3", sup:"2", qualities:"None", type:"natural", origin:"Kami Manifest Air Tiny"},
{armor: "Skin of Stone", phys:"4", sup:"0", qualities:"Sacred", type:"natural", origin:"Kami Manifest Earth Tiny"},
{armor: "Ghostly Energy", phys:"10", sup:"0", qualities:"", type:"natural", origin:"Furiribi"},
{armor: "Blazing Body", phys:"2", sup:"0", qualities:"", type:"natural", origin:"Tiny Manifest Fire Kami"},
{armor: "Malleable Form", phys:"2", sup:"2", qualities:"", type:"natural", origin:"Tiny Manifest Water Kami"},
				];