var npcweapons=[
				{name:"Ritual Knife", range:0, damage:2, deadliness:6, qualities:"Concealable, Razor-Edged, Unholy",type:"equipped"},
				{name:"Obsidian-Edged Katana",range:1,damage:5,deadliness:9,qualities:"Razor-Edged, Unholy",type:"equipped"},
				{name:"Rusty Katana",range:1,damage:4,deadliness:5,qualities:"Ceremonial, Damaged, Razor-Edged",type:"equipped"},
				{name:"Crushing Claws and Fangs",range:"1-2",damage:8,deadliness:6,qualities:"None",type:"natural"},
				{name:"Tusks",range:0,damage:7,deadliness:7,qualities:"Durable, Razor-Edged",type:"natural"},
				{name:"Little Claws",range:0,damage:1,deadliness:2,qualities:"Concealable, Razor-Edged",type:"natural"},
				{name:"Vicious Bite",range:0,damage:4,deadliness:2,qualities:"Snaring",type:"natural"},
				{name:"Little Bite",range:0,damage:2,deadliness:1,qualities:"Snaring",type:"natural"},
				{name:"Beak and Talons",range:0,damage:1,deadliness:6,qualities:"None",type:"natural"},
				{name:"Hooves",range:"1-2",damage:6,deadliness:5,qualities:"None",type:"natural"},
				{name:"Rending Claws and Fangs",range:1,damage:5,deadliness:9,qualities:"Razor-Edged",type:"natural"},
				{name:"Mighty Hooves",range:"1-2",damage:7,deadliness:6,qualities:"None",type:"natural"},
				{name:"Vicious Fangs",range:0,damage:4,deadliness:4,qualities:"Snaring",type:"natural"},
				{name:"Decrepit Yumi",range:"2-5",damage:5,deadliness:3,qualities:"Damaged",type:"equipped"},
				{name:"Twisted Talons",range:"1-2",damage:4,deadliness:5,qualities:"Razor-Edged, Unholy",type:"natural"},
				{name:"Horrific Maw",range:0,damage:1,deadliness:8,qualities:"None",type:"natural"},
				{name:"Small Yari",range:1,damage:5,deadliness:3,qualities:"Wargear",type:"equipped",},
				{name:"Small Yumi",range:"2-3",damage:4,deadliness:3,qualities:"None",type:"equipped"},
				{name:"Crushing Claws",range:"1-2",damage:6,deadliness:8,qualities:"Unholy, Razor-Edged",type:"natural"},
				{name:"Jagged Teeth",range:0,damage:3,deadliness:5,qualities:"Unholy",type:"natural"},
				{name:"Grasping Hands",range:"0-1",damage:2,deadliness:1,qualities:"Snaring",type:"natural"},
				{name:"Massive Cudgel",range:2,damage:9,deadliness:5,qualities:"Cumbersome",type:"natural"},
				{name:"Rending Grip",range:1,damage:4,deadliness:6,qualities:"None",type:"natural"},
				{name:"Majestic Antlers",range:"1-2",damage:4,deadliness:6,qualities:"Ceremonial, Sacred",type:"natural"},
				{name:"Talons of Air",range:"2-3",damage:4,deadliness:7,qualities:"Deals supernatural damage",type:"natural"},
				{name:"Stone Fists",range:"0-2",damage:7,deadliness:4,qualities:"Deals physical or supernatural damage",type:"natural"},
				{name:"Blazing Touch",range:"1-3",damage:6,deadliness:6,qualities:"Razor-Edged, Deals supernatural damage",type:"natural",},
				{name:"Smashing Torrent",range:"1-2",damage:7,deadliness:3,qualities:"Snaring, Deals supernatural damage",type:"natural"},
				{name:"Claws and Teeth",range:"0-2",damage:7,deadliness:7,qualities:"Unholy",type:"natural"},
				{name:"Barbed Hair",range:"0-2",damage:3,deadliness:6,qualities:"Unholy",type:"natural"},
				{name:"Smothering Papers",range:"0-1",damage:4,deadliness:4,qualities:"Unholy, Snaring",type:"natural"},
				{name:"Tentacle Entrails",range:"0-2",damage:5,deadliness:6,qualities:"Snaring, Unholy",type:"natural"},
				{name:"Tree Trunk",range:"1-2",damage:8,deadliness:2,qualities:"",type:"equipped"},
				{name:"Heavy Masakari",range:"0-1",damage:"4/5",deadliness:"4/6",qualities:"Mundane",type:"equipped"},
				{name:"Biting Teeth",range:"0",damage:4,deadliness:3,qualities:"Razor-Edged, Unholy",type:"natural"},
				{name:"Rotted Fists and Teeth",range:"0",damage:6,deadliness:3,qualities:"Unholy",type:"natural"},
				{name:"Crushing Fire",range:"0",damage:4,deadliness:4,qualities:"Unholy",type:"natural"},
				{name:"Tangling Vines",range:"0-2",damage:3,deadliness:2,qualities:"Snaring, Unholy",type:"natural"},
				{name:"Teeth and Hooves",range:"0-1",damage:4,deadliness:3,qualities:"Unholy",type:"natural"},
				{name:"Ritual Dagger",range:"0",damage:2,deadliness:4,qualities:"Unholy, Razor-Edged",type:"equipped"},
				{name:"Nezumi dagger",range:"0-1",damage:3,deadliness:3,qualities:"",type:"equipped"},
				{name:"Nezumi knife",range:"0",damage:2,deadliness:4,qualities:"Concealable, Mundane",type:"equipped"},
				{name:"Nezumi Claws and Teeth",range:"0",damage:2,deadliness:3,qualities:"",type:"natural"},
				{name:"Sharp Little Teeth",range:"0",damage:1,deadliness:2,qualities:"Razor-Edged",type:"natural"},
				{name: "Tentacle Arms", range:"0-5", damage:"8", deadliness:"6", qualities:"", type:"natural"},
				{name: "Scorpion Claws", range:"0", damage:"4", deadliness:"3", qualities:"", type:"natural"},
				{name: "Tail Stinger", range:"0-1", damage:"3", deadliness:"6", qualities:"", type:"natural"},
{name: "None", range:"0", damage:"0", deadliness:"0", qualities:"", type:"natural"},
{name: "Arcing Lightning", range:"0-4", damage:"4", deadliness:"5", qualities:"deals Supernatural damage", type:"natural"},
{name: "Razor Teeth", range:"0", damage:"7", deadliness:"9", qualities:"Razor-Edged", type:"natural"},
{name: "Razor Claws", range:"0", damage:"4", deadliness:"6", qualities:"Razor-Edged", type:"natural"},
{name: "Deadly Claws", range:"0-1", damage:"5", deadliness:"4", qualities:"Razor-Edged, Unholy", type:"natural"},
{name: "Urumi", range:"1-2", damage:"4", deadliness:"5", qualities:"Cumbersome, Razor-Edged, Snaring", type:"equipped"},



				];
var npcarmor=[
				{armor:"Rags",phys:0,sup:0,qualities:"Mundane",type:"equipped"},
				{armor:"None",phys:0,sup:0,qualities:"None",type:"natural"},
				{armor:"Sorcerous Raiment",phys:2,sup:4,qualities:"Unholy",type:"equipped"},
				{armor:"Thick Hide",phys:4,sup:0,qualities:"None",type:"natural"},
				{armor:"Thick Fur",phys:2,sup:0,qualities:"None",type:"natural"},
				{armor:"Hide",phys:2,sup:0,qualities:"None",type:"natural"},
				{armor:"Hide and Barding",phys:4,sup:0,qualities:"None",type:"natural"},
				{armor:"Soft Fur",phys:0,sup:0,qualities:"Resplendant, Lovely to Touch",type:"natural"},
				{armor:"Ancient Armor",phys:3,sup:0,qualities:"Wargear",type:"equipped"},
				{armor:"Fresh Skin",phys:3,sup:5,qualities:"Unholy",type:"natural"},
				{armor:"Demonic Hide",phys:5,sup:5,qualities:"Unholy",type:"natural"},
				{armor:"Decaying Flesh",phys:2,sup:0,qualities:"None",type:"natural"},
				{armor:"Scaled Hide",phys:1,sup:1,qualities:"None",type:"natural"},
				{armor:"Magical Hide",phys:3,sup:3,qualities:"None",type:"natural"},
				{armor:"Misty Mantle",phys:6,sup:0,qualities:"Sacred",type:"natural"},
				{armor:"Rocky Hide",phys:5,sup:5,qualities:"Unholy",type:"natural"},
				{armor:"Corona of Flames",phys:3,sup:0,qualities:"None",type:"natural"},
				{armor:"Enshrouding Fog",phys:3,sup:4,qualities:"None",type:"natural"},
				{armor:"Bone Plating",phys:3,sup:0,qualities:"Unholy",type:"natural"},
				{armor:"Layers of Paper",phys:6,sup:6,qualities:"Unholy",type:"natural"},
				{armor:"Body Shell",phys:3,sup:0,qualities:"",type:"natural"},
				{armor:"Numerous Hides",phys:2,sup:0,qualities:"",type:"equipped"},
				{armor:"Rusted Armor",phys:2,sup:0,qualities:"",type:"equipped"},
				{armor:"Slimy Skin",phys:1,sup:0,qualities:"",type:"natural"},
				{armor:"Rotting Flesh",phys:3,sup:0,qualities:"",type:"natural"},
				{armor:"Wooden Form",phys:3,sup:1,qualities:"",type:"natural"},
				{armor:"Outer Husk",phys:3,sup:0,qualities:"",type:"natural"},
				{armor:"Corrupted armor",phys:2,sup:1,qualities:"Unholy",type:"equipped"},
				{armor:"Defiled priestly robes",phys:1,sup:2,qualities:"Unholy",type:"equipped"},
				{armor:"Nezumi vestments",phys:2,sup:2,qualities:"",type:"equipped"},
				{armor:"Nezumi armour",phys:2,sup:1,qualities:"Wargear",type:"equipped"},
				{armor:"Rememberer's robes",phys:1,sup:2,qualities:"Ceremonial",type:"equipped"},
				{armor:"Fur",phys:1,sup:0,qualities:"",type:"natural"},
				{armor: "Supernatural Hide", phys:"3", sup:"3", qualities:"", type:"natural"},
				{armor: "Chitinous Hide", phys:"3", sup:"0", qualities:"", type:"natural"},
{armor: "Electric Form", phys:"10", sup:"0", qualities:"", type:"natural"},
{armor: "Turtle Shell", phys:"4", sup:"2", qualities:"", type:"natural"},
{armor: "Unholy Hide", phys:"3", sup:"2", qualities:"Unholy", type:"equipped"},



				];