var npcweapons=[
				{title:"Ritual Knife", range:0, damage:2, deadliness:6, qualities:"Concealable, Razor-Edged, Unholy",type:"equipped"},
				{title:"Obsidian-Edged Katana",range:1,damage:5,deadliness:9,qualities:"Razor-Edged, Unholy",type:"equipped"},
				{title:"Rusty Katana",range:1,damage:4,deadliness:5,qualities:"Ceremonial, Damaged, Razor-Edged",type:"equipped"},
				{title:"Crushing Claws and Fangs",range:"1-2",damage:8,deadliness:6,qualities:"None",type:"natural"},
				{title:"Tusks",range:0,damage:7,deadliness:7,qualities:"Durable, Razor-Edged",type:"natural"},
				{title:"Little Claws",range:0,damage:1,deadliness:2,qualities:"Concealable, Razor-Edged",type:"natural"},
				{title:"Vicious Bite",range:0,damage:4,deadliness:2,qualities:"Snaring",type:"natural"},
				{title:"Little Bite",range:0,damage:2,deadliness:1,qualities:"Snaring",type:"natural"},
				{title:"Beak and Talons",range:0,damage:1,deadliness:6,qualities:"None",type:"natural"},
				{title:"Hooves",range:"1-2",damage:6,deadliness:5,qualities:"None",type:"natural"},
				{title:"Rending Claws and Fangs",range:1,damage:5,deadliness:9,qualities:"Razor-Edged",type:"natural"},
				{title:"Mighty Hooves",range:"1-2",damage:7,deadliness:6,qualities:"None",type:"natural"},
				{title:"Vicious Fangs",range:0,damage:4,deadliness:4,qualities:"Snaring",type:"natural"},
				{title:"Decrepit Yumi",range:"2-5",damage:5,deadliness:3,qualities:"Damaged",type:"equipped"},
				{title:"Twisted Talons",range:"1-2",damage:4,deadliness:5,qualities:"Razor-Edged, Unholy",type:"natural"},
				{title:"Horrific Maw",range:0,damage:1,deadliness:8,qualities:"None",type:"natural"},
				{title:"Small Yari",range:1,damage:5,deadliness:3,qualities:"Wargear",type:"equipped",},
				{title:"Small Yumi",range:"2-3",damage:4,deadliness:3,qualities:"None",type:"equipped"},
				{title:"Crushing Claws",range:"1-2",damage:6,deadliness:8,qualities:"Unholy, Razor-Edged",type:"natural"},
				{title:"Jagged Teeth",range:0,damage:3,deadliness:5,qualities:"Unholy",type:"natural"},
				{title:"Grasping Hands",range:"0-1",damage:2,deadliness:1,qualities:"Snaring",type:"natural"},
				{title:"Massive Cudgel",range:2,damage:9,deadliness:5,qualities:"Cumbersome",type:"natural"},
				{title:"Rending Grip",range:1,damage:4,deadliness:6,qualities:"None",type:"natural"},
				{title:"Majestic Antlers",range:"1-2",damage:4,deadliness:6,qualities:"Ceremonial, Sacred",type:"natural"},
				{title:"Talons of Air",range:"2-3",damage:4,deadliness:7,qualities:"Deals supernatural damage",type:"natural"},
				{title:"Stone Fists",range:"0-2",damage:7,deadliness:4,qualities:"Deals physical or supernatural damage",type:"natural"},
				{title:"Blazing Touch",range:"1-3",damage:6,deadliness:6,qualities:"Razor-Edged, Deals supernatural damage",type:"natural",},
				{title:"Smashing Torrent",range:"1-2",damage:7,deadliness:3,qualities:"Snaring, Deals supernatural damage",type:"natural"},
				];
var npcarmor=[
				{title:"Rags",phys:0,sup:0,qualities:"Mundane",type:"equipped"},
				{title:"None",phys:0,sup:0,qualities:"None",type:"natural"},
				{title:"Sorcerous Raiment",phys:2,sup:4,qualities:"Unholy",type:"equipped"},
				{title:"Thick Hide",phys:4,sup:0,qualities:"None",type:"natural"},
				{title:"Thick Fur",phys:2,sup:0,qualities:"None",type:"natural"},
				{title:"Hide",phys:2,sup:0,qualities:"None",type:"natural"},
				{title:"Hide and Barding",phys:4,sup:0,qualities:"None",type:"natural"},
				{title:"Soft Fur",phys:0,sup:0,qualities:"Resplendant, Lovely to Touch",type:"equipped",type:"natural"},
				{title:"Ancient Armor",phys:3,sup:0,qualities:"Wargear",type:"equipped"},
				{title:"Fresh Skin",phys:3,sup:5,qualities:"Unholy",type:"natural"},
				{title:"Demonic Hide",phys:5,sup:5,qualities:"Unholy",type:"natural"},
				{title:"Decaying Flesh",phys:2,sup:0,qualities:"None",type:"natural"},
				{title:"Scaled Hide",phys:1,sup:1,qualities:"None",type:"natural"},
				{title:"Magical Hide",phys:3,sup:3,qualities:"None",type:"natural"},
				{title:"Misty Mantle",phys:6,sup:0,qualities:"Sacred",type:"natural"},
				{title:"Rocky Hide",phys:5,sup:5,qualities:"Unholy",type:"natural"},
				{title:"Corona of Flames",phys:3,sup:0,qualities:"None",type:"natural"},
				{title:"Enshrouding Fog",phys:3,sup:4,qualities:"None",type:"natural"},
				];

var demeanors =[
{demeanor:"Ambitious",tns:"Fire +2, Water -2",unmasking:"Bend Principles",desc:"This character pursues power whenever possible and is extremely resistant to giving it up. However, they jump to support appeals that line up with their own desires."},
{demeanor:"Assertive",tns:"Earth +2, Air -2",unmasking:"Rage",desc:"This person is used to being in charge, and does not like being told what they can or cannot to do. They are most pliant when they think they are getting their way."},
{demeanor:"Detached",tns:"Earth +1, Fire +1, Void -2",unmasking:"Expose an Opening",desc:"This individual is extremely meditative, spiritual, enlightened, or simply uninterested in other people."},
{demeanor:"Gruff",tns:"Water +2, Earth -2",unmasking:"Inappropriate Outburst",desc:"With a rough exterior and a no-nonsense attitude, this person has little tolerance for frivolity, niceties, or trickery."},
{demeanor:"Shrewd",tns:"Air +2, Fire -2",unmasking:"Panicked Retreat",desc:"This individual is used to maneuvering around powerful people, and tends to avoid direct conflict. They are also very wary of such efforts on the part of others."},
{demeanor:"Courageous",tns:"Air +2, Earth -2",unmasking:"Angry Dismay",desc:"This character does not hesitate to overcome their fear and act with courage, no matter the consequences."},
{demeanor:"Intimidating",tns:"Fire +2, Air -2",unmasking:"Threats or Violence",desc:""},
{demeanor:"Playful",tns:"Earth +2, Water -2",unmasking:"",desc:""},
{demeanor:"Friendly",tns:"Fire +1, Earth -2, Water -2",unmasking:"",desc:""},
{demeanor:"Loyal",tns:"Air +1, Earth -2, Fire -2",unmasking:"",desc:""},
{demeanor:"Proud",tns:"Fire +2, Earth -2",unmasking:"",desc:""},
{demeanor:"Opportunistic",tns:"Water +2, Fire -2",unmasking:"",desc:""},
{demeanor:"Cautious",tns:"Air +2, Earth -2",unmasking:"",desc:""},
{demeanor:"Angry",tns:"Fire +2, Air -2",unmasking:"",desc:""},
{demeanor:"Flighty",tns:"Air +2, Fire -2",unmasking:"",desc:""},
{demeanor:"Obstinate",tns:"Water +2, Air -2",unmasking:"",desc:""},
{demeanor:"Intense",tns:"Air +2, Water -2",unmasking:"",desc:""},
{demeanor:"Adaptable",tns:"Fire +2, Earth -2",unmasking:"",desc:""},
{demeanor:"Territorial",tns:"Fire +2, Air -2",unmasking:"",desc:""},
{demeanor:"Hungry",tns:"Fire +2, Air -2",unmasking:"",desc:""},
]

var archetypes =[
		{
			title:"Rank 1 Samurai",
			type:"Rokugani",
			equiptype:"equipped",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:1,
				Fire:1,
				Water:1,
				Void:1,},
			honor:30,
			glory:20,
			status:30,
			endurance:6,
			composure:6,
			focus:4,
			vigilance:2,
			max:3,
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:[],
			advantages:[
					],
			disadvantages:[	

					],
			weapon:["Katana","Wakizashi","Yari","Yumi",],
			armor:["Traveling Clothes","Ashigaru Armor",],
			abilities:[],
			techniques:[],
		},		{
			title:"Rank 2 Samurai",
			type:"Rokugani",
			equiptype:"equipped",
			conflictcombat:2,
			conflictintrigue:2,
			rank:2,
			ring:{
				type: "random",
				Earth:1,
				Air:1,
				Fire:1,
				Water:1,
				Void:1,},
			honor:40,
			glory:40,
			status:35,
			endurance:9,
			composure:9,
			focus:5,
			vigilance:2,
			max:4,
			skills:{
				artisanskill:1,
				martialskill:1,
				scholarskill:1,
				socialskill:1,
				tradeskill:1,},
			demeanor:[],
			advantages:[
					
					],
			disadvantages:[	

					],
			weapon:["Katana","Wakizashi","Yari","Yumi",],
			armor:["Traveling Clothes","Ashigaru Armor",],
			abilities:[],
			techniques:[],
			extra: function(){
						this.ring.Earth = 1
						this.ring.Air = 1
						this.ring.Fire = 1
						this.ring.Water = 1
						this.ring.Void = 1
						array=[1,1,0,0,0];
						array = shuffle(array);
						this.ring.Earth += array[0];
						this.ring.Air += array[1];
						this.ring.Fire += array[2];
						this.ring.Water += array[3];
						this.ring.Void += array[4];
			}
			
		},	{
			title:"Rank 3 Samurai",
			type:"Rokugani",
			equiptype:"equipped",
			conflictcombat:3,
			conflictintrigue:3,
			rank:3,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:2,
				Water:2,
				Void:2,},
			honor:40,
			glory:40,
			status:35,
			endurance:11,
			composure:11,
			focus:6,
			vigilance:2,
			max:4,
			skills:{
				artisanskill:1,
				martialskill:1,
				scholarskill:1,
				socialskill:1,
				tradeskill:1,},
			demeanor:[],
			advantages:[
					
					],
			disadvantages:[	

					],
			weapon:["Katana","Wakizashi","Yari","Yumi",],
			armor:["Traveling Clothes","Ashigaru Armor",],
			abilities:[],
			techniques:[],
		},{
			title:"Bear",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:1,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:12,
			composure:9,
			focus:4,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:["Intimidating"],
			advantages:[
					"Enormous Stature (Earth) [Martial; Physical]"
					],
			disadvantages:[	
					"Opportunist (Fire) [Martial; Mental]"
					],
			weapon:["Crushing Claws and Fangs",],
			armor:["Thick Hide",],
			abilities:["Crushing Swipe: A bear is a silhouette 3 creature with terrifying strength. When a bear inflicts a critical strike, the TN of the check to resist is 4, and if the target fails, they suffer the Dazed condition in addition to the other effects."],
			techniques:[],
		},{
			title:"Boar",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:5,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:2,
				Fire:4,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:8,
			composure:4,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:["Territorial"],
			advantages:[
					"Keen Sense of Smell (Fire) [Trade; Physical]"
					],
			disadvantages:[	
					"Hot Tempered (Water) [Martial; Mental]"
					],
			weapon:["Tusks",],
			armor:["Thick Hide",],
			abilities:["Sustaining Fury: After a boar suffers a critical strike, it becomes Enraged. While Enraged, a boar cannot suffer the Unconscious condition and may perform Attack actions even while Incapacitated."],
			techniques:[],
		},{
			title:"Cat",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:4,
				Fire:1,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:3,
			composure:9,
			focus:6,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Playful"],
			advantages:[
					"Winsome Manner (Water) [Social; Interpersonal]",
					"Silent Stalker (Air) [Martial; Physical]"
					],
			disadvantages:[	
					"Hubris (Air) [Social; Mental]"
					],
			weapon:["Little Claws",],
			armor:["Soft Fur",],
			abilities:["Pouncing Predator: A cat is a silhouette 0 creature. When performing an Attack action check against an unaware or Prone target, it may spend <span class='l5r'>O</span> as follows:<br> <span class='l5r'>O</span>: The target suffers the Disoriented condition."],
			techniques:[],
		},{
			title:"Panda, Red",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:3,
				Fire:1,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:4,
			composure:7,
			focus:6,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:1,
				tradeskill:1,},
			demeanor:["Playful"],
			advantages:[
					"Clever Little Hands (Fire) [Trade; Physical]",
					"Good Communicator (Water) [Social; Interpersonal]",
					"Winsome Manner (Water) [Social; Interpersonal]",
					"Deft Climber (Air) [Martial; Physical]"
					],
			disadvantages:[	
					"Light Fingers (Water) [Social; Mental]"
					],
			weapon:["Little Bite",],
			armor:["Soft Fur",],
			abilities:["The Red Panda is a devastatingly cute silhouetto 0 creature.  When attempting to captivate a human, it may spend <span class='l5r'>O</span> as follows:<br> <span class='l5r'>O</span>: The target suffers the Disoriented condition."],
			techniques:[],
		},{
			title:"Dog, Large",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:1,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:6,
			composure:5,
			focus:3,
			vigilance:4,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Friendly"],
			advantages:[
					"Keen Tracker (Water) [Trade; Physical]",
					"Such a Good Boy! (Water) [Social; Interpersonal]",
					],
			disadvantages:[	
					"Dependent on Humans (Fire) [Trade; Mental]"
					],
			weapon:["Vicious Bite",],
			armor:["Hide",],
			abilities:["Working Companion: Choose one Martial or Trade skill. When the dog provides assistance on a check with this skill, it counts as providing skilled assistance (see page 26)."],
			techniques:[],
		},{
			title:"Dog, Small",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:1,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:4,
			composure:2,
			focus:3,
			vigilance:5,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Friendly"],
			advantages:[
					"Keen Tracker (Water) [Trade; Physical]"
					],
			disadvantages:[	
					"Yappy (Air) [Mental]",
					"Small Dog Complex (Water) [Mental]",
					"Dependent on Humans (Fire) [Trade; Mental]"
					],
			weapon:["Little Bite",],
			armor:["Soft Fur",],
			abilities:["Working Companion: Choose one Martial or Trade skill. When the dog provides assistance on a check with this skill, it counts as providing skilled assistance (see page 26)."],
			techniques:[],
		},{
			title:"Hawk",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:4,
				Fire:2,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:2,
			composure:5,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:["Proud"],
			advantages:[
					"Sharp Eyesight (Water) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Hollow Bones (Earth) [Martial; Physical]"
					],
			weapon:["Beak and Talons",],
			armor:["None",],
			abilities:["Nimble Flier: A hawk is a silhouette 0 creature that can fly. It can move vertically and ignores the negative effects of terrain",
						"Swoop: When performing an Attack action check, a hawk may spend <span class='l5r'>O</span> as follows: <br><span class='l5r'>O</span>+: Move 1 range band away from the target per <span class='l5r'>O</span> spent this way. If the target is of silhouette 0 or smaller, the hawk may carry it to its destination instead."],
			techniques:[],
		},{
			title:"Horse, Rokugani Pony",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:2,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:8,
			composure:4,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Loyal"],
			advantages:[
					"Tireless Runner (Earth) [Martial; Physical]"
					],
			disadvantages:[	
					"Skittish (Fire) [Martial; Mental]"
					],
			weapon:["Hooves",],
			armor:["Hide",],
			abilities:["Loyal Steed: A Rokugani pony is a silhouette 3 creature. It can be ridden by a human-sized (silhouette 2 or lower) rider.","Trained Mount: While it is being ridden during a conflict, a mount does not take a turn of its own, and provides the following benefits to its rider:<br>- When the rider succeeds on a Movement action check, add bonus successes equal to the mount's Water Ring. <br>- The rider may use their Survival skill in place of their Fitness skill for any Fitness check they make.<br>- During narrative and downtime scenes, a mounted character doubles their overland travel speed."],
			techniques:[],
		},{
			title:"Horse, Shinjo Riding Horse",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:3,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:2,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:12,
			composure:8,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:2,
				tradeskill:0,},
			demeanor:["Loyal"],
			advantages:[
					"Tireless Runner (Earth) [Martial; Physical]"
					],
			disadvantages:[	
					"Proud and Haughty (Water) [Social; Interpersonal]",
					"Traumatised by War (Fire) [Martial; Mental]",
					"Quick to Anger (Fire) [Social; Interpersonal]",
					"Dependent on Rider (Earth) [Social, Martial; Mental]"
					],
			weapon:["Hooves",],
			armor:["Hide",],
			abilities:["Loyal Steed: A Shinjo Riding Horse is a silhouette 3 creature. It can be ridden by a human-sized (silhouette 2 or lower) rider.","Trained Mount: While it is being ridden during a conflict, a mount does not take a turn of its own, and provides the following benefits to its rider:<br>- When the rider succeeds on a Movement action check, add bonus successes equal to the mount's Water Ring. <br>- The rider may use their Survival skill in place of their Fitness skill for any Fitness check they make.<br>- During narrative and downtime scenes, a mounted character doubles their overland travel speed."],
			techniques:[],
		},{
			title:"Horse, Utaku Steed",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:4,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:14,
			composure:10,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:3,
				scholarskill:0,
				socialskill:3,
				tradeskill:0,},
			demeanor:["Loyal"],
			advantages:[
					"Tireless Runner (Earth) [Martial; Physical]"
					],
			disadvantages:[	
					"Proud and Haughty (Water) [Social; Interpersonal]",
					"Traumatised by War (Fire) [Martial; Mental]",
					"Quick to Anger (Fire) [Social; Interpersonal]",
					"Dependent on Rider (Earth) [Social, Martial; Mental]"
					],
			weapon:["Mighty Hooves",],
			armor:["Hide and Barding",],
			abilities:["Legendary Steed: An Utaku steed is a silhouette 3 creature. It can be ridden by a human-sized (silhouette 2 or lower) rider, but generally does not tolerate any rider other than a worthy Utaku Battle Maiden.",
					"Paragon of Horses: A Utaku steed grants its rider skilled assistance (Core p26) on Martial checks they make while mounted","Trained Mount: While it is being ridden during a conflict, a mount does not take a turn of its own, and provides the following benefits to its rider:<br>- When the rider succeeds on a Movement action check, add bonus successes equal to the mount's Water Ring. <br>- The rider may use their Survival skill in place of their Fitness skill for any Fitness check they make.<br>- During narrative and downtime scenes, a mounted character doubles their overland travel speed."],
			techniques:[],
		},{
			title:"Hunting Cat",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:6,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:4,
				Fire:1,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:6,
			composure:12,
			focus:6,
			vigilance:4,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Opportunistic"],
			advantages:[
					"Silent Stalker (Air) [Martial; Physical]"
					],
			disadvantages:[	
					"Hubris (Air) [Social; Mental]"
					],
			weapon:["Rending Claws and Fangs",],
			armor:["Thick Fur",],
			abilities:["Pouncing Predator: A hunting cat is a silhouette 3 creature. When performing an Attack action check against an unaware or Prone target, it may spend <span class='l5r'>O</span> as follows: <br><span class='l5r'>O</span>: The target suffers the Disoriented condition.","Savage Mauling: Disoriented targets cannot defend against damage dealt by a hunting cat."],
			techniques:[],
		},{
			title:"Wolf",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:4,
			composure:4,
			focus:6,
			vigilance:4,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Cautious"],
			advantages:[
					"Pack Tactics (Water) [Martial, Social; Interpersonal]"
					],
			disadvantages:[	
					"Cautious Hunter (Fire) [Martial; Mental]"
					],
			weapon:["Vicious Fangs",],
			armor:["Hide",],
			abilities:["Circle the Kill: When performing a Martial Arts [Unarmed] check, a wolf may spend <span class='l5r'>O</span> in the following ways. <br>Water <span class='l5r'>O</span>: The target suffers the Bleeding condition. <br>Fire <span class='l5r'>O</span> : The target treats all terrain as Dangerous (see page 267) until the end of their next turn."],
			techniques:[],
		},{
			title:"Bushi Skeleton",
			type:"Creatures",
			equiptype:"equipped",
			conflictcombat:3,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:2,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:7,
			composure:"Infinite",
			focus:3,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:1,},
			demeanor:["Angry"],
			advantages:[
					"Unholy Vigor (Earth) [Martial; Physical, Spiritual]"
					],
			disadvantages:[	
					"Visage of Death (Water) [Social; Interpersonal]"
					],
			weapon:["Rusty Katana","Decrepit Yumi",],
			armor:["Ancient Armor",],
			abilities:["Clattering Bones: A skeletal bushi is an Otherworldly, Tainted being. Additionally, the first time it would be defeated each scene, it receives a Scar disadvantage of the GM's choice instead as one of its limbs snaps or flies off.","Does not Bleed: A skeletal bushi ignores conditions and critical strikes from non-Sacred sources."],
			techniques:[],
		},{
			title:"Bog Hag",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:8,
			conflictintrigue:5,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:4,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:14,
			composure:8,
			focus:6,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:3,
				martialskill:2,
				scholarskill:6,
				socialskill:2,
				tradeskill:1,},
			demeanor:["Shrewd"],
			advantages:[
					"Shapeshifter's Guile (Air) [Social; Interpersonal]",
					"Sorcerous Lore (Void) [Scholar; Mental]"
					],
			disadvantages:[	
					"Dreadful Hunger (Earth) [Social; Interpersonal, Mental]"
					],
			weapon:["Twisted Talons","Horrific Maw"],
			armor:["Fresh Skin",],
			abilities:[
						"Accursed Regneneration: At the end of each round, if the bog hag has not suffered damage from a Sacred source this round, the bog hag removes the Lightly Injured condition or reduces the Severely Injured condition to Lightly Injured.",
						"Seeker of Vile Lore: The bog hag is an Otherworldly, Tainted being. Optionally, choose 0-3 maho techniques (see page 224) that the bog hag can perform. Add 1 to this character's combat rank for each maho chosen this way",
						"Skins of the Slaughtered: As an action, a bog hag may assume the illusory form of anyone it has killed. A character may make a TN 3 Sentiment check (Earth 4, Fire 1), or another appropriate check to see through this illusion. At the GM's discretion, a character may spend <span class='l5r'>O</span> <span class='l5r'>O</span> from any check to interact with the bog hag to see one of the following: a misplaced fold in the skin, luminescence in one eye, an impossible movement of the jaw, oddly sharp teeth, the smell of viscera, a conversational fixation on fresh and bloody meat. "
					],
			techniques:[],
		},{
			title:"Goblin",
			type:"Creatures",
			equiptype:"equipped",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:2,
				Water:1,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:3,
			composure:4,
			focus:3,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:1,},
			demeanor:["Shrewd"],
			advantages:[
					"Expert Skulker (Air) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Cowardice (Earth) [Martial, Social; Mental]"
					],
			weapon:["Small Yari","Small Yumi"],
			armor:["Ashigaru Armor"],
			abilities:[
					"Shadowlands Creature: A Shadowlands goblin is a Tainted being of silhouette 1.",
					"Unsightly Rabble: When making an Attack action check with assistance, a goblin may spend <span class='l5r'>O</span> as follows: <span class='l5r'>O</span>+: One character other than the target at range 0-2 suffers 4 physical damage. This <span class='l5r'>O</span> can be activated a number of times per round equal to the number of goblins assisting with the check.)"
											],
			techniques:[],
		},{
			title:"Sinister Oni",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:12,
			conflictintrigue:5,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:3,
				Fire:6,
				Water:3,
				Void:3,},
			honor:0,
			glory:4,
			status:0,
			endurance:24,
			composure:12,
			focus:8,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:4,
				scholarskill:3,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Assertive"],
			advantages:[
					"Massive Stature (Earth) [Martial; Physical]",
					"Unholy Might (Fire) [Martial; Physical, Spiritual]"
					],
			disadvantages:[	
					"Horrifying Visage (Water) [Social; Interpersonal]"
					],
			weapon:["Crushing Claws"],
			armor:["Demonic Hide"],
			abilities:[
						"Dread Bellow: Once per scene as a Scheme action, the oni may roar, feeding on the primal terror it instills. Each other character at range 0-4 must resist with a TN 4 Meditation check (Earth 2, Air 5) or suffer the Afflicted condition and stumble back 1 range band from the oni. For each character who fails, the oni removes 2 fatigue.",
						"Horror of Jigoku: An oni is an Otherworldly, Tainted being of silhouette 4. After any character performs a successful Attack action that deals 0 damage to the oni (after resistance is applied), that character suffers 3 strife."
											],
			techniques:[],
		},{
			title:"Zombie Peasant",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:0,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:3,
				Water:2,
				Void:0,},
			honor:0,
			glory:4,
			status:0,
			endurance:4,
			composure:"Infinite",
			focus:3,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:["Hungry"],
			advantages:[
					"Hungry for Flesh (Fire) [Martial; Mental]"
					],
			disadvantages:[	
					"Stumbling Gait (Water) [Martial; Physical]"
					],
			weapon:["Jagged Teeth","Grasping Hands"],
			armor:["Decaying Flesh"],
			abilities:[
						"Cadavarous Bite: Increase the TN of checks to resist critical strikes inflicted by zombies by 2",
						"Horrifying Reanimation: A zombie is an Otherworldly, Tainted being. The first time it is defeated by damage from a non-Sacred source, if a zombie is in Defiled terrain, it reanimates. At the start of its next turn, it removes all fatigue and staggers to its feet with a scar disadvantage of the GM's choice"
											],
			techniques:[],
		},{
			title:"Forest Troll",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:4,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:2,
				Fire:5,
				Water:4,
				Void:3,},
			honor:30,
			glory:10,
			status:5,
			endurance:16,
			composure:9,
			focus:4,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:1,
				martialskill:3,
				scholarskill:3,
				socialskill:2,
				tradeskill:1,},
			demeanor:["Assertive"],
			advantages:[
					"Brute Strength (Fire) [Martial; Physical]"
					],
			disadvantages:[	
					"Insatiable Appetites (Water) [Social; Physical]"
					],
			weapon:["Massive Cudgel","Rending Grips"],
			armor:["Scaled Hide"],
			abilities:[
						"Ancient and Powerful: A troll is an Otherworldly being of silhouette 4.",
						"Sorcerous Scales: After a troll suffers damage from a physical or supernatural source, increase its resistance to that damage type by 4. This effect persists until it suffers damage from a source of a different type."
											],
			techniques:[],
		},{
			title:"Ki-Rin",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:7,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:3,
				Fire:2,
				Water:4,
				Void:5,},
			honor:60,
			glory:50,
			status:39,
			endurance:14,
			composure:16,
			focus:3,
			vigilance:5,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:5,
				scholarskill:6,
				socialskill:3,
				tradeskill:0,},
			demeanor:["Detached"],
			advantages:[
					"Wisdom of the Forest (Air) [Scholar; Mental]"
					],
			disadvantages:[	
					],
			weapon:["Majestic Antlers"],
			armor:["Magical Hide"],
			abilities:[
						"Mystical Creature: A ki-rin is an Otherworldly being of silhouette 3 that can fly. It can move vertically and ignores the negative effects of terrain. Additionally, once per scene, it may perform an Earth or Water invocation technique, and counts as succeeding with three bonus successes and <span class='l5r'>O</span> <span class='l5r'>O</span>.",
						"Sacred Envoy: The ki-rin can speak any language, and it knows many secrets of the world. The righteous can sense its hallowed nature; to perform an Attack action against it, a character must forfeit honor equal to their honor rank (and glory equal to their glory rank, if they are seen doing it).",
						"Wrath for the Wicked: Once per scene as a Attack action, the ki-rin may breathe holy fire from its mouth. Each Tainted being at range 0-4 must resist with a TN 4 Fitness check (Air 3, Earth 5) or suffer 8 supernatural damage with the Sacred quality, plus additional damage equal to its shortfall, and suffer the Burning condition."
											],
			techniques:[],
		},{
			title:"Manifest Air Kami",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:5,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:6,
				Fire:1,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:11,
			composure:6,
			focus:2,
			vigilance:4,
			max:5,
			skills:{
				artisanskill:3,
				martialskill:3,
				scholarskill:0,
				socialskill:3,
				tradeskill:2,},
			demeanor:["Flighty"],
			advantages:[
					"Ethereal Form (Air) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Easily Distrcted (Fire) [Scholar, Social; Mental]"
					],
			weapon:["Talons of Air"],
			armor:["Misty Mantle"],
			abilities:[
						"Flight: A manifest air kami can move vertically and ignores the negative effects of terrain.",
						"Living Air Spirit: A manifest air kami is an Otherworldly being of silhouette 2, 3, or 4, and may change its size as an action. Additionally, once per scene as an action of the appropriate types, a manifest air kami may perform any one Air invocation other than Rise, Air. It counts as succeeding with 3 bonus successes and 2 <span class='l5r'>O</span>.",
						"Swoop: When performing an Attack action check, a manifest air kami may spend <span class='l5r'>O</span> as follows: <span class='l5r'>O</span>+: Move 1 range band away from the target per <span class='l5r'>O</span> spent this way. If the target is of silhouette 5 or smaller, the air kami may carry it to its destination instead."
											],
			techniques:[],
		},{
			title:"Manifest Earth Kami",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:8,
			conflictintrigue:2,
			rank:1,
			ring:{
				type: "set",
				Earth:6,
				Air:1,
				Fire:2,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:15,
			composure:8,
			focus:3,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:2,
				martialskill:3,
				scholarskill:3,
				socialskill:0,
				tradeskill:3,},
			demeanor:["Obstinate"],
			advantages:[
					"Massive Stature (Earth) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Honest to a Fault (Air) [Social, Trade; Mental]"
					],
			weapon:["Stone Fists"],
			armor:["Rocky Hide"],
			abilities:[
						"Burrow: As a Movement action, a manifest earth kami may withdraw into the ground. It cannot be targeted by actions or effects, or perform actions other than Eruption.",
						"Eruption: As an Attack and Movement action while burrowed, a manifest earth kami may burst from the ground at a chosen point at range 0-3. Each character at range 0-2 of that point must resist with a TN 4 Fitness check (Air 2, Water 5) or suffer 6 physical damage and the Prone condition.",
						"Living Earth Spirit: A manifest earth kami is an Otherworldly being of silhouette 3. Additionally, once per scene as an action of the appropriate types, a manifest earth kami may perform any one Earth invocation other than Rise, Earth. It counts as succeeding with 3 bonus successes and 2 <span class='l5r'>O</span>."
											],
			techniques:[],
		},{
			title:"Manifest Fire Kami",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:9,
			conflictintrigue:2,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:1,
				Fire:6,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:12,
			composure:3,
			focus:4,
			vigilance:1,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:3,
				scholarskill:3,
				socialskill:2,
				tradeskill:3,},
			demeanor:["Intense"],
			advantages:[
					"Primal Terror (Air) [Martial, Social; Interpersonal"
					],
			disadvantages:[	
					"Endless Hunger (Water) [Artisan, Scholar; Mental]"
					],
			weapon:["Blazing Touch"],
			armor:["Corona of Flames"],
			abilities:[
						"Living Fire Spirit: A manifest kami is an Otherworldly being. Additionally, once per scene as an action of the appropriate types, a manifest fire kami may perform any one Fire invocation other than Rise, Fire. It counts as succeeding with 3 bonus successes and 2 <span class='l5r'>O</span>.",
						"Mantle of Smoke and Ash: Other characters treat the area at range 0-1 of the manifest fire kami as Dangerous and Obscuring terrain (Core p267).",
						"Searing Caress: When performing an Attack action check, a manifest fire kami may spend <span class='l5r'>O</span> as follows: <span class='l5r'>O</span>+: The target and up to one other character per <span class='l5r'>O</span> spent this way at range 0-1 of the target suffer the Burning condition (Core p272)"
											],
			techniques:[],
		},{
			title:"Manifest Water Kami",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:4,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:2,
				Fire:1,
				Water:6,
				Void:2,},
			honor:0,
			glory:0,
			status:0,
			endurance:14,
			composure:8,
			focus:8,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:3,
				martialskill:2,
				scholarskill:3,
				socialskill:3,
				tradeskill:0,},
			demeanor:["Adaptable"],
			advantages:[
					"Liquid Body (Water) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Without Convictions (Earth) [Artisan, Social; Mental]"
					],
			weapon:["Smashing Torrent"],
			armor:["Enshrouding Fog"],
			abilities:[
						"Living Water Spirit: A manifest kami is an Otherworldly being. Additionally, once per scene as an action of the appropriate types, a manifest water kami may perform any one Water invocation other than Rise, Water. It counts as succeeding with 3 bonus successes and 2 <span class='l5r'>O</span>",						"Split: Once per round, after a manifest water kami suffers a critical strike, it may split in two. The two new manifest water kami each have endurance equal to half that of the original, and any fatigue it had suffered is divided as evenly as possible. Then, both may remove any conditions the original was suffering. All of them act during the original water kami's turn, in the order of the GM's choosing."
											],
			techniques:[],
		},
		{
			title:"Loyal Bushi",
			type:"Pregen",
			conflictcombat:4,
			conflictintrigue:2,
			ring:{
				type: "set",
				Earth:3,
				Air:2,
				Fire:3,
				Water:3,
				Void:2,},
			honor:55,
			glory:50,
			status:39,
			endurance:12,
			composure:9,
			focus:5,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:1,
				martialskill:3,
				scholarskill:2,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Assertive"],
			advantages:["Tested in War (Earth) [Martial: Mental, Physical]", "Sworn to Bushido (Void) ]Social: Mental]",],
			disadvantages:["Hot-Tempered (Water) [Social: Mental]","Old War Wound (Air)[Martial; Physical]"],
			weapon:["Katana","Yumi","Naginata","Yari","Tetsubo","Ono"],
			armor:["Ashigaru Armor","Lacquered Armor","Common Clothes"],
			abilities:["Sworn Protector: Once per scene, when an Attack action check targeting another character at range 0-1 succeeds, a bushi may intervene, becoming the target of the action instead.",],
			techniques:["Crescent Moon Style"],
		},{
			title:"Humble Peasant",
			conflictcombat:1,
			conflictintrigue:1,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:2,
				Air:1,
				Fire:2,
				Water:2,
				Void:1,},
			honor:20,
			glory:25,
			status:15,
			endurance:4,
			composure:4,
			focus:3,
			vigilance:2,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:1,
				tradeskill:2,},			
			demeanor:["Shrewd"],
			advantages:["Salt of the Earth (Earth) [Trade: Interpersonal]",],
			disadvantages:["Deferential (Water) [Social: Interpersonal, Mental]",],
			weapon:["Knife",],
			armor:["Rags","Common Clothes"],
			abilities:["Overlooked: When a peasant makes a check targeting a character with a higher status rank, they treat that character's vigilance as 1 lower.",],
			techniques:[],
		},{
			title:"Seasoned Courtier",
			conflictcombat:1,
			conflictintrigue:5,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:2,
				Air:4,
				Fire:2,
				Water:3,
				Void:2,},
			honor:60,
			glory:50,
			status:39,
			endurance:6,
			composure:12,
			focus:6,
			vigilance:4,
			equiptype:"equipped",
			skills:{
				artisanskill:3,
				martialskill:0,
				scholarskill:2,
				socialskill:3,
				tradeskill:0,},			
			demeanor:["Shrewd"],
			advantages:["Inexhaustible Politeness (Air) [Social; Interpersonal]", 
						"Wealth and Resources (Water) [Trade; Material]",],
			disadvantages:["Sheltered from War (Fire) [Martial; Mental]",],
			weapon:["Wakizashi",],
			armor:["Ceremonial Robes","Concealed Armor"],
			abilities:["Whispering Winds: Once per session as an action, the courtier may make a Courtesy (Air) check targeting one character in the scene. The TN is equal to 6 minus the target's glory rank (to a minimum of 1). If they succeed, the courtier learns a rumor about the target. <span class='l5r'>O</span> <span class='l5r'>O</span>: The courtier learns one of the target's advantages or disadvantages of the target's choice.",],
			techniques:["Fanning the Flames"],
		},{
			title:"Scholarly Shugenja",
			conflictcombat:4,
			conflictintrigue:3,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:3,
				Air:3,
				Fire:3,
				Water:3,
				Void:3,},
			honor:60,
			glory:45,
			status:39,
			endurance:10,
			composure:12,
			focus:6,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:3,
				martialskill:0,
				scholarskill:2,
				socialskill:3,
				tradeskill:0,},		
			demeanor:["Ambitious"],
			advantages:["Mystical Knowledge (Void) [Scholar; Mental]", "Holy Personage (Void) [Social; Interpersonal]",],
			disadvantages:["Scholar's Physique (Earth) [Martial; Physical]",],
			weapon:["Wakizashi","Yumi",],
			armor:["Sanctified Robes","Ceremonial Robes","Common Clothes"],
			abilities:["Disciple of Secret Lore: (Choose 0-5 additional invocations (see page 189) and 0-3 additional rituals (see page 212) that this shugenja can perform. Add 1 to this character's combat rank for each invocation with a prerequisite of rank 3+ chosen this way.",],
			techniques:["Path to Inner Peace", "Fires from Within"],
		},{
			title:"Trained Ashigaru",
			conflictcombat:2,
			conflictintrigue:1,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:2,
				Water:2,
				Void:1,},
			honor:25,
			glory:29,
			status:19,
			endurance:6,
			composure:12,
			focus:6,
			vigilance:2,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:1,},			
			demeanor:["Gruff",],
			advantages:["Strength in Numbers (Earth) [Martial; Physical]",],
			disadvantages:["Jaded by Battle (Fire) [Social; Mental]",],
			weapon:["Yari","Yumi","Naginata"],
			armor:["Ashigaru Armor","Traveling Clothes"],
			abilities:["Rank Tactics: When an ashigaru provides assistance (Core p26) to the Martial skill check of another character at range 0-2, that character adds one kept <span class='l5r'>d</span> set to a <span class='l5r'>S</span> result instead of rolling an additional die.",],
			techniques:[],
		},{
			title:"Venerable Provincial Daimyo",
			conflictcombat:7,
			conflictintrigue:6,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:4,
				Air:3,
				Fire:4,
				Water:4,
				Void:4,},
			honor:55,
			glory:70,
			status:65,
			endurance:14,
			composure:16,
			focus:7,
			vigilance:4,
			equiptype:"equipped",
			skills:{
				artisanskill:2,
				martialskill:4,
				scholarskill:3,
				socialskill:3,
				tradeskill:1,},
			demeanor:["Assertive"],
			advantages:["Wisdom of Experience (Void) [Scholar; Mental]", "Bolstering Presence (Earth) [Social; Interpersonal]",],
			disadvantages:["Long at Court (Water) [Martial; Mental, Physical]",],
			weapon:["Wakizashi","Katana","Naginata","Nodachi","Tessen"],
			armor:["Plated Armor","Ceremonial Robes",],
			abilities:["Lord's Command: Once per scene, as a Support action, a daimyo may advise a character who can hear them on how to complete a task they wish the character to perform. The character may use the daimyo's ring or skill in place of their own for the next check they make to complete this task before the end of the game session.",],
			techniques:[],
},{
			title:"Desperate Bandit",
			type:"Fighters, Outlaws, Rokugani",
			demeanor:["Ambitious",],
			conflictcombat:1,
			conflictintrigue:1,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:2,
				Water:2,
				Void:1,},
			honor:15,
			glory:20,
			status:1,
			endurance:5,
			composure:6,
			focus:4,
			vigilance:2,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			advantages:[
				"Nothing to Lose: (Fire) [Martial, Social; Mental]",
			],
			disadvantages:[
				"Fool's Avarice: (Earth) [Social; Mental]",
				"Quarrelsome: (Void) [Social; Interpersonal]",
			],
			weapon:[
				"Yari", "Sling","Masakari","Bo","Hammer","Kama",
			],
			armor:["Traveling Clothes","Common Clothes"],
			abilities:[
				"Ambush Tactics: When performing an  Attack action against a target with the Dazed or Disoriented condition, increase any damage dealt by 2.",
			],
			techniques:[],
},{
			title:"Experienced Bandit",
			conflictcombat:3,
			conflictintrigue:2,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:3,
				Air:2,
				Fire:3,
				Water:3,
				Void:1,},
			honor:10,
			glory:15,
			status:3,
			endurance:9,
			composure:8,
			focus:6,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:2,
				scholarskill:0,
				socialskill:1,
				tradeskill:1,},			
			demeanor:["Shrewd"],
			advantages:["Age and Cunning (Water) [Interpersonal, Physical]",],
			disadvantages:["Fool's Avarice (Earth) [Social; Mental]",],
			weapon:["Rusty Katana","Kusari-gama","Ono",],
			armor:["Ashigaru Armor","Traveling Clothes"],
			abilities:["Dirty Tricks : When performing an Attack action check, an experienced bandit may spend <span class='l5r'>O</span> in the following way: <span class='l5r'>O</span> : One character at range 0-2 suffers the Disoriented condition. Then you may move 1 range band, ","...Get them, you fools!: As an action, an experienced bandit may have up to two Desperate Bandits who have not yet acted this round immediately move 1 range band and perform a Strike action with skilled assistance (Core p26) .",],
			techniques:[],
		},{
			title:"Skilful Ronin",
			conflictcombat:4,
			conflictintrigue:2,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:3,
				Air:3,
				Fire:2,
				Water:2,
				Void:2,},			
			honor:30,
			glory:40,
			status:20,
			endurance:12,
			composure:11,
			focus:5,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:3,
				scholarskill:1,
				socialskill:0,
				tradeskill:2,},
			demeanor:["Detached"],
			advantages:["Killer Instinct (Fire) [Martial; Mental]", "Worldly Wanderer (Void) [Scholar, Trade; Mental]",],
			disadvantages:["Unnecessarily Rude (Water) [Social; Interpersonal]",],
			weapon:["Katana","Yumi","Naginata","Wakizashi","Chokuto"],
			armor:["Traveling Clothes","Ashigaru Armor"],
			abilities:["School of the Wolf: Once per round, when an Attack action check targeting the ronin succeeds, the ronin may suffer 3 fatigue to change the target to another character (other than the attacker) at range 0-1 of the ronin.",],
			techniques:["Striking as Fire"],
	},{
			title:"Deadly Bloodspeaker",
			conflictcombat:9,
			conflictintrigue:9,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:6,
				Air:4,
				Fire:4,
				Water:4,
				Void:3,},
			honor:5,
			glory:7,
			status:0,
			endurance:18,
			composure:16,
			focus:6,
			vigilance:4,
			equiptype:"equipped",
			skills:{
				artisanskill:2,
				martialskill:3,
				scholarskill:5,
				socialskill:4,
				tradeskill:1,},
			demeanor:["Ambitious"],
			advantages:["Undying (Earth) [Martial; Physical, Spiritual]", "Whispers of Fu Leng (Void) [Scholar; Mental]",],
			disadvantages:["Heartless (Void) [Social; Physical, Spiritual]",],
			weapon:["Obsidian-Edged Katana","Ritual Knife"],
			armor: ["Sorcerous Raiment","Ceremonial Robes"],
			abilities:["Bleed the Soul: After the Bloodspeaker inflicts a Critical Strike on a living target, the target suffers the Dazed condition and the Bloodspeaker removes 3 fatigue.", "Hidden Heart: The Bloodspeaker cannot truly be vanquished until its heart (usually buried in some deadly tomb or sanctum of evil) has been destroyed. It ignores the Unconscious condition. If slain, it can possess a fresh corpse after its allies have prepared the corpse through a dark rite that takes four days to complete.", "Master of Vile Lore: The Bloodspeaker is a Tainted being who can perform all maho (Core p224).",],
			techniques:[],
		},{
			title:"Wicked Maho-Tsukai",
			conflictcombat:4,
			conflictintrigue:3,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:4,
				Air:3,
				Fire:3,
				Water:3,
				Void:2,},
			honor:1,
			glory:15,
			status:0,
			endurance:14,
			composure:8,
			focus:7,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:3,
				socialskill:2,
				tradeskill:1,},			
			demeanor:["Ambitious"],
			advantages:["Excellent Liar (Air) [Social; Interpersonal]", "Whispers of Fu Leng (Void) [Scholar; Mental]",],
			disadvantages:["Rotting from Within (Earth) [Martial; Physical, Spiritual]",],
			weapon:["Ritual Knife",],
			armor: ["Sorcerous Raiment","Ceremonial Robes"],
			abilities:["Mark of Desecration: As a Support action, the maho-tsukai may make a TN 2 Theology (Earth) check targeting up to three corpses at range 0-3. If the maho-tsukai succeeds, each target rises as a Zombie Peasant (Core p321), or a Bushi Skeleton if it was a warrior in life (Core p318). Then, an area encompassing 1 range band around each target's position gains the Defiled terrain quality (Core p267)", "Seeker of Vile Lore: The maho-tsukai is a Tainted being. Optionally, choose 0-2 additional maho (Core p224) that the maho-tsukai can perform. Add 1 to this character's combat rank for each maho chosen this way.",],
			techniques:[],
		},

		]
var templates = [
{
title:"Artist",
	conflictcombat:0,
	conflictintrigue:2,
	ring:{
		type: "set",
		Air: 0,
		Earth: 1,
		Water: 0,
		Void: 1,
		Fire: 2,
	},
	endurance:-2,
	composure:2,
	focus:0,
	vigilance:1,
	artisanskill:2,
	martialskill:0,
	socialskill:1,
	scholarskill:0,
	tradeskill:0,
	advantages:["Eye for Detail (Air) [Artisan; Mental]",
			"Renown (Fire) [Artisan; Interpersonal]",
			"Steady Hand (Earth) [Artisan; Physical]",
			"Creative Soul (Fire) [Artisan; Mental]",
			"Impeccable Brushwork (Air) [Artisan; Mental]",
			],
	disadvantages:["Prima Donna (Water) [Social; Interpersonal]", 
			"Naivete (Fire) [Social; Interpersonal]", 
			"Sheltered from Battle (Fire) [Social; Interpersonal]",
			"World-Weariness (Earth) [Social; Interpersonal]",
			"Angsty Artist (Air) [Social, Artisan; Mental]",
			],
	extratechs:3,
	techtypes:["Shuji"],
	demeanor:["Detached", "Gruff", "Shrewd"],
},{
title:"Investigator",
	conflictcombat:1,
	conflictintrigue:1,
	ring:{
		type: "set",
		Air: 1,
		Earth: 0,
		Fire: 1,
		Water: 1,
		Void: 1,
	},
	endurance:1,
	composure:1,
	focus:0,
	vigilance:1,
	artisanskill:0,
	martialskill:1,
	socialskill:1,
	scholarskill:1,
	tradeskill:0,
	advantages:["Analytical Mind (Fire) [Scholar; Mental]", 
		"Self-Awareness (Void) [Martial; Mental]", 
		"Sharp Eyes (Water) [Scholar; Physical]",
		"A Nose for the Truth (Water) [Scholar, Social; Mental]",
		],
	disadvantages:["Sceptical Attitude (Fire) [Social; Mental]", 
		"Haughty Tone (Air) [Social; Interpersonal]", 
		"Functional Alcoholic (Water) [Social,Scholar,Martial; Physical]",
		"Seen It All Before (Earth) [Scholar, Social; Mental]",

		],
	extratechs:3,
	techtypes:["Kata", "Shuji"],
	demeanor:["Gruff", "Shrewd"],
	},{
title:"Socialite",
	conflictcombat:0,
	conflictintrigue:2,
	ring:{
		type: "set",
		Air: 1,
		Earth: 0,
		Fire: 1,
		Void: 0,
		Water: 2,
	},
	endurance:-1,
	composure:+1,
	focus:0,
	vigilance:1,
	artisanskill:0,
	martialskill:0,
	socialskill:2,
	scholarskill:0,
	tradeskill:1,
	advantages:["Well-Spoken (Air) [Social; Interpersonal]", 
		"Wealth and Resources (Water) [Trade; Material]",
		"Seems Trustworthy (Water) [Social; Interpersonal]",
		"Inexhaustible Politeness (Air) [Social; Interpersonal]",
		"Social Connections (Air) [Social; Interpersonal]",
		],
	disadvantages:["Doomed Love (Fire) [Social; Interpersonal]", 
		"Lack of Empathy (Air) [Social; Mental]", 
		"Poor Memory (Earth) [Scholar; Mental]",
		"Busybody (Air) [Social; Mental]",
		"Avaricious (Fire) [Social; Interpersonal]",
		],
	extratechs:3,
	techtypes:["Shuji", "Ritual"],
	demeanor:["Assertive", "Shrewd"],
	},{
title:"Spiritualist",
	conflictcombat:1,
	conflictintrigue:1,
	ring:{
		type: "random",
	},
	endurance:-1,
	composure:1,
	focus:0,
	vigilance:0,
	artisanskill:1,
	martialskill:0,
	socialskill:0,
	scholarskill:2,
	tradeskill:0,
	advantages:["Keen Empathy (Air) [Social; Interpersonal]", 
		"Friendly Kami or Spirit (Fire, Earth, Air, or Water) [Scholar; Spiritual]",
		"Holy Personage (Water) [Social; Interpersonal]",
		"Mystical Knowledge (Void) [Scholar; Mental]",
		],
	disadvantages:["Above Worldly Matters (Water) [Trade, Social; Interpersonal]", 
		"Repressed (Fire) [Social; Mental]",
		"Frailty (Earth) [Martial; Physical]",
		"Possessed by Curiosity (Water) [Scholar; Mental]",
		],
	extratechs:3,
	techtypes:["Invocation", "Ritual"],
	demeanor:["Detached", "Assertive"],
	},{
title:"Trickster",
	conflictcombat:1,
	conflictintrigue:1,
	ring:{
		type: "set",
		Air: 2,
		Earth: 0,
		Fire: 1,
		Water: 1,
		Void: 0,
	},
	endurance:-1,
	composure:1,
	focus:0,
	vigilance:1,
	artisanskill:0,
	martialskill:0,
	socialskill:2,
	scholarskill:1,
	tradeskill:0,
	advantages:["Excellent Liar (Air) [Social; Interpersonal]", 
		"Patience (Earth) [Scholar; Mental]", 
		"Loves Haggling (Water) [Trade; Interpersonal]",
		"Unmemorable Face (Air) [Social; Physical]",
		"Skilled Mimic (Air) [Artisan, Social; Interpersonal, Physical]",
		],
	disadvantages:["Fear of Failure (Fire) [Martial; Mental]", 
		"Narcissism (Earth) [Social; Mental]", 
		],
	extratechs:3,
	techtypes:["Ninjutsu", "Shuji"],
	demeanor:["Ambitious", "Shrewd"],
	},{
title:"Warrior",
	conflictcombat:2,
	conflictintrigue:0,
	ring:{
		type: "random",
	},
	endurance:2,
	composure:-2,
	focus:1,
	vigilance:-1,
	artisanskill:0,
	martialskill:2,
	socialskill:1,
	scholarskill:0,
	tradeskill:0,
	advantages:["Tested in War (Earth) [Martial: Mental, Physical]", 
		"Fearsome Presence (Fire) [Social; Interpersonal]", 
		"Veteran's Instincts (Water) [Martial; Mental]"],
	disadvantages:["Bad Dreams (Void) [Martial; Mental]", 
		"Quick to Anger (Fire) [Social; Interpersonal]", 
		"Shattered by War (Earth) [Social; Mental]",
		"Old War Wound (Air)[Martial; Physical]",
		],
	extratechs:3,
	techtypes:["Kata"],
	demeanor:["Assertive", "Gruff"],
	},{
title:"Ascetic",
	conflictcombat:2,
	conflictintrigue:0,
	ring:{
		type:"set",
		Void: 2,
		Air: 0,
		Earth: 1,
		Fire: 0,
		Water: 1,
	},
	endurance:1,
	composure:1,
	focus:0,
	vigilance:0,
	artisanskill:0,
	martialskill:1,
	socialskill:1,
	scholarskill:1,
	tradeskill:0,
	advantages:["Partial Enlightenment (Void) [Scholar; Spiritual]",
		"Honed Physique (Earth) [Martial; Physical]",
		"Acrobatic Fighter (Air) [Martial; Physical]"],
	disadvantages:["Poverty (Water) [Trade; Material]", 
		"Fanaticism (Fire) [Social; Mental]",
		"Cantankerous (Water) [Social; Interpersonal]",
		"Above Worldly Matters (Water) [Trade, Social; Interpersonal]"],
	extratechs:3,
	techtypes:["Ritual", "Kiho"],
	demeanor:["Detached", "Shrewd"],
},{
title:"Yojimbo",
	conflictcombat:2,
	conflictintrigue:0,
		ring:{
		type:"random",
	},
	endurance:0,
	composure:0,
	focus:2,
	vigilance:1,
	artisanskill:1,
	martialskill:2,
	socialskill:0,
	scholarskill:0,
	tradeskill:0,
	advantages:[
		"Eager to Make a Name (Fire) [Social; Mental]",
		"Duelist's Reflexes (Fire) [Martial; Physical]",
		"Yojimbo's Instincts (Void) [Martial, Social; Physical, Interpersonal]",
		"Famed Duelist (Water) [Martial, Social; Physical, Interpersonal]",
	],
	disadvantages:[
		"Softhearted Duelist (Fire) [Martial; Mental]",
		"Old Dueling Scar (Fire) [Martial; Physical]",
		"Arrogant (Fire) [Social; Interpersonal]",
		"Washed Up Duelist (Fire) [Social; Interpersonal]",
	],
	extratechs:3,
	techtypes:["Kata","Shuji"],
	demeanor:["Detached", "Assertive", "Ambitious"],
},{
title:"Tactician",
	conflictcombat:2,
	conflictintrigue:0,
		ring:{
		type:"random",
	},
	endurance:0,
	composure:0,
	focus:2,
	vigilance:1,
	artisanskill:0,
	martialskill:2,
	socialskill:0,
	scholarskill:1,
	tradeskill:0,
	advantages:[
			"Bolstering Presence (Earth) [Social; Interpersonal]",
			"Famously Cunning Strategist (Air) [Martial; Interpersonal, Mental]",
			"Beloved by the Troops (Water) [Social; Interpersonal]",
			"Never Seen A Gamble That Didn't Pay Off (Fire) [Martial,Social; Mental]"
	],
	disadvantages:[
			"Old War Scar (Fire) [Martial, Trade; Physical]",
			"Despised by the Troops (Water) [Social; Interpersonal]",
			"Conventional Thinker (Fire) [Martial, Social; Interpersonal]",
			"Inexperienced Leader (Earth) [Martial; Interpersonal]",
	],
	extratechs:3,
	techtypes:["Kata","Shuji"],
	demeanor:["Assertive", "Ambitious"],
},{
title:"Scout",
	conflictcombat:1,
	conflictintrigue:1,
		ring:{
		type:"set",
		Void: 0,
		Air: 2,
		Earth: 1,
		Fire: 0,
		Water: 1,
	},
	endurance:0,
	composure:0,
	focus:2,
	vigilance:1,
	artisanskill:0,
	martialskill:1,
	socialskill:0,
	scholarskill:0,
	tradeskill:2,
	advantages:[
			"Excellent Skulker (Air) [Martial, Trade; Physical]",
			"Expert Tracker (Air) [Trade; Mental]",
			"Unmemorable Face (Air) [Social; Physical]",
			"Light Fingers (Air) [Trade; Physical]",
			"Acrobatic Fighter (Air) [Martial; Physical]",
	],
	disadvantages:[
			"Risk-Taker (Air) [Martial; Physical]"
	],
	extratechs:3,
	techtypes:["Kata","Ninjutsu"],
	demeanor:["Detached", "Ambitious"],
},{
title:"Dark Sage",
	conflictcombat:1,
	conflictintrigue:1,
	ring:{
		type: "random",
	},
	endurance:-2,
	composure:1,
	focus:1,
	vigilance:1,
	artisanskill:0,
	martialskill:0,
	socialskill:0,
	scholarskill:2,
	tradeskill:1,
	advantages:["Forbidden Knowledge [Maho] (Fire) [Scholar; Mental]", 
		"Exact Memory (Earth) [Scholar; Mental]", 
		"Well-Read (Fire) [Scholar; Mental]",
		"Nimble Bureaucrat (Air) [Scholar, Social; Interpersonal, Mental]",
		],
	disadvantages:["Bitter Marriage (Water) [Social; Interpersonal]", 
		"Know-It-All (Air) [Social; Interpersonal]", 
		"Bad Eyesight (Water) [Scholar; Physical]",
		"Scholar's Physique (Earth) [Martial; Physical]"
		],
	extratechs:3,
	techtypes:["Shuji", "Invocation", "Maho",],
	demeanor:["Detached", "Ambitious"],
},
]

