
var demeanors =[
{demeanor:"Ambitious",tns:"Fire +2, Water -2",unmasking:"Bend Principles",desc:"This character pursues power whenever possible and is extremely resistant to giving it up. However, they jump to support appeals that line up with their own desires."},
{demeanor:"Assertive",tns:"Earth +2, Air -2",unmasking:"Rage",desc:"This person is used to being in charge, and does not like being told what they can or cannot to do. They are most pliant when they think they are getting their way."},
{demeanor:"Detached",tns:"Earth +1, Fire +1, Void -2",unmasking:"Expose an Opening",desc:"This individual is extremely meditative, spiritual, enlightened, or simply uninterested in other people."},
{demeanor:"Gruff",tns:"Water +2, Earth -2",unmasking:"Inappropriate Outburst",desc:"With a rough exterior and a no-nonsense attitude, this person has little tolerance for frivolity, niceties, or trickery."},
{demeanor:"Shrewd",tns:"Air +2, Fire -2",unmasking:"Panicked Retreat",desc:"This individual is used to maneuvering around powerful people, and tends to avoid direct conflict. They are also very wary of such efforts on the part of others."},
{demeanor:"Courageous",tns:"Air +2, Earth -2",unmasking:"Angry Dismay",desc:"This character does not hesitate to overcome their fear and act with courage, no matter the consequences."},
{demeanor:"Intimidating",tns:"Fire +2, Air -2",unmasking:"Threats or Violence",desc:""},
{demeanor:"Aggressive",tns:"Fire +2, Water -2",unmasking:"Threats or Violence",desc:""},
{demeanor:"Suspicious",tns:"Air +2, Earth -2",unmasking:"Flimsy Accusations",desc:""},
{demeanor:"Uncertain",tns:"Air +2, Earth -2",unmasking:"Paralysed by Indecision",desc:""},
{demeanor:"Playful",tns:"Earth +2, Water -2",unmasking:"Expose an Opening",desc:""},
{demeanor:"Friendly",tns:"Fire +1, Earth -2, Water -2",unmasking:"Expose an Opening",desc:""},
{demeanor:"Loyal",tns:"Air +1, Earth -2, Fire -2",unmasking:"Expose an Opening",desc:""},
{demeanor:"Proud",tns:"Fire +2, Earth -2",unmasking:"Inappropriate Outburst",desc:""},
{demeanor:"Opportunistic",tns:"Water +2, Fire -2",unmasking:"Bend Principles",desc:""},
{demeanor:"Cautious",tns:"Air +2, Earth -2",unmasking:"Panicked Retreat",desc:""},
{demeanor:"Angry",tns:"Fire +2, Air -2",unmasking:"Rage",desc:""},
{demeanor:"Flighty",tns:"Air +2, Fire -2",unmasking:"Inappropriate Outburst",desc:""},
{demeanor:"Obstinate",tns:"Water +2, Air -2",unmasking:"Angry Dismay",desc:""},
{demeanor:"Intense",tns:"Air +2, Water -2",unmasking:"Expose an Opening",desc:""},
{demeanor:"Adaptable",tns:"Fire +2, Earth -2",unmasking:"Bend Principles",desc:""},
{demeanor:"Territorial",tns:"Fire +2, Air -2",unmasking:"Threats or Violence",desc:""},
{demeanor:"Hungry",tns:"Fire +2, Air -2",unmasking:"Must... Consume...",desc:""},
{demeanor:"Curious",tns:"Fire +2, Earth -2",unmasking:"",desc:""},
]

var skilllist =[
	["Aesthetics","Composition","Design","Smithing"],
	["Command","Courtesy","Games","Performance"],
	["Culture","Government","Medicine","Sentiment","Theology"],
	["Fitness","Melee","Ranged","Unarmed","Meditation","Tactics"],
	["Animal Handling","Commerce","Labor","Seafaring","Skulduggery","Survival"]
]

var skillsets = ["Artisan","Social","Scholar","Martial","Trade"]

var archetypes =[
		{
			fullname:"Rank 1",
			title:"Rank1",
			type:"Clan Samurai",
			equiptype:"equipped",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:1,
				Fire:1,
				Water:1,
				Void:1,},
			honor:30,
			glory:20,
			status:30,
			endurance:6,
			composure:6,
			focus:4,
			vigilance:2,
			max:3,
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:[],
			advantages:[
					],
			disadvantages:[	

					],
			weapon:["Katana","Wakizashi","Yari","Yumi",],
			armor:["Traveling Clothes","Ashigaru Armor",],
			abilities:[],
			techniques:[],
		},		{
			fullname:"Rank 2",
			title:"Rank2",
			type:"Clan Samurai",
			equiptype:"equipped",
			conflictcombat:2,
			conflictintrigue:2,
			rank:2,
			ring:{
				type: "random",
				Earth:1,
				Air:1,
				Fire:1,
				Water:1,
				Void:1,},
			honor:40,
			glory:40,
			status:35,
			endurance:9,
			composure:9,
			focus:5,
			vigilance:2,
			max:4,
			skills:{
				artisanskill:1,
				martialskill:1,
				scholarskill:1,
				socialskill:1,
				tradeskill:1,},
			demeanor:[],
			advantages:[
					
					],
			disadvantages:[	

					],
			weapon:["Katana","Wakizashi","Yari","Yumi",],
			armor:["Traveling Clothes","Ashigaru Armor",],
			abilities:[],
			techniques:[],
			extra: function(){
						this.ring.Earth = 1
						this.ring.Air = 1
						this.ring.Fire = 1
						this.ring.Water = 1
						this.ring.Void = 1
						array=[1,1,0,0,0];
						array = shuffle(array);
						this.ring.Earth += array[0];
						this.ring.Air += array[1];
						this.ring.Fire += array[2];
						this.ring.Water += array[3];
						this.ring.Void += array[4];
			}
			
		},	{
			title:"Rank3",
			fullname: "Rank 3",
			type:"Clan Samurai",
			equiptype:"equipped",
			conflictcombat:3,
			conflictintrigue:3,
			rank:3,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:2,
				Water:2,
				Void:2,},
			honor:40,
			glory:40,
			status:35,
			endurance:11,
			composure:11,
			focus:6,
			vigilance:2,
			max:4,
			skills:{
				artisanskill:1,
				martialskill:1,
				scholarskill:1,
				socialskill:1,
				tradeskill:1,},
			demeanor:[],
			advantages:[
					
					],
			disadvantages:[	

					],
			weapon:["Katana","Wakizashi","Yari","Yumi",],
			armor:["Traveling Clothes","Ashigaru Armor",],
			abilities:[],
			techniques:[],
		},{
			title:"Bear",
			fullname: "Bear",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:1,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:12,
			composure:9,
			focus:4,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:["Intimidating","Territorial","Cautious","Angry"],
			advantages:[
					"Enormous Stature (Earth) [Martial; Physical]"
					],
			disadvantages:[	
					"Opportunist (Fire) [Martial; Mental]"
					],
			weapon:["Crushing Claws and Fangs",],
			armor:["Thick Hide",],
			qualities: "A bear is a silhouette 3 creature with terrifying strength.",
			abilities:["Crushing Swipe: When a bear inflicts a critical strike, the TN of the check to resist is 4, and if the target fails, they suffer the Dazed condition in addition to the other effects."],
			techniques:[],
		},{
			title:"Boar",
			fullname:"Boar",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:5,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:2,
				Fire:4,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:8,
			composure:4,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:["Intimidating","Territorial","Cautious","Angry","Aggressive"],
			advantages:[
					"Keen Sense of Smell (Fire) [Trade; Physical]"
					],
			disadvantages:[	
					"Hot Tempered (Water) [Martial; Mental]"
					],
			weapon:["Tusks",],
			armor:["Thick Hide",],
			abilities:["Sustaining Fury: After a boar suffers a critical strike, it becomes Enraged. While Enraged, a boar cannot suffer the Unconscious condition and may perform Attack actions even while Incapacitated."],
			techniques:[],
		},{
			title:"Cat",
			fullname:"Cat",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:4,
				Fire:1,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:3,
			composure:9,
			focus:5,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Playful","Friendly","Loyal","Proud"],
			advantages:[
					"Winsome Manner (Water) [Social; Interpersonal]",
					"Silent Stalker (Air) [Martial; Physical]",
					"Deft Climber (Air) [Martial; Physical]",
					"Good Communicator (Water) [Social; Interpersonal]",
					],
			disadvantages:[	
					"Hubris (Air) [Social; Mental]",
					"Trusting Soul (Air) [Social; Interpersonal]",
					],
			weapon:["Little Claws",],
			armor:["Soft Fur",],
			qualities: "A cat is an agile silhouette 0 creature.",
			abilities:["Pouncing Predator: When performing an Attack action check against an unaware or Prone target, it may spend <span class='l5r'>O</span> as follows:<br> <span class='l5r'>O</span>: The target suffers the Disoriented condition."],
			techniques:[],
		},{
			title:"PandaRed",
			fullname:"Panda, Red",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:2,
				Fire:1,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:4,
			composure:7,
			focus:4,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:1,
				tradeskill:1,},
			demeanor:["Playful","Friendly","Loyal","Flighty"],
			advantages:[
					"Clever Little Hands (Fire) [Trade; Physical]",
					"Good Communicator (Water) [Social; Interpersonal]",
					"Winsome Manner (Water) [Social; Interpersonal]",
					"Deft Climber (Air) [Martial; Physical]",
					],
			disadvantages:[	
					"Light Fingers (Water) [Social; Mental]",
					"Trusting Soul (Air) [Social; Interpersonal]",
					"Easily Persuaded By Treats (Water) [Social; Interpersonal]",
					],
			weapon:["Little Bite",],
			armor:["Soft Fur",],
			qualities: "The Red Panda is a devastatingly cute silhouette 0 creature.",
			abilities:["When making a Scheme action to captivate a human, it may spend <span class='l5r'>O</span> as follows:<br> <span class='l5r'>O</span>: The target suffers the Dazed condition."],
			techniques:[],
		},{
			title:"DogLarge",
			fullname:"Dog, Large",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:1,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:6,
			composure:5,
			focus:3,
			vigilance:4,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Loyal","Assertive","Playful","Friendly",],
			advantages:[
					"Keen Tracker (Water) [Trade; Physical]",
					"Such a Good Boy! (Water) [Social; Interpersonal]",
					],
			disadvantages:[	
					"Dependent on Humans (Fire) [Trade; Mental]",
					"Trusting Soul (Air) [Social; Interpersonal]",
					],
			weapon:["Vicious Bite",],
			armor:["Hide",],
			abilities:["Working Companion: Choose one Martial or Trade skill. When the dog provides assistance on a check with this skill, it counts as providing skilled assistance (see page 26)."],
			techniques:[],
		},{
			title:"DogSmall",
			fullname:"Dog, Small",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:1,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:4,
			composure:2,
			focus:3,
			vigilance:5,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Friendly","Playful","Loyal",],
			advantages:[
					"Keen Tracker (Water) [Trade; Physical]",
					"Good Communicator (Water) [Social; Interpersonal]",
					],
			disadvantages:[	
					"Yappy (Air) [Mental]",
					"Small Dog Complex (Water) [Mental]",
					"Dependent on Humans (Fire) [Trade; Mental]",
					"Trusting Soul (Air) [Social; Interpersonal]",
					],
			weapon:["Little Bite",],
			armor:["Soft Fur",],
			abilities:["Working Companion: Choose one Martial or Trade skill. When the dog provides assistance on a check with this skill, it counts as providing skilled assistance (see page 26)."],
			techniques:[],
		},{
			title:"Hawk",
			fullname:"Hawk",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:4,
				Fire:2,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:2,
			composure:5,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:["Proud","Aggressive","Obstinate","Territorial","Cautious","Loyal"],
			advantages:[
					"Sharp Eyesight (Water) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Hollow Bones (Earth) [Martial; Physical]"
					],
			weapon:["Beak and Talons",],
			armor:["None",],
			qualities:"A hawk is a silhouette 0 creature that can fly.",
			abilities:["Nimble Flier: It can move vertically and ignores the negative effects of terrain",
						"Swoop: When performing an Attack action check, a hawk may spend <span class='l5r'>O</span> as follows: <br><span class='l5r'>O</span>+: Move 1 range band away from the target per <span class='l5r'>O</span> spent this way. If the target is of silhouette 0 or smaller, the hawk may carry it to its destination instead."],
			techniques:[],
		},{
			title:"HorseRokuganiPony",
			fullname:"Horse, Rokugani Pony",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:2,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:8,
			composure:4,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Loyal","Flighty","Obstinate","Shrewd"],
			advantages:[
					"Tireless Runner (Earth) [Martial; Physical]"
					],
			disadvantages:[	
					"Skittish (Fire) [Martial; Mental]"
					],
			weapon:["Hooves",],
			armor:["Hide",],
			qualities:"A Rokugani pony is a silhouette 3 creature.  It can be ridden by a human-sized (silhouette 2 or lower) rider.",
			abilities:["Trained Mount: While it is being ridden during a conflict, a mount does not take a turn of its own, and provides the following benefits to its rider:<br>- When the rider succeeds on a Movement action check, add bonus successes equal to the mount's Water Ring. <br>- The rider may use their Survival skill in place of their Fitness skill for any Fitness check they make.<br>- During narrative and downtime scenes, a mounted character doubles their overland travel speed."],
			techniques:[],
		},{
			fullname:"Horse, Shinjo Riding Horse",
			title:"HorseShinjoRidingHorse",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:3,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:2,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:12,
			composure:8,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:2,
				tradeskill:0,},
			demeanor:["Loyal","Flighty","Obstinate","Shrewd"],
			advantages:[
					"Tireless Runner (Earth) [Martial; Physical]"
					],
			disadvantages:[	
					"Proud and Haughty (Water) [Social; Interpersonal]",
					"Traumatised by War (Fire) [Martial; Mental]",
					"Quick to Anger (Fire) [Social; Interpersonal]",
					"Dependent on Rider (Earth) [Social, Martial; Mental]"
					],
			weapon:["Hooves",],
			armor:["Hide",],
			qualities:"A Shinjo Riding Horse is a silhouette 3 creature. It can be ridden by a human-sized (silhouette 2 or lower) rider.",
			abilities:["Loyal Steed: While it is being ridden during a conflict, a mount does not take a turn of its own, and provides the following benefits to its rider:<br>- When the rider succeeds on a Movement action check, add bonus successes equal to the mount's Water Ring. <br>- The rider may use their Survival skill in place of their Fitness skill for any Fitness check they make.<br>- During narrative and downtime scenes, a mounted character doubles their overland travel speed."],
			techniques:[],
		},{
			fullname:"Horse, Utaku Steed",
			title:"HorseUtakuSteed",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:4,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:14,
			composure:10,
			focus:6,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:3,
				scholarskill:0,
				socialskill:3,
				tradeskill:0,},
			demeanor:["Loyal","Proud","Playful","Intimidating","Obstinate","Assertive","Friendly"],
			advantages:[
					"Tireless Runner (Earth) [Martial; Physical]",
					"Good Communicator (Water) [Social; Interpersonal]",
					"Eerie Intelligence (Water) [Social; Interpersonal]",
					],
			disadvantages:[	
					"Proud and Haughty (Water) [Social; Interpersonal]",
					"Traumatised by War (Fire) [Martial; Mental]",
					"Quick to Anger (Fire) [Social; Interpersonal]",
					"Dependent on Rider (Earth) [Social, Martial; Mental]"
					],
			weapon:["Mighty Hooves",],
			armor:["Hide and Barding",],
			qualities:"An Utaku steed is a silhouette 3 creature. It can be ridden by a human-sized (silhouette 2 or lower) rider, but generally does not tolerate any rider other than a worthy Utaku Battle Maiden.",
			abilities:["Paragon of Horses: A Utaku steed grants its rider skilled assistance (Core p26) on Martial checks they make while mounted","Legendary Steed: While it is being ridden during a conflict, a mount does not take a turn of its own, and provides the following benefits to its rider:<br>- When the rider succeeds on a Movement action check, add bonus successes equal to the mount's Water Ring. <br>- The rider may use their Survival skill in place of their Fitness skill for any Fitness check they make.<br>- During narrative and downtime scenes, a mounted character doubles their overland travel speed."],
			techniques:[],
		},{
			fullname:"Hunting Cat",
			title:"HuntingCat",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:6,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:4,
				Fire:1,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:6,
			composure:12,
			focus:6,
			vigilance:4,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Opportunistic","Loyal","Proud","Playful","Intimidating"],
			advantages:[
					"Silent Stalker (Air) [Martial; Physical]"
					],
			disadvantages:[	
					"Hubris (Air) [Social; Mental]"
					],
			weapon:["Rending Claws and Fangs",],
			armor:["Thick Fur",],
			qualities:"A hunting cat is a silhouette 3 creature.",
			abilities:["Pouncing Predator: When performing an Attack action check against an unaware or Prone target, the hunting cat may spend <span class='l5r'>O</span> as follows: <br><span class='l5r'>O</span>: The target suffers the Disoriented condition.","Savage Mauling: Disoriented targets cannot defend against damage dealt by a hunting cat."],
			techniques:[],
		},{
			fullname:"Wolf",
			title:"Wolf",
			type:"Animals",
			equiptype:"natural",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:4,
			composure:4,
			focus:6,
			vigilance:4,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Cautious","Loyal","Intimidating","Territorial","Opportunistic"],
			advantages:[
					"Pack Tactics (Water) [Martial, Social; Interpersonal]"
					],
			disadvantages:[	
					"Cautious Hunter (Fire) [Martial; Mental]"
					],
			weapon:["Vicious Fangs",],
			armor:["Hide",],
			abilities:["Circle the Kill: When performing a Martial Arts [Unarmed] check, a wolf may spend <span class='l5r'>O</span> in the following ways. <br>Water <span class='l5r'>O</span>: The target suffers the Bleeding condition. <br>Fire <span class='l5r'>O</span> : The target treats all terrain as Dangerous (see page 267) until the end of their next turn."],
			techniques:[],
		},{
			fullname:"Bushi Skeleton",
			title:"BushiSkeleton",
			type:"Creatures",
			equiptype:"equipped",
			conflictcombat:3,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:2,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:7,
			composure:99,
			focus:3,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:1,},
			demeanor:["Angry","Hungry"],
			advantages:[
					"Unholy Vigor (Earth) [Martial; Physical, Spiritual]"
					],
			disadvantages:[	
					"Visage of Death (Water) [Social; Interpersonal]"
					],
			weapon:["Rusty Katana","Decrepit Yumi",],
			armor:["Ancient Armor",],
			qualities:"A skeletal bushi is an Otherworldly, Tainted being.",
			abilities:["Clattering Bones: The first time it would be defeated each scene, it receives a Scar disadvantage of the GM's choice instead as one of its limbs snaps or flies off.","Does not Bleed: A skeletal bushi ignores conditions and critical strikes from non-Sacred sources."],
			techniques:[],
		},{
			fullname:"Bog Hag",
			title:"BogHag",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:8,
			conflictintrigue:5,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:4,
				Fire:3,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:14,
			composure:8,
			focus:6,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:3,
				martialskill:2,
				scholarskill:6,
				socialskill:2,
				tradeskill:1,},
			demeanor:["Shrewd","Opportunistic","Territorial","Playful","Intimidating","Adaptable","Cautious"],
			advantages:[
					"Shapeshifter's Guile (Air) [Social; Interpersonal]",
					"Sorcerous Lore (Void) [Scholar; Mental]"
					],
			disadvantages:[	
					"Dreadful Hunger (Earth) [Social; Interpersonal, Mental]"
					],
			weapon:["Twisted Talons","Horrific Maw"],
			armor:["Fresh Skin",],
			abilities:[
						"Accursed Regneneration: At the end of each round, if the bog hag has not suffered damage from a Sacred source this round, the bog hag removes the Lightly Injured condition or reduces the Severely Injured condition to Lightly Injured.",
						"Seeker of Vile Lore: The bog hag is an Otherworldly, Tainted being. Optionally, choose 0-3 maho techniques (see page 224) that the bog hag can perform. Add 1 to this character's combat rank for each maho chosen this way",
						"Skins of the Slaughtered: As an action, a bog hag may assume the illusory form of anyone it has killed. A character may make a TN 3 Sentiment check (Earth 4, Fire 1), or another appropriate check to see through this illusion. At the GM's discretion, a character may spend <span class='l5r'>O</span> <span class='l5r'>O</span> from any check to interact with the bog hag to see one of the following: a misplaced fold in the skin, luminescence in one eye, an impossible movement of the jaw, oddly sharp teeth, the smell of viscera, a conversational fixation on fresh and bloody meat. "
					],
			techniques:[],
		},{
			title:"Goblin",
			fullname:"Goblin",
			type:"Creatures",
			equiptype:"equipped",
			conflictcombat:1,
			conflictintrigue:1,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:2,
				Water:1,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:3,
			composure:4,
			focus:3,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:1,},
			demeanor:["Shrewd","Uncertain","Flighty","Opportunistic","Cautious"],
			advantages:[
					"Expert Skulker (Air) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Cowardice (Earth) [Martial, Social; Mental]"
					],
			weapon:["Small Yari","Small Yumi"],
			armor:["Ashigaru Armor"],
			qualities:"A Shadowlands goblin is a Tainted being of silhouette 1.",
			abilities:[			
					"Unsightly Rabble: When making an Attack action check with assistance, a goblin may spend <span class='l5r'>O</span> as follows: <span class='l5r'>O</span>+: One character other than the target at range 0-2 suffers 4 physical damage. This <span class='l5r'>O</span> can be activated a number of times per round equal to the number of goblins assisting with the check.)"
											],
			techniques:[],
		},{
			fullname:"Sinister Oni",
			title:"SinisterOni",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:12,
			conflictintrigue:5,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:3,
				Fire:6,
				Water:3,
				Void:3,},
			honor:0,
			glory:4,
			status:0,
			endurance:24,
			composure:12,
			focus:8,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:4,
				scholarskill:3,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Ambitious","Intimidating","Aggressive","Playful","Territorial"],
			advantages:[
					"Massive Stature (Earth) [Martial; Physical]",
					"Unholy Might (Fire) [Martial; Physical, Spiritual]"
					],
			disadvantages:[	
					"Horrifying Visage (Water) [Social; Interpersonal]"
					],
			weapon:["Crushing Claws"],
			armor:["Demonic Hide"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:[
						"Dread Bellow: Once per scene as a Scheme action, the oni may roar, feeding on the primal terror it instills. Each other character at range 0-4 must resist with a TN 4 Meditation check (Earth 2, Air 5) or suffer the Afflicted condition and stumble back 1 range band from the oni. For each character who fails, the oni removes 2 fatigue.",
						"Horror of Jigoku: After any character performs a successful Attack action that deals 0 damage to the oni (after resistance is applied), that character suffers 3 strife."
											],
			techniques:[],
		},{
			fullname:"Zombie Peasant",
			title:"ZombiePeasant",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:2,
			conflictintrigue:0,
			rank:1,
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:3,
				Water:2,
				Void:0,},
			honor:0,
			glory:4,
			status:0,
			endurance:4,
			composure:"Infinite",
			focus:3,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:["Hungry"],
			advantages:[
					"Hungry for Flesh (Fire) [Martial; Mental]"
					],
			disadvantages:[	
					"Stumbling Gait (Water) [Martial; Physical]"
					],
			weapon:["Jagged Teeth","Grasping Hands"],
			armor:["Decaying Flesh"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:[
						"Cadavarous Bite: Increase the TN of checks to resist critical strikes inflicted by zombies by 2",
						"Horrifying Reanimation: A zombie is an Otherworldly, Tainted being. The first time it is defeated by damage from a non-Sacred source, if a zombie is in Defiled terrain, it reanimates. At the start of its next turn, it removes all fatigue and staggers to its feet with a scar disadvantage of the GM's choice"
											],
			techniques:[],
		},{
			fullname:"Forest Troll",
			title:"ForestTroll",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:4,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:2,
				Fire:5,
				Water:4,
				Void:3,},
			honor:30,
			glory:10,
			status:5,
			endurance:16,
			composure:9,
			focus:4,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:1,
				martialskill:3,
				scholarskill:3,
				socialskill:2,
				tradeskill:1,},
			demeanor:["Assertive","Detached","Gruff","Shrewd","Aggressive","Cautious","Territorial"],
			advantages:[
					"Brute Strength (Fire) [Martial; Physical]"
					],
			disadvantages:[	
					"Insatiable Appetites (Water) [Social; Physical]"
					],
			weapon:["Massive Cudgel","Rending Grips"],
			armor:["Scaled Hide"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:[
						"Ancient and Powerful: A troll is an Otherworldly being of silhouette 4.",
						"Sorcerous Scales: After a troll suffers damage from a physical or supernatural source, increase its resistance to that damage type by 4. This effect persists until it suffers damage from a source of a different type."
											],
			techniques:[],
		},{
			fullname:"Ki-Rin",
			title:"Ki-Rin",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:7,
			rank:1,
			ring:{
				type: "set",
				Earth:4,
				Air:3,
				Fire:2,
				Water:4,
				Void:5,},
			honor:60,
			glory:50,
			status:39,
			endurance:14,
			composure:16,
			focus:3,
			vigilance:5,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:5,
				scholarskill:6,
				socialskill:3,
				tradeskill:0,},
			demeanor:["Detached","Intimidating","Proud","Intense"],
			advantages:[
					"Wisdom of the Forest (Air) [Scholar; Mental]"
					],
			disadvantages:[	"Removed from the Earth (Fire) [Scholar; Mental]"
					],
			weapon:["Majestic Antlers"],
			armor:["Magical Hide"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:[
						"Mystical Creature: A ki-rin is an Otherworldly being of silhouette 3 that can fly. It can move vertically and ignores the negative effects of terrain. Additionally, once per scene, it may perform an Earth or Water invocation technique, and counts as succeeding with three bonus successes and <span class='l5r'>O</span> <span class='l5r'>O</span>.",
						"Sacred Envoy: The ki-rin can speak any language, and it knows many secrets of the world. The righteous can sense its hallowed nature; to perform an Attack action against it, a character must forfeit honor equal to their honor rank (and glory equal to their glory rank, if they are seen doing it).",
						"Wrath for the Wicked: Once per scene as a Attack action, the ki-rin may breathe holy fire from its mouth. Each Tainted being at range 0-4 must resist with a TN 4 Fitness check (Air 3, Earth 5) or suffer 8 supernatural damage with the Sacred quality, plus additional damage equal to its shortfall, and suffer the Burning condition."
											],
			techniques:[],
		},{
			fullname:"Manifest Air Kami",
			title:"ManifestAirKami",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:5,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:6,
				Fire:1,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:11,
			composure:6,
			focus:2,
			vigilance:4,
			max:5,
			skills:{
				artisanskill:3,
				martialskill:3,
				scholarskill:0,
				socialskill:3,
				tradeskill:2,},
			demeanor:["Flighty"],
			advantages:[
					"Ethereal Form (Air) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Easily Distrcted (Fire) [Scholar, Social; Mental]"
					],
			weapon:["Talons of Air"],
			armor:["Misty Mantle"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:[
						"Flight: A manifest air kami can move vertically and ignores the negative effects of terrain.",
						"Living Air Spirit: A manifest air kami is an Otherworldly being of silhouette 2, 3, or 4, and may change its size as an action. Additionally, once per scene as an action of the appropriate types, a manifest air kami may perform any one Air invocation other than Rise, Air. It counts as succeeding with 3 bonus successes and 2 <span class='l5r'>O</span>.",
						"Swoop: When performing an Attack action check, a manifest air kami may spend <span class='l5r'>O</span> as follows: <span class='l5r'>O</span>+: Move 1 range band away from the target per <span class='l5r'>O</span> spent this way. If the target is of silhouette 5 or smaller, the air kami may carry it to its destination instead."
											],
			techniques:[],
		},{
            fullname:"Manifest Earth Kami",
			title:"ManifestEarthKami",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:8,
			conflictintrigue:2,
			rank:1,
			ring:{
				type: "set",
				Earth:6,
				Air:1,
				Fire:2,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:15,
			composure:8,
			focus:3,
			vigilance:3,
			max:5,
			skills:{
				artisanskill:2,
				martialskill:3,
				scholarskill:3,
				socialskill:0,
				tradeskill:3,},
			demeanor:["Obstinate"],
			advantages:[
					"Massive Stature (Earth) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Honest to a Fault (Air) [Social, Trade; Mental]"
					],
			weapon:["Stone Fists"],
			armor:["Rocky Hide"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:[
						"Burrow: As a Movement action, a manifest earth kami may withdraw into the ground. It cannot be targeted by actions or effects, or perform actions other than Eruption.",
						"Eruption: As an Attack and Movement action while burrowed, a manifest earth kami may burst from the ground at a chosen point at range 0-3. Each character at range 0-2 of that point must resist with a TN 4 Fitness check (Air 2, Water 5) or suffer 6 physical damage and the Prone condition.",
						"Living Earth Spirit: A manifest earth kami is an Otherworldly being of silhouette 3. Additionally, once per scene as an action of the appropriate types, a manifest earth kami may perform any one Earth invocation other than Rise, Earth. It counts as succeeding with 3 bonus successes and 2 <span class='l5r'>O</span>."
											],
			techniques:[],
		},{
			fullname:"Manifest Fire Kami",
			title:"ManifestFireKami",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:9,
			conflictintrigue:2,
			rank:1,
			ring:{
				type: "set",
				Earth:2,
				Air:1,
				Fire:6,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:12,
			composure:3,
			focus:4,
			vigilance:1,
			max:5,
			skills:{
				artisanskill:0,
				martialskill:3,
				scholarskill:3,
				socialskill:2,
				tradeskill:3,},
			demeanor:["Intense"],
			advantages:[
					"Primal Terror (Air) [Martial, Social; Interpersonal"
					],
			disadvantages:[	
					"Endless Hunger (Water) [Artisan, Scholar; Mental]"
					],
			weapon:["Blazing Touch"],
			armor:["Corona of Flames"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:[
						"Living Fire Spirit: A manifest kami is an Otherworldly being. Additionally, once per scene as an action of the appropriate types, a manifest fire kami may perform any one Fire invocation other than Rise, Fire. It counts as succeeding with 3 bonus successes and 2 <span class='l5r'>O</span>.",
						"Mantle of Smoke and Ash: Other characters treat the area at range 0-1 of the manifest fire kami as Dangerous and Obscuring terrain (Core p267).",
						"Searing Caress: When performing an Attack action check, a manifest fire kami may spend <span class='l5r'>O</span> as follows: <span class='l5r'>O</span>+: The target and up to one other character per <span class='l5r'>O</span> spent this way at range 0-1 of the target suffer the Burning condition (Core p272)"
											],
			techniques:[],
		},{
            fullname:"Manifest Water Kami",
			title:"ManifestWaterKami",
			type:"Creatures",
			equiptype:"natural",
			conflictcombat:7,
			conflictintrigue:4,
			rank:1,
			ring:{
				type: "set",
				Earth:1,
				Air:2,
				Fire:1,
				Water:6,
				Void:2,},
			honor:0,
			glory:0,
			status:0,
			endurance:14,
			composure:8,
			focus:8,
			vigilance:2,
			max:5,
			skills:{
				artisanskill:3,
				martialskill:2,
				scholarskill:3,
				socialskill:3,
				tradeskill:0,},
			demeanor:["Adaptable"],
			advantages:[
					"Liquid Body (Water) [Martial, Trade; Physical]"
					],
			disadvantages:[	
					"Without Convictions (Earth) [Artisan, Social; Mental]"
					],
			weapon:["Smashing Torrent"],
			armor:["Enshrouding Fog"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:[
						"Living Water Spirit: A manifest kami is an Otherworldly being. Additionally, once per scene as an action of the appropriate types, a manifest water kami may perform any one Water invocation other than Rise, Water. It counts as succeeding with 3 bonus successes and 2 <span class='l5r'>O</span>",						"Split: Once per round, after a manifest water kami suffers a critical strike, it may split in two. The two new manifest water kami each have endurance equal to half that of the original, and any fatigue it had suffered is divided as evenly as possible. Then, both may remove any conditions the original was suffering. All of them act during the original water kami's turn, in the order of the GM's choosing."
											],
			techniques:[],
		},
		{
            fullname:"Loyal Bushi",
			title:"LoyalBushi",
			type:"Pregen",
			conflictcombat:4,
			conflictintrigue:2,
			ring:{
				type: "set",
				Earth:3,
				Air:2,
				Fire:3,
				Water:3,
				Void:2,},
			honor:55,
			glory:50,
			status:39,
			endurance:12,
			composure:9,
			focus:5,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:1,
				martialskill:3,
				scholarskill:2,
				socialskill:1,
				tradeskill:0,},
			demeanor:["Assertive","Courageous","Gruff","Shrewd","Proud","Opportunistic","Loyal","Friendly"],
			advantages:["Tested in War (Earth) [Martial: Mental, Physical]", "Sworn to Bushido (Void) ]Social: Mental]",],
			disadvantages:["Hot-Tempered (Water) [Social: Mental]","Old War Wound (Air)[Martial; Physical]"],
			weapon:["Katana","Yumi","Naginata","Yari","Tetsubo","Ono"],
			armor:["Ashigaru Armor","Lacquered Armor","Common Clothes"],
			abilities:["Sworn Protector: Once per scene, when an Attack action check targeting another character at range 0-1 succeeds, a bushi may intervene, becoming the target of the action instead.",],
			techniques:["Crescent Moon Style"],
		},{
            fullname:"Humble Peasant",
			title:"HumblePeasant",
			conflictcombat:1,
			conflictintrigue:1,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:2,
				Air:1,
				Fire:2,
				Water:2,
				Void:1,},
			honor:20,
			glory:25,
			status:15,
			endurance:4,
			composure:4,
			focus:3,
			vigilance:2,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:0,
				scholarskill:0,
				socialskill:1,
				tradeskill:2,},			
			demeanor:["Shrewd","Cautious","Friendly","Opportunistic"],
			advantages:["Salt of the Earth (Earth) [Trade: Interpersonal]",],
			disadvantages:["Deferential (Water) [Social: Interpersonal, Mental]",],
			weapon:["Knife",],
			armor:["Rags","Common Clothes"],
			abilities:["Overlooked: When a peasant makes a check targeting a character with a higher status rank, they treat that character's vigilance as 1 lower.",],
			techniques:[],
		},{
            fullname:"Seasoned Courtier",
			title:"SeasonedCourtier",
			conflictcombat:1,
			conflictintrigue:5,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:2,
				Air:4,
				Fire:2,
				Water:3,
				Void:2,},
			honor:60,
			glory:50,
			status:39,
			endurance:6,
			composure:12,
			focus:6,
			vigilance:4,
			equiptype:"equipped",
			skills:{
				artisanskill:3,
				martialskill:0,
				scholarskill:2,
				socialskill:3,
				tradeskill:0,},			
			demeanor:["Shrewd","Detached","Friendly","Proud","Uncertain"],
			advantages:["Inexhaustible Politeness (Air) [Social; Interpersonal]", 
						"Wealth and Resources (Water) [Trade; Material]",],
			disadvantages:["Sheltered from War (Fire) [Martial; Mental]",],
			weapon:["Wakizashi",],
			armor:["Ceremonial Robes","Concealed Armor"],
			abilities:["Whispering Winds: Once per session as an action, the courtier may make a Courtesy (Air) check targeting one character in the scene. The TN is equal to 6 minus the target's glory rank (to a minimum of 1). If they succeed, the courtier learns a rumor about the target. <span class='l5r'>O</span> <span class='l5r'>O</span>: The courtier learns one of the target's advantages or disadvantages of the target's choice.",],
			techniques:["Fanning the Flames"],
		},{
            fullname:"Scholarly Shugenja",
			title:"ScholarlyShugenja",
			conflictcombat:4,
			conflictintrigue:3,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:3,
				Air:3,
				Fire:3,
				Water:3,
				Void:3,},
			honor:60,
			glory:45,
			status:39,
			endurance:10,
			composure:12,
			focus:6,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:3,
				martialskill:0,
				scholarskill:2,
				socialskill:3,
				tradeskill:0,},		
			demeanor:["Ambitious","Assertive","Courageous","Detached","Intense","Cautious"],
			advantages:["Mystical Knowledge (Void) [Scholar; Mental]", "Holy Personage (Void) [Social; Interpersonal]",],
			disadvantages:["Scholar's Physique (Earth) [Martial; Physical]",],
			weapon:["Wakizashi","Yumi",],
			armor:["Sanctified Robes","Ceremonial Robes","Common Clothes"],
			abilities:["Disciple of Secret Lore: (Choose 0-5 additional invocations (see page 189) and 0-3 additional rituals (see page 212) that this shugenja can perform. Add 1 to this character's combat rank for each invocation with a prerequisite of rank 3+ chosen this way.",],
			techniques:["Path to Inner Peace", "Fires from Within"],
		},{
            fullname:"Trained Ashigaru",
			title:"TrainedAshigaru",
			conflictcombat:2,
			conflictintrigue:1,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:3,
				Air:1,
				Fire:2,
				Water:2,
				Void:1,},
			honor:25,
			glory:29,
			status:19,
			endurance:6,
			composure:12,
			focus:6,
			vigilance:2,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:1,},			
			demeanor:["Gruff","Loyal","Ambitious","Courageous","Uncertain"],
			advantages:["Strength in Numbers (Earth) [Martial; Physical]",],
			disadvantages:["Jaded by Battle (Fire) [Social; Mental]",],
			weapon:["Yari","Yumi","Naginata"],
			armor:["Ashigaru Armor","Traveling Clothes"],
			abilities:["Rank Tactics: When an ashigaru provides assistance (Core p26) to the Martial skill check of another character at range 0-2, that character adds one kept <span class='l5r'>d</span> set to a <span class='l5r'>S</span> result instead of rolling an additional die.",],
			techniques:[],
		},{
            fullname:"Venerable Provincial Daimyo",
			title:"VenerableProvincialDaimyo",
			conflictcombat:7,
			conflictintrigue:6,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:4,
				Air:3,
				Fire:4,
				Water:4,
				Void:4,},
			honor:55,
			glory:70,
			status:65,
			endurance:14,
			composure:16,
			focus:7,
			vigilance:4,
			equiptype:"equipped",
			skills:{
				artisanskill:2,
				martialskill:4,
				scholarskill:3,
				socialskill:3,
				tradeskill:1,},
			demeanor:["Assertive","Proud","Courageous","Aggressive","Intimidating","Suspicious","Uncertain","Opportunistic"],
			advantages:["Wisdom of Experience (Void) [Scholar; Mental]", "Bolstering Presence (Earth) [Social; Interpersonal]",],
			disadvantages:["Long at Court (Water) [Martial; Mental, Physical]",],
			weapon:["Wakizashi","Katana","Naginata","Nodachi","Tessen"],
			armor:["Plated Armor","Ceremonial Robes",],
			abilities:["Lord's Command: Once per scene, as a Support action, a daimyo may advise a character who can hear them on how to complete a task they wish the character to perform. The character may use the daimyo's ring or skill in place of their own for the next check they make to complete this task before the end of the game session.",],
			techniques:[],
},{
            fullname:"Desperate Bandit",
			title:"DesperateBandit",
			type:"Fighters, Outlaws, Rokugani",
			demeanor:["Ambitious",],
			conflictcombat:1,
			conflictintrigue:1,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:2,
				Air:2,
				Fire:2,
				Water:2,
				Void:1,},
			honor:15,
			glory:20,
			status:1,
			endurance:5,
			composure:6,
			focus:4,
			vigilance:2,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:0,
				socialskill:0,
				tradeskill:0,},
			demeanor:["Assertive","Shrewd","Cautious","Friendly","Intimidating","Suspicious","Uncertain","Opportunistic"],
			advantages:[
				"Nothing to Lose: (Fire) [Martial, Social; Mental]",
			],
			disadvantages:[
				"Fool's Avarice: (Earth) [Social; Mental]",
				"Quarrelsome: (Void) [Social; Interpersonal]",
			],
			weapon:[
				"Yari", "Sling","Masakari","Bo","Hammer","Kama",
			],
			armor:["Traveling Clothes","Common Clothes"],
			abilities:[
				"Ambush Tactics: When performing an  Attack action against a target with the Dazed or Disoriented condition, increase any damage dealt by 2.",
			],
			techniques:[],
},{
            fullname:"Experienced Bandit",
			title:"ExperiencedBandit",
			conflictcombat:3,
			conflictintrigue:2,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:3,
				Air:2,
				Fire:3,
				Water:3,
				Void:1,},
			honor:10,
			glory:15,
			status:3,
			endurance:9,
			composure:8,
			focus:6,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:2,
				scholarskill:0,
				socialskill:1,
				tradeskill:1,},			
			demeanor:["Shrewd","Assertive","Cautious","Friendly","Intimidating","Suspicious","Uncertain","Opportunistic"],
			advantages:["Age and Cunning (Water) [Interpersonal, Physical]",],
			disadvantages:["Fool's Avarice (Earth) [Social; Mental]",],
			weapon:["Rusty Katana","Kusari-gama","Ono",],
			armor:["Ashigaru Armor","Traveling Clothes"],
			abilities:["Dirty Tricks : When performing an Attack action check, an experienced bandit may spend <span class='l5r'>O</span> in the following way: <span class='l5r'>O</span> : One character at range 0-2 suffers the Disoriented condition. Then you may move 1 range band, ","...Get them, you fools!: As an action, an experienced bandit may have up to two Desperate Bandits who have not yet acted this round immediately move 1 range band and perform a Strike action with skilled assistance (Core p26) .",],
			techniques:[],
		},{
            fullname:"Skilful Ronin",
			title:"SkilfulRonin",
			conflictcombat:4,
			conflictintrigue:2,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:3,
				Air:3,
				Fire:2,
				Water:2,
				Void:2,},			
			honor:30,
			glory:40,
			status:20,
			endurance:12,
			composure:11,
			focus:5,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:3,
				scholarskill:1,
				socialskill:0,
				tradeskill:2,},
			demeanor:["Detached","Ambitious","Courageous","Intimidating","Aggressive","Suspicious","Friendly","Cautious"],
			advantages:["Killer Instinct (Fire) [Martial; Mental]", "Worldly Wanderer (Void) [Scholar, Trade; Mental]",],
			disadvantages:["Unnecessarily Rude (Water) [Social; Interpersonal]",],
			weapon:["Katana","Yumi","Naginata","Wakizashi","Chokuto"],
			armor:["Traveling Clothes","Ashigaru Armor"],
			abilities:["School of the Wolf: Once per round, when an Attack action check targeting the ronin succeeds, the ronin may suffer 3 fatigue to change the target to another character (other than the attacker) at range 0-1 of the ronin.",],
			techniques:["Striking as Fire"],
	},{
            fullname:"Deadly Bloodspeaker",
			title:"DeadlyBloodspeaker",
			conflictcombat:9,
			conflictintrigue:9,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:6,
				Air:4,
				Fire:4,
				Water:4,
				Void:3,},
			honor:5,
			glory:7,
			status:0,
			endurance:18,
			composure:16,
			focus:6,
			vigilance:4,
			equiptype:"equipped",
			skills:{
				artisanskill:2,
				martialskill:3,
				scholarskill:5,
				socialskill:4,
				tradeskill:1,},
			demeanor:["Ambitious","Shrewd","Detached","Opportunistic","Suspicious"],
			advantages:["Undying (Earth) [Martial; Physical, Spiritual]", "Whispers of Fu Leng (Void) [Scholar; Mental]",],
			disadvantages:["Heartless (Void) [Social; Physical, Spiritual]",],
			weapon:["Obsidian-Edged Katana","Ritual Knife"],
			armor: ["Sorcerous Raiment","Ceremonial Robes"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Bleed the Soul: After the Bloodspeaker inflicts a Critical Strike on a living target, the target suffers the Dazed condition and the Bloodspeaker removes 3 fatigue.", "Hidden Heart: The Bloodspeaker cannot truly be vanquished until its heart (usually buried in some deadly tomb or sanctum of evil) has been destroyed. It ignores the Unconscious condition. If slain, it can possess a fresh corpse after its allies have prepared the corpse through a dark rite that takes four days to complete.", "Master of Vile Lore: The Bloodspeaker is a Tainted being who can perform all maho (Core p224).",],
			techniques:[],
		},{
            fullname:"Wicked Maho-Tsukai",
			title:"WickedMaho-Tsukai",
			conflictcombat:4,
			conflictintrigue:3,
			type:"Pregen",
			ring:{
				type: "set",
				Earth:4,
				Air:3,
				Fire:3,
				Water:3,
				Void:2,},
			honor:1,
			glory:15,
			status:0,
			endurance:14,
			composure:8,
			focus:7,
			vigilance:3,
			equiptype:"equipped",
			skills:{
				artisanskill:0,
				martialskill:1,
				scholarskill:3,
				socialskill:2,
				tradeskill:1,},			
			demeanor:["Ambitious","Shrewd","Detached","Opportunistic","Suspicious"],
			advantages:["Excellent Liar (Air) [Social; Interpersonal]", "Whispers of Fu Leng (Void) [Scholar; Mental]",],
			disadvantages:["Rotting from Within (Earth) [Martial; Physical, Spiritual]",],
			weapon:["Ritual Knife",],
			armor: ["Sorcerous Raiment","Ceremonial Robes"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Mark of Desecration: As a Support action, the maho-tsukai may make a TN 2 Theology (Earth) check targeting up to three corpses at range 0-3. If the maho-tsukai succeeds, each target rises as a Zombie Peasant (Core p321), or a Bushi Skeleton if it was a warrior in life (Core p318). Then, an area encompassing 1 range band around each target's position gains the Defiled terrain quality (Core p267)", "Seeker of Vile Lore: The maho-tsukai is a Tainted being. Optionally, choose 0-2 additional maho (Core p224) that the maho-tsukai can perform. Add 1 to this character's combat rank for each maho chosen this way.",],
			techniques:[],
		},{
            fullname:"Gashadokuro",
			title:"Gashadokuro",
			conflictcombat:14,
			conflictintrigue:0,
			type:"Creatures",
			ring:{
				type: "set",
				Earth:6,
				Air:2,
				Fire:4,
				Water:2,
				Void:2,},
			honor:0,
			glory:0,
			status:0,
			endurance:20,
			composure:99,
			focus:6,
			vigilance:2,
			equiptype:"natural",
			skills:{
				artisanskill:0,
				martialskill:5,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},			
			demeanor:["Aggressive"],
			advantages:["Massive Stature (Earth) [Martial; Physical]",],
			disadvantages:["Easily Distracted (Fire) [Social; Interpersonal]",],
			weapon:["Claws and Teeth",],
			armor: ["Bone Plating",],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Massive Bones: a gashadokuro is an Otherworldly, Tainted being of silhouette 5.  The first time it would be defeated due to suffering damage each scene, it ignores that damage and its bone plating is destroyed instead.<br>Shadowlands p15",],
			techniques:[],
		},{
            fullname:"Harionago",
			title:"Harionago",
			conflictcombat:4,
			conflictintrigue:3,
			type:"Creatures",
			ring:{
				type: "set",
				Earth:1,
				Air:3,
				Fire:2,
				Water:2,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:16,
			composure:10,
			focus:9,
			vigilance:3,
			equiptype:"natural",
			skills:{
				artisanskill:2,
				martialskill:2,
				scholarskill:0,
				socialskill:2,
				tradeskill:1,},			
			demeanor:["Shrewd"],
			advantages:["Expert in Disguise (Air) [Social; Interpersonal]",],
			disadvantages:["Impatience (Earth) [Social; Mental]",],
			weapon:["Barbed Hair",],
			armor: ["x",],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Entangling Tresses: A harionago is an Otherworldly, Tainted being.  When a harionago deals damage to an Immobilized target, it ignores 2 points of the target's physical resistance.<br>Shadowlands p16",],
			techniques:[],
		},{
            fullname:"Kyorinrin",
			title:"Kyorinrin",
			conflictcombat:3,
			conflictintrigue:2,
			type:"Creatures",
			ring:{
				type: "set",
				Earth:2,
				Air:3,
				Fire:1,
				Water:3,
				Void:1,},
			honor:0,
			glory:0,
			status:0,
			endurance:6,
			composure:10,
			focus:4,
			vigilance:3,
			equiptype:"natural",
			skills:{
				artisanskill:0,
				martialskill:3,
				scholarskill:0,
				socialskill:1,
				tradeskill:0,},			
			demeanor:["Shrewd"],
			advantages:["Subtle Appearance (Air) [Martial; Physical]",],
			disadvantages:["Fear of Fire (Fire) [Social; Mental]",],
			weapon:["Smothering Papers",],
			armor: ["Layers of Paper",],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Masses of Paper: A kyorinrin is an Otherworldly, Tainted being of silhouette 3.  When a kyorinrin defends against fire damage, its resistance counts as 0.  When a kyorinrin makes a successful Attack action check, it may spend <span class='l5r'>O</span> <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span> <span class='l5r'>O</span>+: The target begins to suffocate (Core p269).  After a character suffers strife and fatigue at the start of their turn from suffocating this way, the character may make a TN 3 Fitness check (Fire 2, Earth 5) to break free and breathe normally.<br>Shadowlands p16",],
			techniques:[],
		},{
            fullname:"Penanggalan",
			title:"Penanggalan",
			type:"Creatures",
			conflictcombat:6,
			conflictintrigue:3,
			ring:{type:'set',Earth:3,Air:4,Fire:5,Water:2,Void:2,},
			honor:0,glory:8,status:0,
			endurance:16,composure:10,focus:9,vigilance:3,
			equiptype:"natural",
			skills:{artisanskill:0,martialskill:5,scholarskill:2,socialskill:3,tradeskill:0,},
			demeanor:["Shrewd"],
			advantages:["Flying Horror (Fire) [Martial; Physical]"],
			disadvantages:["Vulnerable While Eating (Earth) [Martial; Physical]"],
			weapon:["Tentacle Entrails"],armor:["Body Shell"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Feaster of Blood: A penanggalan is an Otherworldly, Tainted being.  While bodiless it is silhouette 2.  When a penanggalan inflicts a critical strike on its target, it removes fatigue equal to the severity (after the check to resist).  Optionally, the GM may choose 0-2 maho that a penanggalan can perform; add 1 to this character's combat rank for each maho chosen this way."],
			source:"Shadowlands p17",
			techniques:[],
		},{
            fullname:"Ravenous Shadowlands Ogre",
			title:"RavenousShadowlandsOgre",
			type:"Creatures",
			conflictcombat:7,
			conflictintrigue:1,
			ring:{type:'set',Earth:4,Air:1,Fire:3,Water:2,Void:1,},
			honor:0,glory:5,status:0,
			endurance:17,composure:7,focus:4,vigilance:2,
			equiptype:"equipped",
			skills:{artisanskill:0,martialskill:3,scholarskill:0,socialskill:0,tradeskill:1,},
			demeanor:["Gruff"],
			advantages:["Single-Minded (Earth) [Social; Interpersonal]"],
			disadvantages:["Always Hungry (Earth) [Martial; Mental]"],
			weapon:["Tree Trunk"],armor:["Numerous Hides"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Rage of the Beast: A ravenous Shadowlands ogre is a Tainted being of silhouette 4.  When the ogre suffers a critical strike, it becomes Enraged.  Whenever it inflicts a critical strike, the target suffers the Prone condition in addition to all other results of the critical strike."],
			source:"Shadowlands p17",
		},{
            fullname:"Revenant",
			title:"Revenant",
			type:"Creatures",
			conflictcombat:6,
			conflictintrigue:2,
			ring:{type:'set',Earth:4,Air:2,Fire:3,Water:2,Void:1,},
			honor:0,glory:5,status:0,
			endurance:14,composure:99,focus:5,vigilance:2,
			equiptype:"equipped",
			skills:{artisanskill:0,martialskill:5,scholarskill:1,socialskill:1,tradeskill:1,},
			demeanor:["Assertive"],
			advantages:["Undead Gunso (Earth) [Social; Interpersonal]"],
			disadvantages:["Self-Knowledge (Void) [Social; Mental]"],
			weapon:["Heavy Masakari"],armor:["Rusted Armor"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Powerful Servant: A revenant is an Otherworldly, Tainted being.  It may issue orders to undead creatures if they were created by the same maho-tsukai.  Undead creatures under its orders ignore their disadvantages and count as having the Revenant's assistance on all Scholar, Social and Trade checks they make."],
			source:"Shadowlands p18",
		},{
            fullname:"Tsumunagi",
			title:"Tsumunagi",
			type:"Creatures",
			conflictcombat:2,
			conflictintrigue:0,
			ring:{type:'set',Earth:2,Air:1,Fire:2,Water:1,Void:0,},
			honor:0,glory:0,status:0,
			endurance:4,composure:6,focus:3,vigilance:1,
			equiptype:"natural",
			skills:{artisanskill:0,martialskill:3,scholarskill:0,socialskill:1,tradeskill:1,},
			demeanor:["Aggressive"],
			advantages:["Slippery (Fire) [Martial; Physical]"],
			disadvantages:["Thirst for Blood (Earth) [Martial; Physical]"],
			weapon:["Biting Teeth"],armor:["Slimy Skin"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Twisting Leech: A tsumunagi is a Tainted being of silhouette 1.  When making an Attack action check, a tsumunagi may spend O O to attach itself to the target.  The target suffers the Bleeding condition, and cannot remove the condition while the tsumunagi is attached.  Any character at range 0-1 may make a TN 3 Medicine check (Air 2, Earth 5) to remove the tsumunagi, reducing the TN by 1 if they use a flame to scorch the creature off.  If they succeed, it is removed.  If they fail, the victim suffers a critical strike with severity 7 plus their shortfall."],
			source:"Shadowlands p17",
		},{
            fullname:"Undead Horror",
			title:"UndeadHorror",
			type:"Creatures",
			conflictcombat:5,
			conflictintrigue:0,
			ring:{type:'set',Earth:5,Air:1,Fire:3,Water:1,Void:1,},
			honor:0,glory:0,status:0,
			endurance:18,composure:99,focus:3,vigilance:2,
			equiptype:"natural",
			skills:{artisanskill:0,martialskill:3,scholarskill:0,socialskill:0,tradeskill:0,},
			demeanor:["Hungry"],
			advantages:["Undead Flesh (Earth) [Martial; Physical]"],
			disadvantages:["Mindless (Void) [Social; Mental]"],
			weapon:["Rotted Fists and Teeth"],armor:["Rotting Flesh"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Fused Corpses: An undead horror is an Otherworldly, Tainted being of silhouette 3.  Unless defeated by damage from a Sacred source, its component corpses separate and arise as three undamaged zombie peasants (Core p321)."],
			source:"Shadowlands p19",
		},{
            fullname:"Wanyudo",
			title:"Wanyudo",
			type:"Creatures",
			conflictcombat:4,
			conflictintrigue:2,
			ring:{type:'set',Earth:3,Air:2,Fire:4,Water:2,Void:2,},
			honor:0,glory:5,status:0,
			endurance:16,composure:10,focus:9,vigilance:3,
			equiptype:"natural",
			skills:{artisanskill:0,martialskill:3,scholarskill:0,socialskill:3,tradeskill:0,},
			demeanor:["Assertive"],
			advantages:["All-Terrain Wheel (Fire) [Martial; Physical]"],
			disadvantages:["Painful Form (Water) [Social; Physical]"],
			weapon:["Crushing Fire"],armor:["Wooden Form"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Fiery Soultaker: A wanyudo is an Otherworldly, Tainted being of silhouette 2.  When making an Attack action check, the wanyudo may spend O O to inflict the Burning condition on its target.  Characters who perish while at range 0 of a wanyudo may have their souls dragged to Jigoku.  The ramifications of this terrible outcome are at the GM's discretion, such as that they cannot be reincarnated until they are rescued."],
			source:"Shadowlands p19",
		},{
            fullname:"Fudoshi",
			title:"Fudoshi",
			type:"Creatures",
			conflictcombat:3,
			conflictintrigue:0,
			ring:{type:'set',Earth:3,Air:1,Fire:2,Water:2,Void:0,},
			honor:0,glory:5,status:0,
			endurance:10,composure:99,focus:3,vigilance:2,
			equiptype:"natural",
			skills:{artisanskill:0,martialskill:2,scholarskill:0,socialskill:0,tradeskill:1,},
			demeanor:["Aggressive"],
			advantages:["No Central Body (Earth) [Martial; Physical]"],
			disadvantages:["Impulse Attacker (Fire) [Martial; Mental]"],
			weapon:["Tangling Vines"],armor:["Outer Husk"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Concealed Constrictor: A fudoshi is a Tainted being of silhouette 3.  Characters count their vigilance as half its normal value for the purposes of noticing a fudoshi or when it uses the Snaring quality of its tangling weapon."],
			source:"Shadowlands p22",
		},{
            fullname:"Dark Moto Bushi",
			title:"DarkMotoBushi",
			type:"Creatures",
			conflictcombat:8,
			conflictintrigue:4,
			ring:{type:'set',Earth:3,Air:2,Fire:3,Water:3,Void:2,},
			honor:22,glory:8,status:0,
			endurance:12,composure:12,focus:5,vigilance:3,
			equiptype:"equipped",
			skills:{artisanskill:0,martialskill:5,scholarskill:1,socialskill:3,tradeskill:2,},
			demeanor:["Assertive"],
			advantages:["Ageless Warrior (Water) [Martial; Mental]"],
			disadvantages:["Corrupted Visage (Water) [Social; Interpersonal]"],
			weapon:["Ujik Lance","Katana","Scimitar","Yumi"],armor:["Corrupted armor"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Ancient Rider: A Dark Moto bushi is an Otherworldly, Tainted being.  When making an Attack action while mounted on horseback, a Dark Moto bushi may spend O O+ to move 1 range band per O O spent this way after resolving this action."],
			source:"Shadowlands p22",
		},{
            fullname:"Onikage",
			title:"Onikage",
			type:"Creatures",
			conflictcombat:2,
			conflictintrigue:0,
			ring:{type:'set',Earth:2,Air:1,Fire:3,Water:2,Void:1,},
			honor:0,glory:0,status:0,
			endurance:10,composure:99,focus:3,vigilance:2,
			equiptype:"natural",
			skills:{artisanskill:0,martialskill:3,scholarskill:0,socialskill:0,tradeskill:1,},
			demeanor:["Fierce"],
			advantages:["Tireless (Earth) [Martial; Physical]"],
			disadvantages:["Hard to Control (Water) [Martial; Mental]"],
			weapon:["Teeth and Hooves"],armor:["Corrupted armor"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Unnatural Speed: An onikage is an Otherworldly, Tainted being of silhouette 3.  It can be ridden by any human-sized rider, using the Mounts and Riding rules (Core p326).  <br>Unless the rider is Tainted, an onikage will attempt to throw the rider then attack him.  <br>Dark Moto Onikage are elite demonic mounts formed from the Unicorn steeds of the Moto.  Like their riders they are corrupted and terrible in appearance, with reptilian hides and crimson eyes.  These steeds use the profile for onikage, adding the following ability: <br>Deadly Steed:  If the rider is a Dark Moto, when making an Attack action check, the rider may spend O to have their mount lash out with its teeth and hooves, inflicting 5 damage with the Unholy quality on a character at range 0-1."],
			source:"Shadowlands p23",
		},{
            fullname:"Goblin Accursed Priest",
			title:"GoblinAccursedPriest",
			type:"Creatures",
			conflictcombat:2,
			conflictintrigue:3,
			ring:{type:'set',Earth:2,Air:2,Fire:2,Water:2,Void:4,},
			honor:0,glory:0,status:0,
			endurance:8,composure:8,focus:4,vigilance:3,
			equiptype:"equipped",
			skills:{artisanskill:1,martialskill:1,scholarskill:2,socialskill:1,tradeskill:2,},
			demeanor:["Cowardly"],
			advantages:["Whispers of Fu Leng (Void) [Scholar; Mental]"],
			disadvantages:["Cowardice (Earth) [Martial; Social]"],
			weapon:["Ritual Dagger"],armor:["Defiled priestly robes"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Favoured of Fu Leng: A goblin accursed priest is a Tainted being of silhouette 1, who reduces the TN of Command checks they make targeting goblins by 1.   Once per scene, they may call on Fu Leng's favour to change any die result containing a T to a result containing E.  The GM can choose 1-3 maho that the goblin accursed priest can perform.  Add 1 to this character's combat rank for each maho chosen this way."],
			source:"Shadowlands p31",
		},{
            fullname:"Nezumi Dreamer",
			title:"NezumiDreamer",
			type:"Creatures",
			conflictcombat:3,
			conflictintrigue:3,
			ring:{type:'set',Earth:3,Air:3,Fire:3,Water:3,Void:4,},
			honor:0,glory:8,status:0,
			endurance:12,composure:12,focus:6,vigilance:3,
			equiptype:"equipped",
			skills:{artisanskill:1,martialskill:2,scholarskill:3,socialskill:2,tradeskill:2,},
			demeanor:["Ambitious"],
			advantages:["Mystical Insight (Void) [Scholar; Spiritual]"],
			disadvantages:["Arrogance (Fire) [Martial; Interpersonal]"],
			weapon:["Nezumi dagger"],armor:["Nezumi vestments"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Dreamshaper: A nezumi dreamer is a being who can never gain the Afflicted condition or the Shadowlands Taint disadvantage.  Once per scene, the nezumi dreamer can make a Theology (Void) check to improve the destiny of a target at range 2.  The TN of the check is equal to the target's Void ring.  If the check is successful, the target gains 1 Void point.<br>Stealer of Fates: Once per scene, a nezumi dreamer can make a Theology (Void) check to snip away at the destiny of a target at range 2.  The TN of the check is equal to the target's Void Ring.  If the check is successful, the target loses 1 Void Point and gains the Disoriented condition.  If the nezumi dreamer is killed, the target regains its Void Point.<br>Dark Illusions: As a Scheme and Support action, a nezumi dreamer can make a Theology (Air) check to plant a nightmare into the mind of a target at range 0-2.  The TN of the check is equal to the target's vigilance.  If the nezumi dreamer succeeds, the target is plagued by nightmares: they cannot remove fatigue or strife until they succeed at a TN 3 Meditation check (Fire 2, Earth 5) as a downtime activity."],
			source:"Shadowlands p44",
		},{
            fullname:"Nezumi Warrior",
			title:"NezumiWarrior",
			type:"Creatures",
			conflictcombat:4,
			conflictintrigue:1,
			ring:{type:'set',Earth:3,Air:2,Fire:3,Water:3,Void:2,},
			honor:0,glory:9,status:0,
			endurance:12,composure:10,focus:5,vigilance:3,
			equiptype:"equipped",
			skills:{artisanskill:0,martialskill:4,scholarskill:0,socialskill:2,tradeskill:2,},
			demeanor:["Assertive"],
			advantages:["Battle Hardened (Earth) [Martial; Mental]"],
			disadvantages:["Arrogance (Fire) [Social; Interpersonal]"],
			weapon:["Katana"],armor:["Nezumi armour"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["A Warrior's Tail: A Nezumi warrior can never gain the Afflicted condition or the Shadowlands Taint disadvantage.  While making an Attack action check against a target a range 0-1, a Nezumi warrior may spend O O to lash their foe with their tail, inflicting 3 physical damage and causing their target to suffer the Immobilized condition.  Additinally, once per scene when an enemy succeeds on an Attack action check targeting another nezumi at range 0-1, a Nezumi warrior may intervene, becoming the target of the attack instead."],
			source:"Shadowlands p45",
		},{
            fullname:"Nezumi Rememberer",
			title:"NezumiRememberer",
			type:"Creatures",
			conflictcombat:1,
			conflictintrigue:4,
			ring:{type:'set',Earth:2,Air:4,Fire:2,Water:3,Void:2,},
			honor:0,glory:3,status:0,
			endurance:8,composure:10,focus:6,vigilance:3,
			equiptype:"equipped",
			skills:{artisanskill:2,martialskill:0,scholarskill:3,socialskill:2,tradeskill:2,},
			demeanor:["Detached"],
			advantages:["Ready to Run (Earth) [Martial; Physical]"],
			disadvantages:["Lost In the Past (Water) [Social; Interpersonal]"],
			weapon:["Nezumi knife"],armor:["Rememberer's robes"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Keeper of History:  A Nezumi rememberer can never gain the Afflicted condition or the Shadowlands Taint disadvantage.  Whenever a character in a scene with the Rememberer makes a Scholar skill check involving the Shadowlands, the character may spend O to have the Rememberer relate something tangentially useful, such as where additional components for a medicine just applied can be found or how long ago their tribe managed to defeat an oni similar to the one currently threatening the group."],
			source:"Shadowlands p46",
		},{
            fullname:"Nezumi pup",
			title:"Nezumipup",
			type:"Creatures",
			conflictcombat:1,
			conflictintrigue:1,
			ring:{type:'set',Earth:1,Air:1,Fire:2,Water:1,Void:1,},
			honor:0,glory:5,status:0,
			endurance:4,composure:4,focus:3,vigilance:1,
			equiptype:"natural",
			skills:{artisanskill:0,martialskill:1,scholarskill:0,socialskill:1,tradeskill:1,},
			demeanor:["Curious"],
			advantages:["Unnoticed (Earth) [Martial; Physical]"],
			disadvantages:["Defenseless (Fire) [Martial; Physical]"],
			weapon:["Little Bite"],armor:["Fur"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Inquisitive: A nezumi pup can never gain the Afflicted condition or the Shadowlands Taint disadvantage.  Their curiosity means they might be found almost anywhere in the Shadowlands, such as curled up in a backpack or behind a tent flap.  As a downtime activity, a character may observe a nezumi pup's playful antics and remove 3 strife.  A character who targets a nezumi pup with an Attack action receives 5 strife."],
			source:"Shadowlands p47",
		},{
            fullname:"Nezumi, feral",
			title:"Nezumiferal",
			type:"Creatures",
			conflictcombat:3,
			conflictintrigue:1,
			ring:{type:'set',Earth:2,Air:1,Fire:3,Water:2,Void:1,},
			honor:0,glory:3,status:0,
			endurance:10,composure:8,focus:4,vigilance:2,
			equiptype:"natural",
			skills:{artisanskill:0,martialskill:3,scholarskill:0,socialskill:1,tradeskill:2,},
			demeanor:["Feral"],
			advantages:["Instinctive Behavior (Fire) [Martial; Physical]"],
			disadvantages:["Always Hungry (Earth) [Martial; Mental]"],
			weapon:["Nezumi Claws and Teeth"],armor:["Fur"],
			qualities:"An oni is an Otherworldly, Tainted being of silhouette 4.",
			abilities:["Ferocious defender: A feral nezumi can never gain the Afflicted condition or the Shadowlands Taint disadvantage.  When it is the target of an Attack action check, it may receive 1 strife to remove O from the attacker's check value."],
			source:"Shadowlands p48",
			},

		]
var templates = [
{
title:"Artist",
	conflictcombat:0,
	conflictintrigue:2,
	ring:{
		type: "set",
		Air: 0,
		Earth: 1,
		Water: 0,
		Void: 1,
		Fire: 2,
	},
	endurance:-2,
	composure:2,
	focus:0,
	vigilance:1,
	artisanskill:2,
	martialskill:0,
	socialskill:1,
	scholarskill:0,
	tradeskill:0,
	advantages:["Eye for Detail (Air) [Artisan; Mental]",
			"Renown (Fire) [Artisan; Interpersonal]",
			"Steady Hand (Earth) [Artisan; Physical]",
			"Creative Soul (Fire) [Artisan; Mental]",
			"Impeccable Brushwork (Air) [Artisan; Mental]",
			],
	disadvantages:["Prima Donna (Water) [Social; Interpersonal]", 
			"Naivete (Fire) [Social; Interpersonal]", 
			"Sheltered from Battle (Fire) [Social; Interpersonal]",
			"World-Weariness (Earth) [Social; Interpersonal]",
			"Angsty Artist (Air) [Social, Artisan; Mental]",
			],
	extratechs:3,
	techtypes:["Shuji"],
	demeanor:["Detached", "Gruff", "Shrewd"],
},{
title:"Investigator",
	conflictcombat:1,
	conflictintrigue:1,
	ring:{
		type: "set",
		Air: 1,
		Earth: 0,
		Fire: 1,
		Water: 1,
		Void: 1,
	},
	endurance:1,
	composure:1,
	focus:0,
	vigilance:1,
	artisanskill:0,
	martialskill:1,
	socialskill:1,
	scholarskill:1,
	tradeskill:0,
	advantages:["Analytical Mind (Fire) [Scholar; Mental]", 
		"Self-Awareness (Void) [Martial; Mental]", 
		"Sharp Eyes (Water) [Scholar; Physical]",
		"A Nose for the Truth (Water) [Scholar, Social; Mental]",
		],
	disadvantages:["Sceptical Attitude (Fire) [Social; Mental]", 
		"Haughty Tone (Air) [Social; Interpersonal]", 
		"Functional Alcoholic (Water) [Social,Scholar,Martial; Physical]",
		"Seen It All Before (Earth) [Scholar, Social; Mental]",

		],
	extratechs:3,
	techtypes:["Kata", "Shuji"],
	demeanor:["Gruff", "Shrewd"],
	},{
title:"Socialite",
	conflictcombat:0,
	conflictintrigue:2,
	ring:{
		type: "set",
		Air: 1,
		Earth: 0,
		Fire: 1,
		Void: 0,
		Water: 2,
	},
	endurance:-1,
	composure:+1,
	focus:0,
	vigilance:1,
	artisanskill:0,
	martialskill:0,
	socialskill:2,
	scholarskill:0,
	tradeskill:1,
	advantages:["Well-Spoken (Air) [Social; Interpersonal]", 
		"Wealth and Resources (Water) [Trade; Material]",
		"Seems Trustworthy (Water) [Social; Interpersonal]",
		"Inexhaustible Politeness (Air) [Social; Interpersonal]",
		"Social Connections (Air) [Social; Interpersonal]",
		],
	disadvantages:["Doomed Love (Fire) [Social; Interpersonal]", 
		"Lack of Empathy (Air) [Social; Mental]", 
		"Poor Memory (Earth) [Scholar; Mental]",
		"Busybody (Air) [Social; Mental]",
		"Avaricious (Fire) [Social; Interpersonal]",
		],
	extratechs:3,
	techtypes:["Shuji", "Ritual"],
	demeanor:["Assertive", "Shrewd"],
	},{
title:"Spiritualist",
	conflictcombat:1,
	conflictintrigue:1,
	ring:{
		type: "random",
	},
	endurance:-1,
	composure:1,
	focus:0,
	vigilance:0,
	artisanskill:1,
	martialskill:0,
	socialskill:0,
	scholarskill:2,
	tradeskill:0,
	advantages:["Keen Empathy (Air) [Social; Interpersonal]", 
		"Friendly Kami or Spirit (Fire, Earth, Air, or Water) [Scholar; Spiritual]",
		"Holy Personage (Water) [Social; Interpersonal]",
		"Mystical Knowledge (Void) [Scholar; Mental]",
		],
	disadvantages:["Above Worldly Matters (Water) [Trade, Social; Interpersonal]", 
		"Repressed (Fire) [Social; Mental]",
		"Frailty (Earth) [Martial; Physical]",
		"Possessed by Curiosity (Water) [Scholar; Mental]",
		],
	extratechs:3,
	techtypes:["Invocation", "Ritual"],
	demeanor:["Detached", "Assertive"],
	},{
title:"Trickster",
	conflictcombat:1,
	conflictintrigue:1,
	ring:{
		type: "set",
		Air: 2,
		Earth: 0,
		Fire: 1,
		Water: 1,
		Void: 0,
	},
	endurance:-1,
	composure:1,
	focus:0,
	vigilance:1,
	artisanskill:0,
	martialskill:0,
	socialskill:2,
	scholarskill:1,
	tradeskill:0,
	advantages:["Excellent Liar (Air) [Social; Interpersonal]", 
		"Patience (Earth) [Scholar; Mental]", 
		"Loves Haggling (Water) [Trade; Interpersonal]",
		"Unmemorable Face (Air) [Social; Physical]",
		"Skilled Mimic (Air) [Artisan, Social; Interpersonal, Physical]",
		],
	disadvantages:["Fear of Failure (Fire) [Martial; Mental]", 
		"Narcissism (Earth) [Social; Mental]", 
		],
	extratechs:3,
	techtypes:["Ninjutsu", "Shuji"],
	demeanor:["Ambitious", "Shrewd"],
	},{
title:"Warrior",
	conflictcombat:2,
	conflictintrigue:0,
	ring:{
		type: "random",
	},
	endurance:2,
	composure:-2,
	focus:1,
	vigilance:-1,
	artisanskill:0,
	martialskill:2,
	socialskill:1,
	scholarskill:0,
	tradeskill:0,
	advantages:["Tested in War (Earth) [Martial: Mental, Physical]", 
		"Fearsome Presence (Fire) [Social; Interpersonal]", 
		"Veteran's Instincts (Water) [Martial; Mental]"],
	disadvantages:["Bad Dreams (Void) [Martial; Mental]", 
		"Quick to Anger (Fire) [Social; Interpersonal]", 
		"Shattered by War (Earth) [Social; Mental]",
		"Old War Wound (Air)[Martial; Physical]",
		],
	extratechs:3,
	techtypes:["Kata"],
	demeanor:["Assertive", "Gruff"],
	},{
title:"Ascetic",
	conflictcombat:2,
	conflictintrigue:0,
	ring:{
		type:"set",
		Void: 2,
		Air: 0,
		Earth: 1,
		Fire: 0,
		Water: 1,
	},
	endurance:1,
	composure:1,
	focus:0,
	vigilance:0,
	artisanskill:0,
	martialskill:1,
	socialskill:1,
	scholarskill:1,
	tradeskill:0,
	advantages:["Partial Enlightenment (Void) [Scholar; Spiritual]",
		"Honed Physique (Earth) [Martial; Physical]",
		"Acrobatic Fighter (Air) [Martial; Physical]"],
	disadvantages:["Poverty (Water) [Trade; Material]", 
		"Fanaticism (Fire) [Social; Mental]",
		"Cantankerous (Water) [Social; Interpersonal]",
		"Above Worldly Matters (Water) [Trade, Social; Interpersonal]"],
	extratechs:3,
	techtypes:["Ritual", "Kiho"],
	demeanor:["Detached", "Shrewd"],
},{
title:"Yojimbo",
	conflictcombat:2,
	conflictintrigue:0,
		ring:{
		type:"random",
	},
	endurance:0,
	composure:0,
	focus:2,
	vigilance:1,
	artisanskill:1,
	martialskill:2,
	socialskill:0,
	scholarskill:0,
	tradeskill:0,
	advantages:[
		"Eager to Make a Name (Fire) [Social; Mental]",
		"Duelist's Reflexes (Fire) [Martial; Physical]",
		"Yojimbo's Instincts (Void) [Martial, Social; Physical, Interpersonal]",
		"Famed Duelist (Water) [Martial, Social; Physical, Interpersonal]",
	],
	disadvantages:[
		"Softhearted Duelist (Fire) [Martial; Mental]",
		"Old Dueling Scar (Fire) [Martial; Physical]",
		"Arrogant (Fire) [Social; Interpersonal]",
		"Washed Up Duelist (Fire) [Social; Interpersonal]",
	],
	extratechs:3,
	techtypes:["Kata","Shuji"],
	demeanor:["Detached", "Assertive", "Ambitious"],
},{
title:"Tactician",
	conflictcombat:2,
	conflictintrigue:0,
		ring:{
		type:"random",
	},
	endurance:0,
	composure:0,
	focus:2,
	vigilance:1,
	artisanskill:0,
	martialskill:2,
	socialskill:0,
	scholarskill:1,
	tradeskill:0,
	advantages:[
			"Bolstering Presence (Earth) [Social; Interpersonal]",
			"Famously Cunning Strategist (Air) [Martial; Interpersonal, Mental]",
			"Beloved by the Troops (Water) [Social; Interpersonal]",
			"Never Seen A Gamble That Didn't Pay Off (Fire) [Martial,Social; Mental]"
	],
	disadvantages:[
			"Old War Scar (Fire) [Martial, Trade; Physical]",
			"Despised by the Troops (Water) [Social; Interpersonal]",
			"Conventional Thinker (Fire) [Martial, Social; Interpersonal]",
			"Inexperienced Leader (Earth) [Martial; Interpersonal]",
	],
	extratechs:3,
	techtypes:["Kata","Shuji"],
	demeanor:["Assertive", "Ambitious"],
},{
title:"Scout",
	conflictcombat:1,
	conflictintrigue:1,
		ring:{
		type:"set",
		Void: 0,
		Air: 2,
		Earth: 1,
		Fire: 0,
		Water: 1,
	},
	endurance:0,
	composure:0,
	focus:2,
	vigilance:1,
	artisanskill:0,
	martialskill:1,
	socialskill:0,
	scholarskill:0,
	tradeskill:2,
	advantages:[
			"Excellent Skulker (Air) [Martial, Trade; Physical]",
			"Expert Tracker (Air) [Trade; Mental]",
			"Unmemorable Face (Air) [Social; Physical]",
			"Light Fingers (Air) [Trade; Physical]",
			"Acrobatic Fighter (Air) [Martial; Physical]",
	],
	disadvantages:[
			"Risk-Taker (Air) [Martial; Physical]"
	],
	extratechs:3,
	techtypes:["Kata","Ninjutsu"],
	demeanor:["Detached", "Ambitious"],
},{
title:"Dark Sage",
	conflictcombat:1,
	conflictintrigue:1,
	ring:{
		type: "random",
	},
	endurance:-2,
	composure:1,
	focus:1,
	vigilance:1,
	artisanskill:0,
	martialskill:0,
	socialskill:0,
	scholarskill:2,
	tradeskill:1,
	advantages:["Forbidden Knowledge [Maho] (Fire) [Scholar; Mental]", 
		"Exact Memory (Earth) [Scholar; Mental]", 
		"Well-Read (Fire) [Scholar; Mental]",
		"Nimble Bureaucrat (Air) [Scholar, Social; Interpersonal, Mental]",
		],
	disadvantages:["Bitter Marriage (Water) [Social; Interpersonal]", 
		"Know-It-All (Air) [Social; Interpersonal]", 
		"Poor Eyesight (Water) [Scholar; Physical]",
		"Scholar's Physique (Earth) [Martial; Physical]"
		],
	extratechs:3,
	techtypes:["Shuji", "Invocation", "Maho",],
	demeanor:["Detached", "Ambitious"],
},
]

