
var schools = {
	Crab:{
		hida: {
			source:'Core p57',
			name:'Hida Defender',
			clan:'Crab',
			ring1: 'Earth',
			ring2: 'Water',
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skillnumber: 5,
			skills: ['Fitness', 'Melee', 'Ranged', 'Unarmed', 'Meditation', 'Survival', 'Tactics'],
			honor: 40,
			techniquetypes: ['Kata', 'Rituals', 'Shuji'],
			role: ['Bushi'],
			startingtechs: ["Lord Hida's Grasp (Crab)"],
			startingtechoptions: ['Striking as Earth', 'Striking as Water'],
			rank1techs:["Rushing Avalanche Style","Honest Assessment",],
			rank2techs:["Touchstone of Courage","Slippery Maneuvers",],
			rank3techs:["Iron in the Mountains Style","Rallying Cry",],
			rank4techs:["Striking as Void","A Samurai's Fate",],
			rank5techs:["Rouse the Soul","The Immovable Hand of Peace",],
			chooseoptions: 1,
			ability:'Ignore the Cumbersome quality of armor you wear. Once per round, before making a check to resist a critical strike, you may reduce the severity of that critical strike by the physical resistance of your armor plus your school rank (to a minimum of 0).',
			keyword:'',
			},
		hiruma: {
			source:'Core p58',
			name:'Hiruma Scout',
			clan:'Crab',
			ring1: 'Air',
			ring2: 'Water',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Fitness','Melee', 'Ranged', 'Skulduggery','Survival','Tactics','Theology'
				],
			honor: 35,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Bushi','Shinobi'],
			startingtechs: ['Pelting Hail Style','Rushing Avalanche Style'
				],
			startingtechoptions: ['Striking as Air','Striking as Water'
				],
			rank1techs:["Threshold Barrier","Slippery Maneuvers",],rank2techs:["Skulk","Lord Hida's Grip",],rank3techs:["Deadly Sting","Touchstone of Courage",],rank4techs:["Noxious Cloud","Crashing Wave Style",],rank5techs:["Rouse the Soul","Silencing Stroke",],
			chooseoptions: 1,
			ability:'After performing an Attack action, you may change your stance. If you do, increase the TN of Attack checks by creatures of silhouette 3 or larger targeting you by your school rank until the start of your next turn.',
			keyword:'',
			},
		kaiu: {
			source:'Core p59',
			name:'Kaiu Engineer',
			clan:'Crab',
			ring1: 'Earth',
			ring2: 'Fire',
			skillnumber: 5,
			schoolskills:{Artisan:1,Social:0,Scholar:0,Martial:1,Trade:0},
			skills: ['Command','Design','Labor','Ranged','Medicine','Smithing','Theology'
				],
			honor: 40,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Bushi','Artisan'],
			startingtechs: ['Tactical Assessment','Stirring the Embers','Stonewall Tactics'
				],
			startingtechoptions: ['None'
				],
			rank1techs:["Pelting Hail Style","Hawk's Precision",],rank2techs:["Battle in the Mind","Noxious Cloud",],rank3techs:["Pillar of Calm","Flowing Water Strike",],rank4techs:["Soul Sunder","Iron in the Mountains Style",],rank5techs:["Sear the Wound","Pin the Fan",],
				chooseoptions: 0,
			ability:'Once per scene, when making a check to use an item you personally crafted, you may add a number of kept <span class="l5r">d</span> set to <span class="l5r">O</span> results equal to your school rank.',
			keyword:'',
			},
		kuni: {
			source:'Core p60',
			name:'Kuni Purifier',
			clan:'Crab',
			ring1: 'Earth',
			ring2: 'Fire',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Melee','Medicine','Sentiment','Skulduggery','Survival','Theology'
				],
			honor: 40,
			techniquetypes: ['Invocations','Kata','Rituals'
				],
			role: ['Shugenja','Bushi'],
			startingtechs: ['Armor of Earth','Jade Strike','Commune with the Spirits','Threshold Barrier'
				],
			startingtechoptions: ['Striking as Earth','Striking as Fire'
				],
			rank1techs:["Bind the Shadow","Biting Steel",],rank2techs:["Crimson Leaves Strike","Symbol of Earth",],rank3techs:["Rise, Earth","Open Hand Style",],rank4techs:["Tomb of Jade","Flowing Water Strike",],rank5techs:["Earthquake","Soul Sunder",],
			chooseoptions: 1,
			ability:'Once per round, when you make a check targeting or involving a Tainted being, you may choose a number of your kept dice up to your school rank containing <span class="l5r">T</span> symbols. Set each of these dice to a <span class="l5r">S</span> result. You cannot use this ability if you are unsure if a being is Tainted or not.',
			keyword:'',
			},
		yasuki: {
			source:'Core p61',
			name:'Yasuki Merchant',
			clan:'Crab',
			ring1: 'Air',
			ring2: 'Earth',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Commerce','Composition','Courtesy','Culture','Design','Government','Ranged'
				],
			honor: 40,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Courtier'],
			startingtechs: ['Artisan&apos;s Appraisal'
				],
			startingtechoptions: ['Rustling of Leaves','Well of Desire'
				],
			rank1techs:["Tributaries of Trade","All in Jest",],rank2techs:["Ebb and Flow","Slippery Maneuvers",],rank3techs:["Pillar of Calm","Lord Hida's Grip",],rank4techs:["Buoyant Arrival","Bravado",],rank5techs:["The Immovable Hand of Peace","Lady Doji's Decree",],
			chooseoptions: 1,
			ability:'As a downtime activity, if you have access to a market, you may acquire a number of items up to your school rank of rarity 4 or lower, or a single item of up to rarity 4 plus your school rank. You do not need to make a check or expend money to acquire these items, nor do you need to forfeit or stake honor or glory for the act of acquiring them, even if they are not befitting of your station or Forbidden (though displaying them openly later is a different matter). The GM can still apply rarity adjustments as usual based on the specifics of the market available.',
			keyword:'',
			},

		kuniwarden: {
			name:'Kuni Warden',
			clan:'Crab',
			ring1: 'Void',
			ring2: 'Fire',
			source: 'Shadowlands',
			skillnumber: 4,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Command','Melee','Unarmed','Meditation','Performance','Theology'],
			honor: 34,
			role: ['Monk'],
			techniquetypes: ['Shuji','Rituals','Kiho'],
			startingtechs: ["Truth Burns Through Lies"],
			startingtechoptions: ['Cleansing Spirit','Flame Fist','Cleansing Rite','Threshold Barrier'],
			rank1techs:["Courtier's Resolve","The Body is an Anvil"],
			rank2techs:["Crimson Leaves Strike","Coiling Serpent Style"],
			rank3techs:["Thunderclap Strike","Rallying Cry"],
			rank4techs:["Bravado","Death Touch"],
			rank5techs:["Striking as Void","Sear the Wound"],
			chooseoptions: 1,
			ability:'Suppressing Blows: When you perform an Attack action check using Martial Arts (Melee) or Martial Arts (Unarmed), you may spend <span class="l5r">O</span> as follows:<br><span class="l5r">O</span>+: One character per <span class="l5r">O</span> spent this way who is in range of the weapon you used suffers the Silenced condition.  You can spend a maximum number of <span class="l5r">O</span> this way up to your school rank.',
			keyword:'',
			},	
	yasukiyojimbo: {
			name:'Yasuki Yojimbo',
			clan:'Crab',
			ring1: 'Earth',
			ring2: 'Water',
			source: 'Courts of Stone',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Melee','Ranged','Tactics','Commerce','Courtesy','Seafaring','Survival'],
			honor: 50,
			role: ['Bushi'],
			techniquetypes: ['Shuji','Rituals','Kata'],
			startingtechs: ['Crescent Moon Style'],
			startingtechoptions: ['Honest Assessment','Well of Desire'],
			chooseoptions: 1,
			ability:"Claws of the Crab: When you successfully perform the Guard action (Core p264) you may spend <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span>+: If you succeed, you may guard one additional character in range per <span class='l5r'>O</span> spent this way.  You can spend a maximum number of <span class='l5r'>O</span> this way up to your school rank.",
			rank1techs:['Iron Forest Style','Trip the Leg'],
			rank2techs:['Touchstone of Courage','Unyielding Terms'],
			rank3techs:['All Shall Fear Me','Pillar of Calm'],
			rank4techs:['Soul Sunder',"A Samurai's Fate"],
			rank5techs:['Rouse the Soul','Striking as Void'],

			keyword:'',
			},
		},
	Crane:{

		asahina: {
			source:'Core p62',
			name:'Asahina Artificer',
			clan:'Crane',
			ring1: 'Air',
			ring2: 'Fire',
			skillnumber: 3,
			schoolskills:{Artisan:1,Social:0,Scholar:1,Martial:0,Trade:0},
			skills: ['Aesthetics','Courtesy','Culture','Design','Games','Theology'
			],
			honor: 50,
			techniquetypes: ['Invocations','Rituals','Shuji'
							],
			role: ['Shugenja','Artisan'],
			startingtechs: ['Commune with the Spirits','Cleansing Rite'
							],
			startingtechoptions: ['Blessed Wind','Armor of Radience','Inari&apos;s Blessing','Reflections of P&apos;an Ku','Token of Memory'
							],
			rank1techs:["Path to Inner Peace","Artisan's Appraisal",],rank2techs:["Grasp of the Air Dragon","Tea Ceremony",],rank3techs:["Wings of the Phoenix","Vapor of Nightmare",],rank4techs:["Rise, Air","Bend with the Storm",],rank5techs:["Ever Changing Waves","Buoyant Arrival",],
			chooseoptions: 3,
			ability:'When making a check to mystically summon an illusion or to summon, augment, or awaken an object, you may add a number of kept <span class="l5r">d</span> set to <span class="l5r">O</span> results equal to your school rank.',
			keyword:'',
			},
		daidoji: {
			source:'Core p63',
			name:'Daidoji Iron Warrior',
			clan:'Crane',
					ring1: 'Earth',
			ring2: 'Water',
			skillnumber: 5,
			skills: ['Command','Courtesy','Culture','Fitness','Government','Melee','Tactics'
				],
			honor: 55,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Bushi'],
			startingtechs: ['Iron Forest Style'
				],
			startingtechoptions: ['Striking as Earth','Striking as Water'
				],
			rank1techs:["Crescent Moon Style","Stonewall Tactics",],rank2techs:["Flowing Water Strike","Lady Doji's Decree",],rank3techs:["Crashing Wave Style","Ebb and Flow",],rank4techs:["Striking as Void","A Samurai's Fate",],rank5techs:["Rouse the Soul","The Immovable Hand of Peace",],
			chooseoptions: 1,
			ability:'Once per round, when another character within range of one of your readied melee weapons would suffer physical damage, you may intercept. If you do, you may suffer fatigue up to your school rank to reduce the damage the target suffers by twice that amount.',
			keyword:'',
			},
		doji: {
			source:'Core p64',
			name:'Doji Diplomat',
			clan:'Crane',
			ring1: 'Air',
			ring2: 'Water',
			skillnumber: 5,
			schoolskills:{Artisan:1,Social:1,Scholar:0,Martial:0,Trade:0},
			skills: ['Aesthetics','Composition','Courtesy','Culture','Design','Government','Ranged'
				],
			honor: 50,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Courtier'],
			startingtechs: ["Lady Doji's Decree (Crane)"
				],
			startingtechoptions: ['Cadence','Shallow Waters','Whispers of Court'
				],
			rank1techs:["Civility Foremost","Tea Ceremony",],rank2techs:["The Wind Blows Both Ways","Artisan's Appraisal",],rank3techs:["Regal Bearing","Ebb and Flow",],rank4techs:["Bend with the Storm","Pillar of Calm",],rank5techs:["Buoyant Arrival","The Immovable Hand of Peace",],
			chooseoptions:1,
			ability:'Once per scene when making a check to persuade or influence someone, you may add a number of kept <span class="l5r">d</span> set to <span class="l5r">O</span> results equal to your school rank.',
			keyword:'',
			},
		kakita: {
			source:'Core p65',
			name:'Kakita Duelist',
			clan:'Crane',
			ring1: 'Air',
			ring2: 'Earth',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:1,Trade:0},
			skills: ['Courtesy','Design','Fitness','Melee','Meditation','Sentiment','Smithing'
				],
			honor: 50,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Bushi','Artisan'],
			startingtechs: ['Iaijutsu Cut: Rising Blade'
				],
			startingtechoptions: ['Shallow Waters','Weight of Duty'
				],
			rank1techs:["Iaijutsu Cut: Crossing Blade","Cadence",],rank2techs:["All Arts Are One","Thunderclap Strike",],rank3techs:["A Samurai's Fate","Heartpiercing Strike",],rank4techs:["Striking as Void","Pillar of Calm",],rank5techs:["Rouse the Soul","Soul Sunder",],
			chooseoptions:1,
			ability:'Once per round, you may increase or decrease the severity of a critical strike you inflict by an amount up to your school rank.',
			keyword:'',
			},

		kakitaswordsmith: {
			name:'Kakita Swordsmith',
			clan:'Crane',
			ring1: 'Air',
			ring2: 'Fire',
			source: 'Shadowlands',
			skillnumber: 5,
			schoolskills:{Artisan:2,Social:0,Scholar:0,Martial:0,Trade:0},
			skills: ['Aesthetics','Melee','Courtesy','Culture','Sentiment','Smithing','Theology'],
			honor: 55,
			role: ['Artisan','Courtier'],
			techniquetypes: ['Kata','Rituals','Shuji'],
			startingtechs: ["Artisan's Appraisal"],
			startingtechoptions: ['Soaring Slice','Striking as Air','Striking as Fire'],
			rank1techs:["Blessing of Steel","Well of Desire"],
			rank2techs:["Ebb and Flow","Tributaries of Trade"],
			rank3techs:['All Arts Are One',"Dazzling Performance"],
			rank4techs:["Soul Sunder","Bravado"],
			rank5techs:["Buoyant Arrival","Striking as Void"],
			chooseoptions: 1,
			ability:'Kakita Pattern: You can apply this item pattern (Shadowlands p109) to any bladed weapon you craft<br>Sacred Art of Steel: Once per game session when you make a check to craft, improve or maintain a weapon, you may add a number of kept <span class="l5r">d</span> set to <span class="l5r">O</span> results equal to your school rank.',
			keyword:'',
			},		
		daidojispymaster: {
			name:'Daidoji Spymaster',
			clan:'Crane',
			ring1: 'Air',
			ring2: 'Earth',
			source: 'Courts of Stone',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Command','Courtesy','Culture','Government','Performance','Sentiment','Skulduggery'],
			honor: 35,
			role: ['Courtier','Shinobi'],
			techniquetypes: ['Kata','Rituals','Shuji'],
			startingtechs: ["Ancestry Unearthed"],
			startingtechoptions: ['Like a Ghost','Skulk','Striking as Air','Striking as Earth'],
			rank1techs:["Lady Doji's Decree","Weight of Duty"],
			rank2techs:["What's Yours is Mine","Treaty Signing"],
			rank3techs:["Hidden in Smoke","Open Hand Style"],
			rank4techs:["Cunning Distraction","Wolf's Proposal"],
			rank5techs:["Noxious Cloud","Bend with the Storm"],
			chooseoptions: 2,
			ability:'Incisive Insight: Once per scene, when making a check for a Scheme action targeting another character, you may receive a number of strife up to your school rank to reduce the TN by that amount (to a minimum of 1).',
			keyword:'',
			},	
		dojibureaucrat: {
			name:'Doji Bureaucrat',
			clan:'Crane',
			ring1: 'Earth',
			ring2: 'Water',
			source: 'Courts of Stone',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:1,Martial:0,Trade:0},
			skills: ['Command','Composition','Courtesy','Culture','Games','Government','Meditation'],
			honor: 55,
			role: ['Courtier'],
			techniquetypes: ['Rituals','Shuji'],
			startingtechs: ["Courtier's Resolve","Stonewall Tactics"],
			startingtechoptions: [],
			rank1techs:["Treaty Signing","Beware the Smallest Mouse"],
			rank2techs:["The Wind Blows Both Ways","Unyielding Terms"],
			rank3techs:["Hidden in Smoke","All Shall Fear Me"],
			rank4techs:["The Immovable Hand of Peace","Rallying Cry"],
			rank5techs:["Bend with the Storm","Formal Tea Ceremony"],
			chooseoptions: 0,
			ability:'Procedure and Protocol: When you cause a character to receive strife as a result of a check using a social approach, that character suffers additional strife equal to your school rank.',
			keyword:'',
			},	
		},
	Dragon:{
		agasha: {
			source:'Core p66',
			name:'Agasha Mystic',
			clan:'Dragon',
			ring1: 'Earth',
			ring2: 'Water',
			skillnumber: 3,
			schoolskills:{Artisan:1,Social:0,Scholar:1,Martial:0,Trade:0},
			skills: ['Fitness','Unarmed','Medicine','Meditation','Smithing','Theology'
				],
			honor: 40,
			techniquetypes: ['Invocations','Rituals','Shuji'
				],
			role: ['Shugenja'],
			startingtechs: ['Path to Inner Peace','Jurojin&apos;s Balm','Cleansing Rite','Commune with the Spirits'
				],
			startingtechoptions: ['The Fires from Within','Tetsubo of Earth'
				],
			rank1techs:["Heart of the Water Dragon","Divination",],rank2techs:["Power of the Earth Dragon","Touchstone of Courage",],rank3techs:["Rise, Earth","Earth Becomes Sky",],rank4techs:["Ever Changing Waves","Rise, Water",],rank5techs:["Sear the Wound","Earthquake",],
			chooseoptions:1,
			ability:'When performing an invocation, you may choose a different ring with which to make the check. While using this school ability, you cannot activate <span class="l5r">O</span> of the original Element of the invocation, but you can activate <span class="l5r">O</span> for the new Element. You can use this school ability a number of times per game session up to your school rank.',
			keyword:'',
			},
		kitsuki: {
			source:'Core p67',
			name:'Kitsuki Investigator',
			clan:'Dragon',
			ring1: 'Air',
			ring2: 'Earth',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:1,Martial:0,Trade:0},
			skills: ['Culture','Government','Melee','Medicine','Sentiment','Skulduggery','Survival'
				],
			honor: 45,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Courtier','Bushi'],
			startingtechs: ['Shallow Waters'
				],
			startingtechoptions: ['Striking as Air','Tactical Assessment'
				],
			rank1techs:["Slippery Maneuvers","Honest Assessment",],rank2techs:["All Arts Are One","Feigned Opening",],rank3techs:["Regal Bearing","Battle in the Mind",],rank4techs:["Sear the Wound","Bravado",],rank5techs:["Wolf's Proposal","Crashing Wave Style",],
			chooseoptions: 1,
			ability:'When performing a check to investigate with any skill (see The Art of Investigation, on page 170), you may treat your ranks in the skill you are using as being equal to your school rank. If your ranks in the skill are equal to or higher than your school rank, or if you have 5 ranks in the skill, you may add a kept <span class="l5r">d</span> set to an <span class="l5r">O</span> result instead.',
			keyword:'',
			},
		mirumoto: {
			source:'Core p68',
			name:'Mirumoto Niten Adept',
			clan:'Dragon',
			ring1: 'Earth',
			ring2: 'Fire',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:1,Trade:0},
			skills: ['Command','Composition','Fitness','Melee','Meditation','Tactics','Theology'
				],
			honor: 50,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Bushi'],
			startingtechs: ['Dazzling Performance'
				],
			startingtechoptions: ['Striking as Fire','Striking as Water','Striking as Earth'
				],
			rank1techs:["Iaijutsu Cut: Rising Blade","Stirring the Embers",],rank2techs:["Heartpiercing Strike","Slippery Maneuvers",],rank3techs:["Pillar of Calm","Commune with the Spirits",],rank4techs:["Striking as Void","Crashing Wave Style",],rank5techs:["Sear the Wound","Rouse the Soul",],
			chooseoptions: 1,
			ability:'Once per round during a duel or skirmish when you are targeted by an Attack check with a melee weapon, you may use one of your weapons readied in a one-handed grip (or one of your hands, if it is empty) to ward or trap. If you ward, the attacker must reroll dice containing <span class="l5r">S</span> or <span clasS="l5r">E</span>  up to your school rank. If you trap, reduce the TN of your next Attack check against the attacker this scene by your school rank (to a minimum of 1). You cannot choose this weapon for Attack actions until the end of your next turn.',
			keyword:'',
			},
		togashi: {
			source:'Core p69',
			name:'Togashi Tattooed Order',
			clan:'Dragon',
			ring1: 'Earth',
			ring2: 'Void',
			skillnumber: 4,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Fitness','Melee','Unarmed','Meditation','Survival','Theology'
				],
			honor: 40,
			techniquetypes: ['Kiho','Shuji','Rituals'
				],
			role: ['Monk'],
			startingtechs: ['Lord Togashi&apos;s Insight (Dragon)'
				],
			startingtechoptions: ['Earthen Fist','Earth Needs No Eyes','Flame Fist','Ki Protection','Water Fist'
				],
			rank1techs:["Way of the Earthquake","Honest Assessment",],rank2techs:["Open-Hand Style","Stirring the Embers",],rank3techs:["Death Touch","All Arts Are One",],rank4techs:["Touch the Void Dragon","Pillar of Calm",],rank5techs:["Rouse the Soul",],
			chooseoptions: 1,
			ability:'You have one mystical tattoo that empowers your kiho, and gain more as your school rank increases. When you make a check to activate a kiho linked to one of your mystical tattoos, if you succeed, add additional bonus successes equal to your school rank. Select a natural motif for your first tattoo and choose one kiho for which you meet the prerequisites that are linked to the tattoo. If you have not learned it, you learn that kiho (without paying its XP cost). You cannot choose the same kiho multiple times this way. Each time your school rank increases, you gain one additional tattoo this way.',
			keyword:'',
			},
		taoistblade: {
			name:'Mirumoto Taoist Blade',
			clan:'Dragon',
			ring1: 'Void',
			ring2: 'Water',
			source: 'Shadowlands',
			skillnumber: 4,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Labor','Melee','Unarmed','Meditation','Survival','Theology'],
			honor: 48,
			role: ['Bushi','Monk'],
			techniquetypes: ['Kata','Rituals','Kiho'],
			startingtechs: ["Water Fist"],
			startingtechoptions: ['Iaijutsu Cut: Rising Blade','Soaring Slice','Striking as Water'],
			rank1techs:["Crescent Moon Style","Ki Protection"],
			rank2techs:["Flowing Water Strike","Iaijutsu Cut: Crossing Blade"],
			rank3techs:["Crimson Leaves Strike","Still the Elements"],
			rank4techs:["Striking as Void","Crashing Wave Style"],
			rank5techs:["Touch the Void Dragon","Way of the Edgeless Sword"],
			chooseoptions: 1,
			ability:'Sharpened Ki: Your kiho that affect your unarmed attack profiles also apply to weapons you wield in a one-handed grip.  When you succeed on a check to activate a kiho that affects your unarmed attack profiles or a weapon you wield in a one handed grip, add bonus successes equal to your school rank.',
			keyword:'',
			},
	togashichronicler: {
			name:'Togashi Chronicler',
			clan:'Dragon',
			ring1: 'Earth',
			ring2: 'Water',
			source: 'Courts of Stone',
			skillnumber: 4,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:1,Trade:0},
			skills: ['Culture','Fitness','Labor','Unarmed','Meditation','Performance'],
			honor: 40,
			role: ['Courtier','Monk'],
			techniquetypes: ['Shuji','Rituals','Kata'],
			startingtechs: ['Divination'],
			startingtechoptions: ['Cleansing Spirit','Ki Protection','Honest Assessment','Truth Burns Through Lies'],
			chooseoptions:2,
			ability:"A Grain of Truth: Once per scene after you succeed on a Social skill check, you may choose a kiho with a prerequisite up to your school rank (whether you know it or not).  You gain the benefits of its Enhancement Effect (see Core p183) as if you had successfully activated it.  This effect persists until the end of the scene.",
			rank1techs:["Lord Togashi's Insight","Beware the Smallest Mouse"],
			rank2techs:["All Arts Are One","Open Hand Style"],
			rank3techs:["The Great Silence","The Ties that Bind"],
			rank4techs:["Breaking Blow","Foreseen Need"],
			rank5techs:["Death Touch","The Immovable Hand of Peace"],
			keyword:'',
			
		},
		},
	Lion:{
		akodo: {
			source:'Core p70',
			name:'Akodo Commander',
			clan:'Lion',
			ring1: 'Earth',
			ring2: 'Water',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Command','Fitness','Government','Melee','Ranged','Meditation','Tactics'
				],
			honor: 50,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Bushi'],
			startingtechs: ['Lord Akodo&apos;s Roar (Lion)'
				],
			startingtechoptions: ['Striking as Earth','Striking as Water'
				],
			rank1techs:["Iron Forest Style","Honest Assessment",],rank2techs:["Rallying Cry","Lightning Raid",],rank3techs:["A Samurai's Fate","Touchstone of Courage",],rank4techs:["Rouse the Soul","Disappearing World Style",],rank5techs:["Bend with the Storm","Striking as Void",],
			chooseoptions: 1,
			ability:'When you succeed at an Attack or Support action check, you may remove an amount of strife from yourself up to your school rank. For each strife you remove this way, add that one bonus success to the check and receive 1 fatigue.',
			keyword:'',
			},
		ikoma: {
			source:'Core p71',
			name:'Ikoma Bard',
			clan:'Lion',
			ring1: 'Fire',
			ring2: 'Water',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:1,Martial:0,Trade:0},
			skills: ['Composition','Courtesy','Culture','Ranged','Performance','Sentiment','Tactics'
				],
			honor: 45,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Courtier'],
			startingtechs: ['Warrior&apos;s Resolve','Fanning the Flames','Tributaries of Trade'
				],
			startingtechoptions: ['None'
				],
			rank1techs:["Slippery Maneuvers","Soaring Slice",],rank2techs:["Dazzling Performance","Spinning Blades Style",],rank3techs:["Rallying Cry","Regal Bearing",],rank4techs:["Sear the Wound","Pillar of Calm",],rank5techs:["Bend with the Storm","Buoyant Arrival",],
			chooseoptions:0,
			ability:'Once per scene, after you perform a check using a Social skill that targets one or more characters, you may agitate or console: If you agitate, transfer strife up to twice your school rank from yourself to your targets (divided among them as you choose). If you console, transfer strife up to twice your school rank from your targets (divided among them as you choose) to yourself.',
			keyword:'',
			},
		kitsu: {
			source:'Core p72',
			name:'Kitsu Medium',
			clan:'Lion',
			ring1: 'Void',
			ring2: 'Water',
			skillnumber: 3,
			schoolskills:{Artisan:1,Social:0,Scholar:1,Martial:0,Trade:0},
			skills: ['Courtesy','Government','Meditation','Performance','Survival','Theology'
				],
			honor: 50,
			techniquetypes: ['Invocations','Rituals','Shuji'
				],
			role: ['Shugenja'],
			startingtechs: ['Commune with the Spirits','Cleansing Rite','Ancestry Unearthed'
				],
			startingtechoptions: ['The Rushing Wave','Path to Inner Peace','Biting Steel'
				],
			rank1techs:["Courage of Seven Thunders","Heart of the Water Dragon",],rank2techs:["Hands of the Tides","Fanning the Flames",],rank3techs:["Rise, Earth","Ebb and Flow",],rank4techs:["Wrath of Kaze-no-Kami","Bravado",],rank5techs:["Sear the Wound","Buoyant Arrival",],
			chooseoptions:2,
			ability:'Once per scene, you may importune one invocation (see Importune Invocations, on page 189) with a school rank prerequisite up to your school rank without making the sacrifices usually required and without the usual TN increase.',
			keyword:'',
			},
		matsu: {
			source:'Core p73',
			name:'Matsu Berserker',
			clan:'Lion',
			ring1: 'Earth',
			ring2: 'Fire',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Command','Fitness','Labor','Melee','Ranged','Unarmed','Survival'
				],
			honor: 55,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Bushi'],
			startingtechs: ['Stirring the Embers'
				],
			startingtechoptions: ['Rushing Avalanche Style','Spinning Blades Style'
				],
			rank1techs:["Lord Akodo's Roar","Stonewall Tactics",],rank2techs:["Heartpiercing Strike","Fanning the Flames",],rank3techs:["Disappearing World Style","Rallying Cry",],rank4techs:["Striking as Void","Bravado",],rank5techs:["Sear the Wound","Rouse the Soul",],
			chooseoptions: 1,
			ability:'After you suffer a critical strike or unmask, you may suffer the Enraged condition to remove an amount of fatigue from yourself equal to your school rank.',
			keyword:'',
			},
		kitsumedic: {
			name:'Kitsu Medic',
			clan:'Lion',
			ring1: 'Earth',
			ring2: 'Water',
			source: 'Shadowlands',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Command','Fitness','Melee','Unarmed','Medicine','Sentiment','Survival'],
			honor: 44,
			role: ['Artisan','Bushi'],
			techniquetypes: ['Shuji','Rituals','Kata'],
			startingtechs: ["Stonewall Tactics"],
			startingtechoptions: ['Crescent Moon Style','Striking as Earth','Striking as Water','Cleansing Rite','Threshold Barrier'],
			rank1techs:["Commune with the Spirits","Honest Assessment"],
			rank2techs:["Flowing Water Strike","Rushing Avalanche Style"],
			rank3techs:["Iron in the Mountains Style","Touchstone of Courage"],
			rank4techs:["Crashing Wave Style","A Samurai's Fate"],
			rank5techs:["Rouse the Soul","Sear the Wound"],
			chooseoptions: 1,
			ability:'Field Medicine: When you perform a Medicine check to remove fatigue or a condition from a friendly character, that character removes additional fatigue up to your school rank',
			keyword:'',
			},
		ikomashadow: {
			name:'Ikoma Shadow',
			clan:'Lion',
			ring1: 'Air',
			ring2: 'Fire',
			source: 'Courts of Stone',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Courtesy','Culture','Government','Melee','Ranged','Skulduggery','Survival'],
			honor: 40,
			role: ['Courtier','Shinobi'],
			techniquetypes: ['Shuji','Rituals','Kata'],
			startingtechs: ["Whispers of Court","Skulk"],
			startingtechoptions: ["Hawk's Precision","Warrior's Resolve"],
			rank1techs:["What's Yours is Mine","Rustling of Leaves"],
			rank2techs:["Crackling Laughter","The Wind Blows Both Ways"],
			rank3techs:["Artful Alibi","All Arts Are One"],
			rank4techs:["Deceitful Strike","Bravado"],
			rank5techs:["Silent Elimination","Pin the Fan"],
			chooseoptions: 1,
			ability:'Victory Before Honor: Once per scene when performing a check, you may stake an amount of honor no greater than your school rank to reroll a number of dice equal to twice the amount of honor staked.  For each rerolled die result that does not contain a <span class="l5r">S</span> or <span class="l5r">E</span>, you forfeit one staked honor',
			keyword:'',
			},
		},
	Phoenix:{
		asako: {
			source:'Core p74',
			name:'Asako Loremaster',
			clan:'Phoenix',
			ring1: 'Air',
			ring2: 'Earth',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:1,Martial:0,Trade:0},
			skills: ['Culture','Government','Unarmed','Medicine','Performance','Sentiment','Theology'
				],
			honor: 45,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Courtier'],
			startingtechs: ['Civility Foremost'
				],
			startingtechoptions: ['Ancestry Unearthed','Cadence'
				],
			rank1techs:["Open Hand Style","Divination",],rank2techs:["All Arts Are One","Tea Ceremony",],rank3techs:["Pillar of Calm","Ebb and Flow",],rank4techs:["Cleansing Spirit","Wolf's Proposal",],rank5techs:["Still the Elements","Bend With The Storm",],
			chooseoptions: 1,
			ability:'When performing a Scholar skill check, you may treat your ranks in the skill as being equal to your school rank. If your ranks in that Scholar skill are equal to or higher than your school rank, or if you have 5 ranks in the skill, you may add one kept <span class="l5r">d</span> set to an <span class="l5r">O</span> result instead.',
			keyword:'',
			},
		isawa: {
			source:'Core p75',
			name:'Isawa Elementalist',
			clan:'Phoenix',
			ring1: 'Any',
			ring2: 'Any',
			skillnumber: 3,
			schoolskills:{Artisan:1,Social:0,Scholar:1,Martial:0,Trade:0},
			skills: ['Composition','Courtesy','Medicine','Meditation','Performance','Theology'
				],
			honor: 40,
			techniquetypes: ['Invocations','Rituals','Shuji'
				],
			role: ['Shugenja'],
			startingtechs: ['Commune with the Spirits','Divination'
				],
			startingtechoptions: ['Extinguish','Grasp of Earth','Path to Inner Peace','Tempest of Air'
				],
			rank1techs:["Dance of Seasons","Cleansing Rite",],rank2techs:["Fanning the Flames","Fury of Osano-Wo",],rank3techs:["Wings of the Phoenix","Strike the Tsunami",],rank4techs:["Wrath of Kaze-no-Kami","Rise, Flame",],rank5techs:["Earthquake","Rouse the Soul",],
			chooseoptions:3,
			ability:'Once per scene when making the check to activate an invocation technique, before rolling dice, you may reduce the TN of the check by your school rank.',
			keyword:'',
			},
		shiba: {
			source:'Core p76',
			name:'Shiba Guardian',
			clan:'Phoenix',
			ring1: 'Earth',
			ring2: 'Water',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Courtesy','Fitness','Melee','Meditation','Survival','Tactics','Theology'
				],
			honor: 45,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Bushi','Courtier'],
			startingtechs: ['Lord Shiba&apos;s Valor (Phoenix)'
				],
			startingtechoptions: ['Striking as Earth','Striking as Water'
				],
			rank1techs:["Civility Foremost","Stirring the Embers",],rank2techs:["Rallying Cry","Slippery Maneuvers",],rank3techs:["A Samurai's Fate","Touchstone of Courage",],rank4techs:["The Immovable Hand of Peace","Touch the Void Dragon",],rank5techs:["Way of the Edgeless Sword","Rouse the Soul",],
			chooseoptions:1,
			ability:'Once per scene, when a character at range 0-3 makes a check that contains 1 or more Strife symbols, you may negate all of those Strife symbols. Then, that character removes strife and fatigue equal to your school rank.',
			keyword:'',
			},
		kaito: {
			source:'Core p77',
			name:'Kaito Shrine Keeper',
			clan:'Phoenix',
			ring1: 'Air',
			ring2: 'Water',
			skillnumber: 4,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Fitness','Ranged','Meditation','Performance','Smithing','Theology'
				],
			honor: 45,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Monk'],
			startingtechs: ['Hawk&apos;s Precision','Tempest of Air'
				],
			startingtechoptions: ['Cleansing Rite','Commune with the Spirits','Threshold Barrier'
				],
			rank1techs:["Bind the Shadow","Striking as Air",],rank2techs:["Grasp of the Air Dragon","Divination",],rank3techs:["Breath of Wind Style","Flowing Water Strike",],rank4techs:["Rise, Air","Soul Sunder",],rank5techs:["Tomb of Jade","Pin the Fan",],
			chooseoptions:3,
			ability:'As an action, you may augment one of your arrows with a prayer to the kami. Make the check to perform one invocation you know, reducing the TN by your school rank, and record the result. The arrow gains the Sacred quality, and remains infused with the invocation until the end of the scene. After you perform an Attack action using the arrow (or fire it at a location, at the GM&apos;s discretion), you may resolve the effects of the invocation from the place the arrow landed. You may spend <span class="l5r">O</span>+ to delay resolving the effects of the invocation for 1 round per <span class="l5r">O</span> spent this way, and may spend <span class="l5r">O</span> <span class="l5r">O</span> from a failed check to affect one target of the attack that you missed.',
			keyword:'',
			},
		inquisitor: {
			name:'Asako Inquisitor',
			clan:'Phoenix',
			ring1: 'Fire',
			ring2: 'Void',
			source: 'Shadowlands',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Courtesy','Meditation','Melee','Unarmed','Performance','Theology'],
			honor: 35,
			role: ['Courtier','Shugenja'],
			techniquetypes: ['Invocations','Shuji','Rituals',],
			startingtechs: ["Cleansing Rite","Commune with the Spirits","Divination"],
			startingtechoptions: ['Cadence','Truth Burns Through Lies'],
			rank1techs:["Threshold Barrier","Weight of Duty"],
			rank2techs:["Essence of Jade","Open Hand Style"],
			rank3techs:["Regal Bearing","Touchstone of Courage"],
			rank4techs:["The Soul's Blade","Bravado"],
			rank5techs:["Striking as Void","Rouse the Soul"],
			chooseoptions: 1,
			ability:'Traces of Passage: Once per scene as a Support action, you may scry to detect any supernatural abilities used at range 0-3 in the last day (such as invocations, maho and kiho).  Reduce the TN of your checks to investigate this phenomenon by your school rank.',
			keyword:'',
			},
		shibaartist: {
			name:'Shiba Artist',
			clan:'Phoenix',
			ring1: 'Fire',
			ring2: 'Void',
			source: 'Courts of Stone',
			skillnumber: 5,
			schoolskills:{Artisan:1,Social:1,Scholar:0,Martial:0,Trade:0},
			skills: ["Aesthetics","Composition","Courtesy","Culture","Design","Performance","Smithing"],
			honor: 50,
			role: ["Artisan"],
			techniquetypes: ['Shuji','Rituals','Kata'],
			startingtechs: ["Tea Ceremony"],
			startingtechoptions: ["Assess Strengths","Cuortier's Resolve","Fun and Games"],
			chooseoptions: 2,
			ability:"Architect of Tranquility: Once per scene after you succeed at an Artisan skill check, you may choose a number of characters in the scene equal to your school rank.  Each chosen character removes 3 strife.",
			rank1techs:["Offend the Sensibilities","Fun and Games"],
			rank2techs:["The Wind Blows Both Ways","Civility Foremost"],
			rank3techs:["Formal Tea Ceremony","All Arts Are One"],
			rank4techs:["Rouse the Soul","Hidden in Smoke"],
			rank5techs:["Bend with the Storm","Buoyant Arrival"],
			keyword:'',
			
		},
		},
Scorpion:{
		bayushi: {
			source:'Core p78',
			name:'Bayushi Manipulator',
			clan:'Scorpion',
			ring1: 'Air',
			ring2: 'Fire',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:1,Trade:0},
			skills: ['Command','Courtesy','Design','Unarmed','Performance','Sentiment','Skulduggery'
				],
			honor: 35,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Courtier'],
			startingtechs: ["Lord Bayushi's Whispers (Scorpion)",
				],
			startingtechoptions: ['Cadence','Rustling of Leaves'
				],
			rank1techs:["Fanning the Flames","Weight of Duty",],rank2techs:["Dazzling Performance","Veiled Menace Style",],rank3techs:["Wolf's Proposal","Skulk",],rank4techs:["Buoyant Arrival","Deadly Sting",],rank5techs:["Bend with the Storm","Sear the Wound",],
			chooseoptions:1,
			ability:'When you exploit a target&apos;s disadvantage (see Turning Advantages and Disadvantages, page 100) as part of a Scheme action, you do not need to spend a Void point, and you may reroll additional dice up to your school rank.',
			keyword:'',
			},
		shosuro: {
			source:'Core p79',
			name:'Shosuro Infiltrator',
			clan:'Scorpion',
			ring1: 'Air',
			ring2: 'Earth',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Courtesy','Fitness','Games','Melee','Unarmed','Performance','Skulduggery'
				],
			honor: 30,
			role: ['Shinobi','Courtier'],
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			startingtechs: ['Deadly Sting'
				],
			startingtechoptions: ['Whispers of Court','Sensational Distraction'
				],
			rank1techs:["Veiled Menace Style","Skulk",],rank2techs:["Lord Bayushi's Whispers","Noxious Cloud",],rank3techs:["Bravado","Dazzling Performance",],rank4techs:["Silencing Stroke","A Samurai's Fate",],rank5techs:["Buoyant Arrival","Sear the Wound",],
			chooseoptions:1,
			ability:'While performing an Attack action against a target who is Compromised, Incapacitated, Unconscious, or unaware of your presence, treat the damage and deadliness of your weapon as being increased by your school rank.',
			keyword:'',
			},
		soshi: {
			source:'Core p80',
			name:'Soshi Illusionist',
			clan:'Scorpion',
			ring1: 'Air',
			ring2: 'Water',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:0,Trade:1},
			skills: ['Courtesy','Fitness','Games','Performance','Skulduggery','Theology'
				],
			honor: 30,
			role: ['Shugenja','Courtier','Shinobi'],
			techniquetypes: ['Invocations','Rituals','Shuji'
				],
			startingtechs: ['Commune with the Spirits','All in Jest'
				],
			startingtechoptions: ['Bo of Water','Cloak of Night','Nature&apos;s Touch','Token of Memory'
				],
			rank1techs:["Mask of Wind","Skulk",],rank2techs:["Vapor of Nightmares","Lord Bayushi's Whispers",],rank3techs:["False Realm of the Fox Spirits","Noxious Cloud",],rank4techs:["Deadly Sting ","Rise, Air",],rank5techs:["Buoyant Arrival","Silencing Stroke",],
			chooseoptions:3,
			ability:'While you are performing an invocation technique or channeling, characters with a vigilance lower than or equal to your school rank plus one cannot detect any physical sign that you are in the act of invoking the spirits. They can still observe effects of the invocation, however. Increase the TN of Theology checks to detect or study your supernatural activities by your school rank.',
			keyword:'',
			},
		yogo: {
			source:'Core p81',
			name:'Yogo Wardmaster',
			clan:'Scorpion',
			ring1: 'Earth',
			ring2: 'Water',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Composition','Fitness','Melee','Unarmed','Meditation','Theology'
				],
			honor: 40,
			role: ['Shugenja'],
			techniquetypes: ['Invocations','Rituals','Shuji'
				],
			startingtechs: ['Shallow Waters','Commune with the Spirits','Threshold Barrier'
				],
			startingtechoptions: ['Jade Strike','Grasp of Earth','The Rushing Wave'
				],
			rank1techs:["Civility Foremost","Path to Inner Peace",],rank2techs:["Ebb and Flow","Embrace of Kenro-ji-Jin",],rank3techs:["Open Hand Style","Earth Becomes Sky",],rank4techs:["Skulk","Rise, Water",],rank5techs:["Deadly Sting","Tomb of Jade",],
			chooseoptions:2,
			ability:'You can have a number of additional wards with prepared invocations (Core p190) up to your school rank. Decoding or using one of your wards requires any other character to make a Theology (Void) check with TN equal to your school rank.',
			keyword:'',
			},
		yogopreserver: {
			name:'Yogo Preserver',
			clan:'Scorpion',
			ring1: 'Fire',
			ring2: 'Void',
			source: 'Shadowlands',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Aesthetics','Courtesy','Melee','Sentiment','Skulduggery','Theology'],
			honor: 38,
			role: ['Shugenja'],
			techniquetypes: ['Invocations','Shuji','Rituals',],
			startingtechs: ["By the Light of the Lord Moon","Embrace of Kenro-Ji-Jin","Yari of Air"],
			startingtechoptions: ['Craft Shikigami','Threshold Barrier'],
			rank1techs:["Cloak of Night","Reflections of P'an Ku"],
			rank2techs:["Hands of the Tides","Skulk"],
			rank3techs:["Vapor of Nightmares","Wings of the Phoenix"],
			rank4techs:["Silencing Stroke","Suijin's Embrace"],
			rank5techs:["Ever-Changing Waves","Tomb of Jade"],
			chooseoptions: 1,
			ability:'Warded Shikigami: You can hyave a number of additional shikigami (Shadowlands p115) up to your school rank.  Once per scene, after you perform an action, you may instruct one of your shikigami to perform an action, for which it benefits from your assistance.',
			keyword:'',
			},
		bayushideathdealer: {
			name:'Bayushi Deathdealer',
			clan:'Scorpion',
			ring1: 'Air',
			ring2: 'Fire',
			source: 'Courts of Stone',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Command','Courtesy','Fitness','Melee','Ranged','Tactics','Sentiment','Skulduggery'],
			honor: 40,
			role: ['Bushi','Shinobi'],
			techniquetypes: ['Shuji','Rituals','Kata'],
			startingtechs: ['Assess Strengths'],
			startingtechoptions: ['Striking As Air','Striking as Fire'],
			chooseoptions: 1,
			ability:"Way of the Scorpion: When you exploit a target's disadvantage (see Core p100) as part of an initiative check for a duel or an Attack action, you do not need to spend a Void point and you may reroll additional dice up to your school rank.",
			rank1techs:['Deceitful Strike',"Spiteful Loss"],
			rank2techs:['Deadly Sting','Iaijutsu Cut: Rising Blade'],
			rank3techs:["Cunning Distraction","All Shall Fear Me"],
			rank4techs:["A Samurai's Fate","Rallying Cry"],
			rank5techs:["Stillness of Death","Hidden in Smoke"],

		},
		},
Unicorn:{
		ide: {
			source:'Core p82',
			name:'Ide Trader',
			clan:'Unicorn',
			ring1: 'Air',
			ring2: 'Water',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:0,Trade:1},
			skills: ['Commerce','Courtesy','Games','Labor','Ranged','Medicine','Survival'
				],
			honor: 45,
			role: ['Courtier'],
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			startingtechs: ['Tributaries of Trade'
				],
			startingtechoptions: ['Cadence','Shallow Waters'
				],
			rank1techs:["Feigned Opening","Hawk's Precision",],rank2techs:["Ebb and Flow","Lady Shinjo's Speed",],rank3techs:["Pillar of Calm","All Arts Are One",],rank4techs:["Sear the Wound","Regal Bearing",],rank5techs:["Bend with the Storm","The Immovable Hand of Peace",],
			chooseoptions:1,
			ability:'Ignore the Forbidden quality when acquiring and handling items. When acquiring, selling, or gifting an item, you may treat its rarity as reduced or increased by your school rank.',
			keyword:'',
			},
		iuchi: {
			source:'Core p83',
			name:'Iuchi Meishodo Master',
			clan:'Unicorn',
			ring1: 'Earth',
			ring2: 'Water',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:0,Trade:1},
			skills: ['Aesthetics','Design','Melee','Meditation','Survival','Theology'
				],
			honor: 40,
			role: ['Shugenja','Artisan'],
			techniquetypes: ['Invocations','Rituals','Shuji'
				],
			startingtechs: ['Commune with the Spirits'
				],
			startingtechoptions: ['Grasp of Earth','Jurojin&apos;s Balm','The Rushing Wave','Ancestry Unearthed','Well of Desire'
				],
			rank1techs:["Sympathetic Energies","Cleansing Rite",],rank2techs:["Hands of the Tides","Artisan's Appraisal",],rank3techs:["Dazzling Performance","Rise, Earth",],rank4techs:["Rouse the Soul","A Samurai's Fate",],rank5techs:["The Soul's Blade","Ever-Changing Waves",],
			chooseoptions:3,
			ability:'As a downtime activity, you may make a TN 2 Design check using any ring to bind a spirit to an inanimate vessel, creating a meishodo talisman for one invocation of that Element that you have learned. While you have the talisman in your possession, reduce the TN of checks to activate that invocation by 1. You can give the talisman to another shugenja, allowing them to perform that invocation even if they have not learned it and reducing the TN to activate it by 1, but the talisman ceases to function after a number of uses equal to your school rank. You can sustain a number of meishodo talismans up to your school rank. You can only have one meishodo talisman for any single invocation.',
			keyword:'',
			},
		moto: {
			source:'Core p84',
			name:'Moto Conqueror',
			clan:'Unicorn',
			ring1: 'Fire',
			ring2: 'Water',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Command', 'Fitness', 'Performance', 'Melee', 'Unarmed', 'Survival', 'Tactics'
				],
			honor: 35,
			role: ['Bushi'],
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			startingtechs: ['All in Jest'
				],
			startingtechoptions: ['Lightning Raid','Slippery Maneuvers'
				],
			rank1techs:["Crescent Moon Style","Stirring the Embers",],rank2techs:["Heartpiercing Strike","Veiled Menace Style",],rank3techs:["Bravado","Dazzling Performance",],rank4techs:["Striking as Void","Crashing Wave Style",],rank5techs:["Sear the Wound","Buoyant Arrival",],
			chooseoptions:1,
			ability:'When performing an Attack action during a skirmish or mass battle, you may spend <span class="l5r">O</span> as follows: <span class="l5r">O</span>:  Choose an enemy other than your target whom you can perceive. Increase the TN of that enemy&apos;s Attack checks targeting you by your school rank until the start of your next turn.',
			keyword:'',
			},
		shinjo: {
			source:'Core p85',
			name:'Shinjo Outrider',
			clan:'Unicorn',
			ring1: 'Earth',
			ring2: 'Fire',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Commerce','Melee','Ranged','Medicine','Skulduggery','Survival','Tactics'
				],
			honor: 40,
			role: ['Bushi','Courtier'],
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			startingtechs: ['Lady Shinjo&apos;s Speed (Unicorn)'
				],
			startingtechoptions: ['Striking as Fire','Striking as Water'
				],
			rank1techs:["Pelting Hail Style","Cadence",],rank2techs:["Flowing Water Strike","Dazzling Performance",],rank3techs:["Crashing Wave Style","Crimson Leaves Strike",],rank4techs:["Bend with the Storm","Bravado",],rank5techs:["Pin the Fan","Rouse the Soul",],
			chooseoptions:1,
			ability:'Once per scene, before rolling dice, you may declare that you are directing your horse (who must be present) to aid in a task and describe how its efforts help in those circumstances. Reduce the TN of the check by your school rank.',
			keyword:'',
			},
		utaku: {
			source:'Core p86',
			name:'Utaku Battle Maiden',
			clan:'Unicorn',
			ring1: 'Air',
			ring2: 'Earth',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Command','Fitness','Government','Melee','Meditation','Smithing','Survival'
				],
			honor: 50,
			role: ['Bushi'],
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			startingtechs: ['Warrior&apos;s Resolve'
				],
			startingtechoptions: ['Crescent Moon Style','Iron Forest Style'
				],
			rank1techs:["Lady Shinjo's Speed","Striking as Air",],rank2techs:["Thunderclap Strike","Rushing Avalanche Style",],rank3techs:["Pillar of Calm","Touchstone of Courage",],rank4techs:["Soul Sunder","Breath of Wind Style",],rank5techs:["Rouse the Soul","Bend With The Storm",],
			chooseoptions:1,
			ability:'When you succeed at an Attack action check, add bonus successes equal to the number of range bands you have moved this round, to a maximum of your school rank. During a duel or mass battle, if you are mounted on your steed, you always count as having moved a number of range bands equal to your school rank this turn. Utaku Steed gives skilled assistance to a mounted Battle Maiden.',
			keyword:'',
			},
		motoavenger: {
			name:'Moto Avenger',
			clan:'Unicorn',
			ring1: 'Air',
			ring2: 'Earth',
			source: 'Shadowlands',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:1,Trade:0},
			skills: ['Courtesy','Melee','Sentiment','Culture','Sentiment','Theology','Survival'],
			honor: 44,
			role: ['Shugenja'],
			techniquetypes: ['Air and Earth Invocations','Shuji','Rituals',],
			startingtechs: ["Grasp of Earth","Tempest of Air"],
			startingtechoptions: ['Ancestry Unearthed','Honest Assessment'],
			rank1techs:["Bind the Shadow","Caress of Earth"],
			rank2techs:["Essence of Jade","Touchstone of Courage"],
			rank3techs:["Earthquake","Earth Becomes Sky"],
			rank4techs:["Rise, Air","Wolf's Proposal"],
			rank5techs:["Rouse the Soul","Tomb of Jade"],
			chooseoptions: 1,
			ability:'Hands of Earth and Sky: When you perform an invocation that targets at least one other character, if you succeed, you may nourish or drain:<br>If you nourish, you may receive fatigue up to your school rank.  One target removes fatigue equal to the amount you received.<br>If you drain, you may remove an amount of fatigue from yourself up to your school rank.  One target receives fatigue equal to the amount you removed.',
			keyword:'',
			},
		},
	Mantis:{
		sailor: {
			name:'Storm Fleet Sailor',
			clan:'Mantis',
			source: 'Mantis DLC',
			ring1: 'Fire',
			ring2: 'Water',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ['Commerce','Fitness','Games','Labor','Melee','Ranged','Seafaring'
			],
			honor: 35,
			role: ['Bushi'],
			techniquetypes: ['Kata','Rituals','Shuji'],
			startingtechs: ['Pelting Hail Style'],
			startingtechoptions: ['All in Jest','Stirring the Embers'],
			rank1techs:["Skulk","Shallow Waters"],
			rank2techs:["Flowing Water Strike","Osano-Wo's Boast (Mantis)"],
			rank3techs:["Bravado","Heartpiercing Strike"],
			rank4techs:["Buoyant Arrival","Crashing Wave Style"],
			rank5techs:["Rouse the Soul","Sear the Wound"],
			chooseoptions: 1,
			ability:'Once per round when making a Trade skill check, if you are not Compromised, you may receive a number of strife up to your school rank to reroll that many rolled dice.<br>Mantis DLC',
			keyword:'Minor clan Mantis',
			},
		seer: {
			name:'Storm Fleet Tide Seer',
			clan:'Mantis',
			ring1: 'Air',
			ring2: 'Water',
			source: 'Mantis DLC',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:0,Trade:1},
			skills: ['Commerce','Fitness','Games','Labor','Melee','Seafaring','Theology'],
			honor: 40,
			role: ['Shugenja'],
			techniquetypes: ['Air & Water Invocations','Rituals','Shuji'],
			startingtechs: ['Domination of Suijin','Tempest of Air','Commune with the Spirits','Divination'],
			startingtechoptions: ['Bo of Water','Yari of Air', 'Path to Inner Peace'],
			rank1techs:["Summon Fog","Reflections of P'an Ku"],
			rank2techs:["Hand of the Tides","Call upon the Wind"],
			rank3techs:["Fury of Osano-Wo","Osano-Wo's Boast (Mantis)"],
			rank4techs:["Wrath of Kaze-no-Kami","Rise, Water"],
			rank5techs:["Ever-Changing Waves","Rise, Air"],
			chooseoptions: 1,
			ability:'When an invocation technique you perform would affect "each character" or "each other character" at a specified range, you may exclude a number of characters up to your school rank from all effects of the invocation except for spiritual backlash (Core p190).<br>Mantis DLC',
			keyword:'Minor clan Mantis',
			},
		},
	Imperial:{
		cartographer: {
			name:'Miya Cartographer',
			clan:'Imperial',
			ring1: 'Air',
			ring2: 'Earth',
			source: 'Emerald Empire p232',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:1,Martial:0,Trade:1},
			skills: ['Aesthetics','Composition','Culture','Fitness','Government','Seafaring','Survival'
			],
			honor: 50,
			role: ['Artisan','Courtier'],
			techniquetypes: ['Kata','Rituals','Shuji'
			],
			startingtechs: ['Striking as Earth','Artisans Appriasal'],
			startingtechoptions: ['Warriors Resolve','Civility Foremost'],
			rank1techs:["Slippery Maneuvers","Threshold Barrier"],
			rank2techs:["The Wind Blows Both Ways","Feigned Opening"],
			rank3techs:["Crimson Leaves Strike","All Arts Are One"],
			rank4techs:["Bend With The Storm","Regal Bearing"],
			rank5techs:["Awe of Heaven (Imperial)","Bravado"],
			chooseoptions: 1,
			ability:'You always know which way is north, and you are always able to find a landmark useful for navigation.  When making a check to recall or ascertain geographical, political, or societal information you may add a number of kept <span class="l5r">d</span> set to <span class="l5r">O</span> or <span class="l5r">S</span> results equal to your school rank.',
			keyword:'',
			},

		herald: {
			name:'Miya Herald',
			clan:'Imperial',
			ring1: 'Air',
			ring2: 'Water',
			source: 'Emerald Empire p233',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:0,Trade:1},
			skills: ['Command','Composition','Courtesy','Fitness','Seafaring','Sentiment','Survival'],
			honor: 50,
			role: ['Courtier'],
			techniquetypes: ['Kata','Rituals','Shuji'],
			startingtechs: [],
			startingtechoptions: ['Cadence','Honest Assessment','Shallow Waters','Weight of Duty'],
			rank1techs:["Feigned Opening","Courtier's Resolve"],
			rank2techs:["Ebb and Flow","Tributaries of Trade"],
			rank3techs:["Awe of Heaven (Imperial)","The Wind Blows Both Ways"],
			rank4techs:["Buoyant Arrival","Pillar of Calm"],
			rank5techs:["Sear the Wound","The Immovable Hand of Peace"],
			chooseoptions: 2,
			keyword:'',
			
			ability:'Once per round, after a character at range 0-4 succeeds on an Attack or Scheme action check, you may cause them to receive strife equal to your school rank.'},
		schemer: {
			name:'Otomo Schemer',
			clan:'Imperial',
			ring1: 'Air',
			ring2: 'Fire',
			source: 'Emerald Empire p234',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:1,Martial:0,Trade:0},
			skills: ['Command','Composition','Courtesy','Culture','Design','Government','Sentiment'],
			honor: 45,
			role: ['Courtier'],
			techniquetypes: ['Kata','Rituals','Shuji'],
			startingtechs: ['Slippery Maneuvers'],
			startingtechoptions: ['Courtiers Resolve','Stirring the Embers'],
			rank1techs:["Civility Foremost","Tea Ceremony"],
			rank2techs:["Awe of Heaven","Prey on the Weak"],
			rank3techs:["Regal Bearing","The Wind Blows Both Ways"],
			rank4techs:["Buoyant Arrival","Wolf's Proposal"],
			rank5techs:["Sear the Wound","The Immovable Hand of Peace"],
			chooseoptions: 1,
			keyword:'',
			
			ability:'You never forfeit honor or glory in order to lie or decieve for the good of the Emperor and Empire (in your opinion).  However you must forfeit twice as much honor or glory to lie for your personal gain (again, in your opinion).  When a character stakes or forfeits an amount of honor or glory in order to act against your desires, you may force them to increase that amount by your school rank.'},
		astrologer: {
			name:'Seppun Astrologer',
			clan:'Imperial',
			ring1: 'Air',
			ring2: 'Water',
			source: 'Emerald Empire p235',
			skillnumber: 3,
			schoolskills:{Artisan:1,Social:0,Scholar:1,Martial:0,Trade:0},
			skills: ['Composition','Government','Medicine','Meditation','Sentiment','Theology'],
			honor: 40,
			role: ['Shugenja','Artisan'],
			techniquetypes: ['Kata','Rituals','Shuji'],
			startingtechs: ['Bind the Shadow','Divination','Commune with the Spirits','Threshold Barrier'],
			startingtechoptions: ['Dominion of Suijin','Jade Strike'],
			rank1techs:["Heart of the Water Dragon","Ancestry Unearthed"],
			rank2techs:["Ebb and Flow","Symbol of Earth"],
			rank3techs:["False Realm of the Fox Spirits","Vapor of Nightmares"],
			rank4techs:["Tomb of Jade","A Samurai's Fate"],
			rank5techs:["Sear the Wound","The Soul's Blade"],
			chooseoptions: 1,
			keyword:'',
			
			ability:'At the beginning of a game session or as a downtime activity, you may make a TN1 Theology check using any ring.  If you succeed, choose a number of kept dice up to your school rank to reserve.   Until the end of the game session or the next downtime scene, when any character makes a skill check using the chosen ring, you may replace one or more kept dice with the same number of reserved dice of the same type.'},
		guard: {
			name:'Seppun Palace Guard',
			clan:'Imperial',
			ring1: 'Earth',
			ring2: 'Void',
			source: 'Emerald Empire p236',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:1,Trade:0},
			skills: ['Fitness','Melee','Ranged','Unarmed','Meditation','Sentiment','Tactics'],
			honor: 50,
			role: ['Bushi'],
			techniquetypes: ['Kata','Rituals','Shuji'],
			startingtechs: [],
			startingtechoptions: ['Iaijutsu Cut: Crossing Blade','Iaijutsu Cut: Rising Blade','Ancestry Unearthed','Honest Assessment'],
			rank1techs:["Crescent Moon Style","Weight of Duty"],
			rank2techs:["Crimson Leaves Strike","Touchstone of Courage"],
			rank3techs:["Iron in the Mountains Style","Threshold Barrier"],
			rank4techs:["Soul Sunder","A Samurai's Fate"],
			rank5techs:["Rouse the Soul","The Immovable Hand of Peace"],			
			chooseoptions: 2,
			keyword:'',
			
			ability:'When you succeed on an Initiative check during a skirmish or duel, add bonus successes equal to your school rank.'},
	},
	
	Other:{
		worldlyronin: {
			source:'Core p87',
			name:'Worldly Ronin',
			clan:'Other',
			ring1: 'Any',
			ring2: 'Any',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:1,Trade:0},
			skills: ['Command','Fitness','Labor','Melee','Ranged','Unarmed','Skulduggery'
				],
			honor: 30,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Bushi','Courtier'],
			startingtechs: [
				],
			startingtechoptions: ['Pelting Hail Style','Crescent Moon Style','All in Jest','Honest Assessment','Stirring the Embers','Rustling of Leaves'
				],
			rank1techs:["Open Hand Style","Shallow Waters",],rank2techs:["All Arts Are One","Iron Forest Style",],rank3techs:["A Samurai's Fate","Dazzling Performance",],rank4techs:["Striking as Void","Crimson Leaves Strike",],rank5techs:["Sear the Wound","Buoyant Arrival",],
				chooseoptions:2,
			ability:'Choose one bonus curriculum skill; this skill henceforth counts as part of the Worldly Ronin Path curriculum for you at all ranks. Each time your school rank increases, choose one additional bonus curriculum skill this way. When you make a check using one of your bonus curriculum skills, you may negate 1 Strife symbol.',
			keyword:'Unaligned',
			
			},

		fortunist: {
			name:'Fortunist Monk',
			clan:'Other',
			ring1: 'Earth',
			ring2: 'Water',
			source: 'Emerald Empire p237',
			skillnumber: 4,
			schoolskills:{Artisan:0,Social:1,Scholar:1,Martial:0,Trade:0},
			skills: ['Courtesy','Culture','Unarmed','Meditation','Survival','Theology'],
			honor: 40,
			techniquetypes: ['Kata','Rituals','Shuji'
				],
			role: ['Monk'],
			startingtechs: ['Open Hand Style','Cleansing Rite','Threshold Barrier'],
			startingtechoptions: ['Shallow Waters','Stirring the Embers'],
			rank1techs:["Crescent Moon Style","Commune with the Spirits"],
			rank2techs:["All Arts Are One","Rushing Avalanche Style"],
			rank3techs:["Regal Bearing","Ebb and Flow"],
			rank4techs:["Buoyant Arrival","Pillar of Calm"],
			rank5techs:["Rouse the Soul","Soul Sunder"],
			chooseoptions: 1,
			ability:'You have gained the goodwill of the Fortune you serve, who grants you certain Invocations.  When you make a check to use an Invocation you learned in this way, add additional bonus successes equal to your school rank.  Select a Fortune to be the primary object of your veneration and choose one appropriate Invocation (Emerald Empire p237) for which you meet the rank prerequisite.  You learn that Invocation without paying its XP cost.  Each time your school rank increases, you gain one additional invocation this way.',
			keyword:'Unaligned',
			},
		shinseist: {
			name:'Shinseist Monk',
			clan:'Other',
			ring1: 'Earth',
			ring2: 'Void',
			source: 'Emerald Empire p238',
			skillnumber: 4,
			schoolskills:{Artisan:1,Social:0,Scholar:0,Martial:1,Trade:0},
			skills: ['Aesthetics','Composition','Fitness','Unarmed','Meditation','Theology'],
			honor: 40,
			role: ['Monk'],
			techniquetypes: ['Kata','Rituals','Kiho'
				],
			startingtechs: ['Striking as Earth'],
			startingtechoptions: ['Cleansing Spirit','Earth Needs No Eyes','Ki Protection'],
			rank1techs:["Earthen Fist","Riding the Clouds"],
			rank2techs:["All Arts Are One","Cleansing Rite"],
			rank3techs:["Grasp the Earth Dragon","Way of the Willow"],
			rank4techs:["Pillar of Calm","Way of the Falling Star"],
			rank5techs:["Rouse the Soul","The Immovable Hand of Peace"],
			chooseoptions: 2,
			ability:'When you spend a Void point to Seize the Moment (Core p36) you may also treat your ranks in the skill you are using as being equal to your school rank,  If your ranks in the skill are equal to or higher than your school rank, or if you have 5 ranks in the skill, you may add one kept <span class="l5r">d</span> set to an <span class="l5r">O</span> result instead.',
			keyword:'Unaligned',
			},
		kitsune: {
			name:'Kitsune Impersonator',
			clan:'Other',
			ring1: 'Air',
			ring2: 'Fire',
			source: 'Emerald Empire p239',			
			skillnumber: 3,
			schoolskills:{Artisan:1,Social:1,Scholar:0,Martial:0,Trade:0},
			skills: ['Courtesy','Games','Performance','Unarmed','Survival','Theology'],
			honor: 30,
			role: ['Courtier','Shugenja'],
			techniquetypes: ['Invocations','Rituals','Shuji'],
			startingtechs: ['Natures Touch','Token of Memory','Commune with the Spirits'],
			startingtechoptions: [],
			rank1techs:["Fanning the Flames","All in Jest"],
			rank2techs:["Dazzling Performance","False Realm of the Fox Spirits"],
			rank3techs:["Crashing Wave Style","Regal Bearing"],
			rank4techs:["Disappearing World Style","Bravado"],
			rank5techs:["Soul Sunder","Buoyant Arrival"],
			chooseoptions: 0,
			ability:'Disadvantage: False Identity (Emerald Empire, p247).  <br>Your true form is that of a large fox with up to eight tails if you are a full-blooded kitsune, or a human with certain furry traits if you possess human ancestry as well.  As a Scheme and Support action you may transform between your human and true forms, or into another silhouette 1 or 2 natural creature at the GM discretion (you cannot mimic specific individuals).  Observers with vigilance lower than or equal to your school rank plus your ranks in Performance do not detect any flaws in your facade.  However certain key features persist across all your forms.  If you become Compromised, your disguise slips, subtly revealing your true tails, ears, feet or shadow.',
			keyword:'Minor Clan Fox',
			
		},
		toritaka: {
			name:'Toritaka Phantom Hunter',
			clan:'Other',
			ring1: 'Air',
			ring2: 'Water',
			source: 'Shadowlands',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:0,Scholar:2,Martial:0,Trade:0},
			skills: ['Culture','Government','Melee','Sentiment','Survival','Theology'],
			honor: 40,
			role: ['Shugenja'],
			techniquetypes: ['Invocations','Rituals','Shuji'],
			startingtechs: ["Cleansing Rite","Commune with the Spirits","Tea Ceremony","Courtier's Resolve"],
			startingtechoptions: ['By the Light of the Lord Moon',],
			rank1techs:["Bo of Water","Threshold Barrier"],
			rank2techs:["Essence of Jade","Striking as Air"],
			rank3techs:["Rise, Water","Crescent Moon Style"],
			rank4techs:["Rouse the Soul","Soul Sunder"],
			rank5techs:["Flowing Water Cut","Wrath of Kaze-no-Kami"],
			chooseoptions: 1,
			ability:'Eyes of Yotogi: Otherworldly beings treat your vigilance as being increased by your school rank.  When you make a check to search for Otherworldly beings, or make an Initiative check in a conflict against them, if you succeed, add bonus successes equal to your school rank.',
			keyword:'Minor Clan Falcon Ghost',
			
		},
		ksaboteur: {
			name:'Kolat Saboteur',
			clan:'Other',
			ring1: 'Air',
			ring2: 'Water',
			source: 'Emerald Empire p240',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:1,Trade:0},
			skills: ['Commerce','Fitness','Melee','Ranged','Medicine','Meditation','Skulduggery'],
			honor: 20,
			role: ['Shinobi'],
			techniquetypes: ['Kata','Shuji'],
			startingtechs: ['Veiled Menace Style','Skulk','Cadence'],
			startingtechoptions: [],
			rank1techs:["Deadly Sting","Shallow Waters"],
			rank2techs:["Noxious Clouds","Tributaries of Trade"],
			rank3techs:["Ebb and Flow","Spin the Web (Kolat)"],
			rank4techs:["Silencing Stroke","Wolf's Proposal"],
			rank5techs:["Buoyant Arrival"],
			chooseoptions: 0,
			ability:'Once per game session at the beginning of a scene, you may reveal that an NPC in that scene is the target of your current assignment.  The GM then decides what your assignment entails, such as sabotaging the targets current activities, framing them for a crime, killing them, or even making sure they survive to play their part in a long and sinister plot.  Until the end of the session, when you make a skill check targeting the chosen NPC, you may reroll a number of dice up to your school rank',
			keyword:'Unaligned',
		
			},
		tortoise:{
			name:'Kasuga Smuggler',
			source: 'Dark Tides Adventure',
			clan:'Other',
			ring1: 'Air',
			ring2: 'Water',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:1,Scholar:0,Martial:0,Trade:1},
			role: ['Bushi'],
			skills: ['Commerce','Culture','Courtesy','Melee','Seafaring','Skulduggery'],
			honor: 29,
			techniquetypes: ['Kata','Rituals','Shuji'],
			startingtechs: ['Rushing Avalanche Style'],
			startingtechoptions: ['Honest Assessment','Well of Desire'],
			rank1techs:[],
			rank2techs:[],
			rank3techs:[],
			rank4techs:[],
			rank5techs:[],
			chooseoptions: 1,
			ability:'You never need to stake glory to publicly use a Trade skill, so long as you are doing so as part of your duty to your clan.  Once per scene, you may add a number of kept <span class="l5r">d</span> set to <span class="l5r">O</span> results equal to your school rank to a check to interact with one or more gaijin, peasants, merchants, burakumin, or any other character with status of 20 or lower.',
			keyword:'Minor clan Tortoise',
			
		},
		mercenaryninja: {
			name:'Mercenary Ninja',
			clan:'Other',
			ring1: 'Air',
			ring2: 'Any',
			source: 'Courts of Stone',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ["Fitness","Melee","Ranged","Unarmed","Medicine","Skulduggery","Survival"],
			honor: 20,
			role: ["Shinobi"],
			techniquetypes: ['Ninjitsu','Rituals','Kata'],
			startingtechs: ["Skulk"],
			startingtechoptions: ["Cadence","Shallow Waters"],
			chooseoptions: 1,
			rank1techs:["Beware the Smallest Mouse","Like a Ghost"],
			rank2techs:["Silent Elimination","Veiled Menace Style"],
			rank3techs:["Feigned Opening","Slicing Wind Kick"],
			rank4techs:["Hidden in Smoke","Breath of Wind Style"],
			rank5techs:["Foreseen Need","Striking as Void"],
			ability:"Disciple of Darkness: When you perform a check to hide, move stealthily, or deceive others as to your true identity, you may suffer a number of strife up to your school rank to choose that many characters targeted by the check.  Treat each chosen character's vigilance as 1 lower while resolving the check.",
			keyword:'Unaligned',
			
		},
		shikamatchmaker: {
			name:'Shika Matchmaker',
			clan:'Other',
			ring1: 'Air',
			ring2: 'Water',
			source: 'Courts of Stone',
			skillnumber: 3,
			schoolskills:{Artisan:0,Social:1,Scholar:1,Martial:0,Trade:0},
			skills: ["Composition","Courtesy","Culture","Meditation","Sentiment","Theology"],
			honor: 50,
			role: ["Courtier","Shugenja"],
			techniquetypes: ['Shuji','Rituals','Air & Water Invocations'],
			startingtechs: ["The Ties that Bind","Yari of Air"],
			startingtechoptions: ["Blessed Wind","Path to Inner Peace","Sympathetic Energies","Tempest of Air"],
			chooseoptions: 2,
			ability:"Gift of Musubi-no-Kami: You may perform the 'Ties that Bind' ritual as an action, instead of as a downtime activity.  When you make a check to perform this ritual, you may add kept <span class='l5r'>d</span> set to <span class='l5r'>O</span> results equal to your school rank.",
			rank1techs:["Ancestry Unearthed","Fun and Games"],
			rank2techs:["Strike the Tsunami","Civility Foremost"],
			rank3techs:["Rise, Air","The Wind Blows Both Ways"],
			rank4techs:["Wrath of Kaze-no-Kami","Treaty Signing"],
			rank5techs:["Buoyant Arrival","Formal Tea Ceremony"],
			keyword:'Minor clan Deer',
			
		},
		skikaspeardancer: {
			name:'Shika Speardancer',
			clan:'Other',
			ring1: 'Air',
			ring2: 'Fire',
			source: 'Courts of Stone',
			skillnumber: 5,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:1,Trade:1},
			skills: ["Melee","Meditation","Skulduggery","Survival","Fitness","Sentiment","Courtesy"],
			honor: 35,
			role: ['Bushi','Shinobi'],
			techniquetypes: ['Shuji','Rituals','Kata'],
			startingtechs: ['Trip the Leg'],
			startingtechoptions: ['Striking as Air',"Striking as Fire"],
			chooseoptions: 1,
			ability:"Typhoon in the Bamboo Grove: When making a Martial Arts (Melee) or Fitness check, you may spend <span class='l5r'>O</span> <span class='l5r'>O</span> to cause a number of characters no greater than your school rank and within range of your readied weapon to suffer the Dazed condition.",
			rank1techs:['Like a Ghost','Soaring Slice'],
			rank2techs:['To Float or Sink','Crescent Moon Style'],
			rank3techs:['Slicing Wind Kick','Pole Vault'],
			rank4techs:['Rouse the Soul','Disappearing World Style'],
			rank5techs:['Silent Elimination','The Ties That Bind'],
			keyword:'Minor clan Deer',
			

		},
	},};

var titles = {

	advisor:{
		title:"Advisor",
		status:"+10 Status (to a minimum of 40",
		xp:36,
		ability:" Title Ability: Skilled Attendant: When you provide assistance on a Scholar skill check, the character you are assisting may also roll <span class='l5r'>D</span> equal to your ranks in that skill instead of rolling D equal to their own ranks in that skill.",
		advance:["Scholar Skills","Commerce","Courtesy","Design","<span class='l5r'>b</span> Fanning the Flames (Core 218) Fire Shuji Rank 2","<span class='l5r'>b</span> Feigned Opening (Core 214) Air Shuji Rank 2", "<span class='l5r'>b</span> Stonewall Tactics (Core 216) Earth Shuji Rank 1"],
		source:"Emerald Empire p249",
	},

	"clan magistrate":{
		title:"Clan Magistrate",
		status:"+10 Status (to a minimum of 45)",
		xp: 30,
		ability:" Title Ability: Justice of the Champion: When you make a Command or Courtesy check targeting a member of your clan, you may spend O as follows:<br>O+: The target receives or removes (your choice) strife equal to O spent this way.",
		advance:["Scholar Skills","Social Skills","Fitness","Martial Arts: Melee", "<span class='l5r'>b</span> Coiling Serpent Style (Core 179) Any Kata Rank 2","<span class='l5r'>b</span> Prey on the Weak (Core 215) Air Shuji Rank 2","<span class='l5r'>b</span> Truth Burns Through Lies (Core 219) Fire Shuji Rank 1"],
		source:"Emerald Empire p249",
	},

	daimyo:{
		title:"Daimyo",
		status:"+20 Status (to a minimum of 55)",
		xp: 36,
		ability:" Title Ability: Voice of Authority: Reduce the TN of Command checks you make targeting your vassals by 1.",
		source:"Emerald Empire p250",
		advance:["Social Skills","Culture","Government","Tactics","<span class='l5r'>b</span> Courtier's Resolve (Core 222) Void Shuji Rank 1","<span class='l5r'>b</span> Shallow Waters (Core 220) Water Shuji Rank 1","<span class='l5r'>b</span> Stirring the Embers (Core 219) Fire Shuji Rank 1"],
	},

	gunso:{
		title:"Gunso",
		status:"+5 Status (to a minimum of 20)",
		xp:24,
		ability:" Title Ability: Lead from the Front: When you defeat an opponent in a clash, your cohort removes panic equal to the opponent's glory rank.  Once per round when you succeed at an Attack action check during a mass battle, your cohort removes panic equal to half of the attrition you inflict.",
		source:"Emerald Empire p250",
		advance:["Martial Skills","Command","Government","Rank 1-4 Kata","<span class='l5r'>b</span> Rallying Cry (Core 219) Fire Shuji Rank 3","Stirring the Embers (Core 219) Fire Shuji Rank 1","Touchstone of Courage (Core 217) Earth Shuji Rank 3"],
	},

	"monastic acolyte":{
		title:"Monastic Acolyte",
		status:"Your status becomes 25",
		xp:24,
		ability:" Title Ability: Enlightened: When you are selected as a target of an action requiring a skill check, you may spend a Void point to increase or decrease the TN of the check by an amount up to your ranks in Meditation (to a minimum of 1)",
		source:"Emerald Empire p251",
		advance:["Martial Skills","Scholar Skills","Aesthetics","Composition","<span class='l5r'>b</span> Cleansing Spirit","<span class='l5r'>b</span> Ki Protection","<span class='l5r'>b</span> Still the Elements"],
	},

	priest:{
		title:"Priest",
		status:"+10 Status (to a minimum of 40)",
		xp:24,
		ability:" Title Ability: Servant of the Kami: You may importune invocations even if you do not know any invocations.  When you importune an invocation, do not increase the TN by 1 (although you still increase the TN if the rank of the invocation is higher than your school rank",
		advance:["Social Skills","Composition","Culture","Theology","<span class='l5r'>b</span> Rank 1-5 Rituals","<span class='l5r'>b</span> Civility Foremost","<span class='l5r'>b</span> Rouse the Soul"],
		source:"Emerald Empire p251",
	},

	spy:{
		title:"Spy",
		status:"-5 Status ",
		xp:24,
		ability:" Title Ability: Ears Everywhere: Once per game session as a Scheme and Support action or as a downtime activity targeting a particular location or social group, you may gather and sift through the current rumors for credible intelligence by making a TN 4 Sentiment (Air) check.  If you succeed, you discover the latest happenings relevant to your current location or social group, as well as which current rumors are false.  If discerning someone's qualities is your social objective in an intrigue scene, you score momentum points equal to your Air Ring plus your bonus successes.<br>O: You plant a rumor that spreads among the characters in the scene or the targeted group (although they don't necessarily believe it)",
		advance:["Social Skills","Government","Sentiment","Skulduggery","<span class='l5r'>b</span> Rank 1-5 Air Shuji","<span class='l5r'>b</span> Shallow Waters","<span class='l5r'>b</span> Skulk"],
		source:"Emerald Empire p252",
	},

	yojimbo:{
		title:"Yojimbo",
		status:"+10 Status (to a minimum of 40)",
		xp: 36,
		ability:" Title Ability: No Sacrifice Too Great: One character is assigned as your charge; this character can order you to treat someone else as your charge instead until they lift this order.  If your charge is at range 0-2, you may spend 1 Void point to replace your charge as the target of an Attack action.  If you suffer a critical strike as a result of this Attack action, gain 1 Void point.",
		advance:["Martial Skills","Government","Medicine","Sentiment","<span class='l5r'>b</span> Iaijutsu Cut: Crossing Blade","<span class='l5r'>b</span> Iaijutsu Cut: Rising Blade","<span class='l5r'>b</span> Warrior's Resolve"],
		source:"Emerald Empire p252",
	},

	yoriki:{
		title:"Yoriki",
		status:"+5 Status (to a minimum of 35)",
		xp:24,
		ability:" Title Ability: Take Them Alive: When you make an Attack action using a weapon with the Snaring quality.  You may alter any number of kept dice containing <span class='l5r'>S</span> or <span class='l5r'>E</span> to results set to <span class='l5r'>O</span>",
		advance:["Social Skills","Government","Martial Arts: Melee","Skulduggery","<span class='l5r'>b</span> Rank 1-3 Kata","F<span class='l5r'>b</span> anning the Flames","<span class='l5r'>b</span> Shallow Waters"],
		source:"Emerald Empire p253",
	},

	"emerald magistrate":{
		title:"Emerald Magistrate",
		status:"+15 Status to a maximum of 40",
		xp:30,
		ability:" Title Ability: Voice of Authority: Once per game session when making a Scheme or Support action check using a Social skill, you may choose additional targets equal to your Glory rank. You cannot choose any additional target with vigilance higher than the highest among your initial targets.",
		advance:["Trade Skills","Fitness","Martial Arts (choose one)","Performance","<span class='l5r'>b</span> Rank 1-2 Kata","<span class='l5r'>b</span> Open Hand Style","<span class='l5r'>b</span> Shallow Waters"],
		source:"Core p305",
	},

	damned:{
		title:"The Damned",
		status:"-20 Status (to a minimum of 30)",
		xp:20,
		ability:" Prerequisite: Must possess at least one Shadowlands Taint disadvantage to receive this title.<br>Immediate Effect: Gain the Ferocity disadvantage.<br>Title Ability: Tainted Warrior: Increase the TN of all your non-Command Social skill checks by 1, and reduce the TN of all your Martial Arts (Any) skill checks targeting Tainted beings by 1 (to a minimum of 1).  Non-Tainted beings receive 1 strife whenever they make a Social skill check targeting you.",
		advance:["Martial Skills","Medicine","Survival","Theology","<span class='l5r'>b</span> Rank 1-2 Kata","<span class='l5r'>b</span> Heartpiercing Strike","<span class='l5r'>b</span> Rallying Cry"],
		source:"Shadowlands",
	},

	harvester:{
		title:"Harvester",
		status:"+10 Status (to a minimum of 45)",
		xp:20,
		ability:"Title Ability: Capture Evil: Reduce the TN of your Survival checks to track down a Tainted being by 1.  When you inflict a critical strike on a Tainted being, you may spend <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span> <span class='l5r'>O</span>: The target suffers the Dazed, Disoriented or Immobilized condition.",
		advance:["Martial Skills","Smithing","Survival","Theology","<span class='l5r'>b</span> Rank 1-2 Kata","<span class='l5r'>b</span> Rank 1-2 Rituals","<span class='l5r'>b</span> Skulk"],
		source:"Shadowlands",
	},

	twentygoblin:{
		title:"Twenty-Goblin Crab",
		status:"+15 Status (to a minimum of 30 and a maximum of 40), officially become samurai and member of the Crab Clan",
		xp:20,
		ability:"Title Ability: Goblin Killer: When making a Martial Arts (Any) check targeting a goblin, you may spend <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span>+: Each goblin at range 0-2 of your target receives 1 strife per <span class='l5r'>O</span> that you spend this way.",
		advance:["Martial Skills","Social Skills","Culture","Government","<span class='l5r'>b</span> Rank 1-2 Kata","<span class='l5r'>b</span> Thunderclap Strike","<span class='l5r'>b</span> Stonewall Tactics"],
		source:"Shadowlands",
	},

	witchhunter:{
		title:"Witch Hunter",
		status:"+10 Status (to a minimum of 30)",
		xp:45,
		ability:"Title Ability: Bane of Sorcerers: When you make a check to resist the effects of a maho technique, you may spend <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span>: Reduce the TN of your next check targeting tbe maho practitioner who performed it by 1 per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: If you succeed on the check to resist, the maho practitioner receives strife equal to your ranks in Theology.",
		advance:["Martial Skills","Scholar Skills","Command","Skulduggery","<span class='l5r'>b</span> Rank 1-4 Kata","<span class='l5r'>b</span> Rank 1-5 Rituals","<span class='l5r'>b</span> Honest Assessment"],
		source:"Shadowlands",
	},

	castellan:{
		title:"Castellan",
		status:"+5 Status (to a maximum of 30), and Glory +10 (to a maximum of 60)",
		xp:20,
		ability:"Title Ability: Every Stone Has Its Place: When undertaking a downtime activity to prepare your castle for an important event (a wedding, a battle, or a Winter Court for example), you may change all rolled blank results to <span class='l5r'>O</span> results.",
		advance:["Social Skills","Culture","Design","Govenment","<span class='l5r'>b</span> Rallying Cry","<span class='l5r'>b</span> Slippery Maneuvers","<span class='l5r'>b</span> Touchstone of Courage"],
		source:"Courts of Stone",
	},

	covertagent:{
		title:"Covert Agent",
		status:"-10 Honor (to a minimum of 25)",
		xp:20,
		ability:"Immediate Effects: Gain the Dark Secret disadvantage.<br>Title Ability: Practiced Prevaricator: When you make a check to decieve or hide from someone, you may negate up to 2 strife symbols.",
		advance:["Social Skills","Meditation","<span class='l5r'>b</span> Artful Alibi","<span class='l5r'>b</span> Cadence","<span class='l5r'>b</span> Cunning Distraction","<span class='l5r'>b</span> To Float Or Sink","<span class='l5r'>b</span> What's Yours Is Mine"		],
		source:"Courts of Stone",
	},
	dreadenforcer:{
		title:"Dread Enforcer",
		status:"-10 Honor (to a minimum of 5), Glory -20 (to a minimum of 15)",
		xp:40,
		ability:"Immediate Effects: Gain the Whispers of Cruelty disadvantage.<br>Title Ability: Merciless Eyes: Whem making a check to plan an assassination or attack with lethal intent, you may negate up to 2 strife symbols.",
		advance:["Martial Skills","Medicine","Skulduggery","<span class='l5r'>b</span> Deceitful Strike","<span class='l5r'>b</span> Like a Ghost","<span class='l5r'>b</span> Silent Elimination","<span class='l5r'>b</span> The Stillness of Death"],
		source:"Courts of Stone",
	},
	esteemednegotiator:{
		title:"Esteemed Negotiator",
		status:"+10 Glory",
		xp:34,
		ability:"Title Ability: Calming Words: Once per scene, as a Scheme and Support action, you may reduce the strife of all characters in the scene by your ranks in Sentiment.",
		advance:["Social Skills","Culture","Government","Sentiment","<span class='l5r'>b</span> Rank 1-3 Earth Shuji","<span class='l5r'>b</span> The Ties that Bind","<span class='l5r'>b</span> Treaty Signing"],
		source:"Courts of Stone",
	},
	kenshinzen:{
		title:"Kenshinzen",
		status:"+20 Glory (to a maximum of 75)",
		xp:24,
		ability:"Title Ability: A Single Moment: When you perform an Attack action that uses a sheathed Razor-Edged weapon, you may spend <span class='l5r'>O</span> as follows:<br>Void <span class='l5r'>O</span> <span class='l5r'>O</span>: Your target cannot defend against the damage from this Attack action unless they spend a Void point.<br>Any <span class='l5r'>O</span>: After you perform this action, you may sheathe the weapon you used.",
		advance:["Martial Skills","Social Skills","Culture","Sentiment","<span class='l5r'>b</span> Rank 1-5 Close Combat Kata","<span class='l5r'>b</span> Rank 1-5 Void Shuji","<span class='l5r'>b</span> Tea Ceremony"],
		source:"Courts of Stone",
	},
	kyudenasakoshieldbearer:{
		title:"Kyuden Asako Shieldbearer",
		status:"+5 Glory (to a maximum of 55)",
		xp:40,
		ability:"Title Ability: Time-Tested Defense: After an Attack action targeting you fails, the attacker suffers strife equal to their shortfall.",
		advance:["Scholar Skills","Martial Skills [Melee]","Martial Skills [Ranged]","Meditation","Tactics","<span class='l5r'>b</span> Rank 1-3 Kata","<span class='l5r'>b</span> Cleansing Rite"],
		source:"Courts of Stone",
	},

	masterartisan:{
		title:"Master Artisan",
		status:"+30 Glory (to a maximum of 80)",
		xp:60,
		ability:"Title Ability: Inspired Creations: When crafting an item, you may spend <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span> <span class='l5r'>O</span> <span class='l5r'>O</span>: The item you create is a singular masterwork.  You must give it a name befitting its status.  Once per game session when making a check that uses the item, a character may add 1 <span class='l5r'>d</span> set to any result of their choice.",
		advance:["Artisan Skills","Courtesy","Culture","Medicine","Meditation","<span class='l5r'>b</span> All Arts Are One","<span class='l5r'>b</span> Formal Tea Ceremony"],
		source:"Courts of Stone",
	},
	wintercourtchampion:{
		title:"Winter Court Champion",
		status:"+20 Glory (to a maximum of 75)",
		xp:16,
		ability:"Title Ability: Accustomed to Attention: When making a check to boast or get people's attention, you may negate up to 2 strife symbols.",
		advance:["Artisan Skills","Social Skills","<span class='l5r'>b</span> Artisan's Appraisal","<span class='l5r'>b</span> Formal Tea Ceremony","<span class='l5r'>b</span> Fun and Games","<span class='l5r'>b</span> Offend the Sensibilities","<span class='l5r'>b</span> Spiteful Loss"],
		source:"Courts of Stone",
	},
	sevenfoldpalaceacolyte:{
		title:"Seven Fold Palace Acolyte",
		status:"+5 Glory (to a maximum of 35)",
		xp:36,
		ability:"Title Ability: First, Forge Yourself: When you make a check to craft an item, you may suffer a number of fatigue up to your ranks in Fitness.  If you do, change that many results containing <span class='l5r'>S</span> to <span class='l5r'>O</span> results",
		advance:["Trade Skills","Aesthetics","Design","Fitness","Meditation","Smithing","<span class='l5r'>b</span> Artisan's Appraisal"],
		source:"Courts of Stone",
	},




}


/*
	witchhunter:{
		title:"",
		status:"",
		xp:,
		ability:"Title Ability: ",
		advance:["Martial Skills","Scholar Skills","Command","Skulduggery","<span class='l5r'>b</span> Rank 1-4 Kata","<span class='l5r'>b</span> Rank 1-5 Rituals","<span class='l5r'>b</span> Honest Assessment"],
		source:"Courts of Stone",
	},

	bayushideathdealer: {
			name:'',
			clan:'',
			ring1: '',
			ring2: '',
			source: 'Courts of Stone',
			skillnumber: ,
			schoolskills:{Artisan:0,Social:0,Scholar:0,Martial:0,Trade:0},
			skills: [],
			honor: 40,
			role: [],
			techniquetypes: ['Shuji','Rituals','Kata'],
			startingtechs: [],
			startingtechoptions: [],
			chooseoptions: ,
			ability:,
			rank1techs:[],
			rank2techs:[],
			rank3techs:[],
			rank4techs:[],
			rank5techs:[],

		},

<span class='l5r'>O</span>
<span class='l5r'>b</span>
*/