
var tabledata = [{
title:"Range Bands", 
ref:"RangeBands",
children:[
	{range:"RANGE", distance:"DISTANCE", description:"DESCRIPTION"}, 
	{range:"Range 0 ", distance:"Touch (1-2 feet)", description:"At this range, two foes can grapple and use small weapons such as knives, but longer weapons are hard to wield effectively. Objects at range 0 might be at the person's feet, or even on their person, and a character can interact with them."}, 
	{range:"Range 1 ", distance:"Sword (1-2 yards)", description:"The optimal range for fighting with a sword. A character can generally interact with people and objects at range 1. Most skills that have a manual aspect require the target or object to be at range 0-1."}, 
	{range:"Range 2", distance:"Spear (3-4 yards)", description:"The range at which polearms such as spears and naginata have the greatest advantage."}, 
	{range:"Range 3", distance:"Throw (5-10 yards) ", description:"The range at which thrown missile weapons are most effective."}, 
	{range:"Range 4 ", distance:"Bow (11-100 yards)", description:"The midrange for missile weapons like bows. Generally speaking, this range coincides with the edge of earshot for most characters."}, 
	{range:"Range 5", distance:"Volley (100+ yards)", description:"The distance to the outer edge of the range at which missile weapons are accurate. This is the farthest most characters can see any details."}, 
	{range:"Range 6", distance:"Sight (more than a few hundred yards)", description:"Range 6 represents the maximum distance at which one can interact with a human-sized target (albeit minimally). To travel beyond range 6 of their current location, a character must generally travel in narrative time or downtime."},
	]},
	{
title:"Silhouettes",
ref:"Silhouettes",
children:[
	{silhouette:"SILHOUETTE", example:"EXAMPLE"}, 
	{silhouette:"0", example:"Handheld objects, cats, small dogs"}, 
	{silhouette:"1", example:"Children, large dogs, goblins"} ,
	{silhouette:"2", example:"Adult humans, ningyo, tengu"} ,
	{silhouette:"3", example:"Horses, naga, rakshasa, trolls"}, 
	{silhouette:"4", example:"Ogres, elephants"} ,
	{silhouette:"5", example:"Dragons"},
	]},
	{
title:"Critical Strikes",
ref:"CriticalStrikes",
children:[
	{Severity:"SEVERITY", Description:"DESCRIPTION", Mechanical:"MECHANICAL"}, 
	{Severity:"0-2", Description:"Close Call: The hit slices the character's hair or clothes but fails to draw blood.", Mechanical:"If the character is wearing armor, the armor gains the Damaged quality (Core p240)."}, 
	{Severity:"3-4", Description:"Flesh Wound: The hit sinks into the character's flesh, slicing shallowly or creating a vicious contusion.", Mechanical:"The character suffers the Lightly Wounded condition for the ring they used for their check to resist. If the attack had the Razor-Edged quality, the character also suffers the Bleeding condition."}, 
	{Severity:"5-6", Description:"Debilitating Gash: The hit is agonizing, cutting a deep furrow in the flesh or splitting muscle and fracturing bone. The character will likely need time to recover fully.", Mechanical:"The character suffers the Severely Wounded condition for the ring they used they used for their check to resist. If the attack had the Razor-Edged quality, the character also suffers the Bleeding condition."}, 
	{Severity:"7-8", Description:"Permanent Injury: The strike leaves the character permanently injured, bearing a scar that will impact them the rest of their life", Mechanical:"The character suffers the Bleeding condition, then chooses one scar of the following disadvantages for the ring they used for their check to resist: Air (Maimed Visage or Nerve Damage), Earth (Damaged Organ or Fractured Spine), Fire (Lost Fingers or Maimed Arm), Water (Lost Eye or Lost Foot), Void (Lost Memories)."}, 
	{Severity:"9-11", Description:"Maiming Blow: The character is gravely hurt by the strike and might never fully recover from it.", Mechanical:"The character suffers the Bleeding condition, then chooses one of the following scar disadvantages for the ring they used for their check to resist: Air (Deafness or Muteness), Earth (Damaged Heart or Damaged Organ), Fire (Lost Arm or Lost Hand), Water (Blindness or Lost Leg), Void (Cognitive Lapses)"}, 
	{Severity:"12-13", Description:"Agonizing Death: The blow is mortal, and the character knows it.", Mechanical:"The character suffers the Severely Wounded condition for the ring they used for their check to resist, as well as the Bleeding and Dying (3 rounds) conditions."}, 
	{Severity:"14-15", Description:"Swift Death: The character lives just long enough to realize their demise.", Mechanical:"The character suffers the Severely Wounded condition for the ring they used for their check to resist, as well as the Bleeding and Dying (1 round) conditions."}, 
	{Severity:"16+", Description:"Instant Death: The character dies without even a last word.", Mechanical:"The character dies immediately."}
	]},

	{
title:"Skills and Approaches",
ref:"SkillsandApproaches",
children:[
	{"Skill Group":"SKILL GROUP", Skill:"SKILL", Approach:"APPROACH"},
	{"Skill Group":"To craft a piece of art (Artisan Skill Group)",
	Skill:"Artisan skills (choose one)<br><span class='l5r'>b</span> Nonutilitarian art (Aesthetics)<br><span class='l5r'>b</span> Literature and poetry (Composition)<br><span class='l5r'>b</span> Finery and worn art (Design)<br><span class='l5r'>b</span> Armor and weapons (Smithing)",
	Approach:"Artisan approaches (choose one)<br><span class='l5r'>b</span> Restore a damaged piece through upkeep (Earth)<br><span class='l5r'>b</span> Adapt an existing piece into something else (Water)<br><span class='l5r'>b</span> Invent a new piece from raw materials (Fire)<br><span class='l5r'>b</span> Refine an existing piece to make it function better (Air)<br><span class='l5r'>b</span> Attune yourself to a piece of art (Void)"},
	{"Skill Group":"To influence a person (Social Skill Group)",
	Skill:"Social skills (choose one)<br><span class='l5r'>b</span> How to assert authority over others, especially of lower status (Command)<br><span class='l5r'>b</span> How to appeal formally to others, especially of higher status (Courtesy)<br><span class='l5r'>b</span> How to discuss and play games to socialize (Games)<br><span class='l5r'>b</span> How to communicate with and influence an audience (Performance)",
	Approach:"Social approaches (choose one)<br><span class='l5r'>b</span> Reason with them to act based on logic and duty (Earth)<br><span class='l5r'>b</span> Charm them to develop positive feelings toward you (Water)<br><span class='l5r'>b</span> Incite them to act on their emotions and desires (Fire)<br><span class='l5r'>b</span> Trick them into believing something you want them to believe (Air)<br><span class='l5r'>b</span> Enlighten them to understand a fundamental truth (Void)"},
	{"Skill Group":"To know or learn a piece of information (Scholar Skill Group",
	Skill:"Scholar skills (choose one)<br><span class='l5r'>b</span> Current events, historical trends, and etiquette (Culture)<br><span class='l5r'>b</span> Law, bureaucracy, posts, and positions (Government)<br><span class='l5r'>b</span> Health, injury, and disease (Medicine)<br><span class='l5r'>b</span> Psychology, emotions, and motivations (Sentiment)<br><span class='l5r'>b</span> The spiritual realms, mystical beings and phenomena, and religious rites (Theology)",
	Approach:"Scholar approaches (choose one)<br><span class='l5r'>b</span> Recall it from memory (Earth)<br><span class='l5r'>b</span> Survey the surroundings for clues about it (Water)<br><span class='l5r'>b</span> Theorize possibilities of its nature (Fire)<br><span class='l5r'>b</span> Analyze a specific thing for details about it (Air)<br><span class='l5r'>b</span> Sense it with your instincts or a hunch (Void)"},
	{"Skill Group":"To overcome an opponent or challenge with force (Martial Skill Group)",
	Skill:"Martial skills (choose one)<br><span class='l5r'>b</span> Performing athletic feats and resisting harm (Fitness)<br><span class='l5r'>b</span> Using close-quarters arms (Martial Arts [Melee])<br><span class='l5r'>b</span> Using missile weapons (Martial Arts [Ranged])<br><span class='l5r'>b</span> Fighting bare-handed and with improvised weapons (Martial Arts [Unarmed])<br><span class='l5r'>b</span> Mastering oneself and controlling emotion such as anger, fear, and hate (Meditation)<br><span class='l5r'>b</span> Fighting with squads and armies (Tactics)",
	Approach:"Martial approaches (choose one)<br><span class='l5r'>b</span> Withstand opposing force to wear it down (Earth)<br><span class='l5r'>b</span> Shift opposing force to work against itself or for you (Water)<br><span class='l5r'>b</span> Overwhelm opposing force with a quick burst of power (Fire)<br><span class='l5r'>b</span> Feint to lure opposing force into a position of vulnerability (Air)<br><span class='l5r'>b</span> Sacrifice to let opposing force score a victory so that you can achieve a greater end (Void)"},
	{"Skill Group":"To get resources or perform work (Trade Skill Group)",
	Skill:"Trade skills (choose one)<br><span class='l5r'>b</span>Direct, communicate with and work with animals (Animal Handling) <br><span class='l5r'>b</span> Sales, trading, and speculation (Commerce)<br><span class='l5r'>b</span> Farming, construction, and production (Labor)<br><span class='l5r'>b</span> Sailing and living on the ocean (Seafaring)<br><span class='l5r'>b</span> Criminal organizations and activities (Skulduggery)<br><span class='l5r'>b</span> Living in the wilds beyond civilization (Survival)",
	Approach:"Trade approaches (choose one)<br><span class='l5r'>b</span> Produce what you need through physical toil (Earth)<br><span class='l5r'>b</span> Exchange one type of labor or resources for another (Water)<br><span class='l5r'>b</span> Innovate a new way to get what you need (Fire)<br><span class='l5r'>b</span> Con someone to get something for nothing (Air)<br><span class='l5r'>b</span> Subsist in your environment without disrupting it (Void)"}
	]},
	{
title:"Falling Damage",
ref:"FallingDamage",
children:[
	{distance: "DISTANCE", effects:"EFFECTS:"},
	{distance: "Range 0", effects:"The character suffers the Disoriented condition."}, 
	{distance: "Range 1", effects:"The character suffers 4 physical damage and the Disoriented condition."}, 
	{distance: "Range 2", effects:"The character suffers 8 physical damage and the Prone and Disoriented conditions."},
	{distance: "Range 3", effects:"The character suffers 12 physical damage and the Prone and Unconscious conditions."},
	{distance: "Range 4", effects:"The character suffers a critical strike with severity 10 and the Prone and Unconscious conditions."},
	{distance: "Range 5", effects:"The character suffers a critical strike with severity 16 and the Prone and Unconscious conditions."},
	{distance: "Range 6", effects:"The character suffers a critical strike with severity 18 and the Prone and Unconscious conditions"},
	]},
	{
title:"Weapons",
ref:"Weapons",
children:[
	{name: "NAME", skill:"SKILL", category:"CATEGORY", range:"RNG", damage:"DMG", deadliness:"DLS", grips:"GRIPS", qualities:"QUALITIES AND SPECIAL RULES", rarity:"RARITY", price:"PRICE", source:"BOOK"},	
	{name: "Bokken", skill:"[Melee]", category:"Swords", range:"1", damage:"3", deadliness:"3", grips:"1-hand: - / 2-hand: Damage +2", qualities:"Mundane", rarity:"3", price:"1 bu", source:"Core"}, 
	{name: "Chokuto", skill:"[Melee]", category:"Swords", range:"0-1", damage:"4", deadliness:"5", grips:"1-hand: -", qualities:"Ceremonial, Razor-Edged", rarity:"7", price:"20 koku", source:"Core"}, 
	{name: "Dao", skill:"[Melee]", category:"Swords", range:"1", damage:"3", deadliness:"5", grips:"1-hand: -", qualities:"-", rarity:"6", price:"15 koku", source:"Core"}, 
	{name: "Gao", skill:"[Melee]", category:"Swords", range:"1", damage:"4", deadliness:"3", grips:"1-hand: -", qualities:"Snaring", rarity:"7", price:"15 koku", source:"Core"}, 
	{name: "Jian", skill:"[Melee]", category:"Swords", range:"0-1", damage:"4", deadliness:"4", grips:"1-hand: - / 2-hand: Deadliness +1", qualities:"-", rarity:"7", price:"15 koku", source:"Core"}, 
	{name: "Katana", skill:"[Melee]", category:"Swords", range:"1", damage:"4", deadliness:"5", grips:"1-hand: - / 2-hand: Deadliness +2", qualities:"Ceremonial, Razor-Edged", rarity:"7", price:"20 koku", source:"Core"}, 
	{name: "Nodachi", skill:"[Melee]", category:"Swords", range:"1-2", damage:"5", deadliness:"6", grips:"2-hand:", qualities:"Ceremonial, Razor-Edged", rarity:"8", price:"20 koku", source:"Core"}, 
	{name: "Scimitar", skill:"[Melee]", category:"Swords", range:"1", damage:"4", deadliness:"5", grips:"1-hand: -", qualities:"Durable, Razor-Edged", rarity:"8", price:"20 koku", source:"Core"}, 
	{name: "Wakizashi", skill:"[Melee]", category:"Swords", range:"0-1", damage:"3", deadliness:"5", grips:"1-hand: - / 2-hand: Deadliness +2", qualities:"Ceremonial, Razor-Edged", rarity:"7", price:"15 koku", source:"Core"}, 
	{name: "Zanbato", skill:"[Melee]", category:"Swords", range:"1-2", damage:"6", deadliness:"7", grips:"2-hand: -", qualities:"Cumbersome, Wargear", rarity:"8", price:"40 koku", source:"Core"}, 
	{name: "Masakari", skill:"[Melee]", category:"Axes", range:"0-1", damage:"3", deadliness:"4", grips:"1-hand: - / 2-hand: Deadliness +2", qualities:"Mundane", rarity:"5", price:"3 bu", source:"Core"}, 
	{name: "Ono", skill:"[Melee]", category:"Axes", range:"1-2", damage:"5", deadliness:"6", grips:"2-hand: -", qualities:"Wargear", rarity:"7", price:"5 koku", source:"Core"}, 
	{name: "Club", skill:"[Melee]", category:"Blunt", range:"0-1", damage:"5", deadliness:"2", grips:"1-hand: - / 2-hand: Damage +1", qualities:"Mundane", rarity:"1", price:"1 bu", source:"Core"}, 
	{name: "Hammer", skill:"[Melee]", category:"Blunt", range:"0-1", damage:"5", deadliness:"2", grips:"1-hand: - / 2-hand: Damage +2", qualities:"Mundane", rarity:"4", price:"2 bu", source:"Core"}, 
	{name: "Kiseru", skill:"[Melee]", category:"Blunt", range:"0", damage:"2", deadliness:"2", grips:"1-hand: -", qualities:"Concealable, Mundane", rarity:"5", price:"1 koku", source:"Core"}, 
	{name: "Otsuchi", skill:"[Melee]", category:"Blunt", range:"1", damage:"8", deadliness:"3", grips:"2-hand: -", qualities:"Cumbersome, Wargear", rarity:"8", price:"30 koku", source:"Core"}, 
	{name: "Tetsubo", skill:"[Melee]", category:"Blunt", range:"1-2", damage:"7", deadliness:"3", grips:"2-hand: -", qualities:"Cumbersome, Durable, Wargear", rarity:"5", price:"20 koku", source:"Core"}, 
	{name: "Jitte", skill:"[Melee]", category:"Hand", range:"0", damage:"3", deadliness:"2", grips:"1-hand: -", qualities:"Concealable, Snaring", rarity:"5", price:"5 koku", source:"Core"}, 
	{name: "Knife", skill:"[Melee]", category:"Hand", range:"0", damage:"2", deadliness:"4", grips:"1-hand: - / 2-hand: Deadliness +2", qualities:"Concealable, Mundane, Razor-Edged", rarity:"1", price:"1 koku", source:"Core"}, 
	{name: "Nunchaku", skill:"[Melee]", category:"Hand", range:"0-1", damage:"4", deadliness:"2", grips:"1-hand: - / 2-hand: Snaring", qualities:"-", rarity:"6", price:"1 koku", source:"Core"}, 
	{name: "Tessen", skill:"[Melee]", category:"Hand", range:"0-1", damage:"4", deadliness:"3", grips:"1-hand: -", qualities:"Ceremonial, Concealable", rarity:"7", price:"15 koku", source:"Core"}, 
	{name: "Bisento", skill:"[Melee]", category:"Polearms", range:"2", damage:"4", deadliness:"6", grips:"1-hand: Range 1 / 2-hand: Damage +2", qualities:"Cumbersome, Durable, Wargear", rarity:"1", price:"15 koku", source:"Core"}, 
	{name: "Bo", skill:"[Melee]", category:"Polearms", range:"1-2", damage:"6", deadliness:"2", grips:"2-hand: -", qualities:"Mundane", rarity:"2", price:"2 bu", source:"Core"}, 
	{name: "Ji", skill:"[Melee]", category:"Polearms", range:"2", damage:"5", deadliness:"2", grips:"2-hand: -", qualities:"Snaring, Wargear", rarity:"6", price:"7 koku", source:"Core"}, 
	{name: "Naginata", skill:"[Melee]", category:"Polearms", range:"2", damage:"6", deadliness:"6", grips:"2-hand: -", qualities:"Cumbersome, Razor-Edged, Wargear", rarity:"8", price:"10 koku", source:"Core"}, 
	{name: "Trident", skill:"[Melee]", category:"Polearms", range:"2", damage:"4", deadliness:"4", grips:"2-hand: -", qualities:"Snaring,", rarity:"7", price:"10 koku", source:"Core"}, 
	{name: "Yari", skill:"[Melee]", category:"Polearms", range:"2", damage:"5", deadliness:"3", grips:"2-hand: -", qualities:"Wargear", rarity:"3", price:"5 koku", source:"Core"}, 
	{name: "Daikyu", skill:"[Ranged]", category:"Bows", range:"3-5", damage:"6", deadliness:"4", grips:"2-hand: -", qualities:"Wargear<br>Armor-Piercing: -2 target phys res / Flesh-Cutter: Deadliness +2 /Humming Bulb: Damage -2, Deadliness -2, Produces loud noise", rarity:"6", price:"6 koku", source:"Core"}, 
	{name: "Horsebow", skill:"[Ranged]", category:"Bows", range:"2-4", damage:"4", deadliness:"5", grips:"2-hand: -", qualities:"Wargear<br>Armor-Piercing: -2 target phys res / Flesh-Cutter: Deadliness +2 / Humming Bulb: Damage -2, Deadliness -2, Produces loud noise", rarity:"4", price:"6 koku", source:"Core"}, 
	{name: "Yumi", skill:"[Ranged]", category:"Bows", range:"2-5", damage:"5", deadliness:"3", grips:"2-hand: -", qualities:"Armor-Piercing: -2 target phys res / Flesh-Cutter: Deadliness +2 / Humming Bulb: Damage -2, Deadliness -2, Produces loud noise", rarity:"3", price:"3 koku", source:"Core"}, 
	{name: "Oyumi", skill:"[Ranged]", category:"Bows", range:"2-5", damage:"7", deadliness:"3", grips:"2-hand: -", qualities:"Prepare, Wargear", rarity:"8", price:"40 koku", source:"Core"}, 
	{name: "Blowgun", skill:"[Ranged]", category:"Specialist", range:"2-3", damage:"1", deadliness:"2", grips:"1-hand: -", qualities:"Concealable", rarity:"7", price:"5 bu", source:"Core"}, 
	{name: "Kama", skill:"[Melee]", category:"Specialist", range:"0-1", damage:"3", deadliness:"3", grips:"1-hand: -", qualities:"Concealable", rarity:"4", price:"1 koku", source:"Core"}, 
	{name: "Kusari-gama", skill:"[Melee]", category:"Specialist", range:"0", damage:"3", deadliness:"3", grips:"1-hand: - / 2-hand: Range 2-3", qualities:"Concealable, Snaring, Wargear", rarity:"6", price:"5 koku", source:"Core"}, 
	{name: "Shuriken", skill:"[Melee]", category:"Specialist", range:"0", damage:"2", deadliness:"4", grips:"1-hand (stab or slash): - / 2-hand (thrown): Martial Arts [Ranged], Range 1-3", qualities:"Concealable", rarity:"6", price:"1 koku", source:"Core"}, 
	{name: "Punch", skill:"[Unarmed]", category:"Unarmed", range:"0", damage:"1", deadliness:"2", grips:"", qualities:"Snaring", rarity:"", price:"", source:"Core"}, 
	{name: "Kick", skill:"[Unarmed]", category:"Unarmed", range:"1", damage:"2", deadliness:"1", grips:"", qualities:"-", rarity:"", price:"", source:"Core"}, 
	{name: "Bite", skill:"[Unarmed]", category:"Unarmed", range:"0", damage:"0", deadliness:"3", grips:"", qualities:"-", rarity:"", price:"", source:"Core"},
	{name: "Butterfly Sword", skill:"[Melee]", category:"Swords", range:"0-1", damage:"3", deadliness:"5", grips:"1-hand: - ", qualities:"Concealable, Snaring", rarity:"6", price:"10 koku", source:"Mantis DLC"},
	{name: "Sai", skill:"[Melee]", category:"Hand", range:"0", damage:"2", deadliness:"2", grips:"1-hand: - ", qualities:"Concealable, Snaring, <br>While you have a pair of sai readied, reduce the <span class='l5r'>O</span> you must spend to activate their Snaring quality by 1.", rarity:"6", price:"2 koku", source:"Mantis DLC"},
	{name: "Tonfa", skill:"[Melee]", category:"Hand", range:"0", damage:"3", deadliness:"3", grips:"1-hand: - ", qualities:"Concealable, Durable, <br>As a Movement and Support action, if you have a tonfa readied, you may increase the TN of the next Attack action check targeting you by 1 and decrease the TN of your next Attack action check using a tonfa by 1. This effect persists until the end of your next turn ", rarity:"5", price:"4 koku", source:"Mantis DLC"},
	{name: "Eku", skill:"[Melee]", category:"Polearms", range:"2", damage:"6", deadliness:"4", grips:"2-hand: - ", qualities:" Cumbersome, Durable, Mundane", rarity:"5", price:"3 koku", source:"Mantis DLC"},
	{name: "Tinbe", skill:"[Melee]", category:"Polearms", range:"0-1", damage:"3", deadliness:"5", grips:"1-hand: - ", qualities:" -  ", rarity:"6", price:"15 koku", source:"Mantis DLC"},
	{name: "Rochin", skill:"[Melee]", category:"Shields", range:"0", damage:"2", deadliness:"2", grips:"1-hand: - ", qualities:"Durable <br> A rochin is a shield, and a character can only wield one shield at a time. As a Movement and Support action, if you have a rochin readied, you may increase the TN of the next Attack action check made targeting you by 1 and decrease the TN of your next Attack action check using a tinbe by 1. This effect persists until the end of your next turn.", rarity:"6", price:"25 koku", source:"Mantis DLC"},
	{name: "Sling", skill:"[Ranged]", category:"Sling", range:"2-3", damage:"3", deadliness:"3", grips:"1-hand: - ", qualities:"Concealable, Mundane", rarity:"1", price:"2 bu", source:"Core p315"},
	{name: "Flyssa", skill:"[Melee]", category:"Swords", range:"1", damage:"4", deadliness:"4", grips:"1-hand: - / 2-hand: Razor-Edged", qualities:"Wargear<br>When making an Attack action check, you may spend <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span> <span class='l5r'>O</span>+: Ignore 1 point of your target's Phys Res per <span class='l5r'>O</span> <span class='l5r'>O</span> spent in this way.", rarity:"8", price:"15 koku", source:"Shadowlands"},
	{name: "Kabutowari", skill:"[Melee]", category:"Swords", range:"0-1", damage:"3", deadliness:"3", grips:"1-hand: - ", qualities:"Durable, Snaring", rarity:"7", price:"6 koku", source:"Shadowlands"},
	{name: "Tekkan", skill:"[Melee]", category:"Swords", range:"1-2", damage:"4", deadliness:"3", grips:"1-hand: Cumbersome / 2-hand: Damage +2", qualities:"Durable, Wargear", rarity:"8", price:"50 koku", source:"Shadowlands"},
	{name: "Genno", skill:"[Melee]", category:"Blunt", range:"0-1", damage:"3", deadliness:"3", grips:"1-hand: - / 2-hand: Damage +4", qualities:"Durable, Mundane<br>When making an Attack action check you may spend <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span> <span class='l5r'>O</span>: If you succeed but your target reduces the damage of this Attack to 0, they suffer the Dazed and Prone conditions.", rarity:"5", price:"1 koku", source:"Shadowlands"},
	{name: "Tsuruhashi", skill:"[Melee]", category:"Axes", range:"1", damage:"4", deadliness:"3", grips:"1-hand: Cumbersome / 2-hand: Deadliness +2", qualities:"Mundane<br>When making an Attack action check you may spend <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span> <span class='l5r'>O</span>: If you succeed but your target reduces the damage of this Attack to 0, their armor gains the Damaged quality and they suffer the Bleeding condition.", rarity:"4", price:"5 bu", source:"Shadowlands"},
	{name: "Doom Crossbow", skill:"[Ranged]", category:"Bows", range:"3-5", damage:"8", deadliness:"6", grips:"2-hand: - ", qualities:"Cumbersome, Prepare, Wargear<br>When you perform an Attack action that inflicts a Critical Strike, increase the severity by the silhouette of the target.", rarity:"10", price:"80 koku", source:"Shadowlands"},
	{name: "Kaiu no Oyumi", skill:"[Ranged]", category:"Bows", range:"2-5", damage:"7", deadliness:"3", grips:"2-hand: - ", qualities:"Cumbersome, Prepare, Wargear<br>When performing an Attack action check you may spend <span class='l5r'>O</span> as follows:<br><span class='l5r'>O</span> <span class='l5r'>O</span>: After performing an Attack action, immediately prepare this weapon for use again.", rarity:"8", price:"60 koku", source:"Shadowlands"},
	{name: "Storm Bow", skill:"[Ranged]", category:"Bows", range:"1-4", damage:"4", deadliness:"3", grips:"2-hand: - ", qualities:"Cumbersome, Prepare, Wargear<br>When performing an attack you may spend <span class='l5r'>O</span> as followsL:<br><span class='l5r'>O</span>: Each character at range 0-1 of your initial target also becomes a target of this attack.", rarity:"9", price:"60 koku", source:"Shadowlands"},
	{name: "Sode", skill:"[Melee]", category:"Shields", range:"0", damage:"1", deadliness:"1", grips:"Shoulder: - ", qualities:"Durable, Wargear<br>A set of sode do not require free hands to wield but cannot be wielded with another shield.  While wielding a readied sode, treat your Phys Res as 1 higher when reducing damage from projectile attacks.", rarity:"8", price:"8 koku", source:"Shadowlands"},
	{name: "Large Shield", skill:"[Melee]", category:"Shields", range:"0", damage:"3", deadliness:"2", grips:"1-hand: - ", qualities:"Cumbersome, Durable, Wargear<br>While you have a readied large shield, treat your Phys Res as 6.<br>As a Movement and Support action, if you have a shield readied, you may increase the TN of Attack action checks made targeting you by 2.  This persists until the start of your next turn.", rarity:"8", price:"10 koku", source:"Shadowlands"},
	{name: "Small Shield", skill:"[Melee]", category:"Shields", range:"0", damage:"2", deadliness:"2", grips:"1-hand: - ", qualities:"Cumbersome, Durable, Wargear<br>While you have a readied large shield, treat your Phys Res as 5.<br>As a Movement and Support action, if you have a shield readied, you may increase the TN of Attack action checks made targeting you by 1.  This persists until the start of your next turn.", rarity:"8", price:"6 koku", source:"Shadowlands"},
	{name: "Ballista", skill:"[Ranged]", category:"Siege", range:"3-5", damage:"14", deadliness:"8", grips:"2-hand: - ", qualities:"Durable, Prepare (2)<br>Damage inflicted with a ballista ignores 4 points of Phys Res.", rarity:"7", price:"60 koku", source:"Shadowlands"},
	{name: "O-Gata Dohou", skill:"[Ranged]", category:"Siege", range:"4-5", damage:"16", deadliness:"6", grips:"2-hand: - ", qualities:"Durable, Prepare (2)", rarity:"7", price:"120 koku", source:"Shadowlands"},
	{name: "Ninjato", skill:"[Melee]", category:"Swords", range:"0-1", damage:"4", deadliness:"4", grips:"1-hand: - / 2-hand: Deadliness +1", qualities:"Concealable, Forbidden, Razor-Edged", rarity:"7", price:"12 koku", source:"Courts of Stone"},
	{name: "Shinobigatana", skill:"[Melee]", category:"Swords", range:"0-1", damage:"4", deadliness:"5", grips:"1-hand: - / 2-hand: Deadliness +1", qualities:"Ceremonial, Concealable, Razor-Edged<br>Appears to be a katana until examined; a character must either see it drawn or make a TN 4 Smithing (Air 2, Water 5) check to find the telltale details that betray the blade's duplicity.  If its true function is discovered, it loses the Ceremonial quality and gains Forbidden for anyone who knows its identity.", rarity:"8", price:"22 koku", source:"Courts of Stone"},
	{name: "Folding Half-Bow", skill:"[Ranged]", category:"Bows", range:"2-3", damage:"4", deadliness:"3", grips:"2-hand: - ", qualities:" - <br>While in its case or otherwise folded, it has the Concealable quality and cannot be fired.  As a Support action, a character may prepare it for use.", rarity:"5", price:"3 koku", source:"Courts of Stone"},
	{name: "Kamayari", skill:"[Melee]", category:"Specialist", range:"2", damage:"4", deadliness:"3", grips:"2-hand: - ", qualities:"Durable, Snaring", rarity:"7", price:"8 koku", source:"Courts of Stone"},
	{name: "Kusari-fundo", skill:"[Melee]", category:"Specialist", range:"1", damage:"2", deadliness:"2", grips:"1-hand: - / 2-hand: Snaring", qualities:"Concealable", rarity:"5", price:"4 bu", source:"Courts of Stone"},
	{name: "Kyoketsu Shoge", skill:"[Ranged]", category:"Specialist", range:"1-2", damage:"2", deadliness:"3", grips:"2-hand: - ", qualities:"Concealable, Forbidden, Snaring", rarity:"6", price:"3 bu", source:"Courts of Stone"},
	{name: "Shakuhachi", skill:"[Melee]", category:"Specialist", range:"0", damage:"3", deadliness:"2", grips:"1-hand: - / 2-hand: Damage +1", qualities:"Durable, Mundane, Subtle", rarity:"4", price:"3 bu", source:"Courts of Stone"},
	{name: "Tekagi", skill:"[Unarmed]", category:"Specialist", range:"0", damage:"1", deadliness:"3", grips:"1-hand: - ", qualities:"Durable, Forbidden<br>Spend <span class='l5r'>O</span> when performing an Attack action:<br><span class='l5r'>O</span>+: If the target's Vigilance is lower or equal to <span class='l5r'>O</span> spent, choose one Razor-Edged weapon the target has readied; it becomes Damaged.", rarity:"6", price:"4 bu", source:"Courts of Stone"},
	{name: "Tekken", skill:"[Unarmed]", category:"Specialist", range:"0", damage:"2", deadliness:"3", grips:"1-hand: - ", qualities:"Durable, Concealable", rarity:"4", price:"3 bu", source:"Courts of Stone"},

	]},
	{
title:"Armors",
ref:"Armors",
children:[
	{armor:"ARMOR", phys:"PHYS", sup:"SUP",qualities:"QUALITIES", rarity:"RARITY", price:"PRICE", source:"SOURCE"}, 
	{armor:"Sleeping Garb", phys:1, sup:0, qualities:"-", rarity:"2", price:"1 koku", source:"Core"}, 
	{armor:"Common Clothes", phys:1, sup:0, qualities:"Mundane", rarity:"1", price:"1 bu", source:"Core"}, 
	{armor:"Ceremonial Robes", phys:1, sup:0, qualities:"Ceremonial, Resplendant", rarity:"4", price:"1 koku", source:"Core"}, 
	{armor:"Sanctified Robes", phys:1, sup:3, qualities:"Ceremonial", rarity:"7", price:"4 koku", source:"Core"}, 
	{armor:"Traveling Clothes", phys:2, sup:0, qualities:"Durable, Mundane, Subtle", rarity:"2", price:"2 bu", source:"Core"}, 
	{armor:"Concealed Armor", phys:3, sup:0, qualities:"Concealable", rarity:"4", price:"5 koku", source:"Core"}, 
	{armor:"Ashigaru Armor", phys:3, sup:0, qualities:"Wargear", rarity:"3", price:"5 koku", source:"Core"}, 
	{armor:"Lacquered Armor", phys:4, sup:0, qualities:"Ceremonial, Cumbersome, Wargear", rarity:"6", price:"25 koku", source:"Core"}, 
	{armor:"Plated Armor", phys:5, sup:0, qualities:"Cumbersome, Durable, Wargear", rarity:"8", price:"40 koku", source:"Core"},
	{armor:"Sailor's Garb", phys:1, sup:0, qualities:"Durable, Mundane<br> Reduce the TN of checks to repair or maintain sailor's garb by 1.", rarity:"2", price:"1 bu", source:"Mantis DLC"},
	{armor:"Shark Leather Armor", phys:2, sup:0, qualities:"Resplendant<br> When you succeed at a check to resist a critical strike while wearing this armor, add two bonus successes.", rarity:"7", price:"12 koku", source:"Mantis DLC"},
	{armor:"O-yoroi", phys:6, sup:0, qualities:"Cumbersome, Resplendant, Wargear<br>While you wear o-yoroi, if you are suffering the Disoriented, Dazed or Immobilised condition, treat your Phys Res as 3 as your foes can strike at your lightly armored back.", rarity:"8", price:"60 koku", source:"Shadowlands"},
	{armor:"Tatami Gusoku", phys:3, sup:0, qualities:"Wargear (while equipped)", rarity:"4", price:"7 koku", source:"Shadowlands"},
	{armor:"Tosei-Gusoku", phys:4, sup:0, qualities:"Cumbersome, Durable, Wargear<br>While wearing tosei-gusoku, treat your Phys Res as 2 higher when reducing damage from projectile attacks.", rarity:"8", price:"50 koku", source:"Shadowlands"},	
	{armor:"Firefighter's Coat", phys:2, sup:0, qualities:"Cumbersome<br>Ignore the effects of Dangerous terrain created by fire, treat resistance against all flames as 4.", rarity:"4", price:"6 bu", source:"Courts of Stone"},
	{armor:"Stealth Clothing", phys:2, sup:0, qualities:"Forbidden, Subtle<br>While wearing set to the appropriate side and in Obscuring terrain, increase the TN of attacks targeting you by an additional 1 (for a total of 2).", rarity:"7", price:"4 bu", source:"Courts of Stone"},	
]},
	{
title:"Patterns",
ref:"Patterns",
children:[
{title:"Pattern",cost:"XP Cost",rarity:"Rarity Mod",effect:"Effect",source:"Source",}, 
{title:"Kakita",cost:6,rarity:4,effect:"A bladed weapon produced in the Kakita Pattern gains +1 deadliness",source:"Shadowlands p109",},
{title:"Kenzo",cost:8,rarity:5,effect:"A weapon produced in the Kenzo smithy gains +1 deadliness, -1 damage, and the Resplendent quality.",source:"Shadowlands p109",},
{title:"Shirogane Jade Inlay",cost:3,rarity:2,effect:"Weapons and armor designed for Shirogane Jade Inlay gain the Sacred quality.  Armor so altered loses 1 point of Physical Resistance, and weapons lose 1 point of deadliness.  Should the item become Damaged, the jade is chipped away as well and must be reapplied.  When this happens, the item loses the Sacred quality until a smith applies more jade resin by making a TN 3 Smithing (Earth) check as a downtime activity.  The process consumes one finger of jade per attempt.",source:"Shadowlands p109",},
{title:"Uchema's Technique",cost:4,rarity:3,effect:"A suit of armor made using Uchema's technique loses the Cumbersome quality and loses 1 point of Physical Resistance",source:"Shadowlands p109",},
{title:"Yasunori Steel",cost:5,rarity:4,effect:"A weapon made from Yasunori steel loses the Ceremonial, Cumbersome and Resplendant qualities (and can never gain any of these).  It gains the Durable quality; if the weapon already has the Durable quality it gains +1 deadliness instead.",source:"Shadowlands p109",},
{title:"Pit-Forged Obsidian",cost:4,rarity:4,effect:"An item produced with Pit-forged obsidian gains +1 damage, +1 deadliness, and the Unholy quality.  Additionally, while in possession of such an item, a character increases the TN of their Fitness or Meditation checks to resist the Taint.",source:"Shadowlands p29",},

]},
{
title:"General",
ref:"GeneralOpportunities",
children:[
	{ring: "", spend:"GENERAL OPPORTUNITY SPENDS:"},
	{ring: "Any", spend:"<span class='l5r'>O</span>: If you failed, determine the easiest way to accomplish the task you were attempting (skill and approach).<br><span class='l5r'>O</span>+: Remove 1 <span class='l5r'>T</span> you gained from this check per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Provide assistance (Core p26) to the next character to attempt a check to accomplish something similar."},
	{ring: "Air", spend:"<span class='l5r'>O</span>: Learn another character in the scene's demeanor (if an NPC) and current<span class='l5r'>T</span>.<br><span class='l5r'>O</span>+: Act subtly to attract minimal attention in your efforts. Extra <span class='l5r'>O</span> makes the attempt even subtler.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Notice an interesting detail about a character in the scene, such as an advantage or disadvantage. At the GM's discretion, you may establish a new detail for an NPC."},
	{ring: "Earth", spend:"<span class='l5r'>O</span>: Reassure another character in the scene with your presence, allowing them to remove 2<span class='l5r'>T</span>.<br><span class='l5r'>O</span>+: Act carefully to minimize consequences of failure or other dangers that could arise from the task. Extra <span class='l5r'>O</span> makes the attempt even safer.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Suddenly recall an important piece of information not directly related to the task. At the GM's discretion, you may establish a small preparatory action you took earlier, such as bringing along a common useful item."},
	{ring: "Fire", spend:"<span class='l5r'>O</span>: Inflame another character in the scene with your presence, causing them to receive 2<span class='l5r'>T</span>.<br><span class='l5r'>O</span>+: Perform the task in a flashy way, drawing attention to yourself. Extra <span class='l5r'>O</span> attracts even more notice.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Notice something missing or out of place in the vicinity that is not directly related to the task. At the GM's discretion, you may establish an absence, such as a lack of shoes outside indicating the occupant's absence."},
	{ring: "Water", spend:"<span class='l5r'>O</span>: Remove 2 <span class='l5r'>T</span> from yourself.<br><span class='l5r'>O</span>+: Perform the task efficiently, completing it more quickly or saving supplies. Extra <span class='l5r'>O</span> further reduces the time or<br>materials expended.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Spot an interesting physical detail present in your environment not directly related to your check. At the GM's discretion, you may establish a piece of terrain (Core p267) or a mundane object nearby."},
	{ring: "Void", spend:"<span class='l5r'>O</span>: Choose a ring other than Void. Reduce the TN of your next check by 1 if it uses that ring.<br><span class='l5r'>O</span>+: Feel a chill down your spine, notice a sudden silence, or detect another sign of the supernatural if there is a spiritual disturbance in the scene. Extra <span class='l5r'>O</span> gives an increasingly precise location for the supernatural occurrence.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Gain spiritual insight into the nature of the universe or your own heart. At the GM's discretion, you may establish a fact about your character that has not been previously revealed but relates to the situation."},
		]},
	{
title:"Initiative",
ref:"InitiativeOpportunities",
children:[
	{ring: "", spend:"INITIATIVE OPPORTUNITY SPENDS:"},
	{ring: "Air", spend:"<span class='l5r'>O</span>: On an Initiative check, assess one foe's weakness. Learn one of their disadvantages of that foe's choice."},
	{ring: "Earth", spend:"<span class='l5r'>O</span>: On an Initiative check, choose another character's disadvantage you know. They do not apply that disadvantage to their checks this scene."},
	{ring: "Fire", spend:"<span class='l5r'>O</span>: On an Initiative check, use your focus instead of your vigilance for your initiative when surprised."},
	{ring: "Water", spend:"<span class='l5r'>O</span>: On an Initiative check, assess the qualities of all terrain in the scene (Core p267)."},
	{ring: "Void", spend:"<span class='l5r'>O</span>: On an Initiative check, sense if there is an Otherworldly being in the scene."},
		]},
	{
title:"Martial",
ref:"MartialOpportunities",
children:[
	{ring: "", spend:"MARTIAL OPPORTUNITY SPENDS:"},
	{ring: "Air", spend:"<span class='l5r'>O</span>: Add a kept <span class='l5r'>d</span> set to an <span class='l5r'>O</span> result to your next Martial skill check.<br><span class='l5r'>O</span>+: During a Movement action check, up to 1 range band of any distance you move per <span class='l5r'>O</span> spent this way may be along a vertical surface.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Increase the TN of the next Martial Arts [Ranged] check targeting you before the start of your next turn by 2."},
	{ring: "Earth", spend:"<span class='l5r'>O</span>: During a Movement action, ignore one terrain quality (Core p267) of your choice.<br><span class='l5r'>O</span>+: Reduce the severity of the next critical strike you suffer before the start of your next turn by 1 per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Do not apply one of your disadvantages to checks until the end of your next turn."},
	{ring: "Fire", spend:"<span class='l5r'>O</span>: Choose another character in the scene; increase the TN of the next check they make before the end of their next turn by 1 if it does not include you as a target.<br><span class='l5r'>O</span>+: During an Attack action check, increase the TN of the next check the target makes to resist a critical strike they suffer before the start of your next turn by 1 per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Other characters must receive 2 <span class='l5r'>T</span> to choose you as the target of their Attack and Scheme actions until the start of your next turn."},
	{ring: "Water", spend:"<span class='l5r'>O</span>: Remove 1 fatigue.<br><span class='l5r'>O</span>+: During an Attack action check, ignore 1 point of target's physical resistance per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Move 1 range band."},
	{ring: "Void", spend:"<span class='l5r'>O</span>: During the next Attack action check you make before the end of your next turn, ignore one terrain quality (Core p267) of your choice.<br><span class='l5r'>O</span>+: During a Support action check, increase your Initiative value by 1 per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Ignore the effects of one condition you are suffering until the end of your next turn."},
		]},
	{
title:"Invocation",
ref:"InvocationOpportunities",
children:[
	{ring: "", spend:"INVOCATION OPPORTUNITY SPENDS:"},
	{ring: "Air", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span>+ Choose one additional target per <span class='l5r'>O</span> <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span>+ Treat the maximum range of this technique as 1 higher per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> Reduce the TN of the next Movement action check you make by 1. This effect persists until the end of your next turn.<br><span class='l5r'>O</span> <span class='l5r'>O</span>+ If this technique can target characters other than you, choose additional target per <span class='l5r'>O</span> <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>+ If this technique targets all characters in an area, choose 1 character in range to exclude as a target per <span class='l5r'>O</span> <span class='l5r'>O</span> spent this way."},
	{ring: "Earth", spend:"<span class='l5r'>O</span> Increase your physical resistance by 1. This effect persists until the end of the beginning of your next turn.<br><span class='l5r'>O</span>+ If this technique can target characters other than you, choose additional target per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span>+ Treat the maximum range of this technique as 1 higher per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> This effect inflicts physical damage instead of supernatural damage.<br><span class='l5r'>O</span> The damage inflicted by this technique has the Sacred quality (Core p241)."},
	{ring: "Fire", spend:"<span class='l5r'>O</span>+ Treat the maximum range of this technique as 1 higher per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span>+ If this technique can target characters other than you, choose additional target per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> Reduce the TN of the next Attack action check you make by 1. This effect persists until the end of your next turn.<br><span class='l5r'>O</span>+ Increase the TN of checks to resist this effect by 1 per <span class='l5r'>O</span> spent this way. <br><span class='l5r'>O</span> <span class='l5r'>O</span>+ One target per <span class='l5r'>O</span> <span class='l5r'>O</span> spent this way must resist with a TN 3 Fitness check (Air 4, Water 1) or suffer the Burning condition."},
	{ring: "Water", spend:"<span class='l5r'>O</span> Increase your supernatural resistance by 1 until the end of your next turn.<br><span class='l5r'>O</span>+ If this technique can target characters other than you, choose additional target per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>+ Treat the maximum or minimum range of this technique as 1 higher or lower per <span class='l5r'>O</span> <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span> Remove 1 fatigue from the target or yourself.<br><span class='l5r'>O</span> Reduce the TN of the next Support action check you make by 1. This effect persists until the end of your next turn."},

		]},
	{
title:"Other Skills",
ref:"OtherSkillsOpportunities",
children:[
	{ring: "", spend:"SKILL OPPORTUNITY SPENDS:"},
	{ring: "Air", spend:"Artisan <span class='l5r'>O</span>: If you succeed, add the Resplendent or Subtle quality to an item that you are refining. <br>Scholar <span class='l5r'>O</span>: Learn a something about a character who created or used the item you are studying (such as one of their advantages or disadvantages of the GM's choice that affected their creation or use of the item). <br>Social <span class='l5r'>O</span>: Learn if the honor, glory, or status attribute of a character in the scene is higher, lower, or equal to yours. <br>Trade <span class='l5r'>O</span>: Convince a buyer to pay an additional 10% for an item you are selling."},
	{ring: "Earth", spend:"Artisan <span class='l5r'>O</span>: If you succeed, add the Durable quality to an item that you are restoring. <br>Scholar <span class='l5r'>O</span>: Remember a place where you can research or study the topic you were attempting to recall.<br>Social <span class='l5r'>O</span>: Increase the TN of the next Social check another character makes before the end of the scene by 1.<br>Trade <span class='l5r'>O</span>: Reduce the TN of the next check another character makes with the same skill before the end of the scene by 1."},
	{ring: "Fire", spend:"Artisan <span class='l5r'>O</span>: If you succeed, make one additional copy of the item you are creating.<br>Scholar <span class='l5r'>O</span>: Extrapolate the motivations or desires of another character in the scene or wider situation.<br>Social <span class='l5r'>O</span>: Reduce the TN of the next Social check another character makes before the end of the scene by 1.<br>Trade <span class='l5r'>O</span>: Unusual inspiration strikes; add a kept <span class='l5r'>d</span> set to an <span class='l5r'>O</span> result to the next check you make with another skill."},
	{ring: "Water", spend:"Artisan <span class='l5r'>O</span>: Add a kept <span class='l5r'>d</span> set to an <span class='l5r'>O</span> result to the next Artisan skill check you make before the end of the game session.<br>Scholar <span class='l5r'>O</span>: Spot a unique or identifying quality, aspect, or ability of something that you are identifying.<br>Social <span class='l5r'>O</span>: Add a kept <span class='l5r'>d</span> set to an <span class='l5r'>O</span> result to your next Social check before the end of the scene.<br>Trade <span class='l5r'>O</span>: Convince a seller to give you an additional 10% discount for an item you are buying."},
	{ring: "Void", spend:"Artisan <span class='l5r'>O</span>: Reduce the TN of the next check you make using the item you are attuning yourself to by 1.<br>Scholar <span class='l5r'>O</span>: Intuit whether you can learn anything of value from your current course of inquiry.<br>Social <span class='l5r'>O</span>: Discern the objective of another character in the scene.<br>Trade <span class='l5r'>O</span>: Reduce any effect you have on your environment (and physical traces of your efforts) to a minimum."},
		]},
	{
title:"Downtime",
ref:"DowntimeOpportunities",
children:[
	{ring: "", spend:"DOWNTIME OPPORTUNITY SPENDS:"},
	{ring: "Air", spend:"<span class='l5r'>O</span>+: Learn a detail about one person in your company (such as an advantage or disadvantage of their choice) per <span class='l5r'>O</span> spent this way. You can learn only one detail about each person this way in a single downtime scene.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Perform your downtime activity without letting one or more others of your choice know that you did."},
	{ring: "Earth", spend:"<span class='l5r'>O</span>+: Another character in your company may remove 1 <span class='l5r'>T</span> or fatigue per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Memorize a small but vital detail from to your activity; you can recall it later without a check."},
	{ring: "Fire", spend:"<span class='l5r'>O</span>+: Assist one other character per <span class='l5r'>O</span> spent this way with their next downtime activity check this session.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Energize another character in your company with your efforts; they may perform 1 additional downtime action this downtime (to a maximum of 2)."},
	{ring: "Water", spend:"<span class='l5r'>O</span>+: Remove 1 <span class='l5r'>T</span> or fatigue per <span class='l5r'>O</span> spent this way.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Make a new friend while undertaking your downtime activity."},
	{ring: "Void", spend:"<span class='l5r'>O</span>+: Reserve 1 dropped die from your check, to a maximum of your ranks in the skill you used. Add that die to your next check with the same skill as a kept die instead of rolling it.<br><span class='l5r'>O</span> <span class='l5r'>O</span>: Have a brief premonition of a possible future event while undertaking your downtime activity."},
		]},
{
title:"Negotiations",
ref:"NegotiationsOpportunities",
children:[
	{ring: "", spend:"NEGOTIATIONS OPPORTUNITY SPENDS:"},
	{ring: "Air", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span>+: Your careful verbal trap ensnares someone in a position in which they must either give up ground or give you a boon. They must offer you a minor concession unrelated to your current social objective unless they give up 1 momentum point per <span class='l5r'>O</span> <span class='l5r'>O</span> spent this way. "},
	{ring: "Earth", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span> <span class='l5r'>O</span>: Your uncompromising dedication to your bottom line stalls the conversation. Choose a character In the scene: that character cannot gain momentum points toward any social objective until the end of your next turn."},
	{ring: "Fire", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span>: You set someone else on the defense with fast-paced questions and demands. Choose a demand or statement another character in the scene has made. Their player (or the GM, for NPCs) must tell you any hidden motivations behind that demand or statement. "},
	{ring: "Water", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span>: You break the tension with a well-timed joke or clever comment. You may ask one personal question of a character in the scene with a different social objective. The question must be unrelated to the subject of the negotiations. If the character answers honestly, they gain 1 momentum point toward their current objective and may ask you a personal question in turn. If they do, you gain 1 momentum point toward your current objective."},
	{ring: "Void", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span> <span class='l5r'>O</span>: You briefly shake someone's conviction with a deep insight into their character or circumstances, causing them to speak without certainty. Until the end of your next turn, any momentum points they score are added to your current social objective instead of to their own. "},
		]},
{
title:"Romance",
ref:"RomanceOpportunities",
children:[
	{ring: "", spend:"ROMANCE OPPORTUNITY SPENDS:"},
	{ring: "Air", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span>: The conversation turns to mutual friends or acquaintances. Name a character you and your intended both know. They must tell you what they think of that character, revealing one of that person's advantages or disadvantages."},
	{ring: "Earth", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span>: An offhand comment reveals that you and your intended share some common ground: an odd hobby, a favorite actor, or a core belief. Make three suggestions to your intended's player; they must tell you which one it is. You and your intended may each remove 2 strife"},
	{ring: "Fire", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span>:  A detail of your appearance catches your intended's interest. Their player must tell you which of your physical attributes they find most captivating. You and your intended each receive 1 strife, and you each reduce the TN of your next Social skill check by 1"},
	{ring: "Water", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span>: Your interaction is pleasant enough that your intended not you, suggests another meeting within the next day or two. They offer you several options for the next time you and they spend personal time together; choose whichever you like the best, and don't be late."},
	{ring: "Void", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span> <span class='l5r'>O</span>: Due to circumstances beyond your control - a gust of wind or an earth tremor, perhaps - you and your intended find yourselves unexpectedly aware of one another! Your intended decides What land of contact it was, from a fateful meeting of the eyes to a brush of your hands against one another as you both reach for a dropped scroll. They also decide how they react, although they not blame you for anything untoward (after all it wasn't your fault). "},
		]},
		{
title:"Espionage",
ref:"EspionageOpportunities",
children:[
	{ring: "", spend:"ESPIONAGE OPPORTUNITY SPENDS:"},
	{ring: "Air", spend:"<span class='l5r'>O</span>+: Your subtlety allows you to step out of sight of people, whether by hiding in a crowd or within convenient terrain. Designate a number of Minion NPCs equal to spent this way or a single Adversary NPC with vigilance lower than or equal to spent this way. Those characters lose sight of you (and do not notice your absence unless actively looking for you)."},
	{ring: "Earth", spend:"<span class='l5r'>O</span>+: You locate an excellent hiding place, either a place where no one questions your cover identity or a concealed location no one checks. While hiding in this location, you reduce the TN of your checks to avoid notice by <span class='l5r'>O</span> spent this way. "},
	{ring: "Fire", spend:"<span class='l5r'>O</span> <span class='l5r'>O</span> <span class='l5r'>O</span>: A stray motion of yours catches the attention of a person or creature- but unexpectedly they are sympathetic or helpful to you when they notice you. Who are they, and how do they offer to help? Do they think you are someone you're not? "},
	{ring: "Water", spend:"<span class='l5r'>O</span>: You observe a clue or hint that indicates to you that information about your target or goal might also be found elsewhere, The GM reveals another viable avenue for espionage or, the same subject, unrelated to your current operation. "},
	{ring: "Void", spend:"<span class='l5r'>O</span>: Your understanding of stealth clues you in on the possibility that you are not. the first spy to pass this way. The GM reveals whether another spy has traversed your location and, if so, what trace they unwittingly left behind.  "},
		]},

];



/*
<span class='l5r'>O</span>

*/